//! C header definition for the Molt FFI layer.
//!
//! This module contains the C header as a constant string, suitable for
//! writing to disk or embedding in a build system.

/// The generated C header content for `molt-ffi`.
pub const HEADER: &str = r#"/* molt_ffi.h - C API for Molt stdlib intrinsics
 *
 * Auto-generated by molt-ffi. Do not edit manually.
 *
 * This header provides two API layers:
 *   1. NaN-boxed API (molt_ffi_*): operates on Molt's u64 object representation.
 *   2. C string API (molt_ffi_c_*): operates on plain C types (double, char*).
 *
 * Naming convention:
 *   molt_ffi_<module>_<function>    — NaN-boxed API
 *   molt_ffi_c_<module>_<function>  — C string/double API
 */
#ifndef MOLT_FFI_H
#define MOLT_FFI_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Lifecycle (NaN-boxed API) ─────────────────────────────────── */
uint64_t molt_ffi_init(void);
uint64_t molt_ffi_shutdown(void);
uint32_t molt_ffi_version(void);
uint32_t molt_ffi_is_initialized(void);

/* ── JSON (NaN-boxed API) ──────────────────────────────────────── */
uint64_t molt_ffi_json_loads(uint64_t json_str_bits);
uint64_t molt_ffi_json_dumps(uint64_t obj_bits);

/* ── Math (NaN-boxed API) ──────────────────────────────────────── */
uint64_t molt_ffi_math_sqrt(uint64_t x_bits);
uint64_t molt_ffi_math_fabs(uint64_t x_bits);
uint64_t molt_ffi_math_floor(uint64_t x_bits);
uint64_t molt_ffi_math_ceil(uint64_t x_bits);
uint64_t molt_ffi_math_log(uint64_t x_bits);
uint64_t molt_ffi_math_log2(uint64_t x_bits);
uint64_t molt_ffi_math_log10(uint64_t x_bits);
uint64_t molt_ffi_math_pow(uint64_t base_bits, uint64_t exp_bits);
uint64_t molt_ffi_math_sin(uint64_t x_bits);
uint64_t molt_ffi_math_cos(uint64_t x_bits);

/* ── Builtins (NaN-boxed API) ──────────────────────────────────── */
uint64_t molt_ffi_len(uint64_t obj_bits);
uint64_t molt_ffi_str(uint64_t obj_bits);
uint64_t molt_ffi_repr(uint64_t obj_bits);

/* ── Capabilities (NaN-boxed API) ──────────────────────────────── */
uint64_t molt_ffi_has_capability(uint64_t cap_name_bits);

/* ── String management (C string API) ──────────────────────────── */
void molt_ffi_free_string(char *s);
char *molt_ffi_last_error(void);

/* ── Math (C double API) ───────────────────────────────────────── */
double molt_ffi_c_math_sqrt(double x);
double molt_ffi_c_math_floor(double x);
double molt_ffi_c_math_ceil(double x);
double molt_ffi_c_math_fabs(double x);
double molt_ffi_c_math_log(double x);
double molt_ffi_c_math_log2(double x);
double molt_ffi_c_math_log10(double x);
double molt_ffi_c_math_pow(double base, double exp);
double molt_ffi_c_math_sin(double x);
double molt_ffi_c_math_cos(double x);

/* ── JSON (C string API) ───────────────────────────────────────── */
char *molt_ffi_c_json_dumps_kv(const char *key, const char *value);

/* ── os.path (C string API) ────────────────────────────────────── */
char *molt_ffi_c_os_path_join(const char *a, const char *b);
int molt_ffi_c_os_path_exists(const char *path);

/* ── Version / introspection (C string API) ────────────────────── */
char *molt_ffi_c_version(void);
int molt_ffi_function_count(void);

#ifdef __cplusplus
}
#endif

#endif /* MOLT_FFI_H */
"#;
