// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub fn resolve_symbol_with(
    symbol: &str,
    runtime_fn_addr: fn(&str, *const ()) -> u64,
) -> Option<u64> {
    match symbol {
        "molt_binascii_a2b_base64" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_a2b_base64",
            crate::binascii::molt_binascii_a2b_base64 as *const (),
        )),
        "molt_binascii_b2a_base64" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_b2a_base64",
            crate::binascii::molt_binascii_b2a_base64 as *const (),
        )),
        "molt_binascii_a2b_hex" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_a2b_hex",
            crate::binascii::molt_binascii_a2b_hex as *const (),
        )),
        "molt_binascii_b2a_hex" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_b2a_hex",
            crate::binascii::molt_binascii_b2a_hex as *const (),
        )),
        "molt_binascii_a2b_qp" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_a2b_qp",
            crate::binascii::molt_binascii_a2b_qp as *const (),
        )),
        "molt_binascii_b2a_qp" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_b2a_qp",
            crate::binascii::molt_binascii_b2a_qp as *const (),
        )),
        "molt_binascii_a2b_uu" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_a2b_uu",
            crate::binascii::molt_binascii_a2b_uu as *const (),
        )),
        "molt_binascii_b2a_uu" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_b2a_uu",
            crate::binascii::molt_binascii_b2a_uu as *const (),
        )),
        "molt_binascii_crc32" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_crc32",
            crate::binascii::molt_binascii_crc32 as *const (),
        )),
        "molt_binascii_crc_hqx" => Some(runtime_fn_addr(
            "molt_runtime_serial::binascii::molt_binascii_crc_hqx",
            crate::binascii::molt_binascii_crc_hqx as *const (),
        )),
        _ => None,
    }
}
