// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub fn resolve_symbol_with(
    symbol: &str,
    runtime_fn_addr: fn(&str, *const ()) -> u64,
) -> Option<u64> {
    match symbol {
        "molt_decimal_context_new" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_new",
            crate::decimal::molt_decimal_context_new as *const (),
        )),
        "molt_decimal_context_get_current" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_current",
            crate::decimal::molt_decimal_context_get_current as *const (),
        )),
        "molt_decimal_context_set_current" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_current",
            crate::decimal::molt_decimal_context_set_current as *const (),
        )),
        "molt_decimal_context_copy" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_copy",
            crate::decimal::molt_decimal_context_copy as *const (),
        )),
        "molt_decimal_context_drop" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_drop",
            crate::decimal::molt_decimal_context_drop as *const (),
        )),
        "molt_decimal_context_get_prec" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_prec",
            crate::decimal::molt_decimal_context_get_prec as *const (),
        )),
        "molt_decimal_context_set_prec" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_prec",
            crate::decimal::molt_decimal_context_set_prec as *const (),
        )),
        "molt_decimal_context_get_rounding" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_rounding",
            crate::decimal::molt_decimal_context_get_rounding as *const (),
        )),
        "molt_decimal_context_set_rounding" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_rounding",
            crate::decimal::molt_decimal_context_set_rounding as *const (),
        )),
        "molt_decimal_context_get_emin" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_emin",
            crate::decimal::molt_decimal_context_get_emin as *const (),
        )),
        "molt_decimal_context_set_emin" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_emin",
            crate::decimal::molt_decimal_context_set_emin as *const (),
        )),
        "molt_decimal_context_get_emax" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_emax",
            crate::decimal::molt_decimal_context_get_emax as *const (),
        )),
        "molt_decimal_context_set_emax" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_emax",
            crate::decimal::molt_decimal_context_set_emax as *const (),
        )),
        "molt_decimal_context_get_clamp" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_clamp",
            crate::decimal::molt_decimal_context_get_clamp as *const (),
        )),
        "molt_decimal_context_set_clamp" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_clamp",
            crate::decimal::molt_decimal_context_set_clamp as *const (),
        )),
        "molt_decimal_context_get_capitals" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_capitals",
            crate::decimal::molt_decimal_context_get_capitals as *const (),
        )),
        "molt_decimal_context_set_capitals" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_capitals",
            crate::decimal::molt_decimal_context_set_capitals as *const (),
        )),
        "molt_decimal_context_etiny" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_etiny",
            crate::decimal::molt_decimal_context_etiny as *const (),
        )),
        "molt_decimal_context_etop" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_etop",
            crate::decimal::molt_decimal_context_etop as *const (),
        )),
        "molt_decimal_context_clear_flags" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_clear_flags",
            crate::decimal::molt_decimal_context_clear_flags as *const (),
        )),
        "molt_decimal_context_get_flag" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_flag",
            crate::decimal::molt_decimal_context_get_flag as *const (),
        )),
        "molt_decimal_context_set_flag" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_flag",
            crate::decimal::molt_decimal_context_set_flag as *const (),
        )),
        "molt_decimal_context_get_trap" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_get_trap",
            crate::decimal::molt_decimal_context_get_trap as *const (),
        )),
        "molt_decimal_context_set_trap" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_context_set_trap",
            crate::decimal::molt_decimal_context_set_trap as *const (),
        )),
        "molt_decimal_from_str" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_from_str",
            crate::decimal::molt_decimal_from_str as *const (),
        )),
        "molt_decimal_from_int" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_from_int",
            crate::decimal::molt_decimal_from_int as *const (),
        )),
        "molt_decimal_clone" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_clone",
            crate::decimal::molt_decimal_clone as *const (),
        )),
        "molt_decimal_drop" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_drop",
            crate::decimal::molt_decimal_drop as *const (),
        )),
        "molt_decimal_to_string" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_to_string",
            crate::decimal::molt_decimal_to_string as *const (),
        )),
        "molt_decimal_as_tuple" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_as_tuple",
            crate::decimal::molt_decimal_as_tuple as *const (),
        )),
        "molt_decimal_to_float" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_to_float",
            crate::decimal::molt_decimal_to_float as *const (),
        )),
        "molt_decimal_div" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_div",
            crate::decimal::molt_decimal_div as *const (),
        )),
        "molt_decimal_quantize" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_quantize",
            crate::decimal::molt_decimal_quantize as *const (),
        )),
        "molt_decimal_compare" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_compare",
            crate::decimal::molt_decimal_compare as *const (),
        )),
        "molt_decimal_compare_total" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_compare_total",
            crate::decimal::molt_decimal_compare_total as *const (),
        )),
        "molt_decimal_normalize" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_normalize",
            crate::decimal::molt_decimal_normalize as *const (),
        )),
        "molt_decimal_exp" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_exp",
            crate::decimal::molt_decimal_exp as *const (),
        )),
        "molt_decimal_abs" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_abs",
            crate::decimal::molt_decimal_abs as *const (),
        )),
        "molt_decimal_add" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_add",
            crate::decimal::molt_decimal_add as *const (),
        )),
        "molt_decimal_adjusted" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_adjusted",
            crate::decimal::molt_decimal_adjusted as *const (),
        )),
        "molt_decimal_as_integer_ratio" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_as_integer_ratio",
            crate::decimal::molt_decimal_as_integer_ratio as *const (),
        )),
        "molt_decimal_copy_abs" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_copy_abs",
            crate::decimal::molt_decimal_copy_abs as *const (),
        )),
        "molt_decimal_copy_negate" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_copy_negate",
            crate::decimal::molt_decimal_copy_negate as *const (),
        )),
        "molt_decimal_copy_sign" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_copy_sign",
            crate::decimal::molt_decimal_copy_sign as *const (),
        )),
        "molt_decimal_floordiv" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_floordiv",
            crate::decimal::molt_decimal_floordiv as *const (),
        )),
        "molt_decimal_fma" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_fma",
            crate::decimal::molt_decimal_fma as *const (),
        )),
        "molt_decimal_from_float" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_from_float",
            crate::decimal::molt_decimal_from_float as *const (),
        )),
        "molt_decimal_hash" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_hash",
            crate::decimal::molt_decimal_hash as *const (),
        )),
        "molt_decimal_is_finite" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_finite",
            crate::decimal::molt_decimal_is_finite as *const (),
        )),
        "molt_decimal_is_infinite" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_infinite",
            crate::decimal::molt_decimal_is_infinite as *const (),
        )),
        "molt_decimal_is_nan" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_nan",
            crate::decimal::molt_decimal_is_nan as *const (),
        )),
        "molt_decimal_is_normal" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_normal",
            crate::decimal::molt_decimal_is_normal as *const (),
        )),
        "molt_decimal_is_signed" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_signed",
            crate::decimal::molt_decimal_is_signed as *const (),
        )),
        "molt_decimal_is_subnormal" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_subnormal",
            crate::decimal::molt_decimal_is_subnormal as *const (),
        )),
        "molt_decimal_is_zero" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_is_zero",
            crate::decimal::molt_decimal_is_zero as *const (),
        )),
        "molt_decimal_ln" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_ln",
            crate::decimal::molt_decimal_ln as *const (),
        )),
        "molt_decimal_log10" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_log10",
            crate::decimal::molt_decimal_log10 as *const (),
        )),
        "molt_decimal_max" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_max",
            crate::decimal::molt_decimal_max as *const (),
        )),
        "molt_decimal_min" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_min",
            crate::decimal::molt_decimal_min as *const (),
        )),
        "molt_decimal_mod" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_mod",
            crate::decimal::molt_decimal_mod as *const (),
        )),
        "molt_decimal_mul" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_mul",
            crate::decimal::molt_decimal_mul as *const (),
        )),
        "molt_decimal_neg" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_neg",
            crate::decimal::molt_decimal_neg as *const (),
        )),
        "molt_decimal_next_minus" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_next_minus",
            crate::decimal::molt_decimal_next_minus as *const (),
        )),
        "molt_decimal_next_plus" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_next_plus",
            crate::decimal::molt_decimal_next_plus as *const (),
        )),
        "molt_decimal_number_class" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_number_class",
            crate::decimal::molt_decimal_number_class as *const (),
        )),
        "molt_decimal_pos" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_pos",
            crate::decimal::molt_decimal_pos as *const (),
        )),
        "molt_decimal_pow" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_pow",
            crate::decimal::molt_decimal_pow as *const (),
        )),
        "molt_decimal_remainder_near" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_remainder_near",
            crate::decimal::molt_decimal_remainder_near as *const (),
        )),
        "molt_decimal_same_quantum" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_same_quantum",
            crate::decimal::molt_decimal_same_quantum as *const (),
        )),
        "molt_decimal_scaleb" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_scaleb",
            crate::decimal::molt_decimal_scaleb as *const (),
        )),
        "molt_decimal_sqrt" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_sqrt",
            crate::decimal::molt_decimal_sqrt as *const (),
        )),
        "molt_decimal_sub" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_sub",
            crate::decimal::molt_decimal_sub as *const (),
        )),
        "molt_decimal_to_eng_string" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_to_eng_string",
            crate::decimal::molt_decimal_to_eng_string as *const (),
        )),
        "molt_decimal_to_int" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_to_int",
            crate::decimal::molt_decimal_to_int as *const (),
        )),
        "molt_decimal_to_integral_exact" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_to_integral_exact",
            crate::decimal::molt_decimal_to_integral_exact as *const (),
        )),
        "molt_decimal_to_integral_value" => Some(runtime_fn_addr(
            "molt_runtime_serial::decimal::molt_decimal_to_integral_value",
            crate::decimal::molt_decimal_to_integral_value as *const (),
        )),
        _ => None,
    }
}
