# Parity test: builtin functions
# All output via print() for diff comparison

print("=== print variations ===")
print()
print("hello")
print("a", "b", "c")
print("a", "b", "c", sep="-")
print("no newline", end="")
print(" continued")
print(1, 2.0, True, None, [1, 2])

print("=== len ===")
print(len([]))
print(len([1, 2, 3]))
print(len("hello"))
print(len({}))
print(len({1, 2, 3}))
print(len((1, 2)))
print(len(range(100)))

print("=== range ===")
print(list(range(5)))
print(list(range(2, 8)))
print(list(range(0, 10, 2)))
print(list(range(10, 0, -1)))
print(list(range(0, 0)))
print(list(range(5, 5)))
print(list(range(10, 0, -3)))
print(len(range(100)))
print(5 in range(10))
print(10 in range(10))
print(range(10)[3])
print(range(10)[-1])

print("=== enumerate ===")
print(list(enumerate(["a", "b", "c"])))
print(list(enumerate(["x", "y"], start=1)))
print(list(enumerate([])))

print("=== zip ===")
print(list(zip([1, 2, 3], ["a", "b", "c"])))
print(list(zip([1, 2], [10, 20, 30])))
print(list(zip([], [1, 2])))
print(list(zip([1, 2, 3], [4, 5, 6], [7, 8, 9])))

print("=== zip strict ===")
print(list(zip([1, 2], [3, 4], strict=True)))
try:
    list(zip([1, 2], [3], strict=True))
except ValueError as e:
    print("zip strict error: ValueError")

print("=== map ===")
print(list(map(str, [1, 2, 3])))
print(list(map(lambda x: x * 2, [1, 2, 3])))
print(list(map(lambda x, y: x + y, [1, 2], [10, 20])))
print(list(map(abs, [-1, -2, 3, -4])))

print("=== filter ===")
print(list(filter(None, [0, 1, "", "a", [], [1], False, True])))
print(list(filter(lambda x: x > 0, [-2, -1, 0, 1, 2])))
print(list(filter(lambda x: x % 2 == 0, range(10))))

print("=== sorted ===")
print(sorted([3, 1, 4, 1, 5, 9]))
print(sorted([3, 1, 4, 1, 5, 9], reverse=True))
print(sorted(["banana", "apple", "cherry"]))
print(sorted(["banana", "apple", "cherry"], key=len))
print(sorted([(1, "b"), (2, "a"), (1, "a")]))

print("=== reversed ===")
print(list(reversed([1, 2, 3, 4, 5])))
print(list(reversed("hello")))
print(list(reversed(range(5))))
print(list(reversed((10, 20, 30))))

print("=== any / all ===")
print(any([False, False, True]))
print(any([False, False, False]))
print(any([]))
print(all([True, True, True]))
print(all([True, False, True]))
print(all([]))
print(any([0, 0, 1]))
print(all([1, 2, 3]))

print("=== sum ===")
print(sum([1, 2, 3]))
print(sum([1, 2, 3], 10))
print(sum([]))
print(sum([], 0))
print(sum([0.1, 0.2, 0.3]))
print(sum(range(100)))

print("=== min / max ===")
print(min(1, 2, 3))
print(max(1, 2, 3))
print(min([5, 3, 8, 1]))
print(max([5, 3, 8, 1]))
print(min("banana", "apple", "cherry"))
print(max("banana", "apple", "cherry"))
print(min([1, 2, 3], key=lambda x: -x))
print(max([1, 2, 3], key=lambda x: -x))
print(min([], default="empty"))
print(max([], default="empty"))

print("=== abs ===")
print(abs(0))
print(abs(-5))
print(abs(5))
print(abs(-3.14))

print("=== round ===")
print(round(3.7))
print(round(3.5))
print(round(4.5))
print(round(3.14159, 2))
print(round(3.14159, 0))
print(round(1234, -2))

print("=== isinstance ===")
print(isinstance(42, int))
print(isinstance(42, float))
print(isinstance(42, (int, float)))
print(isinstance("hi", str))
print(isinstance(True, int))
print(isinstance(True, bool))
print(isinstance(None, type(None)))

print("=== type ===")
print(type(42))
print(type("hi"))
print(type(3.14))
print(type(True))
print(type(None))
print(type([]))
print(type({}))
print(type(()))
print(type(set()))

print("=== hasattr / getattr / setattr ===")
class Obj:
    x = 10

o = Obj()
print(hasattr(o, "x"))
print(hasattr(o, "y"))
print(getattr(o, "x"))
print(getattr(o, "y", "default"))
setattr(o, "y", 20)
print(o.y)
print(hasattr(o, "y"))

print("=== delattr ===")
delattr(o, "y")
print(hasattr(o, "y"))

print("=== callable ===")
print(callable(print))
print(callable(len))
print(callable(42))
print(callable("hi"))
print(callable(lambda: None))
print(callable(Obj))

print("=== int / float / str / bool conversions ===")
print(int("42"))
print(int("0xff", 16))
print(int("0b1010", 2))
print(int("0o77", 8))
print(int(3.14))
print(int(-3.14))
print(int(True))
print(int(False))
print(float("3.14"))
print(float("inf"))
print(float("-inf"))
print(float("nan") != float("nan"))
print(float(42))
print(str(42))
print(str(3.14))
print(str(True))
print(str(None))
print(str([1, 2, 3]))
print(bool(0))
print(bool(1))
print(bool(""))
print(bool("hi"))
print(bool([]))
print(bool([1]))
print(bool(None))

print("=== repr ===")
print(repr(42))
print(repr("hello"))
print(repr([1, 2, 3]))
print(repr(None))
print(repr(True))
print(repr((1, 2)))
print(repr({"a": 1}))

print("=== chr / ord ===")
print(chr(65))
print(chr(97))
print(chr(8364))
print(ord("A"))
print(ord("a"))

print("=== hex / oct / bin ===")
print(hex(255))
print(hex(-1))
print(oct(8))
print(oct(0))
print(bin(10))
print(bin(-10))

print("=== divmod / pow ===")
print(divmod(17, 5))
print(divmod(-17, 5))
print(pow(2, 10))
print(pow(2, 10, 1000))
print(pow(3, -1))

print("=== hash ===")
print(type(hash(42)))
print(hash(42) == hash(42))
print(type(hash("hello")))
print(hash("hello") == hash("hello"))

print("=== id ===")
a = [1, 2, 3]
b = a
c = [1, 2, 3]
print(id(a) == id(b))
print(id(a) == id(c))

print("=== iter / next ===")
it = iter([10, 20, 30])
print(next(it))
print(next(it))
print(next(it))
print(next(it, "done"))

print("=== input to list/tuple/set/dict ===")
print(list("abc"))
print(tuple("abc"))
print(sorted(set("abcabc")))
print(dict([("a", 1), ("b", 2)]))
print(list(range(5)))

print("=== format ===")
print(format(42, "05d"))
print(format(3.14, ".1f"))
print(format(255, "x"))
print(format(255, "#x"))
print(format(1000000, ","))

print("=== ascii ===")
print(ascii("hello"))
print(ascii("caf\u00e9"))

print("=== vars on object ===")
class Simple:
    def __init__(self):
        self.a = 1
        self.b = 2
print(sorted(vars(Simple()).items()))

print("=== dir basics ===")
print("append" in dir([]))
print("upper" in dir(""))
print("keys" in dir({}))

print("=== bool edge cases ===")
print(bool(0))
print(bool(0.0))
print(bool(0j))
print(bool(""))
print(bool(b""))
print(bool([]))
print(bool(()))
print(bool({}))
print(bool(set()))
print(bool(None))
print(bool(1))
print(bool(-1))
print(bool("0"))
print(bool([0]))

print("=== slice ===")
s = slice(1, 5, 2)
print(s.start, s.stop, s.step)
print(s.indices(10))
