# Parity test: string operations
# All output via print() for diff comparison

print("=== String basics ===")
print("hello" + " " + "world")
print("ha" * 3)
print("" * 100)
print("abc" * 0)
print(len("hello"))
print(len(""))

print("=== Indexing and slicing ===")
s = "abcdefgh"
print(s[0])
print(s[-1])
print(s[2:5])
print(s[:3])
print(s[5:])
print(s[::2])
print(s[::-1])
print(s[1:6:2])
print(s[-3:])
print(s[:-3])

print("=== Case methods ===")
print("hello".upper())
print("HELLO".lower())
print("hello world".title())
print("hello world".capitalize())
print("Hello World".swapcase())
print("hello".casefold())

print("=== Strip methods ===")
print("  hello  ".strip())
print("  hello  ".lstrip())
print("  hello  ".rstrip())
print("xxhelloxx".strip("x"))
print("xxhelloxx".lstrip("x"))
print("xxhelloxx".rstrip("x"))

print("=== Find and search ===")
print("hello world".find("world"))
print("hello world".find("xyz"))
print("hello world".find("o"))
print("hello world".rfind("o"))
print("hello world".index("world"))
print("hello world".count("l"))
print("hello world".count("o"))
print("aaa".count("aa"))

print("=== Replace ===")
print("hello world".replace("world", "python"))
print("aaa".replace("a", "bb"))
print("aaa".replace("a", "bb", 2))
print("hello".replace("x", "y"))

print("=== Split and join ===")
print("a,b,c".split(","))
print("a,,b".split(","))
print("  a  b  c  ".split())
print("a,b,c".split(",", 1))
print(",".join(["a", "b", "c"]))
print("--".join(["x", "y", "z"]))
print("".join(["a", "b", "c"]))
print(",".join([]))
print("a\nb\nc".splitlines())
print("a\r\nb\nc\r".splitlines())

print("=== Startswith / endswith ===")
print("hello".startswith("hel"))
print("hello".startswith("xyz"))
print("hello".startswith(("hel", "xyz")))
print("hello".endswith("llo"))
print("hello".endswith("xyz"))
print("hello".endswith(("llo", "xyz")))

print("=== Predicates ===")
print("123".isdigit())
print("abc".isalpha())
print("abc123".isalnum())
print("   ".isspace())
print("Hello".istitle())
print("HELLO".isupper())
print("hello".islower())
print("".isdigit())
print("".isalpha())

print("=== Formatting ===")
print("hello %s, you are %d" % ("world", 42))
print("{} and {}".format("a", "b"))
print("{0} and {1} and {0}".format("a", "b"))
print("{name} is {age}".format(name="Alice", age=30))
print(f"{'hello':>10}")
print(f"{'hello':<10}|")
print(f"{'hello':^11}")
print(f"{42:05d}")
print(f"{3.14:.1f}")
print(f"{1000000:,}")
print(f"{255:#x}")
print(f"{255:#o}")
print(f"{255:#b}")

print("=== f-string expressions ===")
x = 42
print(f"x = {x}")
print(f"x + 1 = {x + 1}")
print(f"{'hello'.upper()}")
print(f"{[1,2,3]}")
print("{literal braces}")

print("=== Encode / decode ===")
print("hello".encode("utf-8"))
print("hello".encode("ascii"))
print(b"hello".decode("utf-8"))
print(b"hello".decode("ascii"))

print("=== Repr and str ===")
print(repr("hello"))
print(repr("hello\nworld"))
print(repr("hello\tworld"))
print(str(42))
print(str(3.14))
print(str(True))
print(str(None))

print("=== Membership ===")
print("ell" in "hello")
print("xyz" in "hello")
print("" in "hello")
print("hello" in "hello")

print("=== Misc methods ===")
print("hello".center(11))
print("hello".center(11, "-"))
print("hello".ljust(10))
print("hello".ljust(10, "."))
print("hello".rjust(10))
print("hello".rjust(10, "."))
print("hello".zfill(10))
print("-42".zfill(10))
print("tab\there".expandtabs(4))

print("=== Partition ===")
print("hello-world-foo".partition("-"))
print("hello-world-foo".rpartition("-"))
print("hello".partition("-"))
print("hello".rpartition("-"))

print("=== Maketrans / translate ===")
t = str.maketrans("aeiou", "12345")
print("hello world".translate(t))

print("=== Multiplication edge cases ===")
print("x" * -1)
print("x" * 0)
print("x" * 1)

print("=== String comparison ===")
print("abc" < "abd")
print("abc" < "abc")
print("abc" <= "abc")
print("abc" == "abc")
print("abc" != "abd")
print("a" < "b")
print("z" > "a")
