use super::*;

pub(super) type RuntimeTableFunc = (&'static str, &'static str, usize);

pub(super) fn builtin_table_funcs() -> Vec<RuntimeTableFunc> {
    let mut builtin_table_funcs: Vec<RuntimeTableFunc> = vec![
        ("molt_missing", "missing", 0),
        ("molt_pending", "pending", 0),
        ("molt_repr_builtin", "repr_builtin", 1),
        ("molt_format_builtin", "format_builtin", 2),
        ("molt_callable_builtin", "callable_builtin", 1),
        ("molt_round_builtin", "round_builtin", 2),
        ("molt_enumerate_builtin", "enumerate_builtin", 2),
        ("molt_iter_sentinel", "iter_sentinel", 2),
        ("molt_next_builtin", "next_builtin", 2),
        ("molt_any_builtin", "any_builtin", 1),
        ("molt_all_builtin", "all_builtin", 1),
        ("molt_sum_builtin", "sum_builtin", 2),
        ("molt_min_builtin", "min_builtin", 3),
        ("molt_max_builtin", "max_builtin", 3),
        ("molt_sorted_builtin", "sorted_builtin", 3),
        ("molt_map_builtin", "map_builtin", 2),
        ("molt_filter_builtin", "filter_builtin", 2),
        ("molt_zip_builtin", "zip_builtin", 2),
        ("molt_reversed_builtin", "reversed_builtin", 1),
        ("molt_getattr_builtin", "getattr_builtin", 3),
        ("molt_dir_builtin", "dir_builtin", 1),
        ("molt_vars_builtin", "vars_builtin", 1),
        ("molt_anext_builtin", "anext_builtin", 2),
        ("molt_print_builtin", "print_builtin", 5),
        ("molt_super_builtin", "super_builtin", 2),
        ("molt_set_attr_name", "set_attr_name", 3),
        ("molt_del_attr_name", "del_attr_name", 2),
        ("molt_has_attr_name", "has_attr_name", 2),
        ("molt_isinstance", "isinstance", 2),
        ("molt_issubclass", "issubclass", 2),
        ("molt_len", "len", 1),
        ("molt_len_dict", "len_dict", 1),
        ("molt_len_list", "len_list", 1),
        ("molt_len_set", "len_set", 1),
        ("molt_len_str", "len_str", 1),
        ("molt_len_tuple", "len_tuple", 1),
        ("molt_id", "id", 1),
        ("molt_hash_builtin", "hash_builtin", 1),
        ("molt_ord", "ord", 1),
        ("molt_ord_at", "ord_at", 2),
        ("molt_chr", "chr", 1),
        ("molt_ascii_from_obj", "ascii_from_obj", 1),
        ("molt_bin_builtin", "bin_builtin", 1),
        ("molt_oct_builtin", "oct_builtin", 1),
        ("molt_hex_builtin", "hex_builtin", 1),
        ("molt_abs_builtin", "abs_builtin", 1),
        ("molt_divmod_builtin", "divmod_builtin", 2),
        ("molt_open_builtin", "open_builtin", 8),
        ("molt_getargv", "getargv", 0),
        ("molt_getframe", "getframe", 1),
        ("molt_trace_enter_slot", "trace_enter_slot", 1),
        ("molt_trace_set_line", "trace_set_line", 1),
        ("molt_trace_exit", "trace_exit", 0),
        ("molt_sys_version_info", "sys_version_info", 0),
        ("molt_sys_version", "sys_version", 0),
        ("molt_sys_hexversion", "sys_hexversion", 0),
        ("molt_sys_api_version", "sys_api_version", 0),
        ("molt_sys_abiflags", "sys_abiflags", 0),
        (
            "molt_sys_implementation_payload",
            "sys_implementation_payload",
            0,
        ),
        ("molt_sys_stdin", "sys_stdin", 0),
        ("molt_sys_stdout", "sys_stdout", 0),
        ("molt_sys_stderr", "sys_stderr", 0),
        ("molt_sys_executable", "sys_executable", 0),
        ("molt_sys_set_version_info", "sys_set_version_info", 6),
        ("molt_env_get", "env_get", 2),
        ("molt_env_snapshot", "env_snapshot", 0),
        ("molt_capabilities_trusted", "capabilities_trusted", 0),
        ("molt_capabilities_has", "capabilities_has", 1),
        ("molt_capabilities_require", "capabilities_require", 1),
        ("molt_os_name", "os_name", 0),
        ("molt_os_close", "os_close", 1),
        ("molt_os_dup", "os_dup", 1),
        ("molt_os_get_inheritable", "os_get_inheritable", 1),
        ("molt_os_set_inheritable", "os_set_inheritable", 2),
        ("molt_os_urandom", "os_urandom", 1),
        ("molt_sys_platform", "sys_platform", 0),
        ("molt_errno_constants", "errno_constants", 0),
        ("molt_socket_constants", "socket_constants", 0),
        ("molt_socket_has_ipv6", "socket_has_ipv6", 0),
        ("molt_socket_new", "socket_new", 4),
        ("molt_socket_close", "socket_close", 1),
        ("molt_socket_drop", "socket_drop", 1),
        ("molt_socket_clone", "socket_clone", 1),
        ("molt_socket_fileno", "socket_fileno", 1),
        ("molt_socket_gettimeout", "socket_gettimeout", 1),
        ("molt_socket_settimeout", "socket_settimeout", 2),
        ("molt_socket_setblocking", "socket_setblocking", 2),
        ("molt_socket_getblocking", "socket_getblocking", 1),
        ("molt_socket_bind", "socket_bind", 2),
        ("molt_socket_listen", "socket_listen", 2),
        ("molt_socket_accept", "socket_accept", 1),
        ("molt_socket_connect", "socket_connect", 2),
        ("molt_socket_connect_ex", "socket_connect_ex", 2),
        ("molt_socket_recv", "socket_recv", 3),
        ("molt_socket_recv_into", "socket_recv_into", 4),
        ("molt_socket_send", "socket_send", 3),
        ("molt_socket_sendall", "socket_sendall", 3),
        ("molt_socket_sendto", "socket_sendto", 4),
        ("molt_socket_recvfrom", "socket_recvfrom", 3),
        ("molt_socket_shutdown", "socket_shutdown", 2),
        ("molt_socket_getsockname", "socket_getsockname", 1),
        ("molt_socket_getpeername", "socket_getpeername", 1),
        ("molt_socket_setsockopt", "socket_setsockopt", 4),
        ("molt_socket_getsockopt", "socket_getsockopt", 4),
        ("molt_socket_detach", "socket_detach", 1),
        ("molt_socketpair", "socketpair", 3),
        ("molt_socket_getaddrinfo", "socket_getaddrinfo", 6),
        ("molt_socket_getnameinfo", "socket_getnameinfo", 2),
        ("molt_socket_gethostname", "socket_gethostname", 0),
        ("molt_socket_getservbyname", "socket_getservbyname", 2),
        ("molt_socket_getservbyport", "socket_getservbyport", 2),
        ("molt_socket_inet_pton", "socket_inet_pton", 2),
        ("molt_socket_inet_ntop", "socket_inet_ntop", 2),
        ("molt_getpid", "getpid", 0),
        ("molt_getcwd", "getcwd", 0),
        ("molt_time_monotonic", "time_monotonic", 0),
        ("molt_time_monotonic_ns", "time_monotonic_ns", 0),
        ("molt_time_perf_counter", "time_perf_counter", 0),
        ("molt_time_perf_counter_ns", "time_perf_counter_ns", 0),
        ("molt_time_process_time", "time_process_time", 0),
        ("molt_time_process_time_ns", "time_process_time_ns", 0),
        ("molt_time_time", "time_time", 0),
        ("molt_time_time_ns", "time_time_ns", 0),
        ("molt_time_localtime", "time_localtime", 1),
        ("molt_time_gmtime", "time_gmtime", 1),
        ("molt_time_strftime", "time_strftime", 2),
        ("molt_time_timezone", "time_timezone", 0),
        ("molt_time_tzname", "time_tzname", 0),
        ("molt_math_log", "math_log", 1),
        ("molt_math_log2", "math_log2", 1),
        ("molt_math_exp", "math_exp", 1),
        ("molt_math_sin", "math_sin", 1),
        ("molt_math_cos", "math_cos", 1),
        ("molt_math_acos", "math_acos", 1),
        ("molt_math_lgamma", "math_lgamma", 1),
        ("molt_path_exists", "path_exists", 1),
        ("molt_path_listdir", "path_listdir", 1),
        ("molt_path_mkdir", "path_mkdir", 2),
        ("molt_path_unlink", "path_unlink", 1),
        ("molt_path_rmdir", "path_rmdir", 1),
        ("molt_path_chmod", "path_chmod", 2),
        ("molt_getrecursionlimit", "getrecursionlimit", 0),
        ("molt_setrecursionlimit", "setrecursionlimit", 1),
        ("molt_site_help0", "site_help0", 0),
        ("molt_site_help1", "site_help1", 1),
        ("molt_future_features", "future_features", 0),
        ("molt_exception_last", "exception_last", 0),
        ("molt_exception_last_pending", "exception_last_pending", 0),
        ("molt_exception_active", "exception_active", 0),
        ("molt_exception_current", "exception_current", 0),
        ("molt_exception_enter_handler", "exception_enter_handler", 1),
        (
            "molt_exception_resolve_captured",
            "exception_resolve_captured",
            1,
        ),
        ("molt_asyncgen_hooks_get", "asyncgen_hooks_get", 0),
        ("molt_asyncgen_hooks_set", "asyncgen_hooks_set", 2),
        ("molt_asyncgen_locals", "asyncgen_locals", 1),
        ("molt_gen_locals", "gen_locals", 1),
        ("molt_asyncgen_shutdown", "asyncgen_shutdown", 0),
        ("molt_code_new", "code_new", 9),
        ("molt_compile_builtin", "compile_builtin", 6),
        ("molt_module_new", "module_new", 1),
        ("molt_module_import", "module_import", 1),
        ("molt_module_cache_set", "module_cache_set", 2),
        ("molt_class_new", "class_new", 1),
        ("molt_class_set_base", "class_set_base", 2),
        ("molt_class_apply_set_name", "class_apply_set_name", 1),
        ("molt_class_merge_layout", "class_merge_layout", 3),
        (
            "molt_function_init_metadata_packed",
            "function_init_metadata_packed",
            4,
        ),
        ("molt_function_set_builtin", "function_set_builtin", 1),
        ("molt_function_set_defaults", "function_set_defaults", 3),
        ("molt_exceptiongroup_match", "exceptiongroup_match", 2),
        ("molt_exceptiongroup_combine", "exceptiongroup_combine", 1),
        ("molt_iter_checked", "iter", 1),
        ("molt_aiter", "aiter", 1),
        ("molt_io_wait_new", "io_wait_new", 3),
        ("molt_ws_wait_new", "ws_wait_new", 3),
        ("molt_ws_pair_obj", "ws_pair_obj", 1),
        ("molt_ws_connect_obj", "ws_connect_obj", 1),
        ("molt_ws_send_obj", "ws_send_obj", 2),
        ("molt_ws_recv", "ws_recv", 1),
        ("molt_ws_close", "ws_close", 1),
        ("molt_ws_drop", "ws_drop", 1),
        ("molt_future_cancel", "future_cancel", 1),
        ("molt_future_cancel_msg", "future_cancel_msg", 2),
        ("molt_future_cancel_clear", "future_cancel_clear", 1),
        ("molt_block_on", "block_on", 1),
        ("molt_lock_new", "lock_new", 0),
        ("molt_lock_acquire", "lock_acquire", 3),
        ("molt_lock_release", "lock_release", 1),
        ("molt_lock_locked", "lock_locked", 1),
        ("molt_lock_drop", "lock_drop", 1),
        ("molt_rlock_new", "rlock_new", 0),
        ("molt_rlock_acquire", "rlock_acquire", 3),
        ("molt_rlock_release", "rlock_release", 1),
        ("molt_rlock_locked", "rlock_locked", 1),
        ("molt_rlock_drop", "rlock_drop", 1),
        ("molt_chan_new", "chan_new", 1),
        ("molt_chan_send", "chan_send", 2),
        ("molt_chan_send_blocking", "chan_send_blocking", 2),
        ("molt_chan_try_send", "chan_try_send", 2),
        ("molt_chan_recv", "chan_recv", 1),
        ("molt_chan_recv_blocking", "chan_recv_blocking", 1),
        ("molt_chan_try_recv", "chan_try_recv", 1),
        ("molt_heapq_heapify", "heapq_heapify", 1),
        ("molt_heapq_heappush", "heapq_heappush", 2),
        ("molt_heapq_heappop", "heapq_heappop", 1),
        ("molt_heapq_heapreplace", "heapq_heapreplace", 2),
        ("molt_heapq_heappushpop", "heapq_heappushpop", 2),
        ("molt_struct_calcsize", "struct_calcsize", 1),
        ("molt_struct_pack", "struct_pack", 2),
        ("molt_struct_unpack", "struct_unpack", 2),
        ("molt_struct_pack_into", "struct_pack_into", 3),
        ("molt_struct_unpack_from", "struct_unpack_from", 3),
        ("molt_struct_iter_unpack", "struct_iter_unpack", 2),
        ("molt_thread_spawn", "thread_spawn", 1),
        ("molt_thread_join", "thread_join", 2),
        ("molt_thread_is_alive", "thread_is_alive", 1),
        ("molt_thread_ident", "thread_ident", 1),
        ("molt_thread_native_id", "thread_native_id", 1),
        ("molt_thread_current_ident", "thread_current_ident", 0),
        (
            "molt_thread_current_native_id",
            "thread_current_native_id",
            0,
        ),
        ("molt_thread_drop", "thread_drop", 1),
        ("molt_process_spawn", "process_spawn", 6),
        ("molt_process_wait_future", "process_wait_future", 1),
        ("molt_process_pid", "process_pid", 1),
        ("molt_process_returncode", "process_returncode", 1),
        ("molt_process_kill", "process_kill", 1),
        ("molt_process_terminate", "process_terminate", 1),
        ("molt_process_stdin", "process_stdin", 1),
        ("molt_process_stdout", "process_stdout", 1),
        ("molt_process_stderr", "process_stderr", 1),
        ("molt_process_drop", "process_drop", 1),
        ("molt_stream_new", "stream_new", 1),
        ("molt_stream_clone", "stream_clone", 1),
        ("molt_stream_send_obj", "stream_send_obj", 2),
        ("molt_stream_recv", "stream_recv", 1),
        ("molt_stream_close", "stream_close", 1),
        ("molt_stream_drop", "stream_drop", 1),
        ("molt_weakref_register", "weakref_register", 3),
        ("molt_weakref_get", "weakref_get", 1),
        ("molt_weakref_drop", "weakref_drop", 1),
    ];
    builtin_table_funcs.extend([
        (
            "molt_importlib_bootstrap_payload",
            "importlib_bootstrap_payload",
            2,
        ),
        (
            "molt_importlib_cache_from_source",
            "importlib_cache_from_source",
            1,
        ),
        (
            "molt_importlib_coerce_module_name",
            "importlib_coerce_module_name",
            3,
        ),
        ("molt_importlib_decode_source", "importlib_decode_source", 1),
        (
            "molt_importlib_ensure_default_meta_path",
            "importlib_ensure_default_meta_path",
            1,
        ),
        (
            "molt_importlib_exec_extension",
            "importlib_exec_extension",
            3,
        ),
        (
            "molt_importlib_exec_restricted_source",
            "importlib_exec_restricted_source",
            3,
        ),
        (
            "molt_importlib_exec_sourceless",
            "importlib_exec_sourceless",
            3,
        ),
        (
            "molt_importlib_extension_loader_payload",
            "importlib_extension_loader_payload",
            3,
        ),
        (
            "molt_importlib_filefinder_find_spec",
            "importlib_filefinder_find_spec",
            3,
        ),
        (
            "molt_importlib_filefinder_invalidate",
            "importlib_filefinder_invalidate",
            1,
        ),
        ("molt_importlib_find_in_path", "importlib_find_in_path", 2),
        (
            "molt_importlib_find_in_path_package_context",
            "importlib_find_in_path_package_context",
            2,
        ),
        ("molt_importlib_find_spec", "importlib_find_spec", 8),
        (
            "molt_importlib_find_spec_orchestrate",
            "importlib_find_spec_orchestrate",
            5,
        ),
        (
            "molt_importlib_frozen_external_payload",
            "importlib_frozen_external_payload",
            2,
        ),
        (
            "molt_importlib_frozen_payload",
            "importlib_frozen_payload",
            2,
        ),
        (
            "molt_importlib_import_transaction",
            "importlib_import_transaction",
            5,
        ),
        (
            "molt_importlib_import_optional",
            "importlib_import_optional",
            1,
        ),
        (
            "molt_importlib_import_or_fallback",
            "importlib_import_or_fallback",
            2,
        ),
        (
            "molt_importlib_import_required",
            "importlib_import_required",
            1,
        ),
        (
            "molt_importlib_invalidate_caches",
            "importlib_invalidate_caches",
            0,
        ),
        (
            "molt_importlib_known_absent_missing_name",
            "importlib_known_absent_missing_name",
            1,
        ),
        (
            "molt_importlib_load_module_shim",
            "importlib_load_module_shim",
            3,
        ),
        (
            "molt_importlib_metadata_dist_paths",
            "importlib_metadata_dist_paths",
            2,
        ),
        (
            "molt_importlib_metadata_distributions_payload",
            "importlib_metadata_distributions_payload",
            2,
        ),
        (
            "molt_importlib_metadata_entry_points_filter_payload",
            "importlib_metadata_entry_points_filter_payload",
            5,
        ),
        (
            "molt_importlib_metadata_entry_points_select_payload",
            "importlib_metadata_entry_points_select_payload",
            4,
        ),
        (
            "molt_importlib_metadata_normalize_name",
            "importlib_metadata_normalize_name",
            1,
        ),
        (
            "molt_importlib_metadata_packages_distributions_payload",
            "importlib_metadata_packages_distributions_payload",
            2,
        ),
        (
            "molt_importlib_metadata_payload",
            "importlib_metadata_payload",
            1,
        ),
        (
            "molt_importlib_metadata_record_payload",
            "importlib_metadata_record_payload",
            1,
        ),
        (
            "molt_importlib_metadata_types_payload",
            "importlib_metadata_types_payload",
            4,
        ),
        (
            "molt_importlib_module_from_spec",
            "importlib_module_from_spec",
            1,
        ),
        (
            "molt_importlib_module_spec_is_package",
            "importlib_module_spec_is_package",
            1,
        ),
        (
            "molt_importlib_package_root_from_origin",
            "importlib_package_root_from_origin",
            1,
        ),
        (
            "molt_importlib_path_is_archive_member",
            "importlib_path_is_archive_member",
            1,
        ),
        (
            "molt_importlib_pathfinder_find_spec",
            "importlib_pathfinder_find_spec",
            3,
        ),
        ("molt_importlib_read_file", "importlib_read_file", 1),
        ("molt_importlib_reload", "importlib_reload", 4),
        ("molt_importlib_resolve_name", "importlib_resolve_name", 2),
        (
            "molt_importlib_resources_as_file_enter",
            "importlib_resources_as_file_enter",
            2,
        ),
        (
            "molt_importlib_resources_as_file_exit",
            "importlib_resources_as_file_exit",
            3,
        ),
        (
            "molt_importlib_resources_contents_from_package",
            "importlib_resources_contents_from_package",
            3,
        ),
        (
            "molt_importlib_resources_contents_from_package_parts",
            "importlib_resources_contents_from_package_parts",
            4,
        ),
        (
            "molt_importlib_resources_files_payload",
            "importlib_resources_files_payload",
            4,
        ),
        (
            "molt_importlib_resources_is_resource_from_package",
            "importlib_resources_is_resource_from_package",
            4,
        ),
        (
            "molt_importlib_resources_is_resource_from_package_parts",
            "importlib_resources_is_resource_from_package_parts",
            4,
        ),
        (
            "molt_importlib_resources_joinpath",
            "importlib_resources_joinpath",
            2,
        ),
        (
            "molt_importlib_resources_loader_reader",
            "importlib_resources_loader_reader",
            2,
        ),
        (
            "molt_importlib_resources_module_name",
            "importlib_resources_module_name",
            2,
        ),
        (
            "molt_importlib_resources_normalize_path",
            "importlib_resources_normalize_path",
            1,
        ),
        (
            "molt_importlib_resources_only",
            "importlib_resources_only",
            3,
        ),
        (
            "molt_importlib_resources_open_mode_is_text",
            "importlib_resources_open_mode_is_text",
            1,
        ),
        (
            "molt_importlib_resources_open_resource_bytes_from_package",
            "importlib_resources_open_resource_bytes_from_package",
            4,
        ),
        (
            "molt_importlib_resources_open_resource_bytes_from_package_parts",
            "importlib_resources_open_resource_bytes_from_package_parts",
            4,
        ),
        (
            "molt_importlib_resources_package_info",
            "importlib_resources_package_info",
            3,
        ),
        (
            "molt_importlib_resources_package_leaf_name",
            "importlib_resources_package_leaf_name",
            1,
        ),
        (
            "molt_importlib_resources_path_payload",
            "importlib_resources_path_payload",
            1,
        ),
        (
            "molt_importlib_resources_read_text_from_package",
            "importlib_resources_read_text_from_package",
            6,
        ),
        (
            "molt_importlib_resources_read_text_from_package_parts",
            "importlib_resources_read_text_from_package_parts",
            6,
        ),
        (
            "molt_importlib_resources_reader_child_names",
            "importlib_resources_reader_child_names",
            2,
        ),
        (
            "molt_importlib_resources_reader_contents",
            "importlib_resources_reader_contents",
            1,
        ),
        (
            "molt_importlib_resources_reader_contents_from_roots",
            "importlib_resources_reader_contents_from_roots",
            1,
        ),
        (
            "molt_importlib_resources_reader_exists",
            "importlib_resources_reader_exists",
            2,
        ),
        (
            "molt_importlib_resources_reader_files_traversable",
            "importlib_resources_reader_files_traversable",
            1,
        ),
        (
            "molt_importlib_resources_reader_is_dir",
            "importlib_resources_reader_is_dir",
            2,
        ),
        (
            "molt_importlib_resources_reader_is_resource",
            "importlib_resources_reader_is_resource",
            2,
        ),
        (
            "molt_importlib_resources_reader_is_resource_from_roots",
            "importlib_resources_reader_is_resource_from_roots",
            2,
        ),
        (
            "molt_importlib_resources_reader_open_resource_bytes",
            "importlib_resources_reader_open_resource_bytes",
            2,
        ),
        (
            "molt_importlib_resources_reader_open_resource_bytes_from_roots",
            "importlib_resources_reader_open_resource_bytes_from_roots",
            2,
        ),
        (
            "molt_importlib_resources_reader_resource_path",
            "importlib_resources_reader_resource_path",
            2,
        ),
        (
            "molt_importlib_resources_reader_resource_path_from_roots",
            "importlib_resources_reader_resource_path_from_roots",
            2,
        ),
        (
            "molt_importlib_resources_reader_roots",
            "importlib_resources_reader_roots",
            1,
        ),
        (
            "molt_importlib_resources_resource_path_from_package",
            "importlib_resources_resource_path_from_package",
            4,
        ),
        (
            "molt_importlib_resources_resource_path_from_package_parts",
            "importlib_resources_resource_path_from_package_parts",
            4,
        ),
        (
            "molt_importlib_runtime_modules",
            "importlib_runtime_modules",
            0,
        ),
        (
            "molt_importlib_set_module_state",
            "importlib_set_module_state",
            8,
        ),
        (
            "molt_importlib_source_exec_payload",
            "importlib_source_exec_payload",
            3,
        ),
        (
            "molt_importlib_source_from_cache",
            "importlib_source_from_cache",
            1,
        ),
        ("molt_importlib_source_hash", "importlib_source_hash", 1),
        (
            "molt_importlib_sourceless_loader_payload",
            "importlib_sourceless_loader_payload",
            3,
        ),
        (
            "molt_importlib_spec_from_file_location",
            "importlib_spec_from_file_location",
            5,
        ),
        (
            "molt_importlib_spec_from_loader",
            "importlib_spec_from_loader",
            5,
        ),
        (
            "molt_importlib_stabilize_module_state",
            "importlib_stabilize_module_state",
            6,
        ),
        (
            "molt_importlib_validate_resource_name",
            "importlib_validate_resource_name",
            1,
        ),
        (
            "molt_importlib_zip_read_entry",
            "importlib_zip_read_entry",
            2,
        ),
        (
            "molt_importlib_zip_source_exec_payload",
            "importlib_zip_source_exec_payload",
            4,
        ),
        ("molt_os_access", "os_access", 2),
        ("molt_os_altsep", "os_altsep", 0),
        ("molt_os_chdir", "os_chdir", 1),
        ("molt_os_chmod", "os_chmod", 2),
        ("molt_os_cpu_count", "os_cpu_count", 0),
        ("molt_os_curdir", "os_curdir", 0),
        ("molt_os_devnull", "os_devnull", 0),
        ("molt_os_dup2", "os_dup2", 2),
        ("molt_os_extsep", "os_extsep", 0),
        ("molt_os_fdopen", "os_fdopen", 3),
        ("molt_os_fsencode", "os_fsencode", 1),
        ("molt_os_fspath", "os_fspath", 1),
        ("molt_os_fstat", "os_fstat", 1),
        ("molt_os_ftruncate", "os_ftruncate", 2),
        ("molt_os_get_terminal_size", "os_get_terminal_size", 1),
        ("molt_os_getcwd", "os_getcwd", 0),
        ("molt_os_getegid", "os_getegid", 0),
        ("molt_os_geteuid", "os_geteuid", 0),
        ("molt_os_getgid", "os_getgid", 0),
        ("molt_os_getloadavg", "os_getloadavg", 0),
        ("molt_os_getlogin", "os_getlogin", 0),
        ("molt_os_getpgrp", "os_getpgrp", 0),
        ("molt_os_getpid", "os_getpid", 0),
        ("molt_os_getppid", "os_getppid", 0),
        ("molt_os_getuid", "os_getuid", 0),
        ("molt_os_isatty", "os_isatty", 1),
        ("molt_os_kill", "os_kill", 2),
        ("molt_os_linesep", "os_linesep", 0),
        ("molt_os_link", "os_link", 2),
        ("molt_os_listdir", "os_listdir", 1),
        ("molt_os_lseek", "os_lseek", 3),
        ("molt_os_lstat", "os_lstat", 1),
        ("molt_os_mkdir", "os_mkdir", 2),
        ("molt_os_open", "os_open", 3),
        ("molt_os_open_flags", "os_open_flags", 0),
        ("molt_os_pardir", "os_pardir", 0),
        ("molt_os_path_commonpath", "os_path_commonpath", 1),
        ("molt_os_path_commonprefix", "os_path_commonprefix", 1),
        ("molt_os_path_getatime", "os_path_getatime", 1),
        ("molt_os_path_getctime", "os_path_getctime", 1),
        ("molt_os_path_getmtime", "os_path_getmtime", 1),
        ("molt_os_path_getsize", "os_path_getsize", 1),
        ("molt_os_path_realpath", "os_path_realpath", 1),
        ("molt_os_path_samefile", "os_path_samefile", 2),
        ("molt_os_pathsep", "os_pathsep", 0),
        ("molt_os_pipe", "os_pipe", 0),
        ("molt_os_read", "os_read", 2),
        ("molt_os_readlink", "os_readlink", 1),
        ("molt_os_removedirs", "os_removedirs", 1),
        ("molt_os_rename", "os_rename", 2),
        ("molt_os_replace", "os_replace", 2),
        ("molt_os_rmdir", "os_rmdir", 1),
        ("molt_os_scandir", "os_scandir", 1),
        ("molt_os_sendfile", "os_sendfile", 4),
        ("molt_os_sep", "os_sep", 0),
        ("molt_os_setpgrp", "os_setpgrp", 0),
        ("molt_os_setsid", "os_setsid", 0),
        ("molt_os_stat", "os_stat", 1),
        ("molt_os_symlink", "os_symlink", 2),
        ("molt_os_sysconf", "os_sysconf", 1),
        ("molt_os_sysconf_names", "os_sysconf_names", 0),
        ("molt_os_truncate", "os_truncate", 2),
        ("molt_os_umask", "os_umask", 1),
        ("molt_os_uname", "os_uname", 0),
        ("molt_os_utime", "os_utime", 3),
        ("molt_os_waitpid", "os_waitpid", 2),
        ("molt_os_walk", "os_walk", 3),
        ("molt_os_wexitstatus", "os_wexitstatus", 1),
        ("molt_os_wifexited", "os_wifexited", 1),
        ("molt_os_wifsignaled", "os_wifsignaled", 1),
        ("molt_os_wifstopped", "os_wifstopped", 1),
        ("molt_os_write", "os_write", 2),
        ("molt_os_wstopsig", "os_wstopsig", 1),
        ("molt_os_wtermsig", "os_wtermsig", 1),
    ]);

    builtin_table_funcs
}

pub(super) fn seed_poll_table_indices(func_to_table_idx: &mut BTreeMap<String, u32>) {
    for (slot, import_name) in POLL_TABLE_FUNCS.iter().enumerate() {
        func_to_table_idx.insert(format!("molt_{import_name}"), (slot + 1) as u32);
    }
}
