#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum LirRuntimeCall {
    Add,
    Sub,
    Mul,
    Div,
    FloorDiv,
    Mod,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Is,
    BitAnd,
    BitOr,
    BitXor,
    Invert,
    LShift,
    RShift,
    Neg,
    Pos,
    Pow,
    Index,
    StoreIndex,
    DelIndex,
    DictGetitem,
    DictSetitem,
    TupleGetitem,
    ListIntGetitem,
    ListIntSetitem,
    Iter,
    IterNext,
    Contains,
    DictContains,
    ListContains,
    SetContains,
    StrContains,
    SliceNew,
    OrdAt,
    Not,
    IsTruthy,
    ExceptionPending,
    FunctionDefaultsVersion,
    ModuleCacheGet,
    ModuleCacheSet,
    ModuleCacheDel,
    ModuleGetAttr,
    ModuleImportFrom,
    ModuleGetGlobal,
    ModuleGetName,
    ModuleSetAttr,
    ModuleDelGlobal,
    ModuleDelGlobalIfPresent,
    IncRefObj,
    DecRefObj,
    IntFromI64,
}

impl LirRuntimeCall {
    #[cfg(test)]
    pub(crate) const ALL: &'static [Self] = &[
        Self::Add,
        Self::Sub,
        Self::Mul,
        Self::Div,
        Self::FloorDiv,
        Self::Mod,
        Self::Eq,
        Self::Ne,
        Self::Lt,
        Self::Le,
        Self::Gt,
        Self::Ge,
        Self::Is,
        Self::BitAnd,
        Self::BitOr,
        Self::BitXor,
        Self::Invert,
        Self::LShift,
        Self::RShift,
        Self::Neg,
        Self::Pos,
        Self::Pow,
        Self::Index,
        Self::StoreIndex,
        Self::DelIndex,
        Self::DictGetitem,
        Self::DictSetitem,
        Self::TupleGetitem,
        Self::ListIntGetitem,
        Self::ListIntSetitem,
        Self::Iter,
        Self::IterNext,
        Self::Contains,
        Self::DictContains,
        Self::ListContains,
        Self::SetContains,
        Self::StrContains,
        Self::SliceNew,
        Self::OrdAt,
        Self::Not,
        Self::IsTruthy,
        Self::ExceptionPending,
        Self::FunctionDefaultsVersion,
        Self::ModuleCacheGet,
        Self::ModuleCacheSet,
        Self::ModuleCacheDel,
        Self::ModuleGetAttr,
        Self::ModuleImportFrom,
        Self::ModuleGetGlobal,
        Self::ModuleGetName,
        Self::ModuleSetAttr,
        Self::ModuleDelGlobal,
        Self::ModuleDelGlobalIfPresent,
        Self::IncRefObj,
        Self::DecRefObj,
        Self::IntFromI64,
    ];

    pub(crate) const fn import_name(self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Sub => "sub",
            Self::Mul => "mul",
            Self::Div => "div",
            Self::FloorDiv => "floordiv",
            Self::Mod => "mod",
            Self::Eq => "eq",
            Self::Ne => "ne",
            Self::Lt => "lt",
            Self::Le => "le",
            Self::Gt => "gt",
            Self::Ge => "ge",
            Self::Is => "is",
            Self::BitAnd => "bit_and",
            Self::BitOr => "bit_or",
            Self::BitXor => "bit_xor",
            Self::Invert => "invert",
            Self::LShift => "lshift",
            Self::RShift => "rshift",
            Self::Neg => "neg",
            Self::Pos => "pos",
            Self::Pow => "pow",
            Self::Index => "index",
            Self::StoreIndex => "store_index",
            Self::DelIndex => "del_index",
            Self::DictGetitem => "dict_getitem",
            Self::DictSetitem => "dict_setitem",
            Self::TupleGetitem => "tuple_getitem",
            Self::ListIntGetitem => "list_int_getitem",
            Self::ListIntSetitem => "list_int_setitem",
            Self::Iter => "iter",
            Self::IterNext => "iter_next",
            Self::Contains => "contains",
            Self::DictContains => "dict_contains",
            Self::ListContains => "list_contains",
            Self::SetContains => "set_contains",
            Self::StrContains => "str_contains",
            Self::SliceNew => "slice_new",
            Self::OrdAt => "ord_at",
            Self::Not => "not",
            Self::IsTruthy => "is_truthy",
            Self::ExceptionPending => "exception_pending",
            Self::FunctionDefaultsVersion => "function_defaults_version",
            Self::ModuleCacheGet => "module_cache_get",
            Self::ModuleCacheSet => "module_cache_set",
            Self::ModuleCacheDel => "module_cache_del",
            Self::ModuleGetAttr => "module_get_attr",
            Self::ModuleImportFrom => "module_import_from",
            Self::ModuleGetGlobal => "module_get_global",
            Self::ModuleGetName => "module_get_name",
            Self::ModuleSetAttr => "module_set_attr",
            Self::ModuleDelGlobal => "module_del_global",
            Self::ModuleDelGlobalIfPresent => "module_del_global_if_present",
            Self::IncRefObj => "inc_ref_obj",
            Self::DecRefObj => "dec_ref_obj",
            Self::IntFromI64 => "int_from_i64",
        }
    }
}
