#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum LirRuntimeCall {
    Add,
    Sub,
    Mul,
    Div,
    FloorDiv,
    Mod,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Is,
    BitAnd,
    BitOr,
    BitXor,
    Invert,
    LShift,
    RShift,
    Neg,
    Pos,
    Pow,
    Index,
    StoreIndex,
    DelIndex,
    DictGetitem,
    DictSetitem,
    TupleGetitem,
    ListIntGetitem,
    ListIntSetitem,
    Not,
    IsTruthy,
    IncRefObj,
    DecRefObj,
    IntFromI64,
}

impl LirRuntimeCall {
    #[cfg(test)]
    pub(crate) const ALL: &'static [Self] = &[
        Self::Add,
        Self::Sub,
        Self::Mul,
        Self::Div,
        Self::FloorDiv,
        Self::Mod,
        Self::Eq,
        Self::Ne,
        Self::Lt,
        Self::Le,
        Self::Gt,
        Self::Ge,
        Self::Is,
        Self::BitAnd,
        Self::BitOr,
        Self::BitXor,
        Self::Invert,
        Self::LShift,
        Self::RShift,
        Self::Neg,
        Self::Pos,
        Self::Pow,
        Self::Index,
        Self::StoreIndex,
        Self::DelIndex,
        Self::DictGetitem,
        Self::DictSetitem,
        Self::TupleGetitem,
        Self::ListIntGetitem,
        Self::ListIntSetitem,
        Self::Not,
        Self::IsTruthy,
        Self::IncRefObj,
        Self::DecRefObj,
        Self::IntFromI64,
    ];

    pub(crate) const fn import_name(self) -> &'static str {
        match self {
            Self::Add => "add",
            Self::Sub => "sub",
            Self::Mul => "mul",
            Self::Div => "div",
            Self::FloorDiv => "floordiv",
            Self::Mod => "mod",
            Self::Eq => "eq",
            Self::Ne => "ne",
            Self::Lt => "lt",
            Self::Le => "le",
            Self::Gt => "gt",
            Self::Ge => "ge",
            Self::Is => "is",
            Self::BitAnd => "bit_and",
            Self::BitOr => "bit_or",
            Self::BitXor => "bit_xor",
            Self::Invert => "invert",
            Self::LShift => "lshift",
            Self::RShift => "rshift",
            Self::Neg => "neg",
            Self::Pos => "pos",
            Self::Pow => "pow",
            Self::Index => "index",
            Self::StoreIndex => "store_index",
            Self::DelIndex => "del_index",
            Self::DictGetitem => "dict_getitem",
            Self::DictSetitem => "dict_setitem",
            Self::TupleGetitem => "tuple_getitem",
            Self::ListIntGetitem => "list_int_getitem",
            Self::ListIntSetitem => "list_int_setitem",
            Self::Not => "not",
            Self::IsTruthy => "is_truthy",
            Self::IncRefObj => "inc_ref_obj",
            Self::DecRefObj => "dec_ref_obj",
            Self::IntFromI64 => "int_from_i64",
        }
    }
}
