use super::*;

#[test]
fn runtime_import_aliases_follow_manifest_runtime_names() {
    assert_eq!(
        wasm_runtime_import("importlib_import_transaction"),
        Some(WasmRuntimeImport::ImportlibImportTransaction)
    );
    assert_eq!(
        wasm_runtime_import("molt_importlib_import_transaction"),
        Some(WasmRuntimeImport::ImportlibImportTransaction)
    );
    assert_eq!(
        wasm_runtime_import("socket_drop"),
        Some(WasmRuntimeImport::SocketDrop)
    );
    assert_eq!(
        wasm_runtime_import("molt_socket_drop"),
        Some(WasmRuntimeImport::SocketDrop)
    );
    assert_eq!(
        wasm_runtime_import("runtime_init"),
        Some(WasmRuntimeImport::RuntimeInit)
    );
    assert_eq!(
        wasm_runtime_import("molt_runtime_init"),
        Some(WasmRuntimeImport::RuntimeInit)
    );
    assert_eq!(
        wasm_runtime_import("runtime_shutdown"),
        Some(WasmRuntimeImport::RuntimeShutdown)
    );
    assert_eq!(
        wasm_runtime_import("molt_runtime_shutdown"),
        Some(WasmRuntimeImport::RuntimeShutdown)
    );
    assert_eq!(
        WasmRuntimeImport::ImportlibImportTransaction.runtime_export_name(),
        "molt_importlib_import_transaction"
    );
    assert_eq!(
        WasmRuntimeImport::RuntimeInit.runtime_export_name(),
        "molt_runtime_init"
    );
    assert_eq!(
        wasm_runtime_export_name("importlib_import_transaction"),
        Some("molt_importlib_import_transaction")
    );
    assert_eq!(
        wasm_runtime_export_name("molt_importlib_import_transaction"),
        Some("molt_importlib_import_transaction")
    );
    assert_eq!(
        wasm_runtime_export_name("socket_drop"),
        Some("molt_socket_drop")
    );
    assert_eq!(
        wasm_runtime_export_name("molt_runtime_init"),
        Some("molt_runtime_init")
    );
}
