from typing import Any

def molt_chan_new(maxsize: int = ...) -> Any: ...
def molt_chan_send(chan: Any, val: Any) -> int: ...
def molt_chan_recv(chan: Any) -> Any: ...
def molt_chan_try_send(chan: Any, val: Any) -> int: ...
def molt_chan_try_recv(chan: Any) -> Any: ...
def molt_chan_send_blocking(chan: Any, val: Any) -> int: ...
def molt_chan_recv_blocking(chan: Any) -> Any: ...
def molt_chan_drop(chan: Any) -> None: ...
def molt_pending() -> Any: ...
def molt_spawn(task: Any) -> None: ...
def molt_async_sleep(_delay: float = ..., _result: Any | None = ...) -> Any: ...
def molt_time_monotonic() -> float: ...
def molt_time_monotonic_ns() -> int: ...
def molt_time_time() -> float: ...
def molt_time_time_ns() -> int: ...
def molt_os_dup(fd: int) -> int: ...
def molt_os_get_inheritable(fd: int) -> bool: ...
def molt_os_set_inheritable(fd: int, inheritable: bool) -> None: ...
def molt_path_listdir(path: Any) -> list[str]: ...
def molt_path_mkdir(path: Any) -> None: ...
def molt_path_chmod(path: Any, mode: int) -> None: ...
def molt_cancel_token_new(parent: int | None = ...) -> int: ...
def molt_cancel_token_clone(token_id: int) -> None: ...
def molt_cancel_token_drop(token_id: int) -> None: ...
def molt_cancel_token_cancel(token_id: int) -> None: ...
def molt_cancel_token_is_cancelled(token_id: int) -> bool: ...
def molt_cancel_token_set_current(token_id: int | None) -> int: ...
def molt_cancel_token_get_current() -> int: ...
def molt_future_cancel(future: Any) -> None: ...
def molt_future_cancel_msg(future: Any, msg: Any) -> None: ...
def molt_future_cancel_clear(future: Any) -> None: ...
def molt_promise_new() -> Any: ...
def molt_promise_set_result(future: Any, result: Any) -> None: ...
def molt_promise_set_exception(future: Any, exc: Any) -> None: ...
def molt_task_register_token_owned(task: Any, token_id: int) -> None: ...
def molt_io_wait(future: Any) -> int: ...
def molt_io_wait_new(socket: Any, events: int, timeout: float | None) -> Any: ...
def molt_thread_submit(fn: Any, args: Any, kwargs: Any) -> Any: ...
def molt_thread_spawn(payload: bytes) -> Any: ...
def molt_thread_join(handle: Any, timeout: float | None) -> Any: ...
def molt_thread_is_alive(handle: Any) -> bool: ...
def molt_thread_ident(handle: Any) -> int | None: ...
def molt_thread_native_id(handle: Any) -> int | None: ...
def molt_thread_current_ident() -> int: ...
def molt_thread_current_native_id() -> int: ...
def molt_thread_drop(handle: Any) -> None: ...
def molt_thread_poll(future: Any) -> int: ...
def molt_lock_new() -> Any: ...
def molt_lock_acquire(handle: Any, blocking: bool, timeout: float | None) -> bool: ...
def molt_lock_release(handle: Any) -> None: ...
def molt_lock_locked(handle: Any) -> bool: ...
def molt_lock_drop(handle: Any) -> None: ...
def molt_rlock_new() -> Any: ...
def molt_rlock_acquire(handle: Any, blocking: bool, timeout: float | None) -> bool: ...
def molt_rlock_release(handle: Any) -> None: ...
def molt_rlock_locked(handle: Any) -> bool: ...
def molt_rlock_drop(handle: Any) -> None: ...
def molt_process_spawn(
    args: Any,
    env: Any,
    cwd: Any,
    stdin: Any,
    stdout: Any,
    stderr: Any,
) -> Any: ...
def molt_process_wait_future(proc: Any) -> Any: ...
def molt_process_poll(future: Any) -> int: ...
def molt_process_pid(proc: Any) -> int: ...
def molt_process_returncode(proc: Any) -> int | None: ...
def molt_process_kill(proc: Any) -> None: ...
def molt_process_terminate(proc: Any) -> None: ...
def molt_process_stdin(proc: Any) -> Any: ...
def molt_process_stdout(proc: Any) -> Any: ...
def molt_process_stderr(proc: Any) -> Any: ...
def molt_process_drop(proc: Any) -> None: ...
def molt_stream_new(capacity: int) -> Any: ...
def molt_stream_clone(stream: Any) -> Any: ...
def molt_stream_send_obj(stream: Any, data: Any) -> int: ...
def molt_stream_recv(stream: Any) -> Any: ...
def molt_stream_close(stream: Any) -> None: ...
def molt_stream_drop(stream: Any) -> None: ...
def molt_socket_new(
    family: int,
    type: int,
    proto: int,
    fileno: int | None,
) -> Any: ...
def molt_socket_close(sock: Any) -> None: ...
def molt_socket_drop(sock: Any) -> None: ...
def molt_socket_clone(sock: Any) -> Any: ...
def molt_socket_fileno(sock: Any) -> int: ...
def molt_socket_gettimeout(sock: Any) -> float | None: ...
def molt_socket_settimeout(sock: Any, timeout: float | None) -> None: ...
def molt_socket_setblocking(sock: Any, flag: bool) -> None: ...
def molt_socket_getblocking(sock: Any) -> bool: ...
def molt_socket_bind(sock: Any, addr: Any) -> None: ...
def molt_socket_listen(sock: Any, backlog: int) -> None: ...
def molt_socket_accept(sock: Any) -> tuple[Any, Any]: ...
def molt_socket_connect(sock: Any, addr: Any) -> None: ...
def molt_socket_connect_ex(sock: Any, addr: Any) -> int: ...
def molt_socket_recv(sock: Any, size: int, flags: int) -> bytes: ...
def molt_socket_recv_into(sock: Any, buffer: Any, size: int, flags: int) -> int: ...
def molt_socket_send(sock: Any, data: Any, flags: int) -> int: ...
def molt_socket_sendall(sock: Any, data: Any, flags: int) -> None: ...
def molt_socket_sendto(sock: Any, data: Any, flags: int, addr: Any) -> int: ...
def molt_socket_recvfrom(sock: Any, size: int, flags: int) -> tuple[bytes, Any]: ...
def molt_socket_shutdown(sock: Any, how: int) -> None: ...
def molt_socket_getsockname(sock: Any) -> Any: ...
def molt_socket_getpeername(sock: Any) -> Any: ...
def molt_socket_setsockopt(sock: Any, level: int, optname: int, value: Any) -> None: ...
def molt_socket_getsockopt(sock: Any, level: int, optname: int, buflen: int) -> Any: ...
def molt_socket_detach(sock: Any) -> int: ...
def molt_socketpair(
    family: int | None, type: int | None, proto: int | None
) -> tuple[Any, Any]: ...
def molt_socket_getaddrinfo(
    host: str | bytes | None,
    port: int | str | bytes | None,
    family: int,
    type: int,
    proto: int,
    flags: int,
) -> list[tuple[int, int, int, str | None, Any]]: ...
def molt_socket_getnameinfo(addr: Any, flags: int) -> tuple[str, str]: ...
def molt_socket_gethostname() -> str: ...
def molt_socket_getservbyname(name: str, proto: str | None) -> int: ...
def molt_socket_getservbyport(port: int, proto: str | None) -> str: ...
def molt_socket_inet_pton(family: int, address: str) -> bytes: ...
def molt_socket_inet_ntop(family: int, packed: bytes) -> str: ...
def molt_socket_constants() -> dict[str, int]: ...
def molt_socket_has_ipv6() -> bool: ...
def molt_code_new(
    filename: str,
    name: str,
    firstlineno: int,
    linetable: Any,
) -> Any: ...
def molt_code_slots_init(count: int) -> None: ...
def molt_code_slot_set(code_id: int, code: Any) -> None: ...
def molt_module_new(name: str) -> Any: ...
def molt_module_cache_set(name: str, module: Any) -> Any: ...
def molt_asyncgen_hooks_get() -> Any: ...
def molt_asyncgen_hooks_set(firstiter: Any, finalizer: Any) -> Any: ...
def molt_asyncgen_locals(asyncgen: Any) -> Any: ...
def molt_function_set_builtin(func: Any) -> None: ...
def molt_class_new(name: str) -> Any: ...
def molt_class_set_base(cls: Any, base: Any) -> Any: ...
def molt_class_apply_set_name(cls: Any) -> Any: ...
def molt_sys_set_version_info(
    major: int,
    minor: int,
    micro: int,
    releaselevel: str,
    serial: int,
    version: str,
) -> Any: ...
def molt_sys_version_info() -> tuple[int, int, int, str, int]: ...
def molt_sys_version() -> str: ...
def molt_sys_stdin() -> Any: ...
def molt_sys_stdout() -> Any: ...
def molt_sys_stderr() -> Any: ...
def molt_trace_enter_slot(code_id: int) -> Any: ...
def molt_trace_set_line(line: int) -> None: ...
