from typing import Any

def molt_chan_new(maxsize: int = ...) -> Any: ...
def molt_chan_send(chan: Any, val: Any) -> int: ...
def molt_chan_recv(chan: Any) -> Any: ...
def molt_spawn(task: Any) -> None: ...
def molt_async_sleep(_delay: float = ..., _result: Any | None = ...) -> Any: ...
def molt_cancel_token_new(parent: int | None = ...) -> int: ...
def molt_cancel_token_clone(token_id: int) -> None: ...
def molt_cancel_token_drop(token_id: int) -> None: ...
def molt_cancel_token_cancel(token_id: int) -> None: ...
def molt_cancel_token_is_cancelled(token_id: int) -> bool: ...
def molt_cancel_token_set_current(token_id: int | None) -> int: ...
def molt_cancel_token_get_current() -> int: ...
