"""Generated runtime intrinsic symbol-prefix feature gates.

Source authorities:
- runtime/molt-runtime/src/intrinsics/categories.toml owns symbol-prefix feature attribution.
- runtime/molt-runtime/Cargo.toml and cfg-gated runtime modules own whether disabling a feature removes linked symbols.
"""

# @generated by tools/gen_intrinsics.py. DO NOT EDIT.

from __future__ import annotations

RUNTIME_FEATURE_GATES: tuple[tuple[str, str], ...] = (
    ("molt_math_", "stdlib_math"),
    ("molt_cmath_", "stdlib_math"),
    ("molt_colorsys_", "stdlib_math"),
    ("molt_fraction_", "stdlib_math"),
    ("molt_random_", "stdlib_math"),
    ("molt_statistics_", "stdlib_math"),
    ("molt_struct_", "stdlib_serial"),
    ("molt_csv_", "stdlib_csv"),
    ("molt_asyncio_", "stdlib_asyncio"),
    ("molt_event_loop_", "stdlib_asyncio"),
    ("molt_pipe_transport_", "stdlib_asyncio"),
    ("molt_argparse_", "stdlib_collections"),
    ("molt_namedtuple_", "stdlib_collections"),
    ("molt_ordereddict_", "stdlib_collections"),
    ("molt_defaultdict_", "stdlib_collections"),
    ("molt_deque_", "stdlib_collections"),
    ("molt_counter_", "stdlib_collections"),
    ("molt_chainmap_", "stdlib_collections"),
    ("molt_importlib_resources_", "stdlib_importlib_extra"),
    ("molt_importlib_metadata_", "stdlib_importlib_extra"),
    ("molt_stringprep_", "stdlib_stringprep"),
    ("molt_sqlite3_", "sqlite"),
    ("molt_hash_", "stdlib_crypto"),
    ("molt_hmac_", "stdlib_crypto"),
    ("molt_compare_digest", "stdlib_crypto"),
    ("molt_pbkdf2_", "stdlib_crypto"),
    ("molt_scrypt", "stdlib_crypto"),
    ("molt_secrets_", "stdlib_crypto"),
    ("molt_bz2_", "stdlib_compression"),
    ("molt_lzma_", "stdlib_compression"),
    ("molt_deflate_", "stdlib_compression"),
    ("molt_inflate_", "stdlib_compression"),
    ("molt_gzip_", "stdlib_compression"),
    ("molt_tarfile_", "stdlib_compression"),
    ("molt_zlib_", "stdlib_compression"),
    ("molt_compression_streams_", "stdlib_compression"),
    ("molt_cbor_", "stdlib_serialization"),
    ("molt_msgpack_", "stdlib_serialization"),
    ("molt_base64_", "stdlib_serial"),
    ("molt_binascii_", "stdlib_serial"),
    ("molt_configparser_", "stdlib_serial"),
    ("molt_datetime_", "stdlib_serial"),
    ("molt_date_", "stdlib_serial"),
    ("molt_timedelta_", "stdlib_serial"),
    ("molt_timezone_", "stdlib_serial"),
    ("molt_uu_codec", "stdlib_serial"),
    ("molt_difflib_", "stdlib_difflib"),
    ("molt_xml_", "stdlib_xml"),
    ("molt_xml_sax_", "stdlib_xml"),
    ("molt_ast_", "stdlib_ast"),
    ("molt_glob_glob", "stdlib_fs_extra"),
    ("molt_glob_iglob", "stdlib_fs_extra"),
    ("molt_glob_pattern", "stdlib_fs_extra"),
    ("molt_tempfile_", "stdlib_fs_extra"),
    ("molt_zipfile_", "stdlib_archive"),
    ("molt_imghdr_", "stdlib_archive"),
    ("molt_tk_", "stdlib_tk"),
    ("molt_html_", "stdlib_text"),
    ("molt_unicodedata_", "stdlib_text"),
    ("molt_zoneinfo_", "stdlib_zoneinfo"),
    ("molt_ctypes_", "stdlib_http"),
    ("molt_http_", "stdlib_http"),
    ("molt_socketserver_", "stdlib_http"),
    ("molt_urllib_", "stdlib_http"),
    ("molt_re_finditer_collect", "stdlib_regex"),
    ("molt_re_fullmatch_check", "stdlib_regex"),
    ("molt_re_match_groupdict", "stdlib_regex"),
    ("molt_re_match_groups", "stdlib_regex"),
    ("molt_re_match_group", "stdlib_regex"),
    ("molt_re_named_backref_advance", "stdlib_regex"),
    ("molt_re_negative_", "stdlib_regex"),
    ("molt_re_pattern_info", "stdlib_regex"),
    ("molt_re_positive_", "stdlib_regex"),
    ("molt_re_strip_verbose", "stdlib_regex"),
    ("molt_re_sub_callable", "stdlib_regex"),
    ("molt_re_compile", "stdlib_regex"),
    ("molt_re_execute", "stdlib_regex"),
    ("molt_re_escape", "stdlib_regex"),
    ("molt_re_split", "stdlib_regex"),
    ("molt_re_sub", "stdlib_regex"),
    ("molt_ipaddress_", "stdlib_ipaddress"),
    ("molt_email_", "stdlib_email"),
    ("molt_quopri_", "stdlib_email"),
    ("molt_decimal_", "stdlib_decimal"),
    ("molt_logging_", "stdlib_logging"),
    ("molt_logging_record_", "stdlib_logging_ext"),
    ("molt_logging_formatter_", "stdlib_logging_ext"),
    ("molt_logging_handler_", "stdlib_logging_ext"),
    ("molt_logging_stream_handler_", "stdlib_logging_ext"),
    ("molt_logging_logger_", "stdlib_logging_ext"),
    ("molt_logging_manager_", "stdlib_logging_ext"),
    ("molt_logging_root_logger", "stdlib_logging_ext"),
    ("molt_logging_basic_config", "stdlib_logging_ext"),
    ("molt_logging_shutdown", "stdlib_logging_ext"),
    ("molt_logging_get_level_name", "stdlib_logging_ext"),
    ("molt_logging_add_level_name", "stdlib_logging_ext"),
    ("molt_logging_level_to_int", "stdlib_logging_ext"),
    ("molt_concurrent_", "stdlib_concurrent"),
    ("molt_dbm_", "stdlib_dbm"),
    ("molt_signal_", "stdlib_signal"),
    ("molt_select_", "stdlib_select"),
    ("molt_gpu_prim_", "molt_gpu_primitives"),
)

LINK_AFFECTING_FEATURES: frozenset[str] = frozenset(
    {
        "molt_gpu_primitives",
        "sqlite",
        "stdlib_archive",
        "stdlib_ast",
        "stdlib_asyncio",
        "stdlib_collections",
        "stdlib_compression",
        "stdlib_crypto",
        "stdlib_csv",
        "stdlib_decimal",
        "stdlib_difflib",
        "stdlib_email",
        "stdlib_fs_extra",
        "stdlib_http",
        "stdlib_ipaddress",
        "stdlib_logging_ext",
        "stdlib_math",
        "stdlib_regex",
        "stdlib_serial",
        "stdlib_serialization",
        "stdlib_stringprep",
        "stdlib_text",
        "stdlib_tk",
        "stdlib_xml",
        "stdlib_zoneinfo",
    }
)


def feature_gate_for_symbol(symbol: str) -> str | None:
    """Return the Cargo feature gate for *symbol*, or None."""
    best: tuple[int, str] | None = None
    for prefix, feature in RUNTIME_FEATURE_GATES:
        if symbol.startswith(prefix):
            prefix_len = len(prefix)
            if best is None or prefix_len > best[0]:
                best = (prefix_len, feature)
    return best[1] if best is not None else None


def link_affecting_feature_gate_for_symbol(symbol: str) -> str | None:
    """Return *symbol*'s feature only when disabling it breaks link."""
    feature = feature_gate_for_symbol(symbol)
    if feature is None or feature not in LINK_AFFECTING_FEATURES:
        return None
    return feature
