"""Purpose: differential coverage for signal module constants."""

import signal

print("SIG_DFL:", signal.SIG_DFL)
print("SIG_IGN:", signal.SIG_IGN)
print("SIGINT:", signal.SIGINT)
print("SIGTERM:", signal.SIGTERM)
print("SIGHUP:", signal.SIGHUP)
print("SIGQUIT:", signal.SIGQUIT)
print("SIGABRT:", signal.SIGABRT)
print("SIGBUS:", signal.SIGBUS)
print("SIGFPE:", signal.SIGFPE)
print("SIGILL:", signal.SIGILL)
print("SIGSEGV:", signal.SIGSEGV)
print("SIGPIPE:", signal.SIGPIPE)
print("SIGALRM:", signal.SIGALRM)
print("SIGUSR1:", signal.SIGUSR1)
print("SIGUSR2:", signal.SIGUSR2)
print("SIGCHLD:", signal.SIGCHLD)
print("SIGCONT:", signal.SIGCONT)
print("SIGSTOP:", signal.SIGSTOP)
print("SIGTSTP:", signal.SIGTSTP)
print("SIGTTIN:", signal.SIGTTIN)
print("SIGTTOU:", signal.SIGTTOU)
print("SIGXCPU:", signal.SIGXCPU)
print("SIGXFSZ:", signal.SIGXFSZ)
print("SIGVTALRM:", signal.SIGVTALRM)
print("SIGPROF:", signal.SIGPROF)
print("SIGWINCH:", signal.SIGWINCH)
print("SIGSYS:", signal.SIGSYS)
print("NSIG:", signal.NSIG)
print("SIG_BLOCK:", signal.SIG_BLOCK)
print("SIG_UNBLOCK:", signal.SIG_UNBLOCK)
print("SIG_SETMASK:", signal.SIG_SETMASK)
