use serde::{Deserialize, Deserializer};

use crate::ir_schema;
use crate::json_boundary::{
    expect_object, optional_bool, optional_bytes, optional_f64, optional_i64, optional_string,
    optional_string_list, required_field, required_string, required_string_list,
};
use crate::tir::op_kinds_generated::{
    SimpleIrRuntimeRequirements, simpleir_kind_has_function_reference_s_value,
    simpleir_kind_is_call_graph_user_call, simpleir_kind_is_return_terminator,
    simpleir_runtime_requirements_table,
};
use crate::tir::simple_def_use::{
    SimpleIrReadField, visit_simple_ir_defined_names, visit_simple_ir_reads,
};
use serde_json::Value as JsonValue;
use std::collections::{BTreeSet, VecDeque};

#[derive(Debug, Default, Clone, Deserialize, serde::Serialize)]
#[serde(default)]
pub struct PgoProfileIR {
    pub version: Option<String>,
    pub hash: Option<String>,
    pub hot_functions: Vec<String>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct SimpleIR {
    pub functions: Vec<FunctionIR>,
    pub profile: Option<PgoProfileIR>,
}

/// Per-build module registry projection (import bedrock, design doc 69 §3).
///
/// Generated by `molt.cli.module_registry` (the checked-in layout authority)
/// and emitted by the native backend into the application object as the
/// exported `molt_module_registry_blob` data symbol.  The backend applies one
/// native function-address relocation per `relocs` entry, so it needs no
/// layout knowledge: `blob` already carries the serialized header/rows/names
/// with zeroed init-pointer slots.  The runtime-side reader is
/// `runtime/molt-runtime/src/builtins/module_table.rs`.
#[derive(Debug, Default, Clone, Deserialize, serde::Serialize)]
#[serde(default)]
pub struct ModuleRegistryIR {
    pub schema: u32,
    pub registry_digest: String,
    pub blob: Vec<u8>,
    /// `[byte_offset_into_blob, init_symbol]` function-address relocations.
    pub relocs: Vec<(u64, String)>,
    /// Every init symbol referenced by `relocs`; the dead-function
    /// elimination roots (init bodies are reachable ONLY through the
    /// registry's MODULE_INIT_TABLE column — invariant I5).
    pub init_symbols: Vec<String>,
    /// `[ModuleId, init_symbol]` dispatch projection. Native applies the
    /// pointer relocations above; WASM lowers these same rows to its dense
    /// ModuleId jump table.
    pub init_rows: Vec<(u32, String)>,
}

impl ModuleRegistryIR {
    pub fn validate(&self) -> Result<(), String> {
        if self.blob.is_empty() {
            return Err("module_registry.blob is empty".to_string());
        }
        for (offset, symbol) in &self.relocs {
            let end = offset
                .checked_add(8)
                .ok_or_else(|| format!("module_registry reloc offset {offset} overflows"))?;
            if end > self.blob.len() as u64 {
                return Err(format!(
                    "module_registry reloc for '{symbol}' at offset {offset} exceeds \
                     blob length {}",
                    self.blob.len()
                ));
            }
            if symbol.is_empty() {
                return Err(format!(
                    "module_registry reloc at offset {offset} has an empty symbol"
                ));
            }
        }
        for symbol in &self.init_symbols {
            if symbol.is_empty() {
                return Err("module_registry init_symbols contains an empty symbol".to_string());
            }
        }
        let mut previous_id = None;
        for (id, symbol) in &self.init_rows {
            if symbol.is_empty() {
                return Err("module_registry init_rows contains an empty symbol".to_string());
            }
            if previous_id.is_some_and(|previous| previous >= *id) {
                return Err(
                    "module_registry init_rows must be strictly ModuleId-sorted".to_string()
                );
            }
            previous_id = Some(*id);
        }
        let row_symbols: BTreeSet<&str> = self
            .init_rows
            .iter()
            .map(|(_, symbol)| symbol.as_str())
            .collect();
        let symbols: BTreeSet<&str> = self.init_symbols.iter().map(String::as_str).collect();
        if row_symbols != symbols {
            return Err(
                "module_registry init_rows and init_symbols disagree on dispatch roots".to_string(),
            );
        }
        Ok(())
    }

    fn from_json_value(value: &JsonValue, ctx: &str) -> Result<Self, String> {
        let obj = expect_object(value, ctx)?;
        let schema =
            optional_i64(obj, "schema", ctx)?.ok_or_else(|| format!("{ctx}.schema is required"))?;
        let schema = u32::try_from(schema).map_err(|_| format!("{ctx}.schema is out of range"))?;
        let registry_digest = optional_string(obj, "registry_digest", ctx)?
            .ok_or_else(|| format!("{ctx}.registry_digest is required"))?;
        let blob =
            optional_bytes(obj, "blob", ctx)?.ok_or_else(|| format!("{ctx}.blob is required"))?;
        let relocs_value = required_field(obj, "relocs", ctx)?;
        let reloc_values = relocs_value
            .as_array()
            .ok_or_else(|| format!("{ctx}.relocs must be an array"))?;
        let mut relocs = Vec::with_capacity(reloc_values.len());
        for (idx, entry) in reloc_values.iter().enumerate() {
            let pair = entry
                .as_array()
                .filter(|pair| pair.len() == 2)
                .ok_or_else(|| format!("{ctx}.relocs[{idx}] must be [offset, symbol]"))?;
            let offset = pair[0]
                .as_u64()
                .ok_or_else(|| format!("{ctx}.relocs[{idx}][0] must be an offset"))?;
            let symbol = pair[1]
                .as_str()
                .ok_or_else(|| format!("{ctx}.relocs[{idx}][1] must be a symbol"))?;
            relocs.push((offset, symbol.to_string()));
        }
        let init_symbols = optional_string_list(obj, "init_symbols", ctx)?.unwrap_or_default();
        let init_rows_value = required_field(obj, "init_rows", ctx)?;
        let init_row_values = init_rows_value
            .as_array()
            .ok_or_else(|| format!("{ctx}.init_rows must be an array"))?;
        let mut init_rows = Vec::with_capacity(init_row_values.len());
        for (idx, entry) in init_row_values.iter().enumerate() {
            let pair = entry
                .as_array()
                .filter(|pair| pair.len() == 2)
                .ok_or_else(|| format!("{ctx}.init_rows[{idx}] must be [id, symbol]"))?;
            let id = pair[0]
                .as_u64()
                .and_then(|value| u32::try_from(value).ok())
                .ok_or_else(|| format!("{ctx}.init_rows[{idx}][0] must be a ModuleId"))?;
            let symbol = pair[1]
                .as_str()
                .ok_or_else(|| format!("{ctx}.init_rows[{idx}][1] must be a symbol"))?;
            init_rows.push((id, symbol.to_string()));
        }
        let registry = Self {
            schema,
            registry_digest,
            blob,
            relocs,
            init_symbols,
            init_rows,
        };
        registry.validate().map_err(|err| format!("{ctx}: {err}"))?;
        Ok(registry)
    }
}

/// The full backend IR document: the function stream plus the per-build
/// sections that ride the same wire (currently the module registry).
/// `SimpleIR` stays the function-stream transport used by every pass; the
/// registry is threaded explicitly to its consumers (native application
/// object emission and dead-function-elimination roots).
#[derive(Debug, Clone)]
pub struct BackendIrDocument {
    pub ir: SimpleIR,
    pub module_registry: Option<ModuleRegistryIR>,
}

impl BackendIrDocument {
    pub fn from_json_str(input: &str) -> Result<Self, String> {
        let value: JsonValue =
            serde_json::from_str(input).map_err(|err| format!("invalid IR JSON: {err}"))?;
        Self::from_json_value(&value)
    }

    pub fn from_json_value(value: &JsonValue) -> Result<Self, String> {
        let ir = SimpleIR::from_json_value(value)?;
        let obj = expect_object(value, "ir")?;
        let module_registry = match obj.get("module_registry") {
            None | Some(JsonValue::Null) => None,
            Some(registry_value) => Some(ModuleRegistryIR::from_json_value(
                registry_value,
                "ir.module_registry",
            )?),
        };
        Ok(Self {
            ir,
            module_registry,
        })
    }

    pub fn from_ndjson_reader<R: std::io::BufRead>(reader: R) -> Result<Self, String> {
        let mut functions = Vec::new();
        let mut profile = None;
        let mut module_registry = None;
        for line in reader.lines() {
            let line = line.map_err(|e| format!("NDJSON read error: {e}"))?;
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }
            let value: JsonValue =
                serde_json::from_str(trimmed).map_err(|e| format!("NDJSON parse error: {e}"))?;
            match value.get("kind").and_then(|v| v.as_str()) {
                Some("ir_stream_start") => {
                    if let Some(p) = value.get("profile")
                        && !p.is_null()
                    {
                        profile = Some(PgoProfileIR::from_json_value(p, "stream.profile")?);
                    }
                    if let Some(registry) = value.get("module_registry")
                        && !registry.is_null()
                    {
                        module_registry = Some(ModuleRegistryIR::from_json_value(
                            registry,
                            "stream.module_registry",
                        )?);
                    }
                }
                Some("function") => {
                    functions.push(FunctionIR::from_json_value(&value, "stream.function")?);
                }
                Some("ir_stream_end") => break,
                _ => {} // skip unknown kinds for forward compat
            }
        }
        Ok(Self {
            ir: SimpleIR::new_validated(functions, profile)?,
            module_registry,
        })
    }
}

impl<'de> Deserialize<'de> for BackendIrDocument {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct BackendIrDocumentWire {
            functions: Vec<FunctionIR>,
            #[serde(default)]
            profile: Option<PgoProfileIR>,
            #[serde(default)]
            module_registry: Option<ModuleRegistryIR>,
        }

        let wire = BackendIrDocumentWire::deserialize(deserializer)?;
        if let Some(registry) = &wire.module_registry {
            registry.validate().map_err(serde::de::Error::custom)?;
        }
        Ok(Self {
            ir: SimpleIR::new_validated(wire.functions, wire.profile)
                .map_err(serde::de::Error::custom)?,
            module_registry: wire.module_registry,
        })
    }
}

#[derive(Debug, Default, Deserialize, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionContextPolicy {
    #[default]
    None,
    Local,
    Inherited,
}

#[derive(Debug, Default, Deserialize, Clone, serde::Serialize)]
pub struct FunctionIR {
    pub name: String,
    pub params: Vec<String>,
    pub ops: Vec<OpIR>,
    pub param_types: Option<Vec<String>>,
    /// Source file path for traceback formatting.
    #[serde(default)]
    pub source_file: Option<String>,
    /// When true, this function's body was stripped (already compiled into
    /// stdlib_shared.o).  The backend emits a declaration (no body) so
    /// the linker resolves the symbol from the shared object.
    #[serde(default)]
    pub is_extern: bool,
    /// Target-neutral execution-context ABI policy.
    #[serde(default)]
    pub execution_context: ExecutionContextPolicy,
}

/// Stream the complete versioned FunctionIR contract into a cache digest or
/// artifact writer without materializing a duplicate O(IR) buffer.
pub fn write_function_ir_contract(
    function: &FunctionIR,
    writer: &mut dyn std::io::Write,
) -> Result<(), String> {
    const FUNCTION_IR_CONTRACT_VERSION: &[u8] = b"molt-function-ir-contract-v1\0";
    // MessagePack's f64 carrier is total and bit-preserving for every legal IR
    // value, including NaN payloads, infinities, and signed zero. JSON is not:
    // serde_json rejects those valid Python float constants. Named struct
    // encoding retains automatic whole-FunctionIR field coverage.
    writer
        .write_all(FUNCTION_IR_CONTRACT_VERSION)
        .map_err(|error| format!("FunctionIR contract prefix write failed: {error}"))?;
    let mut serializer = rmp_serde::Serializer::new(writer).with_struct_map();
    serde::Serialize::serialize(function, &mut serializer)
        .map_err(|error| format!("FunctionIR contract serialization failed: {error}"))
}

#[derive(Debug, Clone, Default, Deserialize, serde::Serialize)]
#[serde(default)]
pub struct OpIR {
    pub kind: String,
    pub value: Option<i64>,
    pub f_value: Option<f64>,
    pub s_value: Option<String>,
    pub bytes: Option<Vec<u8>>,
    pub var: Option<String>,
    pub args: Option<Vec<String>>,
    pub out: Option<String>,
    /// Transitional transport compatibility hint for legacy consumers.
    /// Not the canonical backend representation contract.
    pub fast_int: Option<bool>,
    /// Transitional transport compatibility hint for legacy consumers.
    /// Not the canonical backend representation contract.
    pub fast_float: Option<bool>,
    pub stack_eligible: Option<bool>,
    /// When true, this allocation should use the function-scoped
    /// `ScopeArena` (bump allocator) instead of individual heap alloc/free.
    /// Set by escape analysis when an `Alloc` is `NoEscape` and the arena
    /// integration is active.
    #[serde(default)]
    pub arena_eligible: Option<bool>,
    /// When true on an `object_new_bound` op, the instance's class defines a
    /// `__del__` finalizer (directly or via its MRO, excluding `object`). The
    /// frontend resolves this statically and the backend escape pass must keep
    /// such an instance heap-allocated with a live refcount — never stack-promote
    /// it (which stamps it IMMORTAL) and never strip its IncRef/DecRef — so the
    /// finalizer-aware `dec_ref_ptr` dispatches `__del__` at the last reference
    /// drop. Without this the refcount-zero transition never occurs and the
    /// finalizer silently never runs (the standing LLVM/WASM parity hole).
    #[serde(default)]
    pub defines_del: Option<bool>,
    /// Named-local fact (#58 ordering keystone): the op's result is bound to
    /// a plain function-local NAME. CPython holds a named local in the frame
    /// until `del`/rebinding/scope exit; an unnamed expression temp dies at
    /// the statement. The ownership-lattice release deferral consumes this to
    /// defer ONLY named finalizer-sensitive values to the scope boundary.
    #[serde(default)]
    pub bound_local: Option<bool>,
    pub task_kind: Option<String>,
    pub container_type: Option<String>,
    pub native_callable_export: Option<String>,
    pub native_callable_binding: Option<String>,
    pub native_callable_symbol: Option<String>,
    pub native_callable_abi: Option<String>,
    /// Python builtin or runtime intrinsic name consumed by `builtin_func`.
    /// `s_value` remains the executable runtime symbol; this field names the
    /// metadata/default authority used by `molt_func_new_builtin_named`.
    pub builtin_name: Option<String>,
    /// Canonical runtime callable provenance resolved by the frontend from a
    /// statically known module attribute/import. Target admission propagates
    /// this fact through SSA aliases before any backend emits source.
    pub runtime_symbol: Option<String>,
    /// Direct-call marker paired with `ExecutionContextPolicy::Inherited` on
    /// the callee; the backend must thread its active context at this call site.
    #[serde(default)]
    pub passes_execution_context: bool,
    /// Transitional semantic hint preserved on the transport surface for
    /// compatibility consumers. The canonical representation contract lives in
    /// TIR/LIR, not this field.
    pub type_hint: Option<String>,
    /// Inline-cache site index for attribute access acceleration.
    /// Assigned by the frontend for `get_attr_generic_ptr` ops.
    pub ic_index: Option<i64>,
    /// Stable source operation index for backend inline-cache site identity.
    /// This is assigned by the SimpleIR -> TIR lift and transported back
    /// through TIR -> SimpleIR so backends do not reconstruct IC identity from
    /// their local stream order.
    pub source_op_idx: Option<i64>,
    /// Column offset (0-based) for traceback caret annotations.
    /// Carried by `line` ops from the frontend AST node's `col_offset`.
    pub col_offset: Option<i64>,
    /// End column offset (0-based) for traceback caret annotations.
    pub end_col_offset: Option<i64>,
    /// Source line number (1-based) for structural source-site attribution.
    /// Frontend JSON annotates executable ops from the active `line` marker;
    /// the SimpleIR -> TIR lift preserves it as the TIR source-site authority.
    pub source_line: Option<i64>,
    /// When true, the bounds-check elimination pass has proven this index
    /// operation is in-range.  Codegen can skip the runtime bounds check
    /// and emit a straight-line element access.
    pub bce_safe: Option<bool>,
    /// Named proof that a normally observable effect/exception edge has
    /// already been discharged by an earlier semantic analysis.
    ///
    /// This is not a representation hint: consumers must validate the proof
    /// name against the op kind before weakening effect semantics.
    pub effect_proof: Option<String>,
    /// The concrete user-class name whose fixed instance layout authored the
    /// `value` byte-offset of a typed-slot field op (`store` / `store_init` /
    /// `load` / `guarded_field_get` / `guarded_field_set` / `guarded_field_init`).
    ///
    /// The frontend emits these offset-based forms ONLY when the object's class
    /// is proven at the op — either by a preceding runtime version-guard (the
    /// `guarded_field_*` forms deopt/raise on class mismatch) or by static type
    /// inference (the plain `store`/`load` forms). Either way the class is the
    /// authority for `offset`, so the alias oracle can assign a class+offset
    /// `TypedField` memory region that disjoint-aliases other classes' fields,
    /// container elements, and module-dict slots (S5-1.5).
    ///
    /// Wire name is `"class"` (the frontend JSON / msgpack key); the manual
    /// `from_json_value` parser and the serde derive (rmp/cbor path) agree on it.
    #[serde(rename = "class")]
    pub class_name: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct OpSourceSite {
    pub source_line: Option<i64>,
    pub col_offset: Option<i64>,
    pub end_col_offset: Option<i64>,
}

impl OpSourceSite {
    pub fn from_op(op: &OpIR) -> Self {
        Self {
            source_line: op.source_line,
            col_offset: op.col_offset,
            end_col_offset: op.end_col_offset,
        }
    }

    pub fn apply_to_op(self, op: &mut OpIR) {
        op.source_line = self.source_line;
        op.col_offset = self.col_offset;
        op.end_col_offset = self.end_col_offset;
    }
}

impl OpIR {
    pub fn source_site(&self) -> OpSourceSite {
        OpSourceSite::from_op(self)
    }

    pub fn inherit_source_site_from(&mut self, other: &OpIR) {
        other.source_site().apply_to_op(self);
    }
}

impl PgoProfileIR {
    fn from_json_value(value: &JsonValue, ctx: &str) -> Result<Self, String> {
        let obj = expect_object(value, ctx)?;
        Ok(Self {
            version: optional_string(obj, "version", ctx)?,
            hash: optional_string(obj, "hash", ctx)?,
            hot_functions: optional_string_list(obj, "hot_functions", ctx)?.unwrap_or_default(),
        })
    }
}

impl SimpleIR {
    pub fn from_json_str(input: &str) -> Result<Self, String> {
        let value: JsonValue =
            serde_json::from_str(input).map_err(|err| format!("invalid IR JSON: {err}"))?;
        Self::from_json_value(&value)
    }

    pub fn from_json_value(value: &JsonValue) -> Result<Self, String> {
        let obj = expect_object(value, "ir")?;
        let functions_value = required_field(obj, "functions", "ir")?;
        let function_values = functions_value
            .as_array()
            .ok_or_else(|| "ir.functions must be an array".to_string())?;
        let mut functions = Vec::with_capacity(function_values.len());
        for (idx, function_value) in function_values.iter().enumerate() {
            functions.push(FunctionIR::from_json_value(
                function_value,
                &format!("ir.functions[{idx}]"),
            )?);
        }
        let profile = match obj.get("profile") {
            None | Some(JsonValue::Null) => None,
            Some(profile_value) => {
                Some(PgoProfileIR::from_json_value(profile_value, "ir.profile")?)
            }
        };
        Self::new_validated(functions, profile)
    }

    pub fn from_ndjson_reader<R: std::io::BufRead>(reader: R) -> Result<Self, String> {
        let mut functions = Vec::new();
        let mut profile = None;
        for line in reader.lines() {
            let line = line.map_err(|e| format!("NDJSON read error: {e}"))?;
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }
            let value: JsonValue =
                serde_json::from_str(trimmed).map_err(|e| format!("NDJSON parse error: {e}"))?;
            match value.get("kind").and_then(|v| v.as_str()) {
                Some("ir_stream_start") => {
                    if let Some(p) = value.get("profile")
                        && !p.is_null()
                    {
                        profile = Some(PgoProfileIR::from_json_value(p, "stream.profile")?);
                    }
                }
                Some("function") => {
                    functions.push(FunctionIR::from_json_value(&value, "stream.function")?);
                }
                Some("ir_stream_end") => break,
                _ => {} // skip unknown kinds for forward compat
            }
        }
        Self::new_validated(functions, profile)
    }

    fn new_validated(
        functions: Vec<FunctionIR>,
        profile: Option<PgoProfileIR>,
    ) -> Result<Self, String> {
        let ir = Self { functions, profile };
        validate_simple_ir_transport_contract(&ir)
            .map_err(|err| format!("invalid SimpleIR contract: {err}"))?;
        Ok(ir)
    }

    pub fn tree_shake_source_emission(&mut self) {
        for func in &mut self.functions {
            match func.name.as_str() {
                "molt_main" => {
                    func.ops.retain(|op| {
                        !(op.kind == "call" && op.s_value.as_deref() == Some("molt_runtime_init"))
                    });
                }
                "molt_init___main__" => {
                    for op in &mut func.ops {
                        if op.kind == "call" && op.s_value.as_deref() == Some("molt_init_sys") {
                            *op = OpIR {
                                kind: "nop".to_string(),
                                ..OpIR::default()
                            };
                        }
                    }
                }
                _ => {}
            }
        }

        let known_functions: BTreeSet<&str> = self
            .functions
            .iter()
            .map(|func| func.name.as_str())
            .collect();
        let mut reachable: BTreeSet<String> = BTreeSet::from([String::from("molt_main")]);
        let mut worklist: VecDeque<String> = VecDeque::from([String::from("molt_main")]);

        while let Some(func_name) = worklist.pop_front() {
            let Some(func) = self
                .functions
                .iter()
                .find(|candidate| candidate.name == func_name)
            else {
                continue;
            };
            for op in &func.ops {
                // Follow direct call targets.
                if op.kind == "call" {
                    let Some(target) = op.s_value.as_deref() else {
                        continue;
                    };
                    if matches!(target, "molt_runtime_init" | "molt_init_sys") {
                        continue;
                    }
                    if !known_functions.contains(target) {
                        continue;
                    }
                    if reachable.insert(target.to_string()) {
                        worklist.push_back(target.to_string());
                    }
                    continue;
                }
                // Follow function object creation ops — these reference
                // user-defined function bodies by name in s_value.  Without
                // this, source emitters prune user functions that are only
                // referenced through func_new (not direct calls).
                if matches!(
                    op.kind.as_str(),
                    "func_new" | "func_new_closure" | "code_new" | "call_internal"
                ) {
                    let Some(target) = op.s_value.as_deref() else {
                        continue;
                    };
                    if !known_functions.contains(target) {
                        continue;
                    }
                    if reachable.insert(target.to_string()) {
                        worklist.push_back(target.to_string());
                    }
                }
            }
        }

        self.functions
            .retain(|func| reachable.contains(func.name.as_str()));
    }

    pub fn tree_shake_luau(&mut self) {
        self.tree_shake_source_emission();
    }
}

impl<'de> Deserialize<'de> for SimpleIR {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        struct SimpleIRWire {
            functions: Vec<FunctionIR>,
            #[serde(default)]
            profile: Option<PgoProfileIR>,
        }

        let wire = SimpleIRWire::deserialize(deserializer)?;
        Self::new_validated(wire.functions, wire.profile).map_err(serde::de::Error::custom)
    }
}

impl FunctionIR {
    fn from_json_value(value: &JsonValue, ctx: &str) -> Result<Self, String> {
        let obj = expect_object(value, ctx)?;
        let ops_value = required_field(obj, "ops", ctx)?;
        let op_values = ops_value
            .as_array()
            .ok_or_else(|| format!("{ctx}.ops must be an array"))?;
        let mut ops = Vec::with_capacity(op_values.len());
        for (idx, op_value) in op_values.iter().enumerate() {
            ops.push(OpIR::from_json_value(
                op_value,
                &format!("{ctx}.ops[{idx}]"),
            )?);
        }
        Ok(Self {
            name: required_string(obj, "name", ctx)?,
            params: required_string_list(obj, "params", ctx)?,
            ops,
            param_types: optional_string_list(obj, "param_types", ctx)?,
            source_file: obj
                .get("source_file")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            is_extern: false,
            execution_context: obj
                .get("execution_context")
                .and_then(|value| value.as_str())
                .map(|value| match value {
                    "none" => Ok(ExecutionContextPolicy::None),
                    "local" => Ok(ExecutionContextPolicy::Local),
                    "inherited" => Ok(ExecutionContextPolicy::Inherited),
                    _ => Err(format!(
                        "{ctx}.execution_context has invalid policy `{value}`"
                    )),
                })
                .transpose()?
                .unwrap_or_default(),
        })
    }
}

impl OpIR {
    fn from_json_value(value: &JsonValue, ctx: &str) -> Result<Self, String> {
        let obj = expect_object(value, ctx)?;
        // Extract ic_index from nested "metadata" object if present.
        let ic_index = obj
            .get("metadata")
            .and_then(|m| m.as_object())
            .and_then(|m| m.get("ic_index"))
            .and_then(|v| v.as_i64());
        Ok(Self {
            kind: required_string(obj, "kind", ctx)?,
            value: optional_i64(obj, "value", ctx)?,
            f_value: optional_f64(obj, "f_value", ctx)?,
            s_value: optional_string(obj, "s_value", ctx)?,
            bytes: optional_bytes(obj, "bytes", ctx)?,
            var: optional_string(obj, "var", ctx)?,
            args: optional_string_list(obj, "args", ctx)?,
            out: optional_string(obj, "out", ctx)?,
            fast_int: optional_bool(obj, "fast_int", ctx)?,
            fast_float: optional_bool(obj, "fast_float", ctx)?,
            stack_eligible: optional_bool(obj, "stack_eligible", ctx)?,
            task_kind: optional_string(obj, "task_kind", ctx)?,
            container_type: optional_string(obj, "container_type", ctx)?,
            native_callable_export: optional_string(obj, "native_callable_export", ctx)?,
            native_callable_binding: optional_string(obj, "native_callable_binding", ctx)?,
            native_callable_symbol: optional_string(obj, "native_callable_symbol", ctx)?,
            native_callable_abi: optional_string(obj, "native_callable_abi", ctx)?,
            builtin_name: optional_string(obj, "builtin_name", ctx)?,
            runtime_symbol: optional_string(obj, "runtime_symbol", ctx)?,
            passes_execution_context: optional_bool(obj, "passes_execution_context", ctx)?
                .unwrap_or(false),
            type_hint: optional_string(obj, "type_hint", ctx)?,
            ic_index,
            source_op_idx: optional_i64(obj, "source_op_idx", ctx)?,
            col_offset: optional_i64(obj, "col_offset", ctx)?,
            end_col_offset: optional_i64(obj, "end_col_offset", ctx)?,
            source_line: optional_i64(obj, "source_line", ctx)?,
            bce_safe: optional_bool(obj, "bce_safe", ctx)?,
            arena_eligible: optional_bool(obj, "arena_eligible", ctx)?,
            defines_del: optional_bool(obj, "defines_del", ctx)?,
            bound_local: optional_bool(obj, "bound_local", ctx)?,
            effect_proof: optional_string(obj, "effect_proof", ctx)?,
            class_name: optional_string(obj, "class", ctx)?,
        })
    }
}

fn is_defined_value_name(name: &str) -> bool {
    !name.is_empty() && name != "none"
}

fn allows_undefined_value(op: &OpIR, name: &str, field: SimpleIrReadField) -> bool {
    if !name.starts_with('v') {
        return false;
    }
    field == SimpleIrReadField::Arg(0) && matches!(op.kind.as_str(), "dict_set" | "index")
}

pub fn validate_simple_ir(ir: &SimpleIR) -> Result<(), String> {
    validate_simple_ir_transport_contract(ir)?;
    for func in &ir.functions {
        let mut defined: BTreeSet<String> = func.params.iter().cloned().collect();
        for (op_index, op) in func.ops.iter().enumerate() {
            let mut undefined = None;
            visit_simple_ir_reads(op, |source| {
                let name = source.name;
                if undefined.is_none()
                    && is_defined_value_name(name)
                    && !defined.contains(name)
                    && !allows_undefined_value(op, name, source.field)
                {
                    undefined = Some(name.to_string());
                }
            });
            if let Some(name) = undefined {
                return Err(format!(
                    "function `{}` op#{op_index} `{}` uses undefined value `{name}`",
                    func.name, op.kind
                ));
            }
            visit_simple_ir_defined_names(op, |name| {
                if is_defined_value_name(name) {
                    defined.insert(name.to_string());
                }
            });
        }
    }
    Ok(())
}

fn validate_simple_ir_transport_contract(ir: &SimpleIR) -> Result<(), String> {
    let inherited = ir
        .functions
        .iter()
        .filter(|func| func.execution_context == ExecutionContextPolicy::Inherited)
        .map(|func| func.name.as_str())
        .collect::<BTreeSet<_>>();
    for func in &ir.functions {
        ir_schema::validate_function_param_types(
            &func.name,
            &func.params,
            func.param_types.as_deref(),
        )?;
        let frame_ops = func
            .ops
            .iter()
            .filter(|op| {
                simpleir_runtime_requirements_table(op.kind.as_str()).is_some_and(|requirements| {
                    requirements.contains(SimpleIrRuntimeRequirements::EXECUTION_FRAME)
                })
            })
            .collect::<Vec<_>>();
        let trace_enters = frame_ops
            .iter()
            .filter(|op| op.kind == "trace_enter_slot")
            .count();
        match func.execution_context {
            ExecutionContextPolicy::Local if trace_enters != 1 => {
                return Err(format!(
                    "function `{}` with local execution context requires exactly one trace_enter_slot",
                    func.name
                ));
            }
            ExecutionContextPolicy::Inherited if trace_enters != 0 => {
                return Err(format!(
                    "function `{}` cannot both inherit and create an execution context",
                    func.name
                ));
            }
            ExecutionContextPolicy::None if trace_enters != 0 => {
                return Err(format!(
                    "function `{}` with trace_enter_slot must declare local execution context",
                    func.name
                ));
            }
            _ => {}
        }
        match func.execution_context {
            ExecutionContextPolicy::Local => {
                if func
                    .ops
                    .first()
                    .is_none_or(|op| op.kind != "trace_enter_slot")
                {
                    return Err(format!(
                        "function `{}` with local execution context requires trace_enter_slot in the entry region",
                        func.name
                    ));
                }
                for (op_index, op) in func.ops.iter().enumerate() {
                    if op.kind == "trace_exit"
                        && func
                            .ops
                            .get(op_index + 1)
                            .is_none_or(|next| !simpleir_kind_is_return_terminator(&next.kind))
                    {
                        return Err(format!(
                            "function `{}` has stray trace_exit at op#{op_index}; lifecycle exits must occur exactly once immediately before normal return terminators",
                            func.name
                        ));
                    }
                    if simpleir_kind_is_return_terminator(&op.kind)
                        && func
                            .ops
                            .get(op_index.wrapping_sub(1))
                            .is_none_or(|previous| previous.kind != "trace_exit")
                    {
                        return Err(format!(
                            "function `{}` normal return op#{op_index} `{}` requires exactly one immediately preceding trace_exit",
                            func.name, op.kind
                        ));
                    }
                }
            }
            ExecutionContextPolicy::Inherited => {
                if let Some(lifecycle) = frame_ops
                    .iter()
                    .find(|op| matches!(op.kind.as_str(), "trace_enter_slot" | "trace_exit"))
                {
                    return Err(format!(
                        "function `{}` with inherited execution context cannot own lifecycle op `{}`",
                        func.name, lifecycle.kind
                    ));
                }
            }
            ExecutionContextPolicy::None => {
                if let Some(frame_op) = frame_ops.first() {
                    return Err(format!(
                        "function `{}` without an execution context cannot contain generated frame op `{}`",
                        func.name, frame_op.kind
                    ));
                }
            }
        }
        for op in &func.ops {
            ir_schema::validate_required_fields(op)?;
            if op.passes_execution_context {
                let Some(target) = op.s_value.as_deref() else {
                    return Err("execution-context call metadata requires a direct target".into());
                };
                if op.kind != "call_internal" {
                    return Err(format!(
                        "execution-context call metadata requires call_internal, found `{}`",
                        op.kind
                    ));
                }
                if !inherited.contains(target) {
                    return Err(format!(
                        "execution-context call metadata targets non-inherited function `{target}`"
                    ));
                }
            }
            if simpleir_kind_is_call_graph_user_call(op.kind.as_str())
                && let Some(target) = op.s_value.as_deref()
                && inherited.contains(target)
                && !op.passes_execution_context
            {
                return Err(format!(
                    "inherited execution-context function `{target}` requires direct threaded call metadata"
                ));
            }
            if simpleir_kind_has_function_reference_s_value(op.kind.as_str())
                && let Some(target) = op.s_value.as_deref()
                && inherited.contains(target)
            {
                return Err(format!(
                    "inherited execution-context function `{target}` cannot escape as an indirect callable"
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod json_parse_tests {
    use super::{FunctionIR, OpIR, SimpleIR, write_function_ir_contract};

    fn contract_bytes(function: &FunctionIR) -> Vec<u8> {
        let mut bytes = Vec::new();
        write_function_ir_contract(function, &mut bytes)
            .expect("Vec-backed test writer cannot fail");
        bytes
    }

    #[test]
    fn function_ir_contract_encoding_is_total_bit_exact_and_deterministic() {
        let function_with_float = |value: f64| FunctionIR {
            name: "float_contract".to_string(),
            params: vec!["x".to_string()],
            ops: vec![OpIR {
                kind: "const_float".to_string(),
                f_value: Some(value),
                bytes: Some(vec![0, 1, 127, 128, 255]),
                out: Some("value".to_string()),
                ..OpIR::default()
            }],
            param_types: Some(vec!["float".to_string()]),
            source_file: Some("float_contract.py".to_string()),
            is_extern: false,
            execution_context: super::ExecutionContextPolicy::None,
        };
        let cases = [
            f64::from_bits(0x7ff8_0000_0000_0001),
            f64::from_bits(0xfff8_0000_0000_0042),
            f64::INFINITY,
            f64::NEG_INFINITY,
            -0.0,
            0.0,
        ];
        let encoded = cases
            .into_iter()
            .map(|value| {
                let function = function_with_float(value);
                let first = contract_bytes(&function);
                assert_eq!(first, contract_bytes(&function));
                first
            })
            .collect::<Vec<_>>();
        for left in 0..encoded.len() {
            for right in left + 1..encoded.len() {
                assert_ne!(
                    encoded[left], encoded[right],
                    "the contract must preserve every distinct f64 bit pattern"
                );
            }
        }

        let with_bytes = function_with_float(1.0);
        let mut different_bytes = with_bytes.clone();
        different_bytes.ops[0].bytes = Some(vec![0, 1, 127, 128, 254]);
        assert_ne!(
            contract_bytes(&with_bytes),
            contract_bytes(&different_bytes)
        );

        let mut absent = with_bytes.clone();
        absent.ops[0].type_hint = None;
        let mut present = absent.clone();
        present.ops[0].type_hint = Some(String::new());
        assert_ne!(
            contract_bytes(&absent),
            contract_bytes(&present),
            "absent optional metadata and a present default-like value are distinct contracts"
        );
    }

    #[test]
    fn simple_ir_from_json_str_applies_optional_defaults() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [{"kind": "ret_void"}]
                    }
                ]
            }"#,
        )
        .expect("ir parse");

        assert_eq!(ir.functions.len(), 1);
        assert!(ir.profile.is_none());
        assert!(ir.functions[0].param_types.is_none());
        assert!(ir.functions[0].ops[0].args.is_none());
        assert!(ir.functions[0].ops[0].fast_int.is_none());
    }

    #[test]
    fn execution_context_validation_uses_typed_call_roles_not_string_collisions() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "module_chunk",
                        "params": [],
                        "execution_context": "inherited",
                        "ops": [{"kind": "ret_void"}]
                    },
                    {
                        "name": "caller",
                        "params": ["module_chunk"],
                        "ops": [
                            {"kind": "const_str", "s_value": "module_chunk", "out": "same_text"},
                            {"kind": "call_internal", "s_value": "module_chunk", "passes_execution_context": true},
                            {"kind": "ret_void"}
                        ]
                    }
                ]
            }"#,
        )
        .expect("non-call strings and SSA names must not be mistaken for function references");

        assert_eq!(ir.functions.len(), 2);
        assert!(ir.functions[1].ops[1].passes_execution_context);
    }

    #[test]
    fn execution_context_validation_rejects_first_class_inherited_function_escape() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "module_chunk",
                        "params": [],
                        "execution_context": "inherited",
                        "ops": [{"kind": "ret_void"}]
                    },
                    {
                        "name": "caller",
                        "params": [],
                        "ops": [
                            {"kind": "func_new", "s_value": "module_chunk", "out": "escaped"},
                            {"kind": "ret_void"}
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("inherited execution contexts require a direct threaded call edge");

        assert!(
            err.contains("cannot escape as an indirect callable"),
            "{err}"
        );
    }

    #[test]
    fn execution_context_validation_rejects_ambiguous_call_metadata() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "module_chunk",
                        "params": [],
                        "execution_context": "inherited",
                        "ops": [{"kind": "ret_void"}]
                    },
                    {
                        "name": "caller",
                        "params": [],
                        "ops": [
                            {"kind": "call", "s_value": "module_chunk", "passes_execution_context": true},
                            {"kind": "ret_void"}
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("only canonical direct-local calls may thread an execution context");

        assert!(
            err.contains("execution-context call metadata requires call_internal, found `call`"),
            "{err}"
        );
    }

    #[test]
    fn execution_context_policy_validates_the_complete_generated_frame_op_family() {
        let parse = |policy: &str, ops: &str| {
            SimpleIR::from_json_str(&format!(
                r#"{{"functions":[{{"name":"frame_policy","params":["locals"],"execution_context":"{policy}","ops":[{ops}]}}]}}"#
            ))
        };
        let enter = r#"{"kind":"trace_enter_slot","value":1}"#;
        let line = r#"{"kind":"line","value":2}"#;
        let locals = r#"{"kind":"frame_locals_set","args":["locals"]}"#;
        let exit = r#"{"kind":"trace_exit"}"#;

        parse(
            "local",
            &format!("{enter},{line},{locals},{exit},{{\"kind\":\"ret_void\"}}"),
        )
        .expect("a Local frame owns one enter, frame state, and lifecycle exits");
        parse("inherited", &format!("{line},{locals}"))
            .expect("Inherited consumes only the bound context's non-lifecycle frame state");

        for lifecycle in [enter, exit] {
            let error = parse("inherited", lifecycle)
                .expect_err("Inherited must not create or destroy its caller's frame");
            assert!(
                error.contains("inherit") || error.contains("lifecycle"),
                "{error}"
            );
        }
        for frame_op in [enter, line, locals, exit] {
            let error = parse("none", frame_op)
                .expect_err("None must reject every generated execution-frame operation");
            assert!(
                error.contains("execution context") || error.contains("trace_enter_slot"),
                "{error}"
            );
        }
        for ops in [line.to_string(), format!("{enter},{enter}")] {
            let error = parse("local", &ops)
                .expect_err("Local requires exactly one generated trace_enter_slot");
            assert!(error.contains("exactly one trace_enter_slot"), "{error}");
        }

        for (ops, expected) in [
            (
                format!(r#"{enter},{{"kind":"ret_void"}}"#),
                "immediately preceding trace_exit",
            ),
            (
                format!(
                    r#"{enter},{exit},{{"kind":"const_none","out":"v"}},{{"kind":"ret_void"}}"#
                ),
                "stray trace_exit",
            ),
            (
                format!(r#"{enter},{exit},{exit},{{"kind":"ret_void"}}"#),
                "stray trace_exit",
            ),
        ] {
            let error = parse("local", &ops).expect_err("invalid Local lifecycle must fail");
            assert!(error.contains(expected), "{error}");
        }

        parse(
            "local",
            &format!(
                r#"{enter},{{"kind":"if","args":["condition"]}},{exit},{{"kind":"ret_void"}},{{"kind":"else"}},{exit},{{"kind":"ret","var":"condition"}},{{"kind":"end_if"}}"#
            ),
        )
        .expect("each normal return in a multi-return Local function owns one exit");
    }

    #[test]
    fn simple_ir_from_json_str_parses_profile_without_hot_functions() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [{"kind": "ret_void"}]
                    }
                ],
                "profile": {
                    "version": "v1"
                }
            }"#,
        )
        .expect("ir parse");

        let profile = ir.profile.expect("profile");
        assert_eq!(profile.version.as_deref(), Some("v1"));
        assert!(profile.hot_functions.is_empty());
    }

    #[test]
    fn simple_ir_from_json_str_rejects_contract_violations() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["seq", "idx"],
                        "ops": [
                            {
                                "kind": "index",
                                "args": ["seq", "idx"],
                                "out": "item",
                                "container_type": "list_int",
                                "bce_safe": true
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("contract-invalid JSON should fail at parse boundary");

        assert!(err.contains("invalid SimpleIR contract"));
        assert!(err.contains("unsupported container_type `list_int`"));
    }

    #[test]
    fn simple_ir_from_json_str_accepts_static_module_class_binding_effect_proof() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [
                            {"kind": "const_str", "s_value": "__main__", "out": "v0"},
                            {
                                "kind": "module_cache_get",
                                "args": ["v0"],
                                "out": "v1",
                                "effect_proof": "static_module_class_binding"
                            },
                            {"kind": "const_str", "s_value": "Point", "out": "v2"},
                            {
                                "kind": "module_get_attr",
                                "args": ["v1", "v2"],
                                "out": "v3",
                                "effect_proof": "static_module_class_binding"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect("static module/class binding proof should validate on module reads");

        assert_eq!(
            ir.functions[0].ops[1].effect_proof.as_deref(),
            Some("static_module_class_binding")
        );
        assert_eq!(
            ir.functions[0].ops[3].effect_proof.as_deref(),
            Some("static_module_class_binding")
        );
    }

    #[test]
    fn simple_ir_from_json_str_rejects_effect_proof_on_non_module_read() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [
                            {
                                "kind": "const_str",
                                "s_value": "Point",
                                "out": "v0",
                                "effect_proof": "static_module_class_binding"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("effect proof should be rejected on non-module reads");

        assert!(err.contains("cannot carry effect_proof `static_module_class_binding`"));
    }

    #[test]
    fn simple_ir_from_json_str_accepts_builtin_name_with_name_operand() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [
                            {"kind": "const_str", "s_value": "open", "out": "v0"},
                            {
                                "kind": "builtin_func",
                                "s_value": "molt_open_builtin",
                                "value": 2,
                                "args": ["v0"],
                                "out": "v1",
                                "builtin_name": "open"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect("named builtin_func should validate with executable name operand");

        let op = &ir.functions[0].ops[1];
        assert_eq!(op.builtin_name.as_deref(), Some("open"));
        assert_eq!(op.args.as_deref(), Some(&["v0".to_string()][..]));
    }

    #[test]
    fn simple_ir_from_json_str_rejects_builtin_name_without_name_operand() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [
                            {
                                "kind": "builtin_func",
                                "s_value": "molt_open_builtin",
                                "value": 2,
                                "out": "v1",
                                "builtin_name": "open"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("builtin_name must not silently fall back to the raw constructor");

        assert!(err.contains("builtin_name requires exactly one name operand"));
    }

    #[test]
    fn simple_ir_from_json_str_rejects_builtin_name_operand_without_metadata() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [
                            {"kind": "const_str", "s_value": "open", "out": "v0"},
                            {
                                "kind": "builtin_func",
                                "s_value": "molt_open_builtin",
                                "value": 2,
                                "args": ["v0"],
                                "out": "v1"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("name operand must not become hidden constructor authority");

        assert!(err.contains("name operand requires builtin_name metadata"));
    }

    #[test]
    fn simple_ir_from_json_str_accepts_native_callable_invoke_ffi_metadata() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["arg0"],
                        "ops": [
                            {
                                "kind": "invoke_ffi",
                                "args": ["arg0"],
                                "out": "result",
                                "native_callable_export": "scipy.ndimage.distance_transform_edt",
                                "native_callable_binding": "direct_symbol",
                                "native_callable_symbol": "molt_scipy_ndimage_distance_transform_edt",
                                "native_callable_abi": "molt.forward_f32_v1"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect("native callable invoke_ffi metadata should validate");

        let op = &ir.functions[0].ops[0];
        assert_eq!(
            op.native_callable_export.as_deref(),
            Some("scipy.ndimage.distance_transform_edt")
        );
        assert_eq!(op.native_callable_binding.as_deref(), Some("direct_symbol"));
        assert_eq!(
            op.native_callable_symbol.as_deref(),
            Some("molt_scipy_ndimage_distance_transform_edt")
        );
        assert_eq!(
            op.native_callable_abi.as_deref(),
            Some("molt.forward_f32_v1")
        );
    }

    #[test]
    fn simple_ir_from_json_str_rejects_native_callable_metadata_on_non_invoke_ffi() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["x"],
                        "ops": [
                            {
                                "kind": "call",
                                "s_value": "scipy__ndimage__distance_transform_edt",
                                "args": ["x"],
                                "out": "result",
                                "native_callable_export": "scipy.ndimage.distance_transform_edt",
                                "native_callable_binding": "module_attr",
                                "native_callable_abi": "molt.forward_f32_v1"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("native callable metadata belongs only on invoke_ffi");

        assert!(err.contains("op `call` cannot carry native callable export metadata"));
    }

    #[test]
    fn simple_ir_from_json_str_rejects_unknown_native_callable_abi() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["arg0"],
                        "ops": [
                            {
                                "kind": "invoke_ffi",
                                "args": ["arg0"],
                                "out": "result",
                                "native_callable_export": "scipy.ndimage.distance_transform_edt",
                                "native_callable_binding": "direct_symbol",
                                "native_callable_symbol": "molt_scipy_ndimage_distance_transform_edt",
                                "native_callable_abi": "molt.forward_f33_v1"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("native callable ABI tokens must be canonical");

        assert!(err.contains("unknown native_callable_abi `molt.forward_f33_v1`"));
        assert!(err.contains(crate::native_callable_abi::NATIVE_CALLABLE_ABI_CHOICES));
    }

    #[test]
    fn simple_ir_from_json_str_rejects_direct_symbol_without_native_symbol() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["arg0"],
                        "ops": [
                            {
                                "kind": "invoke_ffi",
                                "args": ["arg0"],
                                "out": "result",
                                "native_callable_export": "scipy.ndimage.distance_transform_edt",
                                "native_callable_binding": "direct_symbol",
                                "native_callable_abi": "molt.forward_f32_v1"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("direct_symbol callable exports require a native symbol");

        assert!(err.contains("direct_symbol requires native_callable_symbol"));
    }

    #[test]
    fn simple_ir_from_json_str_rejects_module_attr_direct_symbol_abi() {
        let err = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["arg0"],
                        "ops": [
                            {
                                "kind": "invoke_ffi",
                                "args": ["func", "arg0"],
                                "out": "result",
                                "native_callable_export": "scipy.ndimage.distance_transform_edt",
                                "native_callable_binding": "module_attr",
                                "native_callable_abi": "molt.forward_f32_v1"
                            }
                        ]
                    }
                ]
            }"#,
        )
        .expect_err("module_attr cannot carry pointer/typed direct-symbol ABIs");

        assert!(err.contains("uses module_attr direct-symbol ABI `molt.forward_f32_v1`"));
    }

    #[test]
    fn simple_ir_from_json_str_accepts_legacy_var_names_at_transport_boundary() {
        let ir = SimpleIR::from_json_str(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": [],
                        "ops": [
                            {"kind": "const", "value": 1, "out": "v0"},
                            {"kind": "store_var", "var": "future_features", "args": ["v0"]},
                            {"kind": "ret_void"}
                        ]
                    }
                ]
            }"#,
        )
        .expect("transport boundary should accept legacy variable identifiers");

        assert_eq!(ir.functions.len(), 1);
    }

    #[test]
    fn serde_deserialize_rejects_contract_violations() {
        let err = serde_json::from_str::<SimpleIR>(
            r#"{
                "functions": [
                    {
                        "name": "__main__",
                        "params": ["x"],
                        "param_types": ["int", "bool"],
                        "ops": [{"kind": "ret_void"}]
                    }
                ]
            }"#,
        )
        .expect_err("serde SimpleIR boundary should validate contracts");

        assert!(err.to_string().contains("invalid SimpleIR contract"));
        assert!(err.to_string().contains("has 1 params but 2 param_types"));
    }

    #[test]
    fn ndjson_reader_parses_stream() {
        let input = r#"{"kind":"ir_stream_start","profile":null}
{"kind":"function","name":"molt_main","params":[],"ops":[{"kind":"ret_void"}]}
{"kind":"function","name":"helper","params":["a"],"ops":[{"kind":"return","args":["a"]}]}
{"kind":"ir_stream_end"}
"#;
        let reader = std::io::BufReader::new(input.as_bytes());
        let ir = SimpleIR::from_ndjson_reader(reader).expect("ndjson parse");
        assert_eq!(ir.functions.len(), 2);
        assert_eq!(ir.functions[0].name, "molt_main");
        assert_eq!(ir.functions[1].name, "helper");
        assert!(ir.profile.is_none());
    }

    #[test]
    fn ndjson_reader_parses_profile() {
        let input = r#"{"kind":"ir_stream_start","profile":{"version":"v1","hot_functions":["f"]}}
{"kind":"function","name":"f","params":[],"ops":[{"kind":"ret_void"}]}
{"kind":"ir_stream_end"}
"#;
        let reader = std::io::BufReader::new(input.as_bytes());
        let ir = SimpleIR::from_ndjson_reader(reader).expect("ndjson parse");
        assert_eq!(ir.functions.len(), 1);
        let profile = ir.profile.expect("profile");
        assert_eq!(profile.version.as_deref(), Some("v1"));
        assert_eq!(profile.hot_functions, vec!["f"]);
    }

    #[test]
    fn ndjson_reader_skips_blank_lines_and_unknown_kinds() {
        let input = r#"{"kind":"ir_stream_start","profile":null}

{"kind":"unknown_future_thing","data":123}
{"kind":"function","name":"main","params":[],"ops":[{"kind":"ret_void"}]}
{"kind":"ir_stream_end"}
"#;
        let reader = std::io::BufReader::new(input.as_bytes());
        let ir = SimpleIR::from_ndjson_reader(reader).expect("ndjson parse");
        assert_eq!(ir.functions.len(), 1);
    }

    #[test]
    fn ndjson_reader_handles_empty_stream() {
        let input = r#"{"kind":"ir_stream_start","profile":null}
{"kind":"ir_stream_end"}
"#;
        let reader = std::io::BufReader::new(input.as_bytes());
        let ir = SimpleIR::from_ndjson_reader(reader).expect("ndjson parse");
        assert_eq!(ir.functions.len(), 0);
        assert!(ir.profile.is_none());
    }

    #[test]
    fn ndjson_reader_rejects_contract_violations() {
        let input = r#"{"kind":"ir_stream_start","profile":null}
{"kind":"function","name":"__main__","params":["x"],"param_types":["int","bool"],"ops":[{"kind":"ret_void"}]}
{"kind":"ir_stream_end"}
"#;
        let reader = std::io::BufReader::new(input.as_bytes());
        let err =
            SimpleIR::from_ndjson_reader(reader).expect_err("NDJSON boundary should validate");

        assert!(err.contains("invalid SimpleIR contract"));
        assert!(err.contains("has 1 params but 2 param_types"));
    }
}
