// @generated by tools/gen_wasm_abi.py from
// runtime/molt-backend-wasm/src/wasm_abi_manifest.toml
// runtime/molt-runtime/src/intrinsics/manifest.pyi
// src/molt/frontend/_types.py
// runtime/molt-runtime/src/intrinsics/categories.toml
// DO NOT EDIT BY HAND.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PythonBuiltinCallableSpec {
    pub python_name: &'static str,
    pub python_module: &'static str,
    pub runtime_name: &'static str,
    pub arity: usize,
}

pub const PYTHON_BUILTIN_CALLABLES: &[PythonBuiltinCallableSpec] = &[
    PythonBuiltinCallableSpec {
        python_name: "__import__",
        python_module: "builtins",
        runtime_name: "molt_importlib_import_transaction",
        arity: 5,
    },
    PythonBuiltinCallableSpec {
        python_name: "abs",
        python_module: "builtins",
        runtime_name: "molt_abs_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "aiter",
        python_module: "builtins",
        runtime_name: "molt_aiter",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "all",
        python_module: "builtins",
        runtime_name: "molt_all_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "anext",
        python_module: "builtins",
        runtime_name: "molt_anext_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "any",
        python_module: "builtins",
        runtime_name: "molt_any_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "ascii",
        python_module: "builtins",
        runtime_name: "molt_ascii_from_obj",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "bin",
        python_module: "builtins",
        runtime_name: "molt_bin_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "callable",
        python_module: "builtins",
        runtime_name: "molt_callable_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "chr",
        python_module: "builtins",
        runtime_name: "molt_chr",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "compile",
        python_module: "builtins",
        runtime_name: "molt_compile_builtin",
        arity: 6,
    },
    PythonBuiltinCallableSpec {
        python_name: "delattr",
        python_module: "builtins",
        runtime_name: "molt_del_attr_name",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "dir",
        python_module: "builtins",
        runtime_name: "molt_dir_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "divmod",
        python_module: "builtins",
        runtime_name: "molt_divmod_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "enumerate",
        python_module: "builtins",
        runtime_name: "molt_enumerate_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "filter",
        python_module: "builtins",
        runtime_name: "molt_filter_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "format",
        python_module: "builtins",
        runtime_name: "molt_format_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "getattr",
        python_module: "builtins",
        runtime_name: "molt_getattr_builtin",
        arity: 3,
    },
    PythonBuiltinCallableSpec {
        python_name: "globals",
        python_module: "builtins",
        runtime_name: "molt_globals_builtin",
        arity: 0,
    },
    PythonBuiltinCallableSpec {
        python_name: "hasattr",
        python_module: "builtins",
        runtime_name: "molt_has_attr_name",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "hash",
        python_module: "builtins",
        runtime_name: "molt_hash_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "hex",
        python_module: "builtins",
        runtime_name: "molt_hex_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "id",
        python_module: "builtins",
        runtime_name: "molt_id",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "isinstance",
        python_module: "builtins",
        runtime_name: "molt_isinstance",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "issubclass",
        python_module: "builtins",
        runtime_name: "molt_issubclass",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "iter",
        python_module: "builtins",
        runtime_name: "molt_iter_checked",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "len",
        python_module: "builtins",
        runtime_name: "molt_len",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "locals",
        python_module: "builtins",
        runtime_name: "molt_locals_builtin",
        arity: 0,
    },
    PythonBuiltinCallableSpec {
        python_name: "map",
        python_module: "builtins",
        runtime_name: "molt_map_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "max",
        python_module: "builtins",
        runtime_name: "molt_max_builtin",
        arity: 3,
    },
    PythonBuiltinCallableSpec {
        python_name: "min",
        python_module: "builtins",
        runtime_name: "molt_min_builtin",
        arity: 3,
    },
    PythonBuiltinCallableSpec {
        python_name: "next",
        python_module: "builtins",
        runtime_name: "molt_next_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "oct",
        python_module: "builtins",
        runtime_name: "molt_oct_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "open",
        python_module: "_io",
        runtime_name: "molt_open_builtin",
        arity: 8,
    },
    PythonBuiltinCallableSpec {
        python_name: "ord",
        python_module: "builtins",
        runtime_name: "molt_ord",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "pow",
        python_module: "builtins",
        runtime_name: "molt_pow_mod",
        arity: 3,
    },
    PythonBuiltinCallableSpec {
        python_name: "print",
        python_module: "builtins",
        runtime_name: "molt_print_builtin",
        arity: 5,
    },
    PythonBuiltinCallableSpec {
        python_name: "repr",
        python_module: "builtins",
        runtime_name: "molt_repr_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "reversed",
        python_module: "builtins",
        runtime_name: "molt_reversed_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "round",
        python_module: "builtins",
        runtime_name: "molt_round_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "setattr",
        python_module: "builtins",
        runtime_name: "molt_set_attr_name",
        arity: 3,
    },
    PythonBuiltinCallableSpec {
        python_name: "sorted",
        python_module: "builtins",
        runtime_name: "molt_sorted_builtin",
        arity: 3,
    },
    PythonBuiltinCallableSpec {
        python_name: "sum",
        python_module: "builtins",
        runtime_name: "molt_sum_builtin",
        arity: 2,
    },
    PythonBuiltinCallableSpec {
        python_name: "vars",
        python_module: "builtins",
        runtime_name: "molt_vars_builtin",
        arity: 1,
    },
    PythonBuiltinCallableSpec {
        python_name: "zip",
        python_module: "builtins",
        runtime_name: "molt_zip_builtin",
        arity: 2,
    },
];

pub fn python_builtin_callable(name: &str) -> Option<&'static PythonBuiltinCallableSpec> {
    PYTHON_BUILTIN_CALLABLES
        .binary_search_by_key(&name, |spec| spec.python_name)
        .ok()
        .map(|index| &PYTHON_BUILTIN_CALLABLES[index])
}
