#[cfg(feature = "llvm")]
use super::fixed::fixed_runtime_import_return_abi;
use crate::runtime_import_abi::{
    MOLT_ASYNCGEN_NEW, MOLT_CANCEL_TOKEN_GET_CURRENT, MOLT_TASK_NEW,
    MOLT_TASK_REGISTER_TOKEN_OWNED, RuntimeImportSignature, RuntimeReturnAbi, runtime_sig,
};
/// Residual runtime symbols that lowering may declare on demand.
///
/// Fixed imports live in `fixed::FIXED_RUNTIME_IMPORTS`; this table is only the
/// conservative all-i64 fallback surface. Keeping it disjoint from the fixed
/// table prevents exact declarations and fallback ABI facts from diverging.
#[cfg(feature = "llvm")]
pub(crate) const CONSERVATIVE_RUNTIME_IMPORTS: &[RuntimeImportSignature] = &[
    runtime_sig("molt_abs_builtin", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_aiter", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_ascii_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_builtin_type", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_callargs_expand_kwstar", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_callargs_expand_star", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_callargs_push_kw", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_cbor_parse_scalar_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_chan_recv", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_chan_send", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_class_apply_set_name", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_class_layout_version", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_class_merge_layout", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_class_set_layout_version", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_closure_load", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_closure_store", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_complex_from_obj", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_depth", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_exit", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_unwind_to", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_dataclass_new", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_dataclass_new_from_values", 5, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_clear", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_copy", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_get", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_items", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_keys", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_popitem", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_set", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_setdefault", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_setdefault_empty_list", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_update", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_update_kwstar", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_update_missing", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_values", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_ellipsis", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_enumerate", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_active", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_class", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_context_set", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_match_builtin", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_new", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_new_builtin", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_new_builtin_empty", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_new_builtin_one", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_set_cause", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_set_last", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_float_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_format_builtin", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_frozenset_add", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_frozenset_new", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_future_poll", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_gen_locals_register", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_generator_close", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_generator_send", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_generator_throw", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_get_attr_name_default", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_get_attr_special", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_guard_layout_ptr", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_guard_type", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_guarded_class_def", 8, RuntimeReturnAbi::I64),
    runtime_sig("molt_guarded_field_get_ptr", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_guarded_field_init_ptr", 7, RuntimeReturnAbi::I64),
    runtime_sig("molt_guarded_field_set_ptr", 7, RuntimeReturnAbi::I64),
    runtime_sig("molt_has_attr_name", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_int_from_obj", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_int_from_str_of_obj", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_is_callable", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_isinstance", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_issubclass", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_iter_checked", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_iter_next_unboxed", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_json_parse_scalar_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_len", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_len_dict", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_len_list", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_len_set", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_len_str", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_len_tuple", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_append", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_extend", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_fill_new", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_from_range", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_missing", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_msgpack_parse_scalar_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_not_implemented", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_obj_get_state", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_obj_set_state", 2, RuntimeReturnAbi::Void),
    runtime_sig("molt_object_field_init_ptr", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_object_field_set_ptr", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_object_new", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_object_new_bound", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_object_new_bound_sized", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_ord", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_ord_at", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_range_new", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_repr_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_add", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_add_probe", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_sleep_register", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_slice", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_str_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_join", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_super_new", 2, RuntimeReturnAbi::I64),
    MOLT_TASK_NEW,
    runtime_sig("molt_tuple_from_list", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_type_of", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_unpack_sequence", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_max_int", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_max_int_range", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_max_int_range_trusted", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_max_int_trusted", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_min_int", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_min_int_range", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_min_int_range_trusted", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_min_int_trusted", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_prod_int", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_prod_int_range", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_prod_int_range_trusted", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_prod_int_trusted", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_float", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_float_range", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_float_range_iter", 2, RuntimeReturnAbi::I64),
    runtime_sig(
        "molt_vec_sum_float_range_iter_trusted",
        2,
        RuntimeReturnAbi::I64,
    ),
    runtime_sig("molt_vec_sum_float_range_trusted", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_float_trusted", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_int", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_int_range", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_int_range_iter", 2, RuntimeReturnAbi::I64),
    runtime_sig(
        "molt_vec_sum_int_range_iter_trusted",
        2,
        RuntimeReturnAbi::I64,
    ),
    runtime_sig("molt_vec_sum_int_range_trusted", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_vec_sum_int_trusted", 2, RuntimeReturnAbi::I64),
    // Frontend-preserved Copy spellings that reach the generic LLVM
    // `molt_<kind>` fallback. `MOLT_RUNTIME_INTRINSIC_SYMBOLS` proves only
    // active-profile availability; this table owns the boxed-call ABI.
    runtime_sig("molt_alloc_class", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_alloc_class_static", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_alloc_class_trusted", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_anext", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_asyncgen_locals_register", 3, RuntimeReturnAbi::I64),
    MOLT_ASYNCGEN_NEW,
    runtime_sig("molt_asyncgen_shutdown", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_block_on", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_bound_method_new", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bridge_unavailable", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_buffer2d_get", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_buffer2d_matmul", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_buffer2d_new", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_buffer2d_set", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_count", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_count_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_endswith", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_endswith_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_fill_range", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_find", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_find_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_from_str", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_replace", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_split", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_split_max", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_startswith", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytearray_startswith_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_count", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_count_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_endswith", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_endswith_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_find", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_find_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_from_obj", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_from_str", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_replace", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_split", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_split_max", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_startswith", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_bytes_startswith_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancel_current", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancel_token_cancel", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancel_token_clone", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancel_token_drop", 1, RuntimeReturnAbi::I64),
    MOLT_CANCEL_TOKEN_GET_CURRENT,
    runtime_sig("molt_cancel_token_is_cancelled", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancel_token_new", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancel_token_set_current", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_cancelled", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_chan_drop", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_chr", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_class_new", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_class_set_base", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_closing", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_enter", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_null", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_context_unwind", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_dataclass_get", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_dataclass_set", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_dataclass_set_class", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_inc", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_pop", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_dict_str_int_inc", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_env_get", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_kind", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_message", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_exception_new_from_class", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_exceptiongroup_combine", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_exceptiongroup_match", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_file_close", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_file_flush", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_file_open", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_file_read", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_file_write", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_function_closure_bits", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_future_cancel", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_future_cancel_clear", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_future_cancel_msg", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_id", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_intarray_from_seq", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_is_bound_method", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_is_generator", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_is_native_awaitable", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_iter", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_clear", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_copy", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_count", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_index", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_index_range", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_insert", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_int_new", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_pop", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_remove", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_list_reverse", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_matmul", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_inplace_matmul", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_memoryview_new", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_memoryview_tobytes", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_module_import_star", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_object_set_class", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_pow_mod", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_promise_new", 0, RuntimeReturnAbi::I64),
    runtime_sig("molt_promise_set_exception", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_promise_set_result", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_round", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_difference_update", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_discard", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_intersection_update", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_pop", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_remove", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_symdiff_update", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_set_update", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_spawn", 1, RuntimeReturnAbi::Void),
    runtime_sig("molt_statistics_mean_slice", 5, RuntimeReturnAbi::I64),
    runtime_sig("molt_statistics_stdev_slice", 5, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_capitalize", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_count", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_count_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_endswith", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_endswith_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_find", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_find_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_format", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_lower", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_lstrip", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_replace", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_rstrip", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_field", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_field_eq", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_field_len", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_field_to_int", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_max", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_sep_dict_inc", 4, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_validate", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_split_ws_dict_inc", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_startswith", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_startswith_slice", 6, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_strip", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_string_upper", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_taq_ingest_line", 3, RuntimeReturnAbi::I64),
    MOLT_TASK_REGISTER_TOKEN_OWNED,
    runtime_sig("molt_thread_submit", 3, RuntimeReturnAbi::I64),
    runtime_sig("molt_trunc", 1, RuntimeReturnAbi::I64),
    runtime_sig("molt_tuple_count", 2, RuntimeReturnAbi::I64),
    runtime_sig("molt_tuple_index", 2, RuntimeReturnAbi::I64),
];

#[cfg(feature = "llvm")]
pub(crate) fn runtime_import_return_abi(
    name: &str,
    param_count: usize,
) -> Option<RuntimeReturnAbi> {
    fixed_runtime_import_return_abi(name, param_count).or_else(|| {
        CONSERVATIVE_RUNTIME_IMPORTS
            .iter()
            .find(|sig| sig.name == name && sig.param_count == param_count)
            .map(|sig| sig.return_abi)
    })
}

#[cfg(feature = "llvm")]
pub(crate) fn is_runtime_import_abi(
    name: &str,
    param_count: usize,
    return_abi: RuntimeReturnAbi,
) -> bool {
    runtime_import_return_abi(name, param_count) == Some(return_abi)
}
