from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "tools" / "bench_report.py"


def _load_module():
    spec = importlib.util.spec_from_file_location(
        "bench_report_under_test", SCRIPT_PATH
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def test_bench_report_updates_status_doc_and_keeps_detailed_report(
    tmp_path: Path,
) -> None:
    module = _load_module()
    native_path = tmp_path / "bench/results/native.json"
    wasm_path = tmp_path / "bench/results/wasm.json"
    out_path = tmp_path / "docs/benchmarks/bench_summary.md"
    status_doc = tmp_path / "docs/spec/STATUS.md"
    status_doc.parent.mkdir(parents=True, exist_ok=True)
    status_doc.write_text(
        "\n".join(
            [
                "# STATUS",
                "",
                "<!-- GENERATED:bench-summary:start -->",
                "stale",
                "<!-- GENERATED:bench-summary:end -->",
                "",
            ]
        ),
        encoding="utf-8",
    )
    _write_json(
        native_path,
        {
            "created_at": "2026-04-03T12:00:00Z",
            "system": {"platform": "macos-14", "machine": "arm64", "python": "3.12.9"},
            "benchmarks": {
                "bench_sum.py": {
                    "molt_ok": True,
                    "molt_time_s": 0.50,
                    "cpython_time_s": 1.00,
                    "molt_speedup": 2.0,
                }
            },
        },
    )
    _write_json(
        wasm_path,
        {
            "created_at": "2026-04-03T12:10:00Z",
            "system": {"platform": "wasmtime", "machine": "wasm32", "python": "n/a"},
            "benchmarks": {
                "bench_sum.py": {
                    "molt_wasm_ok": True,
                    "molt_wasm_time_s": 2.00,
                    "molt_wasm_size_kb": 321.0,
                }
            },
        },
    )

    assert (
        module.main(
            [
                "--native",
                str(native_path),
                "--wasm",
                str(wasm_path),
                "--out",
                str(out_path),
                "--update-status-doc",
                "--status-doc-path",
                str(status_doc),
            ]
        )
        == 0
    )

    assert out_path.exists()
    report = out_path.read_text(encoding="utf-8")
    assert "Generated by `tools/bench_report.py`." in report

    updated_status = status_doc.read_text(encoding="utf-8")
    assert "Latest run: 2026-04-03" in updated_status
    assert "Top speedups:" in updated_status
    assert "WASM run: 2026-04-03" in updated_status


def test_bench_report_requires_status_markers_when_updating_status_doc(
    tmp_path: Path,
) -> None:
    module = _load_module()
    native_path = tmp_path / "bench/results/native.json"
    wasm_path = tmp_path / "bench/results/wasm.json"
    out_path = tmp_path / "docs/benchmarks/bench_summary.md"
    status_doc = tmp_path / "docs/spec/STATUS.md"
    status_doc.parent.mkdir(parents=True, exist_ok=True)
    status_doc.write_text("# STATUS\n", encoding="utf-8")
    _write_json(
        native_path,
        {
            "created_at": "2026-04-03T12:00:00Z",
            "system": {"platform": "macos-14", "machine": "arm64", "python": "3.12.9"},
            "benchmarks": {},
        },
    )
    _write_json(
        wasm_path,
        {
            "created_at": "2026-04-03T12:10:00Z",
            "system": {"platform": "wasmtime", "machine": "wasm32", "python": "n/a"},
            "benchmarks": {},
        },
    )

    assert (
        module.main(
            [
                "--native",
                str(native_path),
                "--wasm",
                str(wasm_path),
                "--out",
                str(out_path),
                "--update-status-doc",
                "--status-doc-path",
                str(status_doc),
            ]
        )
        == 1
    )
