from __future__ import annotations

from collections import OrderedDict
import importlib.util
from pathlib import Path
from types import SimpleNamespace


ROOT = Path(__file__).resolve().parents[1]
GEN_INTRINSICS = ROOT / "tools" / "gen_intrinsics.py"


def _load_gen_intrinsics_module():
    spec = importlib.util.spec_from_file_location(
        "molt_test_gen_intrinsics", GEN_INTRINSICS
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_backend_symbol_overrides_file_is_removed() -> None:
    assert not (
        ROOT / "runtime/molt-backend/src/intrinsic_symbol_overrides.rs"
    ).exists()


def test_async_sleep_intrinsic_symbol_matches_public_name() -> None:
    module = _load_gen_intrinsics_module()
    _raw, entries = module._load_manifest()
    symbols = {name: symbol for name, symbol, _arity in entries}
    assert symbols["molt_async_sleep"] == "molt_async_sleep"


def test_manifest_literal_defaults_feed_generated_intrinsic_metadata() -> None:
    module = _load_gen_intrinsics_module()
    _raw, entries = module._load_manifest()

    by_name = {entry.name: entry for entry in entries}
    length_hint = by_name["molt_operator_length_hint"]

    assert length_hint.arity == 2
    assert length_hint.defaults == ("IntrinsicDefaultValue::Int(0)",)

    generated = (ROOT / "runtime/molt-runtime/src/intrinsics/generated.rs").read_text()
    assert "pub(crate) enum IntrinsicDefaultValue" in generated
    assert "molt_operator_length_hint" in generated
    assert "defaults: &[IntrinsicDefaultValue::Int(0)]," in generated

    registry = (ROOT / "runtime/molt-runtime/src/intrinsics/registry.rs").read_text()
    assert "fn attach_function_defaults" in registry
    assert "b\"__defaults__\"" in registry
    assert "function_set_attr_bits(_py, ptr, defaults_name, defaults_bits)" in registry
    assert (
        registry.count("build_intrinsic_func(_py, fn_ptr, spec.arity, spec.defaults)")
        == 2
    ), "eager and lazy intrinsic registration must attach manifest defaults"


def test_ssl_intrinsic_abi_is_not_profile_gated() -> None:
    module = _load_gen_intrinsics_module()
    _raw, entries = module._load_manifest()

    ssl_symbols = sorted(
        {symbol for _name, symbol, _arity in entries if symbol.startswith("molt_ssl_")}
    )
    assert ssl_symbols
    for symbol in ssl_symbols:
        assert module._feature_gate_for_symbol(symbol) is None

    assert module._feature_gate_for_symbol("molt_http_client_execute") == "stdlib_http"
    assert module._feature_gate_for_symbol("molt_html_escape") == "stdlib_text"
    assert module._feature_gate_for_symbol("molt_unicodedata_category") == "stdlib_text"
    assert (
        module._feature_gate_for_symbol("molt_zoneinfo_available_timezones")
        == "stdlib_zoneinfo"
    )

    generated = (
        ROOT / "runtime/molt-runtime/src/intrinsics/generated_resolvers/ssl_resolver.rs"
    ).read_text()
    ssl_block = generated.split("pub(super) fn resolve_symbol", 1)[1].split(
        "        _ => None,",
        1,
    )[0]
    assert '#[cfg(feature = "stdlib_net")]' not in ssl_block


def test_runtime_feature_gates_are_generated_from_categories() -> None:
    module = _load_gen_intrinsics_module()
    gates_path = ROOT / "src/molt/_runtime_feature_gates.py"
    spec = importlib.util.spec_from_file_location(
        "molt_test_runtime_feature_gates", gates_path
    )
    assert spec is not None
    assert spec.loader is not None
    gates_module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gates_module)

    expected_gates = module._load_runtime_feature_gates_from_categories()
    assert list(gates_module.RUNTIME_FEATURE_GATES) == expected_gates
    assert tuple(sorted(gates_module.LINK_AFFECTING_FEATURES)) == (
        module._mechanically_derived_link_affecting_features(expected_gates)
    )
    assert "# @generated by tools/gen_intrinsics.py. DO NOT EDIT." in (
        gates_path.read_text()
    )


def test_toml_prefixes_do_not_fall_back_to_extra_prefix_modules() -> None:
    module = _load_gen_intrinsics_module()
    _builtin_symbols, _internal_prefixes, stdlib_modules = module._load_categories()
    toml_prefixes = [
        (prefix, module_name)
        for module_name, prefixes in stdlib_modules.items()
        for prefix in prefixes
    ]
    shadowed = [
        (extra_prefix, extra_module, toml_prefix, toml_module)
        for extra_prefix, extra_module in module._EXTRA_PREFIX_MODULES
        for toml_prefix, toml_module in toml_prefixes
        if extra_prefix.startswith(toml_prefix)
    ]
    assert shadowed == []


def test_generated_resolvers_are_split_from_manifest_table() -> None:
    """Resolver address-taking is generated into per-module Rust files."""
    generated_path = ROOT / "runtime/molt-runtime/src/intrinsics/generated.rs"
    resolver_root = ROOT / "runtime/molt-runtime/src/intrinsics/generated_resolvers"
    generated = generated_path.read_text()
    resolver_mod = (resolver_root / "mod.rs").read_text()
    core_resolver = (resolver_root / "core_resolver.rs").read_text()
    ssl_resolver = (resolver_root / "ssl_resolver.rs").read_text()

    assert (
        '#[path = "generated_resolvers/mod.rs"]\nmod generated_resolvers;' in generated
    )
    assert "pub(crate) use generated_resolvers::resolve_symbol;" in generated
    assert "IntrinsicSpec {" in generated
    assert "fn resolve_core_symbol" not in generated
    assert "mod core_resolver;" in resolver_mod
    assert "pub(crate) fn resolve_symbol" in resolver_mod
    assert "molt_capabilities_trusted" in core_resolver
    assert "molt_ssl_context_new" not in core_resolver
    assert "molt_ssl_context_new" in ssl_resolver

    html_resolver = (resolver_root / "html_resolver.rs").read_text()
    unicodedata_resolver = (resolver_root / "unicodedata_resolver.rs").read_text()
    zoneinfo_resolver = (resolver_root / "zoneinfo_resolver.rs").read_text()
    assert '#[cfg(feature = "stdlib_text")]' in html_resolver
    assert '#[cfg(feature = "stdlib_text")]' in unicodedata_resolver
    assert '#[cfg(feature = "stdlib_zoneinfo")]' in zoneinfo_resolver


def test_stringprep_category_is_toml_owned() -> None:
    module = _load_gen_intrinsics_module()
    builtin_symbols, internal_prefixes, stdlib_modules = module._load_categories()

    assert stdlib_modules["stringprep"] == ["molt_stringprep_"]
    assert ("molt_stringprep_", "stringprep") not in module._EXTRA_PREFIX_MODULES
    assert "feature" not in module.LEAF_RESOLVER_REGISTRIES["stringprep"]
    assert (
        module._classify_symbol(
            "molt_stringprep_in_table",
            builtin_symbols,
            internal_prefixes,
            stdlib_modules,
        )
        == "stringprep"
    )
    assert (
        module._leaf_resolver_feature_gate("stringprep", ["molt_stringprep_in_table"])
        == "stdlib_stringprep"
    )


def test_stringprep_resolver_is_leaf_owned() -> None:
    resolver_root = ROOT / "runtime/molt-runtime/src/intrinsics/generated_resolvers"
    facade_resolver = (resolver_root / "stringprep_resolver.rs").read_text()
    leaf_resolver = (
        ROOT / "runtime/molt-runtime-stringprep/src/intrinsics_generated.rs"
    ).read_text()

    assert "molt_runtime_stringprep::intrinsics_generated::resolve_symbol_with" in (
        facade_resolver
    )
    assert "crate::builtins::functions::runtime_fn_addr" in facade_resolver
    assert "crate::molt_stringprep_in_table as *const ()" not in facade_resolver
    assert "pub fn resolve_symbol_with" in leaf_resolver
    assert "crate::stringprep::molt_stringprep_in_table as *const ()" in leaf_resolver
    assert "molt_runtime_stringprep::stringprep::molt_stringprep_in_table" in (
        leaf_resolver
    )


def test_collections_and_argparse_categories_are_toml_owned() -> None:
    module = _load_gen_intrinsics_module()
    builtin_symbols, internal_prefixes, stdlib_modules = module._load_categories()

    assert stdlib_modules["argparse"] == ["molt_argparse_"]
    assert stdlib_modules["collections"] == [
        "molt_namedtuple_",
        "molt_ordereddict_",
        "molt_defaultdict_",
        "molt_deque_",
        "molt_counter_",
        "molt_chainmap_",
    ]
    for prefix in (
        "molt_argparse_",
        "molt_namedtuple_",
        "molt_ordereddict_",
        "molt_defaultdict_",
        "molt_deque_",
        "molt_counter_",
        "molt_chainmap_",
    ):
        assert all(prefix != extra[0] for extra in module._EXTRA_PREFIX_MODULES)

    assert (
        module._classify_symbol(
            "molt_argparse_parser_new",
            builtin_symbols,
            internal_prefixes,
            stdlib_modules,
        )
        == "argparse"
    )
    assert (
        module._classify_symbol(
            "molt_deque_append",
            builtin_symbols,
            internal_prefixes,
            stdlib_modules,
        )
        == "collections"
    )
    assert (
        module._classify_symbol(
            "molt_collections_abc_runtime_types",
            builtin_symbols,
            internal_prefixes,
            stdlib_modules,
        )
        == "core"
    )


def test_collections_and_argparse_resolvers_are_leaf_owned() -> None:
    resolver_root = ROOT / "runtime/molt-runtime/src/intrinsics/generated_resolvers"
    facade_argparse = (resolver_root / "argparse_resolver.rs").read_text()
    facade_collections = (resolver_root / "collections_resolver.rs").read_text()
    leaf_root = ROOT / "runtime/molt-runtime-collections/src/intrinsics_generated"
    leaf_index = (leaf_root / "mod.rs").read_text()
    leaf_argparse = (leaf_root / "argparse_resolver.rs").read_text()
    leaf_collections = (leaf_root / "collections_resolver.rs").read_text()
    generated = (ROOT / "runtime/molt-runtime/src/intrinsics/generated.rs").read_text()
    manifest = (ROOT / "runtime/molt-runtime/src/intrinsics/manifest.pyi").read_text()

    assert "def molt_argparse_parse(" not in manifest
    assert 'name: "molt_argparse_parse"' not in generated
    assert "pub mod argparse_resolver;" in leaf_index
    assert "pub mod collections_resolver;" in leaf_index

    assert (
        "molt_runtime_collections::intrinsics_generated::argparse_resolver"
        "::resolve_symbol_with" in facade_argparse
    )
    assert (
        "molt_runtime_collections::intrinsics_generated::collections_resolver"
        "::resolve_symbol_with" in facade_collections
    )
    assert "crate::molt_argparse_parser_new as *const ()" not in facade_argparse
    assert "crate::molt_deque_append as *const ()" not in facade_collections
    assert "crate::builtins::functions::runtime_fn_addr" in facade_argparse
    assert "crate::builtins::functions::runtime_fn_addr" in facade_collections

    assert "crate::argparse::molt_argparse_parser_new as *const ()" in leaf_argparse
    assert (
        "molt_runtime_collections::argparse::molt_argparse_parser_new"
        in leaf_argparse
    )
    assert "crate::collections_ext::molt_deque_append as *const ()" in (
        leaf_collections
    )
    assert "molt_runtime_collections::collections_ext::molt_deque_append" in (
        leaf_collections
    )


def test_rustfmt_uses_shared_memory_guard(monkeypatch, tmp_path: Path) -> None:
    module = _load_gen_intrinsics_module()
    calls: list[dict[str, object]] = []
    target = tmp_path / "generated.rs"
    target.write_text("fn main(){}\n", encoding="utf-8")

    def fake_guarded_completed_process(cmd, **kwargs):
        calls.append({"cmd": list(cmd), **kwargs})
        return SimpleNamespace(
            returncode=0,
            stdout="",
            stderr="",
            check_returncode=lambda: None,
        )

    monkeypatch.setattr(
        module,
        "_HARNESS_MEMORY_GUARD",
        SimpleNamespace(guarded_completed_process=fake_guarded_completed_process),
    )

    module._rustfmt(target)

    assert calls == [
        {
            "cmd": ["rustfmt", str(target)],
            "prefix": "MOLT_GENERATOR",
            "cwd": ROOT,
            "capture_output": True,
            "text": True,
            "timeout": 60.0,
        }
    ]


def test_rustfmt_failure_reports_guarded_output(monkeypatch, tmp_path: Path) -> None:
    module = _load_gen_intrinsics_module()
    target = tmp_path / "generated.rs"
    target.write_text("fn main( {\n", encoding="utf-8")

    def fake_guarded_completed_process(_cmd, **_kwargs):
        return SimpleNamespace(
            returncode=1,
            stdout="format stdout",
            stderr="format stderr",
        )

    monkeypatch.setattr(
        module,
        "_HARNESS_MEMORY_GUARD",
        SimpleNamespace(guarded_completed_process=fake_guarded_completed_process),
    )

    try:
        module._rustfmt(target)
    except RuntimeError as exc:
        message = str(exc)
    else:  # pragma: no cover - explicit fail branch for pytest output clarity
        raise AssertionError("rustfmt failure did not raise RuntimeError")

    assert f"rustfmt failed for {target}" in message
    assert "stdout:\nformat stdout" in message
    assert "stderr:\nformat stderr" in message


def test_write_rust_if_changed_skips_rustfmt_for_exact_match(
    monkeypatch, tmp_path: Path
) -> None:
    module = _load_gen_intrinsics_module()
    target = tmp_path / "generated.rs"
    text = "// @generated by tools/gen_intrinsics.py. DO NOT EDIT.\nfn main() {}\n"
    target.write_text(text, encoding="utf-8")
    calls: list[Path] = []

    monkeypatch.setattr(module, "_rustfmt", lambda path: calls.append(path))

    assert module._write_rust_if_changed(target, text) is False
    assert calls == []
    assert target.read_text(encoding="utf-8") == text


def test_resolver_cleanup_preserves_concurrent_temp_files(
    monkeypatch, tmp_path: Path
) -> None:
    module = _load_gen_intrinsics_module()
    resolver_root = tmp_path / "generated_resolvers"
    resolver_root.mkdir()
    hidden_temp = resolver_root / ".ssl_resolver.rs.12345.tmp.rs"
    hidden_temp.write_text("temp", encoding="utf-8")
    stale_resolver = resolver_root / "removed_resolver.rs"
    stale_resolver.write_text("stale", encoding="utf-8")

    monkeypatch.setattr(module, "OUT_RS_RESOLVERS_DIR", resolver_root)
    monkeypatch.setattr(module, "_rustfmt", lambda _path: None)

    module._write_resolver_modules(OrderedDict({"core": ["molt_capabilities_trusted"]}))

    assert hidden_temp.read_text(encoding="utf-8") == "temp"
    assert not stale_resolver.exists()
    assert (resolver_root / "core_resolver.rs").exists()
