from __future__ import annotations

import importlib.util
import json
import math
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "tools" / "bench_report.py"


def _load_module():
    spec = importlib.util.spec_from_file_location(
        "bench_report_under_test", SCRIPT_PATH
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def _write_manifest(path: Path, payload: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def test_bench_report_updates_status_doc_and_keeps_detailed_report(
    tmp_path: Path,
) -> None:
    module = _load_module()
    module.ROOT = tmp_path
    native_path = tmp_path / "bench/results/native.json"
    wasm_path = tmp_path / "bench/results/wasm.json"
    out_path = tmp_path / "docs/benchmarks/bench_summary.md"
    status_doc = tmp_path / "docs/spec/STATUS.md"
    manifest_path = tmp_path / "bench/results/docs_manifest.json"
    status_doc.parent.mkdir(parents=True, exist_ok=True)
    status_doc.write_text(
        "\n".join(
            [
                "# STATUS",
                "",
                "<!-- GENERATED:bench-summary:start -->",
                "stale",
                "<!-- GENERATED:bench-summary:end -->",
                "",
            ]
        ),
        encoding="utf-8",
    )
    _write_json(
        native_path,
        {
            "created_at": "2026-04-03T12:00:00Z",
            "timing_mode": "warm_throughput",
            "warmup": 1,
            "samples": 3,
            "system": {"platform": "macos-14", "machine": "arm64", "python": "3.12.9"},
            "benchmarks": {
                "bench_sum.py": {
                    "molt_ok": True,
                    "molt_time_s": 0.50,
                    "cpython_time_s": 1.00,
                    "molt_speedup": 2.0,
                }
            },
        },
    )
    _write_json(
        wasm_path,
        {
            "created_at": "2026-04-03T12:10:00Z",
            "timing_mode": "cold_first_run",
            "warmup": 0,
            "samples": 1,
            "system": {"platform": "wasmtime", "machine": "wasm32", "python": "n/a"},
            "benchmarks": {
                "bench_sum.py": {
                    "molt_wasm_ok": True,
                    "molt_wasm_time_s": 2.00,
                    "molt_wasm_size_kb": 321.0,
                }
            },
        },
    )
    _write_manifest(
        manifest_path,
        {
            "native": "bench/results/native.json",
            "wasm": "bench/results/wasm.json",
            "out": "docs/benchmarks/bench_summary.md",
            "status_doc": "docs/spec/STATUS.md",
        },
    )

    assert (
        module.main(
            [
                "--manifest",
                str(manifest_path),
                "--update-status-doc",
            ]
        )
        == 0
    )

    assert out_path.exists()
    report = out_path.read_text(encoding="utf-8")
    assert "Generated by `tools/bench_report.py`." in report
    assert "Generated:" not in report
    assert "`bench/results/native.json`" in report
    assert "`bench/results/wasm.json`" in report
    assert "timing_mode=warm_throughput, warmup=1, samples=3" in report
    assert "timing_mode=cold_first_run, warmup=0, samples=1" in report
    assert str(native_path) not in report
    assert str(wasm_path) not in report

    updated_status = status_doc.read_text(encoding="utf-8")
    assert "Latest run: 2026-04-03" in updated_status
    assert "Top speedups:" in updated_status
    assert "WASM run: 2026-04-03" in updated_status
    assert (
        module.main(
            [
                "--manifest",
                str(manifest_path),
                "--check",
                "--update-status-doc",
            ]
        )
        == 0
    )


def test_bench_report_requires_status_markers_when_updating_status_doc(
    tmp_path: Path,
) -> None:
    module = _load_module()
    native_path = tmp_path / "bench/results/native.json"
    wasm_path = tmp_path / "bench/results/wasm.json"
    out_path = tmp_path / "docs/benchmarks/bench_summary.md"
    status_doc = tmp_path / "docs/spec/STATUS.md"
    status_doc.parent.mkdir(parents=True, exist_ok=True)
    status_doc.write_text("# STATUS\n", encoding="utf-8")
    _write_json(
        native_path,
        {
            "created_at": "2026-04-03T12:00:00Z",
            "system": {"platform": "macos-14", "machine": "arm64", "python": "3.12.9"},
            "benchmarks": {},
        },
    )
    _write_json(
        wasm_path,
        {
            "created_at": "2026-04-03T12:10:00Z",
            "system": {"platform": "wasmtime", "machine": "wasm32", "python": "n/a"},
            "benchmarks": {},
        },
    )

    assert (
        module.main(
            [
                "--native",
                str(native_path),
                "--wasm",
                str(wasm_path),
                "--out",
                str(out_path),
                "--update-status-doc",
                "--status-doc-path",
                str(status_doc),
            ]
        )
        == 1
    )


def test_bench_report_check_fails_for_stale_generated_outputs(tmp_path: Path) -> None:
    module = _load_module()
    module.ROOT = tmp_path
    native_path = tmp_path / "bench/results/native.json"
    wasm_path = tmp_path / "bench/results/wasm.json"
    out_path = tmp_path / "docs/benchmarks/bench_summary.md"
    status_doc = tmp_path / "docs/spec/STATUS.md"
    manifest_path = tmp_path / "bench/results/docs_manifest.json"
    status_doc.parent.mkdir(parents=True, exist_ok=True)
    status_doc.write_text(
        "\n".join(
            [
                "# STATUS",
                "",
                "<!-- GENERATED:bench-summary:start -->",
                "stale",
                "<!-- GENERATED:bench-summary:end -->",
                "",
            ]
        ),
        encoding="utf-8",
    )
    _write_json(
        native_path,
        {
            "created_at": "2026-04-03T12:00:00Z",
            "system": {"platform": "macos-14", "machine": "arm64", "python": "3.12.9"},
            "benchmarks": {},
        },
    )
    _write_json(
        wasm_path,
        {
            "created_at": "2026-04-03T12:10:00Z",
            "system": {"platform": "wasmtime", "machine": "wasm32", "python": "n/a"},
            "benchmarks": {},
        },
    )
    _write_manifest(
        manifest_path,
        {
            "native": "bench/results/native.json",
            "wasm": "bench/results/wasm.json",
            "out": "docs/benchmarks/bench_summary.md",
            "status_doc": "docs/spec/STATUS.md",
        },
    )

    assert (
        module.main(
            [
                "--manifest",
                str(manifest_path),
                "--update-status-doc",
            ]
        )
        == 0
    )

    out_path.write_text("# stale\n", encoding="utf-8")
    assert (
        module.main(
            [
                "--manifest",
                str(manifest_path),
                "--check",
                "--update-status-doc",
            ]
        )
        == 1
    )


def test_failed_wasm_zero_time_is_not_reported_as_speed(tmp_path: Path) -> None:
    module = _load_module()
    module.ROOT = tmp_path
    native_path = tmp_path / "bench/results/native.json"
    wasm_path = tmp_path / "bench/results/wasm.json"
    out_path = tmp_path / "docs/benchmarks/bench_summary.md"
    _write_json(
        native_path,
        {
            "created_at": "2026-04-03T12:00:00Z",
            "system": {"platform": "macos-14", "machine": "arm64", "python": "3.12.9"},
            "benchmarks": {
                "ok.py": {
                    "molt_ok": True,
                    "molt_time_s": 0.50,
                    "cpython_time_s": 1.00,
                    "molt_speedup": 2.0,
                },
                "failed.py": {
                    "molt_ok": True,
                    "molt_time_s": 0.25,
                    "cpython_time_s": 1.00,
                    "molt_speedup": 4.0,
                },
            },
        },
    )
    _write_json(
        wasm_path,
        {
            "created_at": "2026-04-03T12:10:00Z",
            "system": {"platform": "wasmtime", "machine": "wasm32", "python": "n/a"},
            "benchmarks": {
                "ok.py": {
                    "molt_wasm_ok": True,
                    "molt_wasm_time_s": 2.00,
                    "molt_wasm_size_kb": 321.0,
                },
                "failed.py": {
                    "molt_wasm_ok": False,
                    "molt_wasm_time_s": 0.00,
                    "molt_wasm_size_kb": 111.0,
                },
            },
        },
    )

    assert (
        module.main(
            [
                "--native",
                str(native_path),
                "--wasm",
                str(wasm_path),
                "--out",
                str(out_path),
            ]
        )
        == 0
    )

    report = out_path.read_text(encoding="utf-8")
    assert "Median wasm speedup vs CPython: 0.50x." in report
    assert "| failed | yes | 1.000000" in report
    assert "| failed | yes | 1.000000" in report and "| no | - | - | -" in report
    assert "failed.py 0.00x" not in module._status_summary(
        module._load_json(native_path),
        module._load_json(wasm_path),
        module._collect_benchmarks(
            module._load_json(native_path), module._load_json(wasm_path)
        )[1],
        module._collect_benchmarks(
            module._load_json(native_path), module._load_json(wasm_path)
        )[2],
    )


def test_wasm_time_filter_rejects_invalid_numeric_values() -> None:
    module = _load_module()

    for value in (True, False, 0.0, -1.0, math.nan, math.inf, -math.inf):
        assert module._valid_positive_time(value) is None

    assert module._valid_positive_time(1.25) == 1.25


def test_failed_native_stale_values_do_not_feed_report_ratios(tmp_path: Path) -> None:
    module = _load_module()
    module.ROOT = tmp_path
    native_path = tmp_path / "native.json"
    wasm_path = tmp_path / "wasm.json"
    native = {
        "benchmarks": {
            "failed.py": {
                "molt_ok": False,
                "molt_time_s": 0.01,
                "cpython_time_s": 1.0,
                "molt_speedup": 100.0,
                "pypy_ok": False,
                "pypy_time_s": 0.01,
            }
        }
    }
    wasm = {"benchmarks": {}}

    report = module._render_report_markdown(native_path, wasm_path, native, wasm)

    assert "Median native speedup vs CPython: -." in report
    assert "| failed | no | 1.000000 | - |" in report
    assert "| - | - | - | no |" in report
    assert "100.00x" not in report


def test_failed_comparator_stale_values_do_not_feed_ratio_tables(
    tmp_path: Path,
) -> None:
    module = _load_module()
    module.ROOT = tmp_path
    native_path = tmp_path / "native.json"
    wasm_path = tmp_path / "wasm.json"
    native = {
        "benchmarks": {
            "bench.py": {
                "molt_ok": True,
                "molt_time_s": 0.5,
                "cpython_time_s": 1.0,
                "molt_speedup": 2.0,
                "codon_ok": False,
                "codon_time_s": 0.01,
            }
        }
    }
    wasm = {"benchmarks": {}}

    report = module._render_report_markdown(native_path, wasm_path, native, wasm)

    assert "## Molt vs Codon" in report
    codon_section = report.split("## Molt vs Codon", maxsplit=1)[1].split(
        "## Molt vs Nuitka", maxsplit=1
    )[0]
    assert "| - | - | - | - |" in codon_section
    assert "0.010000" not in codon_section
