entry_list! {
    (0, molt_type_call, "type_call", 1)
    (1, molt_type_new, "type_new", 5)
    (2, molt_type_init, "type_init", 5)
    (3, molt_object_new_bound, "object_new_bound", 1)
    (4, molt_object_init, "object_init", 1)
    (5, molt_object_init_subclass, "object_init_subclass", 1)
    (6, molt_exception_new_bound, "exception_new_bound", 2)
    (7, molt_exception_init, "exception_init", 2)
    (8, molt_exceptiongroup_init, "exceptiongroup_init", 2)
}
