"""Intrinsic-first stdlib package stub for `msilib`.

Generated by tools/gen_stdlib_stubs.py; lowering the package replaces this file.
"""

from _intrinsics import require_intrinsic as _require_intrinsic

_require_intrinsic("molt_capabilities_has")


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `msilib` package stub with full intrinsic-backed lowering.
def __getattr__(attr: str):
    if attr in {
        "schema",
        "sequence",
        "text",
    }:
        raise AttributeError(f"module {__name__!r} has no attribute {attr!r}", name=attr)
    raise RuntimeError(
        'stdlib package "msilib" is not fully lowered yet; only an intrinsic-first stub is available.'
    )


globals().pop("_require_intrinsic", None)
