"""Intrinsic-first stdlib module stub for `zoneinfo._common`.

Generated by tools/gen_stdlib_stubs.py; lowering the module replaces this file.
"""


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `zoneinfo._common` module stub with a full lowering.
def __getattr__(attr: str):
    raise RuntimeError(
        'stdlib module "zoneinfo._common" is not fully lowered yet; only an intrinsic-first stub is available.'
    )
