pub(crate) mod abc;
pub(crate) mod annotations;
pub(crate) mod array_mod;
#[cfg(feature = "stdlib_ast")]
pub(crate) mod ast;
pub(crate) mod asyncio_core;
pub(crate) mod asyncio_helpers;
pub(crate) mod asyncio_queue;
pub(crate) mod atexit;
pub(crate) mod attr;
pub(crate) mod attributes;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod bz2;
pub(crate) mod callable;
pub(crate) mod classes;
pub(crate) mod codecs;
pub(crate) mod codecs_ext;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod compression_bridge;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod compression_common;
pub(crate) mod concurrent;
pub(crate) mod containers;
pub(crate) mod containers_alloc;
pub(crate) mod context;
pub(crate) mod contextlib;
pub(crate) mod contextvars;
pub(crate) mod copy_mod;
pub(crate) mod dbm_dumb;
#[cfg(not(feature = "stdlib_difflib"))]
pub(crate) mod difflib;
pub(crate) mod enum_ext;
pub(crate) mod exceptions;
pub(crate) mod fcntl;
pub(crate) mod fnmatch;
pub(crate) mod frames;
pub(crate) mod functions;
pub(crate) mod functions_fnmatch;
#[cfg(not(feature = "stdlib_http"))]
pub(crate) mod functions_logging;
pub(crate) mod functions_pickle;
pub(crate) mod functions_re;
pub(crate) mod functions_stat;
pub(crate) mod functions_textwrap;
pub(crate) mod functools;
pub(crate) mod gpu;
pub(crate) mod gpu_backend;
#[cfg(feature = "molt_gpu_primitives")]
pub(crate) mod gpu_primitives;
pub(crate) mod graphlib;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod gzip;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod hashlib;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod hmac;
pub(crate) mod inspect;
pub(crate) mod io;
pub(crate) mod io_path;
pub(crate) mod io_path_utils;
#[cfg(not(feature = "stdlib_ipaddress"))]
pub(crate) mod ipaddress;
#[cfg(not(feature = "stdlib_itertools"))]
pub(crate) mod itertools;
pub(crate) mod json;
#[cfg(all(feature = "stdlib_compression", not(target_arch = "wasm32")))]
pub(crate) mod lzma;
#[cfg(all(feature = "stdlib_compression", target_arch = "wasm32"))]
#[path = "lzma_wasm.rs"]
pub(crate) mod lzma;
pub(crate) mod methods;
mod micro_stubs;
pub(crate) mod modules;
pub(crate) mod numbers;
pub(crate) mod operator;
#[cfg(not(feature = "stdlib_path"))]
pub(crate) mod os_ext;
#[cfg(not(feature = "stdlib_path"))]
pub(crate) mod pathlib;
pub(crate) mod platform;
pub(crate) mod platform_mod;
pub(crate) mod pprint_ext;
pub(crate) mod punycode;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod secrets;
pub(crate) mod select;
pub(crate) mod shutil;
pub(crate) mod signal_ext;
pub(crate) mod sitebuiltins;
#[cfg(feature = "sqlite")]
pub(crate) mod sqlite3;
pub(crate) mod ssl;
pub(crate) mod string_ext;
pub(crate) mod strings;
pub(crate) mod subprocess_ext;
pub(crate) mod sys_ext;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod tarfile;
#[cfg(feature = "stdlib_fs_extra")]
pub(crate) mod tempfile_mod;
pub(crate) mod threading_helpers;
#[cfg(feature = "stdlib_tk")]
pub(crate) mod tkinter_core;
pub(crate) mod type_ops;
pub(crate) mod types;
pub(crate) mod warnings_ext;
#[cfg(not(feature = "stdlib_xml"))]
pub(crate) mod xml_etree;
#[cfg(not(feature = "stdlib_xml"))]
pub(crate) mod xml_sax;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod zlib;
