pub(crate) mod abc;
pub(crate) mod annotations;
pub(crate) mod argparse;
pub(crate) mod array_mod;
#[cfg(feature = "stdlib_ast")]
pub(crate) mod ast;
pub(crate) mod asyncio_core;
pub(crate) mod asyncio_helpers;
pub(crate) mod asyncio_queue;
pub(crate) mod atexit;
pub(crate) mod attr;
pub(crate) mod attributes;
pub(crate) mod base64_mod;
pub(crate) mod binascii;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod bz2;
pub(crate) mod callable;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod compression_bridge;
pub(crate) mod classes;
pub(crate) mod cmath_mod;
pub(crate) mod codecs;
pub(crate) mod codecs_ext;
pub(crate) mod collections_ext;
pub(crate) mod colorsys;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod compression_common;
pub(crate) mod concurrent;
pub(crate) mod configparser;
pub(crate) mod containers;
pub(crate) mod containers_alloc;
pub(crate) mod context;
pub(crate) mod contextlib;
pub(crate) mod contextvars;
pub(crate) mod copy_mod;
pub(crate) mod csv;
pub(crate) mod datetime;
pub(crate) mod dbm_dumb;
pub(crate) mod decimal;
pub(crate) mod difflib;
pub(crate) mod enum_ext;
pub(crate) mod exceptions;
pub(crate) mod fcntl;
pub(crate) mod fnmatch;
#[cfg(not(feature = "stdlib_math"))]
pub(crate) mod fractions;
pub(crate) mod frames;
pub(crate) mod functions;
pub(crate) mod functools;
#[cfg(feature = "stdlib_fs_extra")]
pub(crate) mod glob_mod;
pub(crate) mod graphlib;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod gzip;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod hashlib;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod hmac;
pub(crate) mod html;
pub(crate) mod inspect;
pub(crate) mod io;
pub(crate) mod ipaddress;
pub(crate) mod itertools;
pub(crate) mod json;
pub(crate) mod logging_ext;
mod micro_stubs;
#[cfg(all(feature = "stdlib_compression", not(target_arch = "wasm32")))]
pub(crate) mod lzma;
#[cfg(all(feature = "stdlib_compression", target_arch = "wasm32"))]
#[path = "lzma_wasm.rs"]
pub(crate) mod lzma;
pub(crate) mod math;
pub(crate) mod methods;
pub(crate) mod modules;
pub(crate) mod numbers;
pub(crate) mod operator;
pub(crate) mod os_ext;
pub(crate) mod pathlib;
pub(crate) mod platform;
pub(crate) mod platform_mod;
pub(crate) mod pprint_ext;
pub(crate) mod punycode;
pub(crate) mod random_mod;
pub(crate) mod regex;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod secrets;
pub(crate) mod select;
pub(crate) mod shutil;
pub(crate) mod signal_ext;
pub(crate) mod sitebuiltins;
#[cfg(feature = "stdlib_net")]
pub(crate) mod ssl;
pub(crate) mod string_ext;
pub(crate) mod stringprep;
pub(crate) mod strings;
pub(crate) mod structs;
pub(crate) mod subprocess_ext;
pub(crate) mod sys_ext;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod tarfile;
#[cfg(feature = "stdlib_fs_extra")]
pub(crate) mod tempfile_mod;
pub(crate) mod threading_helpers;
#[cfg(feature = "stdlib_tk")]
pub(crate) mod tkinter_core;
pub(crate) mod type_ops;
pub(crate) mod types;
pub(crate) mod unicodedata_mod;
pub(crate) mod warnings_ext;
pub(crate) mod xml_etree;
pub(crate) mod xml_sax;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod zlib;
pub(crate) mod zoneinfo;
