pub(crate) mod abc;
pub(crate) mod annotations;
#[cfg(not(feature = "stdlib_collections"))]
pub(crate) mod argparse;
pub(crate) mod array_mod;
#[cfg(feature = "stdlib_ast")]
pub(crate) mod ast;
pub(crate) mod asyncio_core;
pub(crate) mod asyncio_helpers;
pub(crate) mod asyncio_queue;
pub(crate) mod atexit;
pub(crate) mod attr;
pub(crate) mod attributes;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod base64_mod;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod binascii;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod bz2;
pub(crate) mod callable;
pub(crate) mod classes;
#[cfg(not(feature = "stdlib_math"))]
pub(crate) mod cmath_mod;
pub(crate) mod codecs;
pub(crate) mod codecs_ext;
#[cfg(not(feature = "stdlib_collections"))]
pub(crate) mod collections_ext;
#[cfg(not(feature = "stdlib_math"))]
pub(crate) mod colorsys;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod compression_bridge;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod compression_common;
pub(crate) mod concurrent;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod configparser;
pub(crate) mod containers;
pub(crate) mod containers_alloc;
pub(crate) mod context;
pub(crate) mod contextlib;
pub(crate) mod contextvars;
pub(crate) mod copy_mod;
#[cfg(not(feature = "stdlib_csv"))]
pub(crate) mod csv;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod datetime;
pub(crate) mod dbm_dumb;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod decimal;
#[cfg(not(feature = "stdlib_difflib"))]
pub(crate) mod difflib;
pub(crate) mod enum_ext;
pub(crate) mod exceptions;
pub(crate) mod fcntl;
pub(crate) mod fnmatch;
#[cfg(not(feature = "stdlib_math"))]
pub(crate) mod fractions;
pub(crate) mod frames;
pub(crate) mod functions;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod functions_email;
#[cfg(not(feature = "stdlib_http"))]
pub(crate) mod functions_http;
#[cfg(not(feature = "stdlib_http"))]
pub(crate) mod functions_logging;
pub(crate) mod functions_pickle;
pub(crate) mod functions_stat;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod functions_zipfile;
pub(crate) mod functools;
#[cfg(feature = "stdlib_fs_extra")]
pub(crate) mod glob_mod;
pub(crate) mod graphlib;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod gzip;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod hashlib;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod hmac;
#[cfg(not(feature = "stdlib_text"))]
pub(crate) mod html;
pub(crate) mod inspect;
pub(crate) mod io;
pub(crate) mod io_path;
pub(crate) mod io_path_utils;
#[cfg(not(feature = "stdlib_ipaddress"))]
pub(crate) mod ipaddress;
#[cfg(not(feature = "stdlib_itertools"))]
pub(crate) mod itertools;
pub(crate) mod json;
#[cfg(not(feature = "stdlib_logging_ext"))]
pub(crate) mod logging_ext;
#[cfg(all(feature = "stdlib_compression", not(target_arch = "wasm32")))]
pub(crate) mod lzma;
#[cfg(all(feature = "stdlib_compression", target_arch = "wasm32"))]
#[path = "lzma_wasm.rs"]
pub(crate) mod lzma;
#[cfg(not(feature = "stdlib_math"))]
pub(crate) mod math;
pub(crate) mod methods;
mod micro_stubs;
pub(crate) mod modules;
pub(crate) mod numbers;
pub(crate) mod operator;
#[cfg(not(feature = "stdlib_path"))]
pub(crate) mod os_ext;
#[cfg(not(feature = "stdlib_path"))]
pub(crate) mod pathlib;
pub(crate) mod platform;
pub(crate) mod platform_mod;
pub(crate) mod pprint_ext;
pub(crate) mod punycode;
#[cfg(not(feature = "stdlib_math"))]
pub(crate) mod random_mod;
#[cfg(not(feature = "stdlib_regex"))]
pub(crate) mod regex;
#[cfg(feature = "stdlib_crypto")]
pub(crate) mod secrets;
pub(crate) mod select;
pub(crate) mod shutil;
pub(crate) mod signal_ext;
pub(crate) mod sitebuiltins;
#[cfg(feature = "stdlib_net")]
pub(crate) mod ssl;
pub(crate) mod string_ext;
#[cfg(not(feature = "stdlib_stringprep"))]
pub(crate) mod stringprep;
pub(crate) mod strings;
#[cfg(not(feature = "stdlib_serial"))]
pub(crate) mod structs;
pub(crate) mod subprocess_ext;
pub(crate) mod sys_ext;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod tarfile;
#[cfg(feature = "stdlib_fs_extra")]
pub(crate) mod tempfile_mod;
pub(crate) mod threading_helpers;
#[cfg(feature = "stdlib_tk")]
pub(crate) mod tkinter_core;
pub(crate) mod type_ops;
pub(crate) mod types;
#[cfg(not(feature = "stdlib_text"))]
pub(crate) mod unicodedata_mod;
pub(crate) mod warnings_ext;
#[cfg(not(feature = "stdlib_xml"))]
pub(crate) mod xml_etree;
#[cfg(not(feature = "stdlib_xml"))]
pub(crate) mod xml_sax;
#[cfg(feature = "stdlib_compression")]
pub(crate) mod zlib;
#[cfg(not(feature = "stdlib_zoneinfo"))]
pub(crate) mod zoneinfo;
