print(len(b"hello"))
print(b"hello"[1:4])
print(b"hi" + b"!")
print(b"hello".find(b"ll"))
print(b"hello".find(b"zz"))
print(b"one,two".split(b","))
print(len(b"one,two".split(b",")))
print(len(b"one,two".split(b",")[0]))
print(b"one,two".replace(b"one", b"uno"))
ba = bytearray(b"one,two")
print(ba.find(b"two"))
print(len(ba.split(b",")))
print(len(ba.split(b",")[1]))
print(ba.replace(b"two", b"dos"))
