"""Purpose: differential coverage for bytes basics."""

print(len(b"hello"))
print(b"hello"[1:4])
print(b"hi" + b"!")
print(b"hello".find(b"ll"))
print(b"hello".find(b"zz"))
print(b"one,two".split(b","))
print(len(b"one,two".split(b",")))
print(len(b"one,two".split(b",")[0]))
print(b"one,two".replace(b"one", b"uno"))
ba = bytearray(b"one,two")
print(ba.find(b"two"))
print(len(ba.split(b",")))
print(len(ba.split(b",")[1]))
print(ba.replace(b"two", b"dos"))
print(b"a\nb".splitlines())
print(b"a\nb\n".splitlines())
print(b"a\n\n".splitlines())
print(b"a\n\n".splitlines(True))
print(b"\n".splitlines())
print(b"".splitlines())
print(b"a\r\nb\r\n".splitlines())
print(b"a\r\nb\r\n".splitlines(True))
print(b"a\x85b".splitlines())
print(b"a\x0b\x0c".splitlines())
print(bytearray(b"a\nb").splitlines())
print(bytearray(b"a\n\n").splitlines(True))
print(bytearray(b"a\r\nb\r\n").splitlines())
print(b"hello".partition(b"ll"))
print(b"hello".partition(b"z"))
print(b"hello".rpartition(b"ll"))
print(b"hello".rpartition(b"z"))
print(bytearray(b"hello").partition(b"ll"))
print(bytearray(b"hello").rpartition(b"ll"))
