def show(label, value):
    print(label, value)


def show_err(label, func):
    try:
        func()
    except Exception as exc:
        print(label, type(exc).__name__, exc)


s = "  hello  world  there  "
show("find0", s.find("world"))
show("find1", s.find("world", 2))
show("find2", s.find("world", 2, 7))
show("find3", s.find("", 5, 7))
show("find4", s.find("x", 2, 7))
show("find5", s.find("hello", None, None))
show("find6", s.find("world", -10))
show("find7", s.find("world", -10, -1))
show("count0", s.count("l"))
show("count1", s.count("l", 3, None))
show("count2", s.count("", 2, 5))
show("count3", s.count("l", -8, -1))
show("starts0", s.startswith("hello"))
show("starts1", s.startswith(("x", "he"), 2))
show("starts2", s.startswith(("x", "he"), 2, 6))
show("starts3", s.startswith((), 2))
show("starts4", s.startswith("world", -10))
show("ends0", s.endswith("there"))
show("ends1", s.endswith(("x", "re"), None, None))
show("ends2", s.endswith("there", -5))
show("split0", s.split())
show("split1", s.split(None, 1))
show("split2", "a  b  c".split(None, 1))
show("split3", "a  b  c".split(None, 0))
show("split4", "a,b,c".split(",", 1))
show("split5", "a,b,c".split(",", -1))
show("split6", "a".split(",", 0))
show("split7", "".split())
show("split8", "".split(None, 1))
show("split9", "  ".split(None, 1))
show("split10", "abc".split(":", 1))
show("replace0", "ababab".replace("ab", "X", 2))
show("replace1", "abc".replace("", "-", 2))
show("replace2", "abc".replace("", "-"))
show("replace3", "xyx".replace("x", "z", 0))
show("strip0", "  hello  ".strip())
show("strip1", "  hello  ".strip(None))
show("strip2", "--hello--".strip("-"))
show("strip3", "--hello--".strip("--"))
show("strip4", "  hello  ".strip(" h"))
show("strip5", "hello".strip(""))
show("join0", ",".join(["a", "b", "c"]))
show("join1", ",".join(x for x in ["a", "b"]))
show("join2", ",".join([]))
show_err("err_join", lambda: ",".join(["a", 1]))
show_err("err_starts", lambda: "abc".startswith(("a", 1)))
show_err("err_count", lambda: "abc".count("a", "1"))
show_err("err_find", lambda: "abc".find(1))
show_err("err_split", lambda: "abc".split(""))
