#!/usr/bin/env python3
"""Emit a drop-in NOT-IMPLEMENTED scaffold for a new pact witness kernel.

Per the per-kernel file-set contract in
`collab/pact/011_molt_reply_progress_sync_and_harness_proposal_20260710.md`
section 2a, Kernels B..7 land as `<k>.py` + `make_<k>_fixture.py` +
`<k>_reference.npz` (regenerable, not tracked) + `<k>_gates.json`. This tool
emits the first three as loud, never-fake scaffolds so a new kernel directory
exists and is wired into the shared `collab/pact/parity/check_parity.py`
engine's vocabulary the moment pact delivers real source — with ZERO chance
of an accidental pass in the meantime.

Two independent, redundant guards make a scaffold un-passable:

  1. (primary, structural) `<k>_gates.json` carries
     `"status": "AWAITING_PACT_KERNEL_SOURCE"`, which
     `collab/pact/parity/check_parity.py::validate_gates` refuses outright
     (`GateSpecError`, exit code 2) before a single array is compared — this
     holds regardless of what the rest of the manifest says.
  2. (defense-in-depth) `<k>.py`'s entry function and `make_<k>_fixture.py`'s
     `main()` both raise `NotImplementedError` unconditionally, so even a
     direct call bypassing the gate manifest cannot produce a result, fake or
     otherwise.

This module deliberately imports no third-party package (no numpy/scipy): it
only ever writes template text and JSON, so it runs in any environment,
including the plain host interpreter used to run this repo's test suite.

Usage:
    python make_kernel_scaffold.py <kernel_name> [--out-dir DIR] [--force]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

KERNEL_ROOT = Path(__file__).resolve().parents[1] / "pact_witness_kernel"

# Must equal collab.pact.parity.check_parity.SCAFFOLD_STATUS. Duplicated as a
# literal (not imported) so this module stays numpy-free; the identity is
# pinned by test_pact_kernel_scaffold.py::test_scaffold_status_matches_engine_constant.
SCAFFOLD_STATUS = "AWAITING_PACT_KERNEL_SOURCE"

# Marks a file as machine-generated by this tool (vs. a real delivered kernel
# source) so re-running the scaffolder never silently clobbers real work.
SCAFFOLD_MARKER = "molt-scaffold:make_kernel_scaffold.py"

_KERNEL_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

_PROPOSAL_REF = (
    "collab/pact/011_molt_reply_progress_sync_and_harness_proposal_20260710.md "
    "section 2a"
)


class ScaffoldNameError(ValueError):
    """The requested kernel name is not a safe/valid identifier."""


def _validate_kernel_name(kernel: str) -> None:
    if not _KERNEL_NAME_RE.match(kernel):
        raise ScaffoldNameError(
            f"kernel name {kernel!r} must match {_KERNEL_NAME_RE.pattern!r} "
            "(lowercase identifier — it becomes the entry-function name and "
            "the <k>.py / make_<k>_fixture.py / <k>_gates.json filenames; no "
            "path separators, no uppercase, no leading digit)"
        )


def _not_implemented_message(kernel: str) -> str:
    return (
        f"NOT IMPLEMENTED — awaiting pact kernel source for kernel {kernel!r}. "
        f"This file is a scaffold emitted by make_kernel_scaffold.py; it must be "
        f"replaced with the real pure numpy/scipy extract (a bit-for-bit tac "
        f"extract, verified by verify_against_tac.py) before this kernel can be "
        f"evaluated. See {_PROPOSAL_REF}."
    )


def _kernel_scaffold_source(kernel: str) -> str:
    msg = _not_implemented_message(kernel)
    return f'''# {SCAFFOLD_MARKER}
"""pact witness kernel `{kernel}` — SCAFFOLD, not yet implemented.

Generated by `collab/pact/parity/make_kernel_scaffold.py`. This is a drop-in
placeholder for kernel `{kernel}` per {_PROPOSAL_REF}: deliver the real
`{kernel}(inputs...) -> dict[str, np.ndarray]` pure numpy/scipy extract here,
keeping this entry-function name and signature so the acceptance lane and
`verify_against_tac.py` wire it in with ZERO Molt code changes.

{msg}

This module never returns a fake/placeholder result — calling `{kernel}(...)`
always raises. The load-bearing guard against an accidental PASS is
`{kernel}_gates.json`'s `"status": "{SCAFFOLD_STATUS}"`, which
`collab/pact/parity/check_parity.py` refuses structurally (exit code 2)
before comparing a single array; this raise is defense-in-depth for a direct
call that bypasses the gate manifest entirely.
"""

from __future__ import annotations

from typing import Any

_NOT_IMPLEMENTED = {msg!r}


def {kernel}(*args: Any, **kwargs: Any) -> dict[str, Any]:
    """SCAFFOLD entry point for kernel `{kernel}` — always raises; see module docstring."""
    raise NotImplementedError(_NOT_IMPLEMENTED)


if __name__ == "__main__":
    raise SystemExit(_NOT_IMPLEMENTED)
'''


def _fixture_scaffold_source(kernel: str) -> str:
    msg = _not_implemented_message(kernel)
    return f'''# {SCAFFOLD_MARKER}
"""deterministic fixture generator for kernel `{kernel}` — SCAFFOLD, not yet implemented.

Generated by `collab/pact/parity/make_kernel_scaffold.py`. Once `{kernel}.py`
is real, replace `main()` below with a deterministic (no RNG/time/I-O),
byte-reproducible fixture generator that writes `{kernel}_fixture.npz` and
documents the shape/dtype of each input key, mirroring
`pact_witness_kernel/make_fixture.py` (Kernel A).

{msg}
"""

from __future__ import annotations

import sys

_NOT_IMPLEMENTED = {msg!r}


def main() -> int:
    raise NotImplementedError(_NOT_IMPLEMENTED)


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _gates_scaffold_json(kernel: str) -> str:
    description = (
        f"SCAFFOLD for kernel '{kernel}' emitted by make_kernel_scaffold.py. "
        f"NOT IMPLEMENTED — awaiting pact kernel source ({_PROPOSAL_REF}). "
        "check_parity.py's structural refusal (GateSpecError) on "
        f"status=='{SCAFFOLD_STATUS}' is the load-bearing guard: this exact "
        "manifest can NEVER produce a PASS, no matter what 'outputs' holds. "
        "Once pact delivers the kernel source, replace 'outputs' with the real "
        "per-array gate declarations (see field_solve_gates.json for the "
        "reference shape) and flip status to \"ready\"."
    )
    manifest = {
        "schema_version": 1,
        "kernel": kernel,
        "status": SCAFFOLD_STATUS,
        "_scaffold_marker": SCAFFOLD_MARKER,
        "description": description,
        "atol_ceiling": 0.001,
        "provenance": "SCAFFOLD — no reference has been generated yet.",
        "outputs": {},
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def _is_generated_scaffold(path: Path) -> bool:
    """True if `path` was itself written by this tool (safe to regenerate)."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    if path.suffix == ".json":
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            return False
        return isinstance(data, dict) and data.get("_scaffold_marker") == SCAFFOLD_MARKER
    return text.startswith(f"# {SCAFFOLD_MARKER}\n")


def make_kernel_scaffold(
    kernel: str,
    out_dir: Path | str = KERNEL_ROOT,
    *,
    force: bool = False,
) -> dict[str, Path]:
    """Write `<k>.py` / `make_<k>_fixture.py` / `<k>_gates.json` scaffolds.

    Returns ``{"kernel": path, "fixture": path, "gates": path}``.

    Refuses (``FileExistsError``) to overwrite any target that exists and is
    NOT itself a previously-generated scaffold, unless ``force=True`` — a real
    delivered kernel source can never be silently reset back to a stub.
    """
    _validate_kernel_name(kernel)
    out_dir = Path(out_dir)

    targets = {
        "kernel": out_dir / f"{kernel}.py",
        "fixture": out_dir / f"make_{kernel}_fixture.py",
        "gates": out_dir / f"{kernel}_gates.json",
    }
    contents = {
        "kernel": _kernel_scaffold_source(kernel),
        "fixture": _fixture_scaffold_source(kernel),
        "gates": _gates_scaffold_json(kernel),
    }

    if not force:
        for key, path in targets.items():
            if path.is_file() and not _is_generated_scaffold(path):
                raise FileExistsError(
                    f"refusing to overwrite non-scaffold file {path} (it does "
                    "not carry the make_kernel_scaffold.py marker, so it looks "
                    "like a real delivered kernel file, not a stub); pass "
                    "force=True to override"
                )

    out_dir.mkdir(parents=True, exist_ok=True)
    for key, path in targets.items():
        path.write_text(contents[key], encoding="utf-8")
    return targets


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Emit a NOT-IMPLEMENTED scaffold for a new pact witness kernel "
            "(<k>.py / make_<k>_fixture.py / <k>_gates.json) per "
            f"{_PROPOSAL_REF}."
        )
    )
    parser.add_argument(
        "kernel", help="kernel name, e.g. 'kernel_c' (lowercase identifier)"
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=KERNEL_ROOT,
        help="directory to write into (default: collab/pact/pact_witness_kernel)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing non-scaffold files (DANGEROUS: only for explicit resets)",
    )
    args = parser.parse_args(argv)

    try:
        written = make_kernel_scaffold(args.kernel, args.out_dir, force=args.force)
    except (ScaffoldNameError, FileExistsError) as exc:
        print(f"refused: {exc}", file=sys.stderr)
        return 2

    for key, path in written.items():
        print(f"wrote {key}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
