// @generated by tools/gen_wasm_abi.py from
// runtime/molt-backend-wasm/src/wasm_abi_manifest.toml
// runtime/molt-runtime/src/intrinsics/manifest.pyi
// DO NOT EDIT BY HAND.

pub(crate) const CALLABLE_TABLE_LAYOUT_SECTION_NAME: &str = "molt.callable_table.layout";
pub(crate) const CALLABLE_TABLE_LAYOUT_VERSION: u32 = 1;
