// @generated by tools/gen_wasm_abi.py from
// runtime/molt-backend-wasm/src/wasm_abi_manifest.toml
// runtime/molt-runtime/src/intrinsics/manifest.pyi
// DO NOT EDIT BY HAND.

use super::import_tokens::WasmRuntimeImport;
use super::lir_runtime_calls::LirRuntimeCall;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum WasmContainerRuntimeOp {
    Contains,
    Index,
    Len,
    StoreIndex,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum WasmContainerRuntimeFact {
    Dict,
    FlatListInt,
    List,
    Set,
    Str,
    Tuple,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct WasmContainerRuntimeSelection {
    pub(crate) import: WasmRuntimeImport,
    pub(crate) lir_runtime_call: Option<LirRuntimeCall>,
}

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct WasmContainerRuntimeSelectorSpec {
    pub(crate) op: WasmContainerRuntimeOp,
    pub(crate) fact: WasmContainerRuntimeFact,
    pub(crate) selection: WasmContainerRuntimeSelection,
}

#[allow(dead_code)]
pub(crate) const WASM_CONTAINER_RUNTIME_SELECTORS: &[WasmContainerRuntimeSelectorSpec] = &[
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Index,
        fact: WasmContainerRuntimeFact::FlatListInt,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::ListIntGetitem,
            lir_runtime_call: Some(LirRuntimeCall::ListIntGetitem),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::StoreIndex,
        fact: WasmContainerRuntimeFact::FlatListInt,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::ListIntSetitem,
            lir_runtime_call: Some(LirRuntimeCall::ListIntSetitem),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Index,
        fact: WasmContainerRuntimeFact::Dict,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::DictGetitem,
            lir_runtime_call: Some(LirRuntimeCall::DictGetitem),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Index,
        fact: WasmContainerRuntimeFact::Tuple,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::TupleGetitem,
            lir_runtime_call: Some(LirRuntimeCall::TupleGetitem),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::StoreIndex,
        fact: WasmContainerRuntimeFact::Dict,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::DictSetitem,
            lir_runtime_call: Some(LirRuntimeCall::DictSetitem),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Contains,
        fact: WasmContainerRuntimeFact::Set,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::SetContains,
            lir_runtime_call: Some(LirRuntimeCall::SetContains),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Contains,
        fact: WasmContainerRuntimeFact::Dict,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::DictContains,
            lir_runtime_call: Some(LirRuntimeCall::DictContains),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Contains,
        fact: WasmContainerRuntimeFact::List,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::ListContains,
            lir_runtime_call: Some(LirRuntimeCall::ListContains),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Contains,
        fact: WasmContainerRuntimeFact::Str,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::StrContains,
            lir_runtime_call: Some(LirRuntimeCall::StrContains),
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Len,
        fact: WasmContainerRuntimeFact::List,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::LenList,
            lir_runtime_call: None,
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Len,
        fact: WasmContainerRuntimeFact::Str,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::LenStr,
            lir_runtime_call: None,
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Len,
        fact: WasmContainerRuntimeFact::Dict,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::LenDict,
            lir_runtime_call: None,
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Len,
        fact: WasmContainerRuntimeFact::Tuple,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::LenTuple,
            lir_runtime_call: None,
        },
    },
    WasmContainerRuntimeSelectorSpec {
        op: WasmContainerRuntimeOp::Len,
        fact: WasmContainerRuntimeFact::Set,
        selection: WasmContainerRuntimeSelection {
            import: WasmRuntimeImport::LenSet,
            lir_runtime_call: None,
        },
    },
];

#[inline]
pub(crate) fn wasm_container_runtime_op(kind: &str) -> Option<WasmContainerRuntimeOp> {
    match kind {
        "contains" => Some(WasmContainerRuntimeOp::Contains),
        "index" => Some(WasmContainerRuntimeOp::Index),
        "len" => Some(WasmContainerRuntimeOp::Len),
        "store_index" => Some(WasmContainerRuntimeOp::StoreIndex),
        _ => None,
    }
}

#[inline]
pub(crate) fn wasm_container_runtime_selection(
    op: WasmContainerRuntimeOp,
    fact: WasmContainerRuntimeFact,
) -> Option<WasmContainerRuntimeSelection> {
    match (op, fact) {
        (WasmContainerRuntimeOp::Index, WasmContainerRuntimeFact::FlatListInt) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::ListIntGetitem,
                lir_runtime_call: Some(LirRuntimeCall::ListIntGetitem),
            })
        }
        (WasmContainerRuntimeOp::StoreIndex, WasmContainerRuntimeFact::FlatListInt) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::ListIntSetitem,
                lir_runtime_call: Some(LirRuntimeCall::ListIntSetitem),
            })
        }
        (WasmContainerRuntimeOp::Index, WasmContainerRuntimeFact::Dict) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::DictGetitem,
                lir_runtime_call: Some(LirRuntimeCall::DictGetitem),
            })
        }
        (WasmContainerRuntimeOp::Index, WasmContainerRuntimeFact::Tuple) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::TupleGetitem,
                lir_runtime_call: Some(LirRuntimeCall::TupleGetitem),
            })
        }
        (WasmContainerRuntimeOp::StoreIndex, WasmContainerRuntimeFact::Dict) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::DictSetitem,
                lir_runtime_call: Some(LirRuntimeCall::DictSetitem),
            })
        }
        (WasmContainerRuntimeOp::Contains, WasmContainerRuntimeFact::Set) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::SetContains,
                lir_runtime_call: Some(LirRuntimeCall::SetContains),
            })
        }
        (WasmContainerRuntimeOp::Contains, WasmContainerRuntimeFact::Dict) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::DictContains,
                lir_runtime_call: Some(LirRuntimeCall::DictContains),
            })
        }
        (WasmContainerRuntimeOp::Contains, WasmContainerRuntimeFact::List) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::ListContains,
                lir_runtime_call: Some(LirRuntimeCall::ListContains),
            })
        }
        (WasmContainerRuntimeOp::Contains, WasmContainerRuntimeFact::Str) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::StrContains,
                lir_runtime_call: Some(LirRuntimeCall::StrContains),
            })
        }
        (WasmContainerRuntimeOp::Len, WasmContainerRuntimeFact::List) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::LenList,
                lir_runtime_call: None,
            })
        }
        (WasmContainerRuntimeOp::Len, WasmContainerRuntimeFact::Str) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::LenStr,
                lir_runtime_call: None,
            })
        }
        (WasmContainerRuntimeOp::Len, WasmContainerRuntimeFact::Dict) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::LenDict,
                lir_runtime_call: None,
            })
        }
        (WasmContainerRuntimeOp::Len, WasmContainerRuntimeFact::Tuple) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::LenTuple,
                lir_runtime_call: None,
            })
        }
        (WasmContainerRuntimeOp::Len, WasmContainerRuntimeFact::Set) => {
            Some(WasmContainerRuntimeSelection {
                import: WasmRuntimeImport::LenSet,
                lir_runtime_call: None,
            })
        }
        _ => None,
    }
}
