// @generated by tools/gen_wasm_abi.py from
// runtime/molt-backend-wasm/src/wasm_abi_manifest.toml
// DO NOT EDIT BY HAND.

mod call_indirect;
mod const_policy;
mod imports;
mod lir_runtime_calls;
mod pure_profile;
mod runtime_callables;
mod runtime_surface;
mod static_types;

pub(crate) use call_indirect::{CALL_INDIRECT_IMPORTS, CALL_INDIRECT_MAX_ARITY};
pub(crate) use const_policy::{
    WasmConstInlineSeed, WasmConstLirFastPolicy, WasmConstLiteralPayload, WasmConstOpPolicySpec,
    WasmConstRawIntEffect, WasmConstScalarValue, wasm_const_op_policy,
};
pub(crate) use imports::{IMPORT_REGISTRY, OP_IMPORT_DEPS};
pub(crate) use lir_runtime_calls::{LirRuntimeCall, preserved_copy_runtime_call};
pub(crate) use pure_profile::pure_profile_skips_import;
pub(crate) use runtime_callables::{
    POLL_TABLE_IMPORTS, RESERVED_RUNTIME_CALLABLE_COUNT, RESERVED_RUNTIME_CALLABLE_SPECS,
    RUNTIME_CALLABLE_IMPORTS, RuntimeCallableResult,
};
pub(crate) use runtime_surface::runtime_surface_requires_direct_import;
pub(crate) use static_types::{STATIC_FUNC_TYPES, STATIC_TYPE_COUNT};
