use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[path = "../build_support/build_python.rs"]
mod build_python;
#[path = "../build_support/unicode_tables.rs"]
mod unicode_tables;
#[path = "../build_support/variadic_exports.rs"]
mod variadic_exports;
#[path = "../build_support/wasi_sysroot.rs"]
mod wasi_sysroot;

fn main() {
    // Native C fixtures use this image's Cargo identities, never an ambient
    // rustc host (which may differ during cross-target or emulated testing).
    for key in ["HOST", "TARGET"] {
        let value = env::var(key).unwrap_or_else(|_| panic!("Cargo {key} missing"));
        println!("cargo:rustc-env=MOLT_CARGO_{key}={value}");
    }
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let target_family = env::var("CARGO_CFG_TARGET_FAMILY").unwrap_or_default();
    emit_wasm_long_double_link_policy(&target_arch);
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    emit_c_api_version(&manifest_dir, &out_dir);
    let build_python = build_python::resolve();
    emit_cpython_abi_variadic_export_anchors(&manifest_dir, &out_dir);

    // The manifest owns only the dependency rlib. Final native/WASM producers
    // select their exact external crate types at Cargo level; Cargo's artifact
    // report, rather than a fixed-name target alias, owns publication identity.
    emit_cpython_abi_requested_export_anchors(&out_dir, &target_arch);

    // Emit `molt_has_net_io` only when the target has Molt's native socket ABI
    // implementation, not merely because the stdlib_net Cargo feature was
    // requested. WASM uses the host-call socket ABI under target_arch = "wasm32";
    // Windows stays on the explicit no-net intrinsic surface until the WinSock
    // constants, sockaddr storage, resolver, SSL fd ownership, and poller
    // contracts land as one coherent target implementation.
    println!("cargo:rustc-check-cfg=cfg(molt_has_net_io)");
    let native_net_target_supported =
        target_arch != "wasm32" && target_family.split(',').any(|family| family == "unix");
    if native_net_target_supported {
        // CARGO_FEATURE_<NAME> is set for every enabled Cargo feature.
        if env::var("CARGO_FEATURE_STDLIB_NET").is_ok() {
            println!("cargo:rustc-cfg=molt_has_net_io");
        }
    }

    unicode_tables::emit_runtime_unicode_tables(&out_dir, &build_python);
    println!("cargo:rerun-if-changed=../build_support/unicode_tables.rs");
    println!("cargo:rerun-if-changed=../build_support/wasi_sysroot.rs");
    println!("cargo:rerun-if-changed=../build_support/variadic_exports.rs");
    println!("cargo:rerun-if-changed=src/object/ops.rs");
    println!("cargo:rerun-if-changed=build.rs");
}

fn emit_cpython_abi_variadic_export_anchors(manifest_dir: &Path, out_dir: &Path) {
    let manifest = manifest_dir.join("../molt-cpython-abi/shims/pyarg_variadic.exports");
    let symbols = variadic_exports::load_variadic_exports(&manifest);
    let output = out_dir.join("molt_cpython_abi_variadic_exports.rs");
    fs::write(&output, variadic_exports::render_rust_anchors(&symbols))
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", output.display()));
    println!("cargo:rerun-if-changed={}", manifest.display());
}

fn emit_cpython_abi_requested_export_anchors(out_dir: &Path, target_arch: &str) {
    println!("cargo:rerun-if-env-changed=MOLT_WASM_CPYTHON_ABI_EXPORTS");
    println!("cargo:rerun-if-env-changed=MOLT_WASM_CPYTHON_ABI_DATA_EXPORTS");
    let output = out_dir.join("molt_cpython_abi_requested_exports.rs");
    let raw = env::var("MOLT_WASM_CPYTHON_ABI_EXPORTS").unwrap_or_default();
    let raw_data = env::var("MOLT_WASM_CPYTHON_ABI_DATA_EXPORTS").unwrap_or_default();
    let mut function_symbols = Vec::new();
    let mut data_symbols = Vec::new();
    if target_arch == "wasm32" {
        let requested_symbols = parse_cpython_abi_export_symbol_list(&raw);
        let requested_data_symbols = parse_cpython_abi_export_symbol_list(&raw_data);
        for symbol in &requested_data_symbols {
            if !requested_symbols.contains(symbol) {
                panic!(
                    "CPython ABI data export symbol {symbol} was not requested for WASM runtime"
                );
            }
        }
        for symbol in requested_symbols {
            if requested_data_symbols.contains(&symbol) {
                data_symbols.push(symbol.to_string());
            } else {
                function_symbols.push(symbol.to_string());
            }
        }
        function_symbols.sort();
        function_symbols.dedup();
        data_symbols.sort();
        data_symbols.dedup();
    }

    let mut source = String::new();
    source.push_str("// @generated by runtime/molt-runtime/build.rs\n");
    if !function_symbols.is_empty() || !data_symbols.is_empty() {
        source.push_str("unsafe extern \"C\" {\n");
        for symbol in &function_symbols {
            source.push_str(&format!("    fn {symbol}();\n"));
        }
        for symbol in &data_symbols {
            source.push_str(&format!("    static mut {symbol}: u8;\n"));
        }
        source.push_str("}\n\n");
    }
    source.push_str(&format!(
        "#[used]\nstatic MOLT_CPYTHON_ABI_REQUESTED_FUNCTION_EXPORT_ANCHORS: [unsafe extern \"C\" fn(); {}] = [\n",
        function_symbols.len()
    ));
    for symbol in &function_symbols {
        source.push_str(&format!("    {symbol},\n"));
    }
    source.push_str("];\n\n");
    source.push_str("pub(super) fn requested_export_anchor_count() -> usize {\n");
    source.push_str(
        "    core::hint::black_box(MOLT_CPYTHON_ABI_REQUESTED_FUNCTION_EXPORT_ANCHORS.as_ptr());\n",
    );
    if !data_symbols.is_empty() {
        source.push_str("    unsafe {\n");
        for symbol in &data_symbols {
            source.push_str(&format!(
                "        core::hint::black_box(&raw mut {symbol});\n"
            ));
        }
        source.push_str("    }\n");
    }
    source.push_str("    MOLT_CPYTHON_ABI_REQUESTED_FUNCTION_EXPORT_ANCHORS.len()");
    if !data_symbols.is_empty() {
        source.push_str(&format!(" + {}", data_symbols.len()));
    }
    source.push('\n');
    source.push_str("}\n");
    fs::write(output, source).expect("failed to write CPython ABI WASM export anchors");
}

fn parse_cpython_abi_export_symbol_list(raw: &str) -> Vec<String> {
    let mut symbols = Vec::new();
    for symbol in raw.split(|ch: char| ch == ',' || ch == ';' || ch.is_whitespace()) {
        let symbol = symbol.trim();
        if symbol.is_empty() {
            continue;
        }
        if !is_c_identifier(symbol) {
            panic!("invalid CPython ABI export symbol requested for WASM runtime: {symbol}");
        }
        symbols.push(symbol.to_string());
    }
    symbols.sort();
    symbols.dedup();
    symbols
}

fn is_c_identifier(symbol: &str) -> bool {
    let mut chars = symbol.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

/// Local native-library ordering puts the SDK formatter before SDK libc.
/// Unbundled lazy inputs avoid duplicating the formatter in the manual reloc
/// link. Raw library links use the selected libc and no executable startup CRT.
/// Emscripten owns a different C runtime and receives no WASI archive.
fn emit_wasm_long_double_link_policy(target_arch: &str) {
    if target_arch != "wasm32" {
        return;
    }
    let target_os = env::var("CARGO_CFG_TARGET_OS").expect("Cargo target OS");
    if target_os == "emscripten" {
        return;
    }
    if target_os != "wasi" && target_os != "unknown" {
        panic!("unsupported wasm C-runtime target OS: {target_os}");
    }
    let plan = wasi_sysroot::WasiCAbiPlan::from_environment();
    // SDK filenames already follow the target's lib<name>.a grammar.
    // Keep the original admitted bytes in place; no OUT_DIR copies or aliases.
    for (source, library) in [
        (plan.long_double(), "c-printscan-long-double"),
        (plan.libc(), "c"),
        (plan.compiler_rt(), "clang_rt.builtins"),
    ] {
        // Target flags already own the SDK search context, including for
        // dependencies and proof capture before this build script executes.
        let whole = if source == plan.long_double() {
            ",+whole-archive"
        } else {
            ""
        };
        println!("cargo:rustc-link-lib=static:-bundle{whole}={library}");
    }
}

/// The shipped header owns the compiled C layout major on every target.
fn emit_c_api_version(manifest_dir: &Path, out_dir: &Path) {
    let header = manifest_dir.join("../../include/molt/molt.h");
    println!("cargo:rerun-if-changed={}", header.display());
    let source = fs::read_to_string(&header).expect("cannot read C API version authority");
    let definitions: Vec<Vec<_>> = source
        .lines()
        .map(|line| line.split_whitespace().collect::<Vec<_>>())
        .filter(|words| words.starts_with(&["#define", "MOLT_C_API_VERSION"]))
        .collect();
    assert_eq!(
        definitions.len(),
        1,
        "expected one whole-line C API version definition"
    );
    assert_eq!(
        definitions[0].len(),
        3,
        "C API version must be a single numeric literal"
    );
    let literal = definitions[0][2];
    let digits = literal.strip_suffix('u').unwrap_or(literal);
    assert!(
        !digits.is_empty() && digits.bytes().all(|byte| byte.is_ascii_digit()),
        "C API version must be a numeric u32 literal"
    );
    let version = digits.parse::<u32>().expect("C API version exceeds u32");
    fs::write(
        out_dir.join("molt_c_api_version.rs"),
        format!(
            "/// libmolt C-API surface version.\npub const MOLT_C_API_VERSION: u32 = {version};\n"
        ),
    )
    .expect("cannot write C API version projection");
}
