"""Intrinsic-first stdlib package stub for `idlelib.idle_test`.

Generated by tools/gen_stdlib_stubs.py; lowering the package replaces this file.
"""

from _intrinsics import require_intrinsic as _require_intrinsic

_require_intrinsic("molt_capabilities_has")


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `idlelib.idle_test` package stub with full intrinsic-backed lowering.
def __getattr__(attr: str):
    if attr in {
        "htest",
        "mock_idle",
        "mock_tk",
        "template",
        "test_autocomplete",
        "test_autocomplete_w",
        "test_autoexpand",
        "test_browser",
        "test_calltip",
        "test_calltip_w",
        "test_codecontext",
        "test_colorizer",
        "test_config",
        "test_config_key",
        "test_configdialog",
        "test_debugger",
        "test_debugger_r",
        "test_debugobj",
        "test_debugobj_r",
        "test_delegator",
        "test_editmenu",
        "test_editor",
        "test_filelist",
        "test_format",
        "test_grep",
        "test_help",
        "test_help_about",
        "test_history",
        "test_hyperparser",
        "test_iomenu",
        "test_macosx",
        "test_mainmenu",
        "test_multicall",
        "test_outwin",
        "test_parenmatch",
        "test_pathbrowser",
        "test_percolator",
        "test_pyparse",
        "test_pyshell",
        "test_query",
        "test_redirector",
        "test_replace",
        "test_rpc",
        "test_run",
        "test_runscript",
        "test_scrolledlist",
        "test_search",
        "test_searchbase",
        "test_searchengine",
        "test_sidebar",
        "test_squeezer",
        "test_stackviewer",
        "test_statusbar",
        "test_text",
        "test_textview",
        "test_tooltip",
        "test_tree",
        "test_undo",
        "test_util",
        "test_warning",
        "test_window",
        "test_zoomheight",
        "test_zzdummy",
        "tkinter_testing_utils",
    }:
        raise AttributeError(f"module {__name__!r} has no attribute {attr!r}", name=attr)
    raise RuntimeError(
        'stdlib package "idlelib.idle_test" is not fully lowered yet; only an intrinsic-first stub is available.'
    )


globals().pop("_require_intrinsic", None)
