"""Intrinsic-first stdlib module stub for `lib2to3.fixes.fix_execfile`.

Generated by tools/gen_stdlib_stubs.py; lowering the module replaces this file.
"""


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `lib2to3.fixes.fix_execfile` module stub with a full lowering.
def __getattr__(attr: str):
    raise RuntimeError(
        'stdlib module "lib2to3.fixes.fix_execfile" is not fully lowered yet; only an intrinsic-first stub is available.'
    )
