// @generated by tools/gen_native_callable_abi.py from
// runtime/native_callable_abi.toml. DO NOT EDIT.

const contracts = {"molt.forward_f32_v1":{"params":["bytes.float32"],"result":"bytes.float32"},"molt.object_call_v1":{"params":["molt.value..."],"result":"molt.value"},"molt.object_callargs_v1":{"params":["molt.callargs"],"result":"molt.value"},"molt.pyinit_module_v1":{"params":[],"result":"molt.pyobject_ptr"}};
for (const signature of Object.values(contracts)) {
  Object.freeze(signature.params);
  Object.freeze(signature);
}
export const NATIVE_CALLABLE_BROWSER_SIGNATURES = Object.freeze(contracts);

export const nativeCallableBrowserSignature = (abi) => {
  const signature = NATIVE_CALLABLE_BROWSER_SIGNATURES[abi];
  if (signature === undefined) {
    throw new Error(`unsupported browser native callable ABI: ${abi}`);
  }
  return { params: [...signature.params], result: signature.result };
};
