package molt:runtime;

interface intrinsics {
    type molt-object = u64;
    type molt-ptr = u32;

    runtime_init: func() -> u64;
    runtime_shutdown: func() -> u64;
    print_obj: func(val: molt-object);
    print_newline: func();
    alloc: func(size: u64) -> u64;
    alloc_class: func(size: u64, class_bits: molt-object) -> molt-object;
    alloc_class_trusted: func(size: u64, class_bits: molt-object) -> molt-object;
    alloc_class_static: func(size: u64, class_bits: molt-object) -> molt-object;
    async_sleep: func(obj: u64) -> u64;
    anext_default_poll: func(obj: u64) -> u64;
    asyncgen_poll: func(obj: u64) -> u64;
    promise_poll: func(obj: u64) -> u64;
    asyncgen_new: func(obj: molt-object) -> molt-object;
    asyncgen_shutdown: func() -> u64;
    future_poll_fn: func(obj: u64) -> u64;
    future_poll: func(obj: u64) -> u64;
    future_cancel: func(obj: u64) -> u64;
    future_cancel_msg: func(obj: u64, msg: u64) -> u64;
    future_cancel_clear: func(obj: u64) -> u64;
    promise_new: func() -> u64;
    promise_set_result: func(obj: u64, result: u64) -> u64;
    promise_set_exception: func(obj: u64, exc: u64) -> u64;
    io_wait: func(obj: molt-object) -> molt-object;
    io_wait_new: func(socket: molt-object, events: molt-object, timeout: molt-object) -> molt-object;
    thread_submit: func(callable: molt-object, args: molt-object, kwargs: molt-object) -> molt-object;
    thread_poll: func(obj: molt-object) -> molt-object;
    process_spawn: func(
        args: molt-object,
        env: molt-object,
        cwd: molt-object,
        stdin: molt-object,
        stdout: molt-object,
        stderr: molt-object
    ) -> molt-object;
    process_wait_future: func(proc: molt-object) -> molt-object;
    process_poll: func(obj: molt-object) -> molt-object;
    process_pid: func(proc: molt-object) -> molt-object;
    process_returncode: func(proc: molt-object) -> molt-object;
    process_kill: func(proc: molt-object) -> molt-object;
    process_terminate: func(proc: molt-object) -> molt-object;
    process_stdin: func(proc: molt-object) -> molt-object;
    process_stdout: func(proc: molt-object) -> molt-object;
    process_stderr: func(proc: molt-object) -> molt-object;
    process_drop: func(proc: molt-object);
    socket_constants: func() -> molt-object;
    socket_has_ipv6: func() -> molt-object;
    socket_new: func(
        family: molt-object,
        sock_type: molt-object,
        proto: molt-object,
        fileno: molt-object
    ) -> molt-object;
    socket_close: func(sock: molt-object) -> molt-object;
    socket_drop: func(sock: molt-object);
    socket_clone: func(sock: molt-object) -> molt-object;
    socket_fileno: func(sock: molt-object) -> molt-object;
    socket_gettimeout: func(sock: molt-object) -> molt-object;
    socket_settimeout: func(sock: molt-object, timeout: molt-object) -> molt-object;
    socket_setblocking: func(sock: molt-object, flag: molt-object) -> molt-object;
    socket_getblocking: func(sock: molt-object) -> molt-object;
    socket_bind: func(sock: molt-object, addr: molt-object) -> molt-object;
    socket_listen: func(sock: molt-object, backlog: molt-object) -> molt-object;
    socket_accept: func(sock: molt-object) -> molt-object;
    socket_connect: func(sock: molt-object, addr: molt-object) -> molt-object;
    socket_connect_ex: func(sock: molt-object, addr: molt-object) -> molt-object;
    socket_recv: func(sock: molt-object, size: molt-object, flags: molt-object) -> molt-object;
    socket_recv_into: func(
        sock: molt-object,
        buffer: molt-object,
        size: molt-object,
        flags: molt-object
    ) -> molt-object;
    socket_send: func(sock: molt-object, data: molt-object, flags: molt-object) -> molt-object;
    socket_sendall: func(sock: molt-object, data: molt-object, flags: molt-object) -> molt-object;
    socket_sendto: func(
        sock: molt-object,
        data: molt-object,
        flags: molt-object,
        addr: molt-object
    ) -> molt-object;
    socket_recvfrom: func(sock: molt-object, size: molt-object, flags: molt-object) -> molt-object;
    socket_shutdown: func(sock: molt-object, how: molt-object) -> molt-object;
    socket_getsockname: func(sock: molt-object) -> molt-object;
    socket_getpeername: func(sock: molt-object) -> molt-object;
    socket_setsockopt: func(
        sock: molt-object,
        level: molt-object,
        optname: molt-object,
        value: molt-object
    ) -> molt-object;
    socket_getsockopt: func(
        sock: molt-object,
        level: molt-object,
        optname: molt-object,
        buflen: molt-object
    ) -> molt-object;
    socket_detach: func(sock: molt-object) -> molt-object;
    socketpair: func(family: molt-object, sock_type: molt-object, proto: molt-object) -> molt-object;
    socket_getaddrinfo: func(
        host: molt-object,
        port: molt-object,
        family: molt-object,
        sock_type: molt-object,
        proto: molt-object,
        flags: molt-object
    ) -> molt-object;
    socket_getnameinfo: func(addr: molt-object, flags: molt-object) -> molt-object;
    socket_gethostname: func() -> molt-object;
    socket_getservbyname: func(name: molt-object, proto: molt-object) -> molt-object;
    socket_getservbyport: func(port: molt-object, proto: molt-object) -> molt-object;
    socket_inet_pton: func(family: molt-object, address: molt-object) -> molt-object;
    socket_inet_ntop: func(family: molt-object, packed: molt-object) -> molt-object;
    sleep_register: func(task: molt-ptr, future: molt-ptr) -> u64;
    block_on: func(task: u64) -> u64;
    spawn: func(task: molt-object);
    cancel_token_new: func(parent: molt-object) -> molt-object;
    cancel_token_clone: func(token: molt-object) -> molt-object;
    cancel_token_drop: func(token: molt-object) -> molt-object;
    cancel_token_cancel: func(token: molt-object) -> molt-object;
    cancel_token_is_cancelled: func(token: molt-object) -> molt-object;
    cancel_token_set_current: func(token: molt-object) -> molt-object;
    cancel_token_get_current: func() -> molt-object;
    cancelled: func() -> molt-object;
    cancel_current: func() -> molt-object;
    chan_new: func(capacity: molt-object) -> molt-ptr;
    chan_send: func(chan: molt-ptr, val: molt-object) -> molt-object;
    chan_recv: func(chan: molt-ptr) -> molt-object;
    chan_drop: func(chan: molt-ptr);

    add: func(a: molt-object, b: molt-object) -> molt-object;
    inplace_add: func(a: molt-object, b: molt-object) -> molt-object;
    vec_sum_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_sum_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_prod_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_prod_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_min_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_min_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_max_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_max_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_sum_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_sum_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_prod_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_prod_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_min_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_min_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_max_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_max_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    sub: func(a: molt-object, b: molt-object) -> molt-object;
    mul: func(a: molt-object, b: molt-object) -> molt-object;
    inplace_sub: func(a: molt-object, b: molt-object) -> molt-object;
    inplace_mul: func(a: molt-object, b: molt-object) -> molt-object;
    bit_or: func(a: molt-object, b: molt-object) -> molt-object;
    bit_and: func(a: molt-object, b: molt-object) -> molt-object;
    bit_xor: func(a: molt-object, b: molt-object) -> molt-object;
    invert: func(a: molt-object) -> molt-object;
    inplace_bit_or: func(a: molt-object, b: molt-object) -> molt-object;
    inplace_bit_and: func(a: molt-object, b: molt-object) -> molt-object;
    inplace_bit_xor: func(a: molt-object, b: molt-object) -> molt-object;
    lshift: func(a: molt-object, b: molt-object) -> molt-object;
    rshift: func(a: molt-object, b: molt-object) -> molt-object;
    matmul: func(a: molt-object, b: molt-object) -> molt-object;
    div: func(a: molt-object, b: molt-object) -> molt-object;
    floordiv: func(a: molt-object, b: molt-object) -> molt-object;
    mod: func(a: molt-object, b: molt-object) -> molt-object;
    pow: func(a: molt-object, b: molt-object) -> molt-object;
    pow_mod: func(a: molt-object, b: molt-object, m: molt-object) -> molt-object;
    round: func(val: molt-object, ndigits: molt-object, has_ndigits: molt-object) -> molt-object;
    trunc: func(val: molt-object) -> molt-object;
    lt: func(a: molt-object, b: molt-object) -> molt-object;
    le: func(a: molt-object, b: molt-object) -> molt-object;
    gt: func(a: molt-object, b: molt-object) -> molt-object;
    ge: func(a: molt-object, b: molt-object) -> molt-object;
    eq: func(a: molt-object, b: molt-object) -> molt-object;
    ne: func(a: molt-object, b: molt-object) -> molt-object;
    string_eq: func(a: molt-object, b: molt-object) -> molt-object;
    is: func(a: molt-object, b: molt-object) -> molt-object;
    closure_load: func(ptr: molt-ptr, offset: u64) -> molt-object;
    closure_store: func(ptr: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    not: func(val: molt-object) -> molt-object;
    contains: func(container: molt-object, item: molt-object) -> molt-object;
    is_truthy: func(val: molt-object) -> u64;
    function_default_kind: func(func: molt-object) -> u64;
    function_closure_bits: func(func: molt-object) -> molt-object;
    function_is_generator: func(func: molt-object) -> molt-object;
    function_is_coroutine: func(func: molt-object) -> molt-object;
    call_arity_error: func(expected: u64, got: u64) -> molt-object;
    callargs_new: func(pos_capacity: u64, kw_capacity: u64) -> molt-object;
    callargs_push_pos: func(builder: u64, val: molt-object) -> molt-object;
    callargs_push_kw: func(builder: u64, name: molt-object, val: molt-object) -> molt-object;
    callargs_expand_star: func(builder: u64, iterable: molt-object) -> molt-object;
    callargs_expand_kwstar: func(builder: u64, mapping: molt-object) -> molt-object;
    call_bind: func(callable: molt-object, builder: u64) -> molt-object;
    iter_sentinel: func(callable: molt-object, sentinel: molt-object) -> molt-object;
    missing: func() -> molt-object;
    not_implemented: func() -> molt-object;
    ellipsis: func() -> molt-object;

    json_parse_scalar: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    msgpack_parse_scalar: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    cbor_parse_scalar: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    json_parse_scalar_obj: func(val: molt-object) -> molt-object;
    msgpack_parse_scalar_obj: func(val: molt-object) -> molt-object;
    cbor_parse_scalar_obj: func(val: molt-object) -> molt-object;
    string_from_bytes: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    bytes_from_bytes: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    bigint_from_str: func(ptr: molt-ptr, len: u64) -> molt-object;
    str_from_obj: func(val: molt-object) -> molt-object;
    repr_from_obj: func(val: molt-object) -> molt-object;
    repr_builtin: func(val: molt-object) -> molt-object;
    format_builtin: func(val: molt-object, format_spec: molt-object) -> molt-object;
    ascii_from_obj: func(val: molt-object) -> molt-object;
    callable_builtin: func(val: molt-object) -> molt-object;
    int_from_obj: func(val: molt-object, base: molt-object, has_base: molt-object) -> molt-object;
    guard_type: func(val: molt-object, expected: molt-object) -> molt-object;
    guard_layout_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64) -> molt-object;
    guarded_field_get_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64, offset: u64, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    guarded_field_set_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64, offset: u64, val: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    guarded_field_init_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64, offset: u64, val: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    handle_resolve: func(bits: molt-object) -> molt-ptr;
    inc_ref_obj: func(val: molt-object);
    get_attr_generic: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    get_attr_ptr: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    get_attr_object: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    get_attr_special: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    set_attr_generic: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64, val: molt-object) -> molt-object;
    set_attr_ptr: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64, val: molt-object) -> molt-object;
    set_attr_object: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64, val: molt-object) -> molt-object;
    del_attr_generic: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    del_attr_ptr: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    del_attr_object: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    object_field_get: func(obj: molt-object, offset: u64) -> molt-object;
    object_field_get_ptr: func(obj: molt-ptr, offset: u64) -> molt-object;
    object_field_set: func(obj: molt-object, offset: u64, val: molt-object) -> molt-object;
    object_field_set_ptr: func(obj: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    object_field_init: func(obj: molt-object, offset: u64, val: molt-object) -> molt-object;
    object_field_init_ptr: func(obj: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    module_new: func(name: molt-object) -> molt-object;
    module_cache_get: func(name: molt-object) -> molt-object;
    module_cache_set: func(name: molt-object, module: molt-object) -> molt-object;
    module_get_attr: func(module: molt-object, attr: molt-object) -> molt-object;
    module_get_global: func(module: molt-object, attr: molt-object) -> molt-object;
    module_get_name: func(module: molt-object, attr: molt-object) -> molt-object;
    module_set_attr: func(module: molt-object, attr: molt-object, val: molt-object) -> molt-object;
    module_import_star: func(src: molt-object, dst: molt-object) -> molt-object;
    get_attr_name: func(obj: molt-object, name: molt-object) -> molt-object;
    get_attr_name_default: func(obj: molt-object, name: molt-object, default: molt-object) -> molt-object;
    has_attr_name: func(obj: molt-object, name: molt-object) -> molt-object;
    set_attr_name: func(obj: molt-object, name: molt-object, val: molt-object) -> molt-object;
    del_attr_name: func(obj: molt-object, name: molt-object) -> molt-object;
    len: func(val: molt-object) -> molt-object;
    id: func(val: molt-object) -> molt-object;
    ord: func(val: molt-object) -> molt-object;
    chr: func(val: molt-object) -> molt-object;
    abs_builtin: func(val: molt-object) -> molt-object;
    divmod_builtin: func(a: molt-object, b: molt-object) -> molt-object;
    open_builtin: func(
        file: molt-object,
        mode: molt-object,
        buffering: molt-object,
        encoding: molt-object,
        errors: molt-object,
        newline: molt-object,
        closefd: molt-object,
        opener: molt-object,
    ) -> molt-object;
    bin_builtin: func(val: molt-object) -> molt-object;
    oct_builtin: func(val: molt-object) -> molt-object;
    hex_builtin: func(val: molt-object) -> molt-object;
    getrecursionlimit: func() -> molt-object;
    getargv: func() -> molt-object;
    setrecursionlimit: func(limit: molt-object) -> molt-object;
    recursion_guard_enter: func() -> u64;
    recursion_guard_exit: func();
    trace_enter_slot: func(code_id: u64) -> molt-object;
    trace_set_line: func(line: molt-object) -> molt-object;
    trace_exit: func() -> molt-object;
    code_slots_init: func(count: u64) -> molt-object;
    code_slot_set: func(code_id: u64, code: molt-object) -> molt-object;
    code_new: func(
        filename: molt-object,
        name: molt-object,
        firstlineno: molt-object,
        linetable: molt-object,
    ) -> molt-object;
    round_builtin: func(val: molt-object, ndigits: molt-object) -> molt-object;
    enumerate_builtin: func(iterable: molt-object, start: molt-object) -> molt-object;
    next_builtin: func(iter: molt-object, default: molt-object) -> molt-object;
    any_builtin: func(iter: molt-object) -> molt-object;
    all_builtin: func(iter: molt-object) -> molt-object;
    sum_builtin: func(iter: molt-object, start: molt-object) -> molt-object;
    min_builtin: func(args: molt-object, key: molt-object, default: molt-object) -> molt-object;
    max_builtin: func(args: molt-object, key: molt-object, default: molt-object) -> molt-object;
    map_builtin: func(func: molt-object, iterables: molt-object) -> molt-object;
    filter_builtin: func(func: molt-object, iterable: molt-object) -> molt-object;
    zip_builtin: func(iterables: molt-object) -> molt-object;
    reversed_builtin: func(seq: molt-object) -> molt-object;
    sorted_builtin: func(iter: molt-object, key: molt-object, reverse: molt-object) -> molt-object;
    getattr_builtin: func(obj: molt-object, name: molt-object, default: molt-object) -> molt-object;
    anext_builtin: func(iter: molt-object, default: molt-object) -> molt-object;
    print_builtin: func(
        args: molt-object,
        sep: molt-object,
        end: molt-object,
        file: molt-object,
        flush: molt-object,
    ) -> molt-object;
    super_builtin: func(type: molt-object, obj: molt-object) -> molt-object;
    slice: func(obj: molt-object, start: molt-object, end: molt-object) -> molt-object;
    slice_new: func(start: molt-object, stop: molt-object, step: molt-object) -> molt-object;
    range_new: func(start: molt-object, stop: molt-object, step: molt-object) -> molt-object;
    list_builder_new: func(capacity: u64) -> u64;
    list_builder_append: func(builder: u64, val: molt-object);
    list_builder_finish: func(builder: u64) -> molt-object;
    tuple_builder_finish: func(builder: u64) -> molt-object;
    list_append: func(list: molt-object, val: molt-object) -> molt-object;
    list_pop: func(list: molt-object, index: molt-object) -> molt-object;
    list_extend: func(list: molt-object, other: molt-object) -> molt-object;
    list_insert: func(list: molt-object, index: molt-object, val: molt-object) -> molt-object;
    list_remove: func(list: molt-object, val: molt-object) -> molt-object;
    list_clear: func(list: molt-object) -> molt-object;
    list_copy: func(list: molt-object) -> molt-object;
    list_reverse: func(list: molt-object) -> molt-object;
    list_sort: func(list: molt-object, key: molt-object, reverse: molt-object) -> molt-object;
    list_count: func(list: molt-object, val: molt-object) -> molt-object;
    list_index: func(list: molt-object, val: molt-object) -> molt-object;
    list_index_range: func(
        list: molt-object,
        val: molt-object,
        start: molt-object,
        stop: molt-object
    ) -> molt-object;
    heapq_heapify: func(list: molt-object) -> molt-object;
    heapq_heappush: func(list: molt-object, item: molt-object) -> molt-object;
    heapq_heappop: func(list: molt-object) -> molt-object;
    heapq_heapreplace: func(list: molt-object, item: molt-object) -> molt-object;
    heapq_heappushpop: func(list: molt-object, item: molt-object) -> molt-object;
    tuple_from_list: func(obj: molt-object) -> molt-object;
    dict_new: func(capacity: u64) -> molt-object;
    dict_from_obj: func(obj: molt-object) -> molt-object;
    dict_set: func(dict: molt-object, key: molt-object, val: molt-object) -> molt-object;
    dict_get: func(dict: molt-object, key: molt-object, default: molt-object) -> molt-object;
    dict_pop: func(dict: molt-object, key: molt-object, default: molt-object, has_default: molt-object) -> molt-object;
    dict_setdefault: func(dict: molt-object, key: molt-object, default: molt-object) -> molt-object;
    dict_update: func(dict: molt-object, other: molt-object) -> molt-object;
    dict_clear: func(dict: molt-object) -> molt-object;
    dict_copy: func(dict: molt-object) -> molt-object;
    dict_popitem: func(dict: molt-object) -> molt-object;
    dict_update_kwstar: func(dict: molt-object, other: molt-object) -> molt-object;
    dict_keys: func(dict: molt-object) -> molt-object;
    dict_values: func(dict: molt-object) -> molt-object;
    dict_items: func(dict: molt-object) -> molt-object;
    set_new: func(capacity: u64) -> molt-object;
    set_add: func(set: molt-object, key: molt-object) -> molt-object;
    set_discard: func(set: molt-object, key: molt-object) -> molt-object;
    set_remove: func(set: molt-object, key: molt-object) -> molt-object;
    set_pop: func(set: molt-object) -> molt-object;
    set_update: func(set: molt-object, other: molt-object) -> molt-object;
    set_intersection_update: func(set: molt-object, other: molt-object) -> molt-object;
    set_difference_update: func(set: molt-object, other: molt-object) -> molt-object;
    set_symdiff_update: func(set: molt-object, other: molt-object) -> molt-object;
    frozenset_new: func(capacity: u64) -> molt-object;
    frozenset_add: func(set: molt-object, key: molt-object) -> molt-object;
    tuple_count: func(tuple: molt-object, val: molt-object) -> molt-object;
    tuple_index: func(tuple: molt-object, val: molt-object) -> molt-object;
    iter: func(obj: molt-object) -> molt-object;
    enumerate: func(iterable: molt-object, start: molt-object, has_start: molt-object) -> molt-object;
    aiter: func(obj: molt-object) -> molt-object;
    iter_next: func(iter: molt-object) -> molt-object;
    anext: func(iter: molt-object) -> molt-object;
    task_new: func(poll_fn: u64, closure_size: u64, kind: u64) -> molt-object;
    task_register_token_owned: func(task: molt-object, token: molt-object) -> molt-object;
    generator_new: func(poll_fn: u64, closure_size: u64) -> molt-object;
    generator_send: func(gen: molt-object, val: molt-object) -> molt-object;
    generator_throw: func(gen: molt-object, exc: molt-object) -> molt-object;
    generator_close: func(gen: molt-object) -> molt-object;
    is_generator: func(obj: molt-object) -> molt-object;
    is_bound_method: func(obj: molt-object) -> molt-object;
    is_function_obj: func(obj: molt-object) -> molt-object;
    is_callable: func(obj: molt-object) -> molt-object;
    index: func(obj: molt-object, key: molt-object) -> molt-object;
    store_index: func(obj: molt-object, key: molt-object, val: molt-object) -> molt-object;
    del_index: func(obj: molt-object, key: molt-object) -> molt-object;
    bytes_find: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_find: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_find: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytes_find_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytearray_find_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    string_find_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    string_format: func(val: molt-object, spec: molt-object) -> molt-object;
    string_startswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytes_startswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_startswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_startswith_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytes_startswith_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytearray_startswith_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    string_endswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytes_endswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_endswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_endswith_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytes_endswith_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytearray_endswith_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    string_count: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytes_count: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_count: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_count_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytes_count_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    bytearray_count_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    env_get: func(key: molt-object, default: molt-object) -> molt-object;
    getpid: func() -> molt-object;
    time_monotonic: func() -> molt-object;
    time_monotonic_ns: func() -> molt-object;
    time_time: func() -> molt-object;
    time_time_ns: func() -> molt-object;
    path_exists: func(path: molt-object) -> molt-object;
    path_unlink: func(path: molt-object) -> molt-object;
    string_join: func(sep: molt-object, items: molt-object) -> molt-object;
    string_split: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_split_max: func(haystack: molt-object, needle: molt-object, maxsplit: molt-object) -> molt-object;
    string_lower: func(haystack: molt-object) -> molt-object;
    string_upper: func(haystack: molt-object) -> molt-object;
    string_capitalize: func(haystack: molt-object) -> molt-object;
    string_strip: func(haystack: molt-object, chars: molt-object) -> molt-object;
    string_lstrip: func(haystack: molt-object, chars: molt-object) -> molt-object;
    string_rstrip: func(haystack: molt-object, chars: molt-object) -> molt-object;
    bytes_split: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytes_split_max: func(haystack: molt-object, needle: molt-object, maxsplit: molt-object) -> molt-object;
    bytearray_split: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_split_max: func(haystack: molt-object, needle: molt-object, maxsplit: molt-object) -> molt-object;
    string_replace: func(haystack: molt-object, needle: molt-object, replacement: molt-object, count: molt-object) -> molt-object;
    bytes_replace: func(haystack: molt-object, needle: molt-object, replacement: molt-object, count: molt-object) -> molt-object;
    bytearray_replace: func(haystack: molt-object, needle: molt-object, replacement: molt-object, count: molt-object) -> molt-object;
    bytes_from_obj: func(obj: molt-object) -> molt-object;
    bytearray_from_obj: func(obj: molt-object) -> molt-object;
    bytes_from_str: func(obj: molt-object, encoding: molt-object, errors: molt-object) -> molt-object;
    bytearray_from_str: func(obj: molt-object, encoding: molt-object, errors: molt-object) -> molt-object;
    float_from_obj: func(obj: molt-object) -> molt-object;
    intarray_from_seq: func(obj: molt-object) -> molt-object;
    memoryview_new: func(obj: molt-object) -> molt-object;
    memoryview_tobytes: func(obj: molt-object) -> molt-object;
    memoryview_cast: func(obj: molt-object, format: molt-object, shape: molt-object, has_shape: molt-object) -> molt-object;
    buffer2d_new: func(rows: molt-object, cols: molt-object, init: molt-object) -> molt-object;
    buffer2d_get: func(buf: molt-object, row: molt-object, col: molt-object) -> molt-object;
    buffer2d_set: func(buf: molt-object, row: molt-object, col: molt-object, val: molt-object) -> molt-object;
    buffer2d_matmul: func(lhs: molt-object, rhs: molt-object) -> molt-object;
    dataclass_new: func(name: molt-object, fields: molt-object, values: molt-object, flags: molt-object) -> molt-object;
    dataclass_get: func(obj: molt-object, index: molt-object) -> molt-object;
    dataclass_set: func(obj: molt-object, index: molt-object, value: molt-object) -> molt-object;
    dataclass_set_class: func(obj: molt-object, class_obj: molt-object) -> molt-object;
    class_new: func(name: molt-object) -> molt-object;
    class_set_base: func(class_obj: molt-object, base_obj: molt-object) -> molt-object;
    class_apply_set_name: func(class_obj: molt-object) -> molt-object;
    super_new: func(type_obj: molt-object, obj: molt-object) -> molt-object;
    builtin_type: func(tag: molt-object) -> molt-object;
    type_of: func(obj: molt-object) -> molt-object;
    class_layout_version: func(class_obj: molt-object) -> molt-object;
    class_set_layout_version: func(class_obj: molt-object, version: molt-object) -> molt-object;
    isinstance: func(obj: molt-object, class_obj: molt-object) -> molt-object;
    issubclass: func(sub_obj: molt-object, class_obj: molt-object) -> molt-object;
    object_new: func() -> molt-object;
    func_new: func(fn_idx: u64, trampoline_ptr: u64, arity: u64) -> molt-object;
    func_new_closure: func(fn_idx: u64, trampoline_ptr: u64, arity: u64, closure: molt-object) -> molt-object;
    bound_method_new: func(func: molt-object, self_obj: molt-object) -> molt-object;
    classmethod_new: func(func: molt-object) -> molt-object;
    staticmethod_new: func(func: molt-object) -> molt-object;
    property_new: func(getter: molt-object, setter: molt-object, deleter: molt-object) -> molt-object;
    object_set_class: func(obj: molt-ptr, class_obj: molt-object) -> molt-object;
    context_null: func(payload: molt-object) -> molt-object;
    context_enter: func(ctx: molt-object) -> molt-object;
    context_exit: func(ctx: molt-object, exc: molt-object) -> molt-object;
    context_unwind: func(exc: molt-object) -> molt-object;
    context_depth: func() -> molt-object;
    context_unwind_to: func(depth: molt-object, exc: molt-object) -> molt-object;
    context_closing: func(payload: molt-object) -> molt-object;
    exception_push: func() -> molt-object;
    exception_pop: func() -> molt-object;
    exception_last: func() -> molt-object;
    exception_active: func() -> molt-object;
    exception_new: func(kind: molt-object, args: molt-object) -> molt-object;
    exception_new_from_class: func(class_obj: molt-object, args: molt-object) -> molt-object;
    exception_clear: func() -> molt-object;
    exception_pending: func() -> u64;
    exception_kind: func(exc: molt-object) -> molt-object;
    exception_class: func(kind: molt-object) -> molt-object;
    exception_message: func(exc: molt-object) -> molt-object;
    exception_set_cause: func(exc: molt-object, cause: molt-object) -> molt-object;
    exception_set_value: func(exc: molt-object, value: molt-object) -> molt-object;
    exception_context_set: func(exc: molt-object) -> molt-object;
    exception_set_last: func(exc: molt-object) -> molt-object;
    raise: func(exc: molt-object) -> molt-object;
    file_open: func(path: molt-object, mode: molt-object) -> molt-object;
    file_read: func(handle: molt-object, size: molt-object) -> molt-object;
    file_readline: func(handle: molt-object, size: molt-object) -> molt-object;
    file_readlines: func(handle: molt-object, hint: molt-object) -> molt-object;
    file_readinto: func(handle: molt-object, buffer: molt-object) -> molt-object;
    file_write: func(handle: molt-object, data: molt-object) -> molt-object;
    file_writelines: func(handle: molt-object, lines: molt-object) -> molt-object;
    file_seek: func(handle: molt-object, offset: molt-object, whence: molt-object) -> molt-object;
    file_tell: func(handle: molt-object) -> molt-object;
    file_fileno: func(handle: molt-object) -> molt-object;
    file_truncate: func(handle: molt-object, size: molt-object) -> molt-object;
    file_flush: func(handle: molt-object) -> molt-object;
    file_readable: func(handle: molt-object) -> molt-object;
    file_writable: func(handle: molt-object) -> molt-object;
    file_seekable: func(handle: molt-object) -> molt-object;
    file_isatty: func(handle: molt-object) -> molt-object;
    file_close: func(handle: molt-object) -> molt-object;
    file_detach: func(handle: molt-object) -> molt-object;
    file_reconfigure: func(handle: molt-object, encoding: molt-object, errors: molt-object, newline: molt-object, line_buffering: molt-object, write_through: molt-object) -> molt-object;
    // TODO(wasm-parity, owner:runtime, milestone:SL1, priority:P2, status:partial):
    // add imports for remaining file methods (readinto1) once implemented.
    bridge_unavailable: func(msg: molt-object) -> molt-object;
    db_query: func(ptr: molt-ptr, len: u64, out: molt-ptr, cancel_token: molt-object) -> s32;
    db_exec: func(ptr: molt-ptr, len: u64, out: molt-ptr, cancel_token: molt-object) -> s32;
    stream_new: func(capacity: u64) -> u64;
    stream_clone: func(handle: u64) -> u64;
    stream_send: func(handle: u64, ptr: molt-ptr, len: u64) -> u64;
    stream_send_obj: func(handle: u64, data: molt-object) -> molt-object;
    stream_recv: func(handle: u64) -> u64;
    stream_close: func(handle: u64);
    stream_drop: func(handle: u64);
    ws_connect: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    ws_pair: func(capacity: u64, out_left: molt-ptr, out_right: molt-ptr) -> s32;
    ws_send: func(handle: u64, ptr: molt-ptr, len: u64) -> u64;
    ws_recv: func(handle: u64) -> u64;
    ws_close: func(handle: u64);
    ws_drop: func(handle: u64);
}

world molt-runtime {
    import intrinsics;
}
