package molt:runtime;

interface intrinsics {
    type molt-object = u64;
    type molt-ptr = u64;

    print_obj: func(val: molt-object);
    print_newline: func();
    alloc: func(size: u64) -> u64;
    alloc_class: func(size: u64, class_bits: molt-object) -> molt-object;
    alloc_class_trusted: func(size: u64, class_bits: molt-object) -> molt-object;
    async_sleep: func(obj: u64) -> u64;
    anext_default_poll: func(obj: u64) -> u64;
    future_poll_fn: func(obj: u64) -> u64;
    sleep_register: func(task: molt-ptr, future: molt-ptr) -> u64;
    block_on: func(task: u64) -> u64;
    cancel_token_new: func(parent: molt-object) -> molt-object;
    cancel_token_clone: func(token: molt-object) -> molt-object;
    cancel_token_drop: func(token: molt-object) -> molt-object;
    cancel_token_cancel: func(token: molt-object) -> molt-object;
    cancel_token_is_cancelled: func(token: molt-object) -> molt-object;
    cancel_token_set_current: func(token: molt-object) -> molt-object;
    cancel_token_get_current: func() -> molt-object;
    cancelled: func() -> molt-object;
    cancel_current: func() -> molt-object;
    chan_new: func(capacity: molt-object) -> molt-ptr;
    chan_send: func(chan: molt-ptr, val: molt-object) -> molt-object;
    chan_recv: func(chan: molt-ptr) -> molt-object;

    add: func(a: molt-object, b: molt-object) -> molt-object;
    vec_sum_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_sum_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_prod_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_prod_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_min_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_min_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_max_int: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_max_int_trusted: func(seq: molt-object, acc: molt-object) -> molt-object;
    vec_sum_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_sum_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_prod_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_prod_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_min_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_min_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_max_int_range: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    vec_max_int_range_trusted: func(seq: molt-object, acc: molt-object, start: molt-object) -> molt-object;
    sub: func(a: molt-object, b: molt-object) -> molt-object;
    mul: func(a: molt-object, b: molt-object) -> molt-object;
    bit_or: func(a: molt-object, b: molt-object) -> molt-object;
    bit_and: func(a: molt-object, b: molt-object) -> molt-object;
    bit_xor: func(a: molt-object, b: molt-object) -> molt-object;
    lshift: func(a: molt-object, b: molt-object) -> molt-object;
    rshift: func(a: molt-object, b: molt-object) -> molt-object;
    matmul: func(a: molt-object, b: molt-object) -> molt-object;
    div: func(a: molt-object, b: molt-object) -> molt-object;
    floordiv: func(a: molt-object, b: molt-object) -> molt-object;
    mod: func(a: molt-object, b: molt-object) -> molt-object;
    pow: func(a: molt-object, b: molt-object) -> molt-object;
    pow_mod: func(a: molt-object, b: molt-object, m: molt-object) -> molt-object;
    round: func(val: molt-object, ndigits: molt-object, has_ndigits: molt-object) -> molt-object;
    trunc: func(val: molt-object) -> molt-object;
    lt: func(a: molt-object, b: molt-object) -> molt-object;
    le: func(a: molt-object, b: molt-object) -> molt-object;
    gt: func(a: molt-object, b: molt-object) -> molt-object;
    ge: func(a: molt-object, b: molt-object) -> molt-object;
    eq: func(a: molt-object, b: molt-object) -> molt-object;
    is: func(a: molt-object, b: molt-object) -> molt-object;
    closure_load: func(ptr: molt-ptr, offset: u64) -> molt-object;
    closure_store: func(ptr: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    not: func(val: molt-object) -> molt-object;
    contains: func(container: molt-object, item: molt-object) -> molt-object;
    is_truthy: func(val: molt-object) -> u64;
    function_default_kind: func(func: molt-object) -> u64;
    function_closure_bits: func(func: molt-object) -> molt-object;
    call_arity_error: func(expected: u64, got: u64) -> molt-object;
    callargs_new: func(pos_capacity: u64, kw_capacity: u64) -> molt-object;
    callargs_push_pos: func(builder: u64, val: molt-object) -> molt-object;
    callargs_push_kw: func(builder: u64, name: molt-object, val: molt-object) -> molt-object;
    callargs_expand_star: func(builder: u64, iterable: molt-object) -> molt-object;
    callargs_expand_kwstar: func(builder: u64, mapping: molt-object) -> molt-object;
    call_bind: func(callable: molt-object, builder: u64) -> molt-object;
    missing: func() -> molt-object;

    json_parse_scalar: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    msgpack_parse_scalar: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    cbor_parse_scalar: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    string_from_bytes: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    bytes_from_bytes: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    bigint_from_str: func(ptr: molt-ptr, len: u64) -> molt-object;
    str_from_obj: func(val: molt-object) -> molt-object;
    repr_from_obj: func(val: molt-object) -> molt-object;
    repr_builtin: func(val: molt-object) -> molt-object;
    ascii_from_obj: func(val: molt-object) -> molt-object;
    callable_builtin: func(val: molt-object) -> molt-object;
    int_from_obj: func(val: molt-object, base: molt-object, has_base: molt-object) -> molt-object;
    guard_type: func(val: molt-object, expected: molt-object) -> molt-object;
    guard_layout_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64) -> molt-object;
    guarded_field_get_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64, offset: u64, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    guarded_field_set_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64, offset: u64, val: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    guarded_field_init_ptr: func(obj: molt-ptr, class_bits: molt-object, expected_version: u64, offset: u64, val: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    handle_resolve: func(bits: molt-object) -> molt-ptr;
    inc_ref_obj: func(val: molt-object);
    get_attr_generic: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    get_attr_ptr: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    get_attr_object: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    get_attr_special: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    set_attr_generic: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64, val: molt-object) -> molt-object;
    set_attr_ptr: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64, val: molt-object) -> molt-object;
    set_attr_object: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64, val: molt-object) -> molt-object;
    del_attr_generic: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    del_attr_ptr: func(obj: molt-ptr, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    del_attr_object: func(obj: molt-object, attr_ptr: molt-ptr, attr_len: u64) -> molt-object;
    object_field_get: func(obj: molt-ptr, offset: u64) -> molt-object;
    object_field_get_ptr: func(obj: molt-ptr, offset: u64) -> molt-object;
    object_field_set: func(obj: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    object_field_set_ptr: func(obj: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    object_field_init: func(obj: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    object_field_init_ptr: func(obj: molt-ptr, offset: u64, val: molt-object) -> molt-object;
    module_new: func(name: molt-object) -> molt-object;
    module_cache_get: func(name: molt-object) -> molt-object;
    module_cache_set: func(name: molt-object, module: molt-object) -> molt-object;
    module_get_attr: func(module: molt-object, attr: molt-object) -> molt-object;
    module_set_attr: func(module: molt-object, attr: molt-object, val: molt-object) -> molt-object;
    get_attr_name: func(obj: molt-object, name: molt-object) -> molt-object;
    get_attr_name_default: func(obj: molt-object, name: molt-object, default: molt-object) -> molt-object;
    has_attr_name: func(obj: molt-object, name: molt-object) -> molt-object;
    set_attr_name: func(obj: molt-object, name: molt-object, val: molt-object) -> molt-object;
    del_attr_name: func(obj: molt-object, name: molt-object) -> molt-object;
    len: func(val: molt-object) -> molt-object;
    id: func(val: molt-object) -> molt-object;
    ord: func(val: molt-object) -> molt-object;
    chr: func(val: molt-object) -> molt-object;
    round_builtin: func(val: molt-object, ndigits: molt-object) -> molt-object;
    enumerate_builtin: func(iterable: molt-object, start: molt-object) -> molt-object;
    next_builtin: func(iter: molt-object, default: molt-object) -> molt-object;
    any_builtin: func(iter: molt-object) -> molt-object;
    all_builtin: func(iter: molt-object) -> molt-object;
    getattr_builtin: func(obj: molt-object, name: molt-object, default: molt-object) -> molt-object;
    anext_builtin: func(iter: molt-object, default: molt-object) -> molt-object;
    print_builtin: func(args: molt-object) -> molt-object;
    super_builtin: func(type: molt-object, obj: molt-object) -> molt-object;
    slice: func(obj: molt-object, start: molt-object, end: molt-object) -> molt-object;
    slice_new: func(start: molt-object, stop: molt-object, step: molt-object) -> molt-object;
    range_new: func(start: molt-object, stop: molt-object, step: molt-object) -> molt-object;
    list_builder_new: func(capacity: u64) -> u64;
    list_builder_append: func(builder: u64, val: molt-object);
    list_builder_finish: func(builder: u64) -> molt-object;
    tuple_builder_finish: func(builder: u64) -> molt-object;
    list_append: func(list: molt-object, val: molt-object) -> molt-object;
    list_pop: func(list: molt-object, index: molt-object) -> molt-object;
    list_extend: func(list: molt-object, other: molt-object) -> molt-object;
    list_insert: func(list: molt-object, index: molt-object, val: molt-object) -> molt-object;
    list_remove: func(list: molt-object, val: molt-object) -> molt-object;
    list_clear: func(list: molt-object) -> molt-object;
    list_copy: func(list: molt-object) -> molt-object;
    list_reverse: func(list: molt-object) -> molt-object;
    list_count: func(list: molt-object, val: molt-object) -> molt-object;
    list_index: func(list: molt-object, val: molt-object) -> molt-object;
    tuple_from_list: func(obj: molt-object) -> molt-object;
    dict_new: func(capacity: u64) -> molt-object;
    dict_from_obj: func(obj: molt-object) -> molt-object;
    dict_set: func(dict: molt-object, key: molt-object, val: molt-object) -> molt-object;
    dict_get: func(dict: molt-object, key: molt-object, default: molt-object) -> molt-object;
    dict_pop: func(dict: molt-object, key: molt-object, default: molt-object, has_default: molt-object) -> molt-object;
    dict_setdefault: func(dict: molt-object, key: molt-object, default: molt-object) -> molt-object;
    dict_update: func(dict: molt-object, other: molt-object) -> molt-object;
    dict_keys: func(dict: molt-object) -> molt-object;
    dict_values: func(dict: molt-object) -> molt-object;
    dict_items: func(dict: molt-object) -> molt-object;
    set_new: func(capacity: u64) -> molt-object;
    set_add: func(set: molt-object, key: molt-object) -> molt-object;
    set_discard: func(set: molt-object, key: molt-object) -> molt-object;
    set_remove: func(set: molt-object, key: molt-object) -> molt-object;
    set_pop: func(set: molt-object) -> molt-object;
    set_update: func(set: molt-object, other: molt-object) -> molt-object;
    set_intersection_update: func(set: molt-object, other: molt-object) -> molt-object;
    set_difference_update: func(set: molt-object, other: molt-object) -> molt-object;
    set_symdiff_update: func(set: molt-object, other: molt-object) -> molt-object;
    frozenset_new: func(capacity: u64) -> molt-object;
    frozenset_add: func(set: molt-object, key: molt-object) -> molt-object;
    tuple_count: func(tuple: molt-object, val: molt-object) -> molt-object;
    tuple_index: func(tuple: molt-object, val: molt-object) -> molt-object;
    iter: func(obj: molt-object) -> molt-object;
    enumerate: func(iterable: molt-object, start: molt-object, has_start: molt-object) -> molt-object;
    aiter: func(obj: molt-object) -> molt-object;
    iter_next: func(iter: molt-object) -> molt-object;
    anext: func(iter: molt-object) -> molt-object;
    generator_new: func(poll_fn: u64, closure_size: u64) -> molt-object;
    generator_send: func(gen: molt-object, val: molt-object) -> molt-object;
    generator_throw: func(gen: molt-object, exc: molt-object) -> molt-object;
    generator_close: func(gen: molt-object) -> molt-object;
    is_generator: func(obj: molt-object) -> molt-object;
    is_bound_method: func(obj: molt-object) -> molt-object;
    is_function_obj: func(obj: molt-object) -> molt-object;
    is_callable: func(obj: molt-object) -> molt-object;
    index: func(obj: molt-object, key: molt-object) -> molt-object;
    store_index: func(obj: molt-object, key: molt-object, val: molt-object) -> molt-object;
    bytes_find: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_find: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_find: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_format: func(val: molt-object, spec: molt-object) -> molt-object;
    string_startswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_endswith: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_count: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_count_slice: func(haystack: molt-object, needle: molt-object, start: molt-object, end: molt-object, has_start: molt-object, has_end: molt-object) -> molt-object;
    env_get: func(key: molt-object, default: molt-object) -> molt-object;
    string_join: func(sep: molt-object, items: molt-object) -> molt-object;
    string_split: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_lower: func(haystack: molt-object) -> molt-object;
    string_upper: func(haystack: molt-object) -> molt-object;
    string_capitalize: func(haystack: molt-object) -> molt-object;
    string_strip: func(haystack: molt-object) -> molt-object;
    bytes_split: func(haystack: molt-object, needle: molt-object) -> molt-object;
    bytearray_split: func(haystack: molt-object, needle: molt-object) -> molt-object;
    string_replace: func(haystack: molt-object, needle: molt-object, replacement: molt-object) -> molt-object;
    bytes_replace: func(haystack: molt-object, needle: molt-object, replacement: molt-object) -> molt-object;
    bytearray_replace: func(haystack: molt-object, needle: molt-object, replacement: molt-object) -> molt-object;
    bytes_from_obj: func(obj: molt-object) -> molt-object;
    bytearray_from_obj: func(obj: molt-object) -> molt-object;
    float_from_obj: func(obj: molt-object) -> molt-object;
    intarray_from_seq: func(obj: molt-object) -> molt-object;
    memoryview_new: func(obj: molt-object) -> molt-object;
    memoryview_tobytes: func(obj: molt-object) -> molt-object;
    buffer2d_new: func(rows: molt-object, cols: molt-object, init: molt-object) -> molt-object;
    buffer2d_get: func(buf: molt-object, row: molt-object, col: molt-object) -> molt-object;
    buffer2d_set: func(buf: molt-object, row: molt-object, col: molt-object, val: molt-object) -> molt-object;
    buffer2d_matmul: func(lhs: molt-object, rhs: molt-object) -> molt-object;
    dataclass_new: func(name: molt-object, fields: molt-object, values: molt-object, flags: molt-object) -> molt-object;
    dataclass_get: func(obj: molt-object, index: molt-object) -> molt-object;
    dataclass_set: func(obj: molt-object, index: molt-object, value: molt-object) -> molt-object;
    dataclass_set_class: func(obj: molt-object, class_obj: molt-object) -> molt-object;
    class_new: func(name: molt-object) -> molt-object;
    class_set_base: func(class_obj: molt-object, base_obj: molt-object) -> molt-object;
    class_apply_set_name: func(class_obj: molt-object) -> molt-object;
    super_new: func(type_obj: molt-object, obj: molt-object) -> molt-object;
    builtin_type: func(tag: molt-object) -> molt-object;
    type_of: func(obj: molt-object) -> molt-object;
    class_layout_version: func(class_obj: molt-object) -> molt-object;
    class_set_layout_version: func(class_obj: molt-object, version: molt-object) -> molt-object;
    isinstance: func(obj: molt-object, class_obj: molt-object) -> molt-object;
    issubclass: func(sub_obj: molt-object, class_obj: molt-object) -> molt-object;
    object_new: func() -> molt-object;
    func_new: func(fn_idx: u64, arity: u64) -> molt-object;
    func_new_closure: func(fn_idx: u64, arity: u64, closure: molt-object) -> molt-object;
    bound_method_new: func(func: molt-object, self_obj: molt-object) -> molt-object;
    classmethod_new: func(func: molt-object) -> molt-object;
    staticmethod_new: func(func: molt-object) -> molt-object;
    property_new: func(getter: molt-object, setter: molt-object, deleter: molt-object) -> molt-object;
    object_set_class: func(obj: molt-ptr, class_obj: molt-object) -> molt-object;
    context_null: func(payload: molt-object) -> molt-object;
    context_enter: func(ctx: molt-object) -> molt-object;
    context_exit: func(ctx: molt-object, exc: molt-object) -> molt-object;
    context_unwind: func(exc: molt-object) -> molt-object;
    context_depth: func() -> molt-object;
    context_unwind_to: func(depth: molt-object, exc: molt-object) -> molt-object;
    context_closing: func(payload: molt-object) -> molt-object;
    exception_push: func() -> molt-object;
    exception_pop: func() -> molt-object;
    exception_last: func() -> molt-object;
    exception_new: func(kind: molt-object, msg: molt-object) -> molt-object;
    exception_clear: func() -> molt-object;
    exception_pending: func() -> u64;
    exception_kind: func(exc: molt-object) -> molt-object;
    exception_message: func(exc: molt-object) -> molt-object;
    exception_set_cause: func(exc: molt-object, cause: molt-object) -> molt-object;
    exception_context_set: func(exc: molt-object) -> molt-object;
    raise: func(exc: molt-object) -> molt-object;
    file_open: func(path: molt-object, mode: molt-object) -> molt-object;
    file_read: func(handle: molt-object, size: molt-object) -> molt-object;
    file_write: func(handle: molt-object, data: molt-object) -> molt-object;
    file_close: func(handle: molt-object) -> molt-object;
    bridge_unavailable: func(msg: molt-object) -> molt-object;
    stream_new: func(capacity: u64) -> u64;
    stream_send: func(handle: u64, ptr: molt-ptr, len: u64) -> u64;
    stream_recv: func(handle: u64) -> u64;
    stream_close: func(handle: u64);
    ws_connect: func(ptr: molt-ptr, len: u64, out: molt-ptr) -> s32;
    ws_pair: func(capacity: u64, out_left: molt-ptr, out_right: molt-ptr) -> s32;
    ws_send: func(handle: u64, ptr: molt-ptr, len: u64) -> u64;
    ws_recv: func(handle: u64) -> u64;
    ws_close: func(handle: u64);
}

world molt-runtime {
    import intrinsics;
}
