//! MLIR textual IR serialization for FusedKernel.
//!
//! Generates MLIR text that maps 1:1 to the 26 primitives.
//! This is string generation only — zero C++ dependencies.

use std::fmt::Write;

use crate::dtype::DType;
use crate::ops::PrimitiveOp;
use crate::render::{FusedKernel, FusedSrc};

/// Serialize a FusedKernel to MLIR textual IR.
pub fn to_mlir_text(kernel: &FusedKernel) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "// Generated by molt-gpu MLIR serializer").unwrap();
    writeln!(out, "// {} ops, {} buffers", kernel.ops.len(), kernel.bufs.len()).unwrap();
    writeln!(out, "func.func @molt_kernel() {{").unwrap();

    // Declare buffer memrefs
    for (i, binding) in kernel.bufs.iter().enumerate() {
        let mlir_type = mlir_element_type(binding.dtype);
        let shape = binding.st.shape();
        let shape_str = shape.iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join("x");
        writeln!(out, "  // buf{}: memref<{}x{}>", i, shape_str, mlir_type).unwrap();
    }

    // Emit ops
    for (i, op) in kernel.ops.iter().enumerate() {
        let mlir_type = mlir_element_type(op.dst_dtype);
        let src_refs: Vec<String> = op.srcs.iter().map(mlir_src_ref).collect();

        let mlir_op = match op.op {
            PrimitiveOp::Add => {
                if op.dst_dtype.is_float() {
                    format!("arith.addf {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.addi {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Sub => {
                if op.dst_dtype.is_float() {
                    format!("arith.subf {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.subi {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Mul => {
                if op.dst_dtype.is_float() {
                    format!("arith.mulf {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.muli {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Idiv => {
                if op.dst_dtype.is_signed_int() {
                    format!("arith.divsi {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.divui {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Mod => {
                if op.dst_dtype.is_signed_int() {
                    format!("arith.remsi {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.remui {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Neg => {
                if op.dst_dtype.is_float() {
                    format!("arith.negf {} : {}", src_refs[0], mlir_type)
                } else {
                    format!("arith.subi %zero , {} : {}", src_refs[0], mlir_type)
                }
            }
            PrimitiveOp::Cmplt => format!("arith.cmpf \"olt\" , {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::Cmpeq => format!("arith.cmpf \"oeq\" , {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::Cmpne => format!("arith.cmpf \"une\" , {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::And => format!("arith.andi {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::Or => format!("arith.ori {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::Xor => format!("arith.xori {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::Shl => format!("arith.shli {} , {} : {}", src_refs[0], src_refs[1], mlir_type),
            PrimitiveOp::Shr => {
                if op.dst_dtype.is_signed_int() {
                    format!("arith.shrsi {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.shrui {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Exp2 => format!("math.exp2 {} : {}", src_refs[0], mlir_type),
            PrimitiveOp::Log2 => format!("math.log2 {} : {}", src_refs[0], mlir_type),
            PrimitiveOp::Sin => format!("math.sin {} : {}", src_refs[0], mlir_type),
            PrimitiveOp::Sqrt => format!("math.sqrt {} : {}", src_refs[0], mlir_type),
            PrimitiveOp::Reciprocal => format!("arith.divf %one , {} : {}", src_refs[0], mlir_type),
            PrimitiveOp::Trunc => format!("math.trunc {} : {}", src_refs[0], mlir_type),
            PrimitiveOp::Max => {
                if op.dst_dtype.is_float() {
                    format!("arith.maximumf {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else if op.dst_dtype.is_signed_int() {
                    format!("arith.maxsi {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                } else {
                    format!("arith.maxui {} , {} : {}", src_refs[0], src_refs[1], mlir_type)
                }
            }
            PrimitiveOp::Where => format!("arith.select {} , {} , {} : {}", src_refs[0], src_refs[1], src_refs[2], mlir_type),
            PrimitiveOp::Cast => format!("// cast to {} : {}", mlir_type, src_refs[0]),
            PrimitiveOp::Bitcast => format!("arith.bitcast {} : {} to {}", src_refs[0], mlir_type, mlir_type),
            PrimitiveOp::ReduceSum => {
                if op.dst_dtype.is_float() {
                    format!("// linalg.reduce {{ arith.addf }} {} : {}", src_refs[0], mlir_type)
                } else {
                    format!("// linalg.reduce {{ arith.addi }} {} : {}", src_refs[0], mlir_type)
                }
            }
            PrimitiveOp::ReduceMax => {
                if op.dst_dtype.is_float() {
                    format!("// linalg.reduce {{ arith.maximumf }} {} : {}", src_refs[0], mlir_type)
                } else if op.dst_dtype.is_signed_int() {
                    format!("// linalg.reduce {{ arith.maxsi }} {} : {}", src_refs[0], mlir_type)
                } else {
                    format!("// linalg.reduce {{ arith.maxui }} {} : {}", src_refs[0], mlir_type)
                }
            }
        };

        writeln!(out, "  %v{} = {}", i, mlir_op).unwrap();
    }

    writeln!(out, "  return").unwrap();
    writeln!(out, "}}").unwrap();

    out
}

fn mlir_element_type(dtype: DType) -> &'static str {
    match dtype {
        DType::Bool => "i1",
        DType::Int8 => "i8",
        DType::Int16 => "i16",
        DType::Int32 => "i32",
        DType::Int64 => "i64",
        DType::UInt8 => "ui8",
        DType::UInt16 => "ui16",
        DType::UInt32 => "ui32",
        DType::UInt64 => "ui64",
        DType::Float16 => "f16",
        DType::BFloat16 => "bf16",
        DType::Float32 => "f32",
        DType::Float64 => "f64",
        // MXFP types map to i8 in MLIR (raw byte storage).
        // Dequantization is expressed as explicit MLIR ops.
        DType::MxFP8 | DType::MxFP4 => "i8",
    }
}

fn mlir_src_ref(src: &FusedSrc) -> String {
    match src {
        FusedSrc::Buf(idx) => format!("%buf{}", idx),
        FusedSrc::Op(idx) => format!("%v{}", idx),
        FusedSrc::Const { val, dtype } => {
            let ty = mlir_element_type(*dtype);
            if dtype.is_float() {
                format!("{}({} : {})", ty, val, ty)
            } else {
                format!("{}({} : {})", ty, *val as i64, ty)
            }
        }
    }
}
