use crate::PyToken;
use std::sync::atomic::{AtomicU64, Ordering as AtomicOrdering};

use super::RuntimeState;
use crate::{alloc_string, dec_ref_bits, init_atomic_bits, MoltObject};

pub(crate) struct InternedNames {
    pub(crate) bases_name: AtomicU64,
    pub(crate) mro_name: AtomicU64,
    pub(crate) get_name: AtomicU64,
    pub(crate) set_name: AtomicU64,
    pub(crate) delete_name: AtomicU64,
    pub(crate) set_name_method: AtomicU64,
    pub(crate) getattr_name: AtomicU64,
    pub(crate) getattribute_name: AtomicU64,
    pub(crate) call_name: AtomicU64,
    pub(crate) init_name: AtomicU64,
    pub(crate) new_name: AtomicU64,
    pub(crate) enter_name: AtomicU64,
    pub(crate) exit_name: AtomicU64,
    pub(crate) setattr_name: AtomicU64,
    pub(crate) delattr_name: AtomicU64,
    pub(crate) write_name: AtomicU64,
    pub(crate) flush_name: AtomicU64,
    pub(crate) sys_name: AtomicU64,
    pub(crate) stdout_name: AtomicU64,
    pub(crate) modules_name: AtomicU64,
    pub(crate) all_name: AtomicU64,
    pub(crate) fspath_name: AtomicU64,
    pub(crate) dict_name: AtomicU64,
    pub(crate) molt_dict_data_name: AtomicU64,
    pub(crate) class_name: AtomicU64,
    pub(crate) annotations_name: AtomicU64,
    pub(crate) annotate_name: AtomicU64,
    pub(crate) field_offsets_name: AtomicU64,
    pub(crate) molt_layout_size: AtomicU64,
    pub(crate) float_name: AtomicU64,
    pub(crate) index_name: AtomicU64,
    pub(crate) int_name: AtomicU64,
    pub(crate) round_name: AtomicU64,
    pub(crate) trunc_name: AtomicU64,
    pub(crate) repr_name: AtomicU64,
    pub(crate) str_name: AtomicU64,
    pub(crate) format_name: AtomicU64,
    pub(crate) qualname_name: AtomicU64,
    pub(crate) name_name: AtomicU64,
    pub(crate) f_lasti_name: AtomicU64,
    pub(crate) f_code_name: AtomicU64,
    pub(crate) f_lineno_name: AtomicU64,
    pub(crate) tb_frame_name: AtomicU64,
    pub(crate) tb_lineno_name: AtomicU64,
    pub(crate) tb_next_name: AtomicU64,
    pub(crate) molt_arg_names: AtomicU64,
    pub(crate) molt_posonly: AtomicU64,
    pub(crate) molt_kwonly_names: AtomicU64,
    pub(crate) molt_vararg: AtomicU64,
    pub(crate) molt_varkw: AtomicU64,
    pub(crate) molt_closure_size: AtomicU64,
    pub(crate) molt_is_coroutine: AtomicU64,
    pub(crate) molt_is_generator: AtomicU64,
    pub(crate) molt_bind_kind: AtomicU64,
    pub(crate) defaults_name: AtomicU64,
    pub(crate) kwdefaults_name: AtomicU64,
    pub(crate) lt_name: AtomicU64,
    pub(crate) le_name: AtomicU64,
    pub(crate) gt_name: AtomicU64,
    pub(crate) ge_name: AtomicU64,
    pub(crate) eq_name: AtomicU64,
    pub(crate) ne_name: AtomicU64,
    pub(crate) add_name: AtomicU64,
    pub(crate) radd_name: AtomicU64,
    pub(crate) mul_name: AtomicU64,
    pub(crate) rmul_name: AtomicU64,
    pub(crate) sub_name: AtomicU64,
    pub(crate) rsub_name: AtomicU64,
    pub(crate) truediv_name: AtomicU64,
    pub(crate) rtruediv_name: AtomicU64,
    pub(crate) floordiv_name: AtomicU64,
    pub(crate) rfloordiv_name: AtomicU64,
    pub(crate) or_name: AtomicU64,
    pub(crate) ror_name: AtomicU64,
    pub(crate) and_name: AtomicU64,
    pub(crate) rand_name: AtomicU64,
    pub(crate) xor_name: AtomicU64,
    pub(crate) rxor_name: AtomicU64,
    pub(crate) iadd_name: AtomicU64,
    pub(crate) isub_name: AtomicU64,
    pub(crate) ior_name: AtomicU64,
    pub(crate) iand_name: AtomicU64,
    pub(crate) ixor_name: AtomicU64,
}

impl InternedNames {
    pub(crate) fn new() -> Self {
        Self {
            bases_name: AtomicU64::new(0),
            mro_name: AtomicU64::new(0),
            get_name: AtomicU64::new(0),
            set_name: AtomicU64::new(0),
            delete_name: AtomicU64::new(0),
            set_name_method: AtomicU64::new(0),
            getattr_name: AtomicU64::new(0),
            getattribute_name: AtomicU64::new(0),
            call_name: AtomicU64::new(0),
            init_name: AtomicU64::new(0),
            new_name: AtomicU64::new(0),
            enter_name: AtomicU64::new(0),
            exit_name: AtomicU64::new(0),
            setattr_name: AtomicU64::new(0),
            delattr_name: AtomicU64::new(0),
            write_name: AtomicU64::new(0),
            flush_name: AtomicU64::new(0),
            sys_name: AtomicU64::new(0),
            stdout_name: AtomicU64::new(0),
            modules_name: AtomicU64::new(0),
            all_name: AtomicU64::new(0),
            fspath_name: AtomicU64::new(0),
            dict_name: AtomicU64::new(0),
            molt_dict_data_name: AtomicU64::new(0),
            class_name: AtomicU64::new(0),
            annotations_name: AtomicU64::new(0),
            annotate_name: AtomicU64::new(0),
            field_offsets_name: AtomicU64::new(0),
            molt_layout_size: AtomicU64::new(0),
            float_name: AtomicU64::new(0),
            index_name: AtomicU64::new(0),
            int_name: AtomicU64::new(0),
            round_name: AtomicU64::new(0),
            trunc_name: AtomicU64::new(0),
            repr_name: AtomicU64::new(0),
            str_name: AtomicU64::new(0),
            format_name: AtomicU64::new(0),
            qualname_name: AtomicU64::new(0),
            name_name: AtomicU64::new(0),
            f_lasti_name: AtomicU64::new(0),
            f_code_name: AtomicU64::new(0),
            f_lineno_name: AtomicU64::new(0),
            tb_frame_name: AtomicU64::new(0),
            tb_lineno_name: AtomicU64::new(0),
            tb_next_name: AtomicU64::new(0),
            molt_arg_names: AtomicU64::new(0),
            molt_posonly: AtomicU64::new(0),
            molt_kwonly_names: AtomicU64::new(0),
            molt_vararg: AtomicU64::new(0),
            molt_varkw: AtomicU64::new(0),
            molt_closure_size: AtomicU64::new(0),
            molt_is_coroutine: AtomicU64::new(0),
            molt_is_generator: AtomicU64::new(0),
            molt_bind_kind: AtomicU64::new(0),
            defaults_name: AtomicU64::new(0),
            kwdefaults_name: AtomicU64::new(0),
            lt_name: AtomicU64::new(0),
            le_name: AtomicU64::new(0),
            gt_name: AtomicU64::new(0),
            ge_name: AtomicU64::new(0),
            eq_name: AtomicU64::new(0),
            ne_name: AtomicU64::new(0),
            add_name: AtomicU64::new(0),
            radd_name: AtomicU64::new(0),
            mul_name: AtomicU64::new(0),
            rmul_name: AtomicU64::new(0),
            sub_name: AtomicU64::new(0),
            rsub_name: AtomicU64::new(0),
            truediv_name: AtomicU64::new(0),
            rtruediv_name: AtomicU64::new(0),
            floordiv_name: AtomicU64::new(0),
            rfloordiv_name: AtomicU64::new(0),
            or_name: AtomicU64::new(0),
            ror_name: AtomicU64::new(0),
            and_name: AtomicU64::new(0),
            rand_name: AtomicU64::new(0),
            xor_name: AtomicU64::new(0),
            rxor_name: AtomicU64::new(0),
            iadd_name: AtomicU64::new(0),
            isub_name: AtomicU64::new(0),
            ior_name: AtomicU64::new(0),
            iand_name: AtomicU64::new(0),
            ixor_name: AtomicU64::new(0),
        }
    }
}

pub(crate) struct MethodCache {
    pub(crate) dict_keys: AtomicU64,
    pub(crate) dict_values: AtomicU64,
    pub(crate) dict_items: AtomicU64,
    pub(crate) dict_get: AtomicU64,
    pub(crate) dict_pop: AtomicU64,
    pub(crate) dict_clear: AtomicU64,
    pub(crate) dict_copy: AtomicU64,
    pub(crate) dict_popitem: AtomicU64,
    pub(crate) dict_setdefault: AtomicU64,
    pub(crate) dict_update: AtomicU64,
    pub(crate) dict_fromkeys: AtomicU64,
    pub(crate) dict_getitem: AtomicU64,
    pub(crate) dict_setitem: AtomicU64,
    pub(crate) dict_delitem: AtomicU64,
    pub(crate) dict_iter: AtomicU64,
    pub(crate) dict_len: AtomicU64,
    pub(crate) dict_contains: AtomicU64,
    pub(crate) dict_reversed: AtomicU64,
    pub(crate) set_add: AtomicU64,
    pub(crate) set_discard: AtomicU64,
    pub(crate) set_remove: AtomicU64,
    pub(crate) set_pop: AtomicU64,
    pub(crate) set_clear: AtomicU64,
    pub(crate) set_update: AtomicU64,
    pub(crate) set_union: AtomicU64,
    pub(crate) set_intersection: AtomicU64,
    pub(crate) set_difference: AtomicU64,
    pub(crate) set_symdiff: AtomicU64,
    pub(crate) set_intersection_update: AtomicU64,
    pub(crate) set_difference_update: AtomicU64,
    pub(crate) set_symdiff_update: AtomicU64,
    pub(crate) set_isdisjoint: AtomicU64,
    pub(crate) set_issubset: AtomicU64,
    pub(crate) set_issuperset: AtomicU64,
    pub(crate) set_copy: AtomicU64,
    pub(crate) set_iter: AtomicU64,
    pub(crate) set_len: AtomicU64,
    pub(crate) set_contains: AtomicU64,
    pub(crate) frozenset_union: AtomicU64,
    pub(crate) frozenset_intersection: AtomicU64,
    pub(crate) frozenset_difference: AtomicU64,
    pub(crate) frozenset_symdiff: AtomicU64,
    pub(crate) frozenset_isdisjoint: AtomicU64,
    pub(crate) frozenset_issubset: AtomicU64,
    pub(crate) frozenset_issuperset: AtomicU64,
    pub(crate) frozenset_copy: AtomicU64,
    pub(crate) frozenset_iter: AtomicU64,
    pub(crate) frozenset_len: AtomicU64,
    pub(crate) frozenset_contains: AtomicU64,
    pub(crate) list_append: AtomicU64,
    pub(crate) list_extend: AtomicU64,
    pub(crate) list_insert: AtomicU64,
    pub(crate) list_remove: AtomicU64,
    pub(crate) list_pop: AtomicU64,
    pub(crate) list_clear: AtomicU64,
    pub(crate) list_init: AtomicU64,
    pub(crate) list_copy: AtomicU64,
    pub(crate) list_reverse: AtomicU64,
    pub(crate) list_count: AtomicU64,
    pub(crate) list_index: AtomicU64,
    pub(crate) list_sort: AtomicU64,
    pub(crate) list_add: AtomicU64,
    pub(crate) list_mul: AtomicU64,
    pub(crate) list_rmul: AtomicU64,
    pub(crate) list_iadd: AtomicU64,
    pub(crate) list_imul: AtomicU64,
    pub(crate) list_getitem: AtomicU64,
    pub(crate) list_setitem: AtomicU64,
    pub(crate) list_delitem: AtomicU64,
    pub(crate) list_iter: AtomicU64,
    pub(crate) list_len: AtomicU64,
    pub(crate) list_contains: AtomicU64,
    pub(crate) list_reversed: AtomicU64,
    pub(crate) str_iter: AtomicU64,
    pub(crate) str_len: AtomicU64,
    pub(crate) str_contains: AtomicU64,
    pub(crate) str_count: AtomicU64,
    pub(crate) str_startswith: AtomicU64,
    pub(crate) str_endswith: AtomicU64,
    pub(crate) str_find: AtomicU64,
    pub(crate) str_rfind: AtomicU64,
    pub(crate) str_format: AtomicU64,
    pub(crate) str_upper: AtomicU64,
    pub(crate) str_lower: AtomicU64,
    pub(crate) str_strip: AtomicU64,
    pub(crate) str_lstrip: AtomicU64,
    pub(crate) str_rstrip: AtomicU64,
    pub(crate) str_split: AtomicU64,
    pub(crate) str_rsplit: AtomicU64,
    pub(crate) str_splitlines: AtomicU64,
    pub(crate) str_partition: AtomicU64,
    pub(crate) str_rpartition: AtomicU64,
    pub(crate) str_replace: AtomicU64,
    pub(crate) str_join: AtomicU64,
    pub(crate) str_encode: AtomicU64,
    pub(crate) bytes_iter: AtomicU64,
    pub(crate) bytes_len: AtomicU64,
    pub(crate) bytes_contains: AtomicU64,
    pub(crate) bytes_count: AtomicU64,
    pub(crate) bytes_startswith: AtomicU64,
    pub(crate) bytes_endswith: AtomicU64,
    pub(crate) bytes_find: AtomicU64,
    pub(crate) bytes_rfind: AtomicU64,
    pub(crate) bytes_split: AtomicU64,
    pub(crate) bytes_rsplit: AtomicU64,
    pub(crate) bytes_reversed: AtomicU64,
    pub(crate) bytes_strip: AtomicU64,
    pub(crate) bytes_lstrip: AtomicU64,
    pub(crate) bytes_rstrip: AtomicU64,
    pub(crate) bytes_splitlines: AtomicU64,
    pub(crate) bytes_partition: AtomicU64,
    pub(crate) bytes_rpartition: AtomicU64,
    pub(crate) bytes_replace: AtomicU64,
    pub(crate) bytes_decode: AtomicU64,
    pub(crate) bytearray_iter: AtomicU64,
    pub(crate) bytearray_len: AtomicU64,
    pub(crate) bytearray_contains: AtomicU64,
    pub(crate) bytearray_count: AtomicU64,
    pub(crate) bytearray_startswith: AtomicU64,
    pub(crate) bytearray_endswith: AtomicU64,
    pub(crate) bytearray_find: AtomicU64,
    pub(crate) bytearray_rfind: AtomicU64,
    pub(crate) bytearray_split: AtomicU64,
    pub(crate) bytearray_rsplit: AtomicU64,
    pub(crate) bytearray_reversed: AtomicU64,
    pub(crate) bytearray_strip: AtomicU64,
    pub(crate) bytearray_lstrip: AtomicU64,
    pub(crate) bytearray_rstrip: AtomicU64,
    pub(crate) bytearray_splitlines: AtomicU64,
    pub(crate) bytearray_partition: AtomicU64,
    pub(crate) bytearray_rpartition: AtomicU64,
    pub(crate) bytearray_replace: AtomicU64,
    pub(crate) bytearray_decode: AtomicU64,
    pub(crate) bytearray_setitem: AtomicU64,
    pub(crate) bytearray_delitem: AtomicU64,
    pub(crate) slice_indices: AtomicU64,
    pub(crate) slice_hash: AtomicU64,
    pub(crate) slice_eq: AtomicU64,
    pub(crate) slice_reduce: AtomicU64,
    pub(crate) slice_reduce_ex: AtomicU64,
    pub(crate) memoryview_tobytes: AtomicU64,
    pub(crate) memoryview_cast: AtomicU64,
    pub(crate) memoryview_setitem: AtomicU64,
    pub(crate) memoryview_delitem: AtomicU64,
    pub(crate) file_read: AtomicU64,
    pub(crate) file_readline: AtomicU64,
    pub(crate) file_readlines: AtomicU64,
    pub(crate) file_readinto: AtomicU64,
    pub(crate) file_write: AtomicU64,
    pub(crate) file_writelines: AtomicU64,
    pub(crate) file_flush: AtomicU64,
    pub(crate) file_close: AtomicU64,
    pub(crate) file_detach: AtomicU64,
    pub(crate) file_reconfigure: AtomicU64,
    pub(crate) file_seek: AtomicU64,
    pub(crate) file_tell: AtomicU64,
    pub(crate) file_fileno: AtomicU64,
    pub(crate) file_truncate: AtomicU64,
    pub(crate) file_readable: AtomicU64,
    pub(crate) file_writable: AtomicU64,
    pub(crate) file_seekable: AtomicU64,
    pub(crate) file_isatty: AtomicU64,
    pub(crate) file_iter: AtomicU64,
    pub(crate) file_next: AtomicU64,
    pub(crate) file_enter: AtomicU64,
    pub(crate) file_exit: AtomicU64,
    pub(crate) asyncgen_aiter: AtomicU64,
    pub(crate) asyncgen_anext: AtomicU64,
    pub(crate) asyncgen_asend: AtomicU64,
    pub(crate) asyncgen_athrow: AtomicU64,
    pub(crate) asyncgen_aclose: AtomicU64,
    pub(crate) object_getattribute: AtomicU64,
    pub(crate) object_init: AtomicU64,
    pub(crate) object_setattr: AtomicU64,
    pub(crate) object_delattr: AtomicU64,
    pub(crate) object_eq: AtomicU64,
    pub(crate) object_ne: AtomicU64,
    pub(crate) exception_init: AtomicU64,
    pub(crate) exception_new: AtomicU64,
    pub(crate) generic_alias_class_getitem: AtomicU64,
}

impl MethodCache {
    pub(crate) fn new() -> Self {
        Self {
            dict_keys: AtomicU64::new(0),
            dict_values: AtomicU64::new(0),
            dict_items: AtomicU64::new(0),
            dict_get: AtomicU64::new(0),
            dict_pop: AtomicU64::new(0),
            dict_clear: AtomicU64::new(0),
            dict_copy: AtomicU64::new(0),
            dict_popitem: AtomicU64::new(0),
            dict_setdefault: AtomicU64::new(0),
            dict_update: AtomicU64::new(0),
            dict_fromkeys: AtomicU64::new(0),
            dict_getitem: AtomicU64::new(0),
            dict_setitem: AtomicU64::new(0),
            dict_delitem: AtomicU64::new(0),
            dict_iter: AtomicU64::new(0),
            dict_len: AtomicU64::new(0),
            dict_contains: AtomicU64::new(0),
            dict_reversed: AtomicU64::new(0),
            set_add: AtomicU64::new(0),
            set_discard: AtomicU64::new(0),
            set_remove: AtomicU64::new(0),
            set_pop: AtomicU64::new(0),
            set_clear: AtomicU64::new(0),
            set_update: AtomicU64::new(0),
            set_union: AtomicU64::new(0),
            set_intersection: AtomicU64::new(0),
            set_difference: AtomicU64::new(0),
            set_symdiff: AtomicU64::new(0),
            set_intersection_update: AtomicU64::new(0),
            set_difference_update: AtomicU64::new(0),
            set_symdiff_update: AtomicU64::new(0),
            set_isdisjoint: AtomicU64::new(0),
            set_issubset: AtomicU64::new(0),
            set_issuperset: AtomicU64::new(0),
            set_copy: AtomicU64::new(0),
            set_iter: AtomicU64::new(0),
            set_len: AtomicU64::new(0),
            set_contains: AtomicU64::new(0),
            frozenset_union: AtomicU64::new(0),
            frozenset_intersection: AtomicU64::new(0),
            frozenset_difference: AtomicU64::new(0),
            frozenset_symdiff: AtomicU64::new(0),
            frozenset_isdisjoint: AtomicU64::new(0),
            frozenset_issubset: AtomicU64::new(0),
            frozenset_issuperset: AtomicU64::new(0),
            frozenset_copy: AtomicU64::new(0),
            frozenset_iter: AtomicU64::new(0),
            frozenset_len: AtomicU64::new(0),
            frozenset_contains: AtomicU64::new(0),
            list_append: AtomicU64::new(0),
            list_extend: AtomicU64::new(0),
            list_insert: AtomicU64::new(0),
            list_remove: AtomicU64::new(0),
            list_pop: AtomicU64::new(0),
            list_clear: AtomicU64::new(0),
            list_init: AtomicU64::new(0),
            list_copy: AtomicU64::new(0),
            list_reverse: AtomicU64::new(0),
            list_count: AtomicU64::new(0),
            list_index: AtomicU64::new(0),
            list_sort: AtomicU64::new(0),
            list_add: AtomicU64::new(0),
            list_mul: AtomicU64::new(0),
            list_rmul: AtomicU64::new(0),
            list_iadd: AtomicU64::new(0),
            list_imul: AtomicU64::new(0),
            list_getitem: AtomicU64::new(0),
            list_setitem: AtomicU64::new(0),
            list_delitem: AtomicU64::new(0),
            list_iter: AtomicU64::new(0),
            list_len: AtomicU64::new(0),
            list_contains: AtomicU64::new(0),
            list_reversed: AtomicU64::new(0),
            str_iter: AtomicU64::new(0),
            str_len: AtomicU64::new(0),
            str_contains: AtomicU64::new(0),
            str_count: AtomicU64::new(0),
            str_startswith: AtomicU64::new(0),
            str_endswith: AtomicU64::new(0),
            str_find: AtomicU64::new(0),
            str_rfind: AtomicU64::new(0),
            str_format: AtomicU64::new(0),
            str_upper: AtomicU64::new(0),
            str_lower: AtomicU64::new(0),
            str_strip: AtomicU64::new(0),
            str_lstrip: AtomicU64::new(0),
            str_rstrip: AtomicU64::new(0),
            str_split: AtomicU64::new(0),
            str_rsplit: AtomicU64::new(0),
            str_splitlines: AtomicU64::new(0),
            str_partition: AtomicU64::new(0),
            str_rpartition: AtomicU64::new(0),
            str_replace: AtomicU64::new(0),
            str_join: AtomicU64::new(0),
            str_encode: AtomicU64::new(0),
            bytes_iter: AtomicU64::new(0),
            bytes_len: AtomicU64::new(0),
            bytes_contains: AtomicU64::new(0),
            bytes_count: AtomicU64::new(0),
            bytes_startswith: AtomicU64::new(0),
            bytes_endswith: AtomicU64::new(0),
            bytes_find: AtomicU64::new(0),
            bytes_rfind: AtomicU64::new(0),
            bytes_split: AtomicU64::new(0),
            bytes_rsplit: AtomicU64::new(0),
            bytes_reversed: AtomicU64::new(0),
            bytes_strip: AtomicU64::new(0),
            bytes_lstrip: AtomicU64::new(0),
            bytes_rstrip: AtomicU64::new(0),
            bytes_splitlines: AtomicU64::new(0),
            bytes_partition: AtomicU64::new(0),
            bytes_rpartition: AtomicU64::new(0),
            bytes_replace: AtomicU64::new(0),
            bytes_decode: AtomicU64::new(0),
            bytearray_iter: AtomicU64::new(0),
            bytearray_len: AtomicU64::new(0),
            bytearray_contains: AtomicU64::new(0),
            bytearray_count: AtomicU64::new(0),
            bytearray_startswith: AtomicU64::new(0),
            bytearray_endswith: AtomicU64::new(0),
            bytearray_find: AtomicU64::new(0),
            bytearray_rfind: AtomicU64::new(0),
            bytearray_split: AtomicU64::new(0),
            bytearray_rsplit: AtomicU64::new(0),
            bytearray_reversed: AtomicU64::new(0),
            bytearray_strip: AtomicU64::new(0),
            bytearray_lstrip: AtomicU64::new(0),
            bytearray_rstrip: AtomicU64::new(0),
            bytearray_splitlines: AtomicU64::new(0),
            bytearray_partition: AtomicU64::new(0),
            bytearray_rpartition: AtomicU64::new(0),
            bytearray_replace: AtomicU64::new(0),
            bytearray_decode: AtomicU64::new(0),
            bytearray_setitem: AtomicU64::new(0),
            bytearray_delitem: AtomicU64::new(0),
            slice_indices: AtomicU64::new(0),
            slice_hash: AtomicU64::new(0),
            slice_eq: AtomicU64::new(0),
            slice_reduce: AtomicU64::new(0),
            slice_reduce_ex: AtomicU64::new(0),
            memoryview_tobytes: AtomicU64::new(0),
            memoryview_cast: AtomicU64::new(0),
            memoryview_setitem: AtomicU64::new(0),
            memoryview_delitem: AtomicU64::new(0),
            file_read: AtomicU64::new(0),
            file_readline: AtomicU64::new(0),
            file_readlines: AtomicU64::new(0),
            file_readinto: AtomicU64::new(0),
            file_write: AtomicU64::new(0),
            file_writelines: AtomicU64::new(0),
            file_flush: AtomicU64::new(0),
            file_close: AtomicU64::new(0),
            file_detach: AtomicU64::new(0),
            file_reconfigure: AtomicU64::new(0),
            file_seek: AtomicU64::new(0),
            file_tell: AtomicU64::new(0),
            file_fileno: AtomicU64::new(0),
            file_truncate: AtomicU64::new(0),
            file_readable: AtomicU64::new(0),
            file_writable: AtomicU64::new(0),
            file_seekable: AtomicU64::new(0),
            file_isatty: AtomicU64::new(0),
            file_iter: AtomicU64::new(0),
            file_next: AtomicU64::new(0),
            file_enter: AtomicU64::new(0),
            file_exit: AtomicU64::new(0),
            asyncgen_aiter: AtomicU64::new(0),
            asyncgen_anext: AtomicU64::new(0),
            asyncgen_asend: AtomicU64::new(0),
            asyncgen_athrow: AtomicU64::new(0),
            asyncgen_aclose: AtomicU64::new(0),
            object_getattribute: AtomicU64::new(0),
            object_init: AtomicU64::new(0),
            object_setattr: AtomicU64::new(0),
            object_delattr: AtomicU64::new(0),
            object_eq: AtomicU64::new(0),
            object_ne: AtomicU64::new(0),
            exception_init: AtomicU64::new(0),
            exception_new: AtomicU64::new(0),
            generic_alias_class_getitem: AtomicU64::new(0),
        }
    }
}

pub(crate) fn intern_static_name(_py: &PyToken<'_>, slot: &AtomicU64, name: &'static [u8]) -> u64 {
    init_atomic_bits(_py, slot, || {
        let ptr = alloc_string(_py, name);
        if ptr.is_null() {
            MoltObject::none().bits()
        } else {
            MoltObject::from_ptr(ptr).bits()
        }
    })
}

pub(crate) fn clear_atomic_bits(_py: &PyToken<'_>, slot: &AtomicU64) {
    crate::gil_assert();
    let bits = slot.swap(0, AtomicOrdering::AcqRel);
    if bits != 0 {
        dec_ref_bits(_py, bits);
    }
}

pub(crate) fn clear_atomic_slots(_py: &PyToken<'_>, slots: &[&AtomicU64]) {
    crate::gil_assert();
    for slot in slots {
        clear_atomic_bits(_py, slot);
    }
}

pub(crate) fn clear_method_cache(_py: &PyToken<'_>, state: &RuntimeState) {
    crate::gil_assert();
    let slots = method_cache_slots(state);
    clear_atomic_slots(_py, &slots);
}

fn method_cache_slots(state: &RuntimeState) -> Vec<&AtomicU64> {
    vec![
        &state.method_cache.dict_keys,
        &state.method_cache.dict_values,
        &state.method_cache.dict_items,
        &state.method_cache.dict_get,
        &state.method_cache.dict_pop,
        &state.method_cache.dict_clear,
        &state.method_cache.dict_copy,
        &state.method_cache.dict_popitem,
        &state.method_cache.dict_setdefault,
        &state.method_cache.dict_update,
        &state.method_cache.dict_fromkeys,
        &state.method_cache.dict_getitem,
        &state.method_cache.dict_setitem,
        &state.method_cache.dict_delitem,
        &state.method_cache.dict_iter,
        &state.method_cache.dict_len,
        &state.method_cache.dict_contains,
        &state.method_cache.dict_reversed,
        &state.method_cache.set_add,
        &state.method_cache.set_discard,
        &state.method_cache.set_remove,
        &state.method_cache.set_pop,
        &state.method_cache.set_iter,
        &state.method_cache.set_len,
        &state.method_cache.set_contains,
        &state.method_cache.frozenset_iter,
        &state.method_cache.frozenset_len,
        &state.method_cache.frozenset_contains,
        &state.method_cache.list_append,
        &state.method_cache.list_extend,
        &state.method_cache.list_insert,
        &state.method_cache.list_remove,
        &state.method_cache.list_pop,
        &state.method_cache.list_clear,
        &state.method_cache.list_copy,
        &state.method_cache.list_reverse,
        &state.method_cache.list_count,
        &state.method_cache.list_index,
        &state.method_cache.list_sort,
        &state.method_cache.list_getitem,
        &state.method_cache.list_setitem,
        &state.method_cache.list_delitem,
        &state.method_cache.list_iter,
        &state.method_cache.list_len,
        &state.method_cache.list_contains,
        &state.method_cache.list_reversed,
        &state.method_cache.str_iter,
        &state.method_cache.str_len,
        &state.method_cache.str_contains,
        &state.method_cache.str_count,
        &state.method_cache.str_startswith,
        &state.method_cache.str_endswith,
        &state.method_cache.str_upper,
        &state.method_cache.str_lower,
        &state.method_cache.str_strip,
        &state.method_cache.str_lstrip,
        &state.method_cache.str_rstrip,
        &state.method_cache.str_split,
        &state.method_cache.str_rsplit,
        &state.method_cache.str_splitlines,
        &state.method_cache.str_partition,
        &state.method_cache.str_rpartition,
        &state.method_cache.str_replace,
        &state.method_cache.str_join,
        &state.method_cache.str_encode,
        &state.method_cache.bytes_iter,
        &state.method_cache.bytes_len,
        &state.method_cache.bytes_contains,
        &state.method_cache.bytes_count,
        &state.method_cache.bytes_startswith,
        &state.method_cache.bytes_endswith,
        &state.method_cache.bytes_find,
        &state.method_cache.bytes_rfind,
        &state.method_cache.bytes_split,
        &state.method_cache.bytes_rsplit,
        &state.method_cache.bytes_reversed,
        &state.method_cache.bytes_strip,
        &state.method_cache.bytes_lstrip,
        &state.method_cache.bytes_rstrip,
        &state.method_cache.bytes_splitlines,
        &state.method_cache.bytes_partition,
        &state.method_cache.bytes_rpartition,
        &state.method_cache.bytes_replace,
        &state.method_cache.bytes_decode,
        &state.method_cache.bytearray_iter,
        &state.method_cache.bytearray_len,
        &state.method_cache.bytearray_contains,
        &state.method_cache.bytearray_count,
        &state.method_cache.bytearray_startswith,
        &state.method_cache.bytearray_endswith,
        &state.method_cache.bytearray_find,
        &state.method_cache.bytearray_rfind,
        &state.method_cache.bytearray_split,
        &state.method_cache.bytearray_rsplit,
        &state.method_cache.bytearray_reversed,
        &state.method_cache.bytearray_strip,
        &state.method_cache.bytearray_lstrip,
        &state.method_cache.bytearray_rstrip,
        &state.method_cache.bytearray_splitlines,
        &state.method_cache.bytearray_partition,
        &state.method_cache.bytearray_rpartition,
        &state.method_cache.bytearray_replace,
        &state.method_cache.bytearray_decode,
        &state.method_cache.bytearray_setitem,
        &state.method_cache.bytearray_delitem,
        &state.method_cache.slice_indices,
        &state.method_cache.slice_hash,
        &state.method_cache.slice_eq,
        &state.method_cache.slice_reduce,
        &state.method_cache.slice_reduce_ex,
        &state.method_cache.memoryview_tobytes,
        &state.method_cache.memoryview_cast,
        &state.method_cache.memoryview_setitem,
        &state.method_cache.memoryview_delitem,
        &state.method_cache.file_read,
        &state.method_cache.file_readline,
        &state.method_cache.file_readlines,
        &state.method_cache.file_readinto,
        &state.method_cache.file_write,
        &state.method_cache.file_writelines,
        &state.method_cache.file_flush,
        &state.method_cache.file_close,
        &state.method_cache.file_detach,
        &state.method_cache.file_reconfigure,
        &state.method_cache.file_seek,
        &state.method_cache.file_tell,
        &state.method_cache.file_fileno,
        &state.method_cache.file_truncate,
        &state.method_cache.file_readable,
        &state.method_cache.file_writable,
        &state.method_cache.file_seekable,
        &state.method_cache.file_isatty,
        &state.method_cache.file_iter,
        &state.method_cache.file_next,
        &state.method_cache.file_enter,
        &state.method_cache.file_exit,
        &state.method_cache.asyncgen_aiter,
        &state.method_cache.asyncgen_anext,
        &state.method_cache.asyncgen_asend,
        &state.method_cache.asyncgen_athrow,
        &state.method_cache.asyncgen_aclose,
        &state.method_cache.object_getattribute,
        &state.method_cache.object_setattr,
        &state.method_cache.object_delattr,
        &state.method_cache.object_eq,
        &state.method_cache.object_ne,
        &state.method_cache.exception_init,
        &state.method_cache.exception_new,
    ]
}
