// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_ast")]
        "molt_ast_parse" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ast_parse",
            crate::molt_ast_parse as *const (),
        )),
        #[cfg(feature = "stdlib_ast")]
        "molt_ast_walk" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ast_walk",
            crate::molt_ast_walk as *const (),
        )),
        #[cfg(feature = "stdlib_ast")]
        "molt_ast_get_docstring" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ast_get_docstring",
            crate::molt_ast_get_docstring as *const (),
        )),
        #[cfg(feature = "stdlib_ast")]
        "molt_ast_iter_fields" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ast_iter_fields",
            crate::molt_ast_iter_fields as *const (),
        )),
        #[cfg(feature = "stdlib_ast")]
        "molt_ast_iter_child_nodes" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ast_iter_child_nodes",
            crate::molt_ast_iter_child_nodes as *const (),
        )),
        _ => None,
    }
}
