// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_contains",
            crate::molt_chainmap_contains as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_delitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_delitem",
            crate::molt_chainmap_delitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_drop",
            crate::molt_chainmap_drop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_getitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_getitem",
            crate::molt_chainmap_getitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_keys" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_keys",
            crate::molt_chainmap_keys as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_len" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_len",
            crate::molt_chainmap_len as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_maps" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_maps",
            crate::molt_chainmap_maps as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_new",
            crate::molt_chainmap_new as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_new_child" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_new_child",
            crate::molt_chainmap_new_child as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_parents" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_parents",
            crate::molt_chainmap_parents as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_chainmap_setitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_chainmap_setitem",
            crate::molt_chainmap_setitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_clear" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_clear",
            crate::molt_ordereddict_clear as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_contains",
            crate::molt_ordereddict_contains as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_copy" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_copy",
            crate::molt_ordereddict_copy as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_delitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_delitem",
            crate::molt_ordereddict_delitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_drop",
            crate::molt_ordereddict_drop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_from_pairs" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_from_pairs",
            crate::molt_ordereddict_from_pairs as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_getitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_getitem",
            crate::molt_ordereddict_getitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_items" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_items",
            crate::molt_ordereddict_items as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_keys" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_keys",
            crate::molt_ordereddict_keys as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_len" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_len",
            crate::molt_ordereddict_len as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_move_to_end" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_move_to_end",
            crate::molt_ordereddict_move_to_end as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_new",
            crate::molt_ordereddict_new as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_pop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_pop",
            crate::molt_ordereddict_pop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_popitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_popitem",
            crate::molt_ordereddict_popitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_setitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_setitem",
            crate::molt_ordereddict_setitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_update" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_update",
            crate::molt_ordereddict_update as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_ordereddict_values" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_ordereddict_values",
            crate::molt_ordereddict_values as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_add" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_add",
            crate::molt_counter_add as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_and" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_and",
            crate::molt_counter_and as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_clear" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_clear",
            crate::molt_counter_clear as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_contains",
            crate::molt_counter_contains as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_copy" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_copy",
            crate::molt_counter_copy as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_delitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_delitem",
            crate::molt_counter_delitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_drop",
            crate::molt_counter_drop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_elements" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_elements",
            crate::molt_counter_elements as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_from_iterable" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_from_iterable",
            crate::molt_counter_from_iterable as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_from_mapping" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_from_mapping",
            crate::molt_counter_from_mapping as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_getitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_getitem",
            crate::molt_counter_getitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_items" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_items",
            crate::molt_counter_items as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_len" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_len",
            crate::molt_counter_len as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_most_common" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_most_common",
            crate::molt_counter_most_common as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_neg" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_neg",
            crate::molt_counter_neg as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_new",
            crate::molt_counter_new as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_or" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_or",
            crate::molt_counter_or as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_pos" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_pos",
            crate::molt_counter_pos as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_pop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_pop",
            crate::molt_counter_pop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_setitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_setitem",
            crate::molt_counter_setitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_sub" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_sub",
            crate::molt_counter_sub as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_subtract" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_subtract",
            crate::molt_counter_subtract as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_total" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_total",
            crate::molt_counter_total as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_counter_update" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_counter_update",
            crate::molt_counter_update as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_defaultdict_copy" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_defaultdict_copy",
            crate::molt_defaultdict_copy as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_defaultdict_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_defaultdict_drop",
            crate::molt_defaultdict_drop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_defaultdict_factory" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_defaultdict_factory",
            crate::molt_defaultdict_factory as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_defaultdict_missing" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_defaultdict_missing",
            crate::molt_defaultdict_missing as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_defaultdict_missing_method" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_defaultdict_missing_method",
            crate::molt_defaultdict_missing_method as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_defaultdict_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_defaultdict_new",
            crate::molt_defaultdict_new as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_append" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_append",
            crate::molt_deque_append as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_appendleft" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_appendleft",
            crate::molt_deque_appendleft as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_clear" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_clear",
            crate::molt_deque_clear as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_contains",
            crate::molt_deque_contains as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_copy" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_copy",
            crate::molt_deque_copy as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_count" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_count",
            crate::molt_deque_count as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_delitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_delitem",
            crate::molt_deque_delitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_drop",
            crate::molt_deque_drop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_extend" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_extend",
            crate::molt_deque_extend as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_extendleft" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_extendleft",
            crate::molt_deque_extendleft as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_from_iterable" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_from_iterable",
            crate::molt_deque_from_iterable as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_getitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_getitem",
            crate::molt_deque_getitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_index" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_index",
            crate::molt_deque_index as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_insert" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_insert",
            crate::molt_deque_insert as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_len" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_len",
            crate::molt_deque_len as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_maxlen" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_maxlen",
            crate::molt_deque_maxlen as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_new",
            crate::molt_deque_new as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_pop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_pop",
            crate::molt_deque_pop as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_popleft" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_popleft",
            crate::molt_deque_popleft as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_remove" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_remove",
            crate::molt_deque_remove as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_reverse" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_reverse",
            crate::molt_deque_reverse as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_rotate" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_rotate",
            crate::molt_deque_rotate as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_deque_setitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_deque_setitem",
            crate::molt_deque_setitem as *const (),
        )),
        #[cfg(feature = "stdlib_collections")]
        "molt_namedtuple_validate_fields" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_namedtuple_validate_fields",
            crate::molt_namedtuple_validate_fields as *const (),
        )),
        _ => None,
    }
}
