// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_all_completed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_all_completed",
            crate::molt_concurrent_all_completed as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_as_completed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_as_completed",
            crate::molt_concurrent_as_completed as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_first_completed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_first_completed",
            crate::molt_concurrent_first_completed as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_first_exception" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_first_exception",
            crate::molt_concurrent_first_exception as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_add_done_callback" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_concurrent_future_add_done_callback",
                crate::molt_concurrent_future_add_done_callback as *const (),
            ))
        }
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_cancel" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_cancel",
            crate::molt_concurrent_future_cancel as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_cancelled" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_cancelled",
            crate::molt_concurrent_future_cancelled as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_done" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_done",
            crate::molt_concurrent_future_done as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_drop",
            crate::molt_concurrent_future_drop as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_exception" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_exception",
            crate::molt_concurrent_future_exception as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_result" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_result",
            crate::molt_concurrent_future_result as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_future_running" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_future_running",
            crate::molt_concurrent_future_running as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_threadpool_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_threadpool_drop",
            crate::molt_concurrent_threadpool_drop as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_threadpool_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_threadpool_new",
            crate::molt_concurrent_threadpool_new as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_threadpool_shutdown" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_threadpool_shutdown",
            crate::molt_concurrent_threadpool_shutdown as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_threadpool_submit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_threadpool_submit",
            crate::molt_concurrent_threadpool_submit as *const (),
        )),
        #[cfg(feature = "stdlib_concurrent")]
        "molt_concurrent_wait" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_concurrent_wait",
            crate::molt_concurrent_wait as *const (),
        )),
        _ => None,
    }
}
