// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_contextvars_types" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_types",
            crate::molt_contextvars_types as *const (),
        )),
        "molt_contextvars_copy_current" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_copy_current",
            crate::molt_contextvars_copy_current as *const (),
        )),
        "molt_contextvars_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_new",
            crate::molt_contextvars_new as *const (),
        )),
        "molt_contextvars_token_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_token_new",
            crate::molt_contextvars_token_new as *const (),
        )),
        "molt_contextvars_missing_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_missing_new",
            crate::molt_contextvars_missing_new as *const (),
        )),
        "molt_contextvars_keys_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_keys_new",
            crate::molt_contextvars_keys_new as *const (),
        )),
        "molt_contextvars_values_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_values_new",
            crate::molt_contextvars_values_new as *const (),
        )),
        "molt_contextvars_items_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_items_new",
            crate::molt_contextvars_items_new as *const (),
        )),
        "molt_contextvars_var_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_var_new",
            crate::molt_contextvars_var_new as *const (),
        )),
        "molt_contextvars_var_get" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_var_get",
            crate::molt_contextvars_var_get as *const (),
        )),
        "molt_contextvars_var_set" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_var_set",
            crate::molt_contextvars_var_set as *const (),
        )),
        "molt_contextvars_var_reset" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_var_reset",
            crate::molt_contextvars_var_reset as *const (),
        )),
        "molt_contextvars_var_hash" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_var_hash",
            crate::molt_contextvars_var_hash as *const (),
        )),
        "molt_contextvars_copy" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_copy",
            crate::molt_contextvars_copy as *const (),
        )),
        "molt_contextvars_len" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_len",
            crate::molt_contextvars_len as *const (),
        )),
        "molt_contextvars_getitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_getitem",
            crate::molt_contextvars_getitem as *const (),
        )),
        "molt_contextvars_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_contains",
            crate::molt_contextvars_contains as *const (),
        )),
        "molt_contextvars_get" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_get",
            crate::molt_contextvars_get as *const (),
        )),
        "molt_contextvars_run" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_run",
            crate::molt_contextvars_run as *const (),
        )),
        "molt_contextvars_keys" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_keys",
            crate::molt_contextvars_keys as *const (),
        )),
        "molt_contextvars_values" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_values",
            crate::molt_contextvars_values as *const (),
        )),
        "molt_contextvars_items" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_items",
            crate::molt_contextvars_items as *const (),
        )),
        "molt_contextvars_iter_self" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_iter_self",
            crate::molt_contextvars_iter_self as *const (),
        )),
        "molt_contextvars_iter_next" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_iter_next",
            crate::molt_contextvars_iter_next as *const (),
        )),
        "molt_contextvars_eq" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_eq",
            crate::molt_contextvars_eq as *const (),
        )),
        "molt_contextvars_ne" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_ne",
            crate::molt_contextvars_ne as *const (),
        )),
        "molt_contextvars_property" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_property",
            crate::molt_contextvars_property as *const (),
        )),
        "molt_contextvars_token_enter" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_token_enter",
            crate::molt_contextvars_token_enter as *const (),
        )),
        "molt_contextvars_token_exit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_token_exit",
            crate::molt_contextvars_token_exit as *const (),
        )),
        "molt_contextvars_var_repr" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_var_repr",
            crate::molt_contextvars_var_repr as *const (),
        )),
        "molt_contextvars_token_repr" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_token_repr",
            crate::molt_contextvars_token_repr as *const (),
        )),
        "molt_contextvars_missing_repr" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_contextvars_missing_repr",
            crate::molt_contextvars_missing_repr as *const (),
        )),
        _ => None,
    }
}
