// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_capabilities_trusted" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_capabilities_trusted",
            crate::molt_capabilities_trusted as *const (),
        )),
        "molt_capabilities_has" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_capabilities_has",
            crate::molt_capabilities_has as *const (),
        )),
        "molt_capabilities_require" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_capabilities_require",
            crate::molt_capabilities_require as *const (),
        )),
        "molt_abc_bootstrap" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_bootstrap",
            crate::molt_abc_bootstrap as *const (),
        )),
        "molt_collections_abc_runtime_types" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_collections_abc_runtime_types",
            crate::molt_collections_abc_runtime_types as *const (),
        )),
        "molt_abc_get_cache_token" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_get_cache_token",
            crate::molt_abc_get_cache_token as *const (),
        )),
        "molt_abc_init" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_init",
            crate::molt_abc_init as *const (),
        )),
        "molt_abc_register" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_register",
            crate::molt_abc_register as *const (),
        )),
        "molt_abc_instancecheck" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_instancecheck",
            crate::molt_abc_instancecheck as *const (),
        )),
        "molt_abc_subclasscheck" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_subclasscheck",
            crate::molt_abc_subclasscheck as *const (),
        )),
        "molt_abc_get_dump" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_get_dump",
            crate::molt_abc_get_dump as *const (),
        )),
        "molt_abc_reset_registry" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_reset_registry",
            crate::molt_abc_reset_registry as *const (),
        )),
        "molt_abc_reset_caches" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_reset_caches",
            crate::molt_abc_reset_caches as *const (),
        )),
        "molt_abc_update_abstractmethods" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_update_abstractmethods",
            crate::molt_abc_update_abstractmethods as *const (),
        )),
        "molt_abc_abstractmethod_check" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_abc_abstractmethod_check",
            crate::molt_abc_abstractmethod_check as *const (),
        )),
        "molt_gpu_linear_contiguous" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_linear_contiguous",
            crate::molt_gpu_linear_contiguous as *const (),
        )),
        "molt_gpu_linear_split_last_dim_contiguous" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_linear_split_last_dim_contiguous",
                crate::molt_gpu_linear_split_last_dim_contiguous as *const (),
            ))
        }
        "molt_gpu_tensor__tensor_linear_split_last_dim" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_tensor__tensor_linear_split_last_dim",
                crate::molt_gpu_tensor__tensor_linear_split_last_dim as *const (),
            ))
        }
        "molt_gpu_tensor__tensor_scaled_dot_product_attention" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_tensor__tensor_scaled_dot_product_attention",
                crate::molt_gpu_tensor__tensor_scaled_dot_product_attention as *const (),
            ))
        }
        "molt_gpu_turboquant_attention_packed" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_turboquant_attention_packed",
                crate::molt_gpu_turboquant_attention_packed as *const (),
            ))
        }
        "molt_gpu_tensor__tensor_concat_first_dim" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_tensor__tensor_concat_first_dim",
                crate::molt_gpu_tensor__tensor_concat_first_dim as *const (),
            ))
        }
        "molt_gpu_tensor__tensor_scatter_rows" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_tensor__tensor_scatter_rows",
                crate::molt_gpu_tensor__tensor_scatter_rows as *const (),
            ))
        }
        "molt_gpu_tensor__tensor_take_rows" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_tensor__tensor_take_rows",
            crate::molt_gpu_tensor__tensor_take_rows as *const (),
        )),
        "molt_gpu_linear_squared_relu_gate_interleaved_contiguous" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_linear_squared_relu_gate_interleaved_contiguous",
                crate::molt_gpu_linear_squared_relu_gate_interleaved_contiguous as *const (),
            ))
        }
        "molt_gpu_tensor_from_parts" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_tensor_from_parts",
            crate::molt_gpu_tensor_from_parts as *const (),
        )),
        "molt_gpu_repeat_axis_contiguous" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_repeat_axis_contiguous",
            crate::molt_gpu_repeat_axis_contiguous as *const (),
        )),
        "molt_gpu_tensor_from_buffer" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_tensor_from_buffer",
            crate::molt_gpu_tensor_from_buffer as *const (),
        )),
        "molt_gpu_tensor__zeros" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_tensor__zeros",
            crate::molt_gpu_tensor__zeros as *const (),
        )),
        "molt_gpu_buffer_to_list" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_buffer_to_list",
            crate::molt_gpu_buffer_to_list as *const (),
        )),
        "molt_gpu_interop_decode_bf16_bytes_to_f32" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_interop_decode_bf16_bytes_to_f32",
                crate::molt_gpu_interop_decode_bf16_bytes_to_f32 as *const (),
            ))
        }
        "molt_gpu_interop_decode_f16_bytes_to_f32" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_interop_decode_f16_bytes_to_f32",
                crate::molt_gpu_interop_decode_f16_bytes_to_f32 as *const (),
            ))
        }
        "molt_gpu_broadcast_binary_contiguous" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_broadcast_binary_contiguous",
                crate::molt_gpu_broadcast_binary_contiguous as *const (),
            ))
        }
        "molt_gpu_matmul_contiguous" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_matmul_contiguous",
            crate::molt_gpu_matmul_contiguous as *const (),
        )),
        "molt_gpu_rope_apply_contiguous" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_rope_apply_contiguous",
            crate::molt_gpu_rope_apply_contiguous as *const (),
        )),
        "molt_gpu_permute_contiguous" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_permute_contiguous",
            crate::molt_gpu_permute_contiguous as *const (),
        )),
        "molt_gpu_softmax_last_axis_contiguous" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_softmax_last_axis_contiguous",
                crate::molt_gpu_softmax_last_axis_contiguous as *const (),
            ))
        }
        "molt_gpu_rms_norm_last_axis_contiguous" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_rms_norm_last_axis_contiguous",
                crate::molt_gpu_rms_norm_last_axis_contiguous as *const (),
            ))
        }
        "molt_gpu_squared_relu_gate_interleaved_contiguous" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_gpu_squared_relu_gate_interleaved_contiguous",
                crate::molt_gpu_squared_relu_gate_interleaved_contiguous as *const (),
            ))
        }
        "molt_pow" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_pow",
            crate::molt_pow as *const (),
        )),
        "molt_pow_mod" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_pow_mod",
            crate::molt_pow_mod as *const (),
        )),
        "molt_context_null" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_context_null",
            crate::molt_context_null as *const (),
        )),
        "molt_block_on" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_block_on",
            crate::molt_block_on as *const (),
        )),
        "molt_pending" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_pending",
            crate::molt_pending as *const (),
        )),
        "molt_spawn" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_spawn",
            crate::molt_spawn as *const (),
        )),
        "molt_getcwd" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_getcwd",
            crate::molt_getcwd as *const (),
        )),
        "molt_getpid" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_getpid",
            crate::molt_getpid as *const (),
        )),
        "molt_env_get" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_get",
            crate::molt_env_get as *const (),
        )),
        "molt_env_snapshot" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_snapshot",
            crate::molt_env_snapshot as *const (),
        )),
        "molt_env_set" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_set",
            crate::molt_env_set as *const (),
        )),
        "molt_env_unset" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_unset",
            crate::molt_env_unset as *const (),
        )),
        "molt_env_len" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_len",
            crate::molt_env_len as *const (),
        )),
        "molt_env_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_contains",
            crate::molt_env_contains as *const (),
        )),
        "molt_env_popitem" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_popitem",
            crate::molt_env_popitem as *const (),
        )),
        "molt_env_clear" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_clear",
            crate::molt_env_clear as *const (),
        )),
        "molt_env_putenv" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_putenv",
            crate::molt_env_putenv as *const (),
        )),
        "molt_env_unsetenv" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_env_unsetenv",
            crate::molt_env_unsetenv as *const (),
        )),
        "molt_gettext_gettext" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gettext_gettext",
            crate::molt_gettext_gettext as *const (),
        )),
        "molt_gettext_ngettext" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gettext_ngettext",
            crate::molt_gettext_ngettext as *const (),
        )),
        "molt_glob" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_glob",
            crate::molt_glob as *const (),
        )),
        "molt_io_class" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_io_class",
            crate::molt_io_class as *const (),
        )),
        "molt_str_repeat" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_str_repeat",
            crate::molt_str_repeat as *const (),
        )),
        "molt_task_register_token_owned" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_task_register_token_owned",
            crate::molt_task_register_token_owned as *const (),
        )),
        "molt_trace_runtime_ready" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_trace_runtime_ready",
            crate::molt_trace_runtime_ready as *const (),
        )),
        "molt_import_smoke_runtime_ready" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_import_smoke_runtime_ready",
            crate::molt_import_smoke_runtime_ready as *const (),
        )),
        "molt_input_builtin" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_input_builtin",
            crate::molt_input_builtin as *const (),
        )),
        "molt_globals_builtin" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_globals_builtin",
            crate::molt_globals_builtin as *const (),
        )),
        "molt_locals_builtin" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_locals_builtin",
            crate::molt_locals_builtin as *const (),
        )),
        "molt_code_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_code_new",
            crate::molt_code_new as *const (),
        )),
        "molt_code_slots_init" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_code_slots_init",
            crate::molt_code_slots_init as *const (),
        )),
        "molt_code_slot_set" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_code_slot_set",
            crate::molt_code_slot_set as *const (),
        )),
        "molt_module_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_module_new",
            crate::molt_module_new as *const (),
        )),
        "molt_module_import" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_module_import",
            crate::molt_module_import as *const (),
        )),
        "molt_module_cache_set" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_module_cache_set",
            crate::molt_module_cache_set as *const (),
        )),
        "molt_exception_active" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_exception_active",
            crate::molt_exception_active as *const (),
        )),
        "molt_exception_last" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_exception_last",
            crate::molt_exception_last as *const (),
        )),
        "molt_exception_pending" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_exception_pending",
            crate::molt_exception_pending as *const (),
        )),
        "molt_exception_clear" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_exception_clear",
            crate::molt_exception_clear as *const (),
        )),
        "molt_getargv" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_getargv",
            crate::molt_getargv as *const (),
        )),
        "molt_getframe" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_getframe",
            crate::molt_getframe as *const (),
        )),
        "molt_getrecursionlimit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_getrecursionlimit",
            crate::molt_getrecursionlimit as *const (),
        )),
        "molt_setrecursionlimit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_setrecursionlimit",
            crate::molt_setrecursionlimit as *const (),
        )),
        "molt_gen_locals" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gen_locals",
            crate::molt_gen_locals as *const (),
        )),
        "molt_function_init_metadata_packed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_function_init_metadata_packed",
            crate::molt_function_init_metadata_packed as *const (),
        )),
        "molt_function_set_builtin" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_function_set_builtin",
            crate::molt_function_set_builtin as *const (),
        )),
        "molt_function_set_defaults" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_function_set_defaults",
            crate::molt_function_set_defaults as *const (),
        )),
        "molt_function_defaults_version" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_function_defaults_version",
            crate::molt_function_defaults_version as *const (),
        )),
        "molt_builtin_class_lookup" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_builtin_class_lookup",
            crate::molt_builtin_class_lookup as *const (),
        )),
        "molt_class_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_class_new",
            crate::molt_class_new as *const (),
        )),
        "molt_class_set_base" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_class_set_base",
            crate::molt_class_set_base as *const (),
        )),
        "molt_class_apply_set_name" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_class_apply_set_name",
            crate::molt_class_apply_set_name as *const (),
        )),
        "molt_bootstrap_descriptor_types" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_bootstrap_descriptor_types",
            crate::molt_bootstrap_descriptor_types as *const (),
        )),
        "molt_classmethod_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_classmethod_new",
            crate::molt_classmethod_new as *const (),
        )),
        "molt_staticmethod_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_staticmethod_new",
            crate::molt_staticmethod_new as *const (),
        )),
        "molt_property_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_property_new",
            crate::molt_property_new as *const (),
        )),
        "molt_generic_alias_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_generic_alias_new",
            crate::molt_generic_alias_new as *const (),
        )),
        "molt_sys_set_version_info" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_sys_set_version_info",
            crate::molt_sys_set_version_info as *const (),
        )),
        "molt_is_string_obj" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_is_string_obj",
            crate::molt_is_string_obj as *const (),
        )),
        "molt_trace_enter_slot" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_trace_enter_slot",
            crate::molt_trace_enter_slot as *const (),
        )),
        "molt_trace_exit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_trace_exit",
            crate::molt_trace_exit as *const (),
        )),
        "molt_trace_set_line" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_trace_set_line",
            crate::molt_trace_set_line as *const (),
        )),
        "molt_types_bootstrap" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_types_bootstrap",
            crate::molt_types_bootstrap as *const (),
        )),
        "molt_stdlib_probe" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_stdlib_probe",
            crate::molt_stdlib_probe as *const (),
        )),
        "molt_fcntl" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fcntl",
            crate::molt_fcntl as *const (),
        )),
        "molt_type_of_borrowed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_type_of_borrowed",
            crate::molt_type_of_borrowed as *const (),
        )),
        "molt_dict_getitem_borrowed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_dict_getitem_borrowed",
            crate::molt_dict_getitem_borrowed as *const (),
        )),
        "molt_list_getitem_borrowed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_list_getitem_borrowed",
            crate::molt_list_getitem_borrowed as *const (),
        )),
        "molt_tuple_getitem_borrowed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tuple_getitem_borrowed",
            crate::molt_tuple_getitem_borrowed as *const (),
        )),
        _ => None,
    }
}
