// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_new",
            crate::molt_email_message_new as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_from_bytes" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_from_bytes",
            crate::molt_email_message_from_bytes as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_set" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_set",
            crate::molt_email_message_set as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_get" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_get",
            crate::molt_email_message_get as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_set_content" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_set_content",
            crate::molt_email_message_set_content as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_add_alternative" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_add_alternative",
            crate::molt_email_message_add_alternative as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_add_attachment" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_add_attachment",
            crate::molt_email_message_add_attachment as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_is_multipart" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_is_multipart",
            crate::molt_email_message_is_multipart as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_payload",
            crate::molt_email_message_payload as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_content" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_content",
            crate::molt_email_message_content as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_content_type" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_content_type",
            crate::molt_email_message_content_type as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_filename" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_filename",
            crate::molt_email_message_filename as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_as_string" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_as_string",
            crate::molt_email_message_as_string as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_items" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_items",
            crate::molt_email_message_items as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_message_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_message_drop",
            crate::molt_email_message_drop as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_utils_make_msgid" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_utils_make_msgid",
            crate::molt_email_utils_make_msgid as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_utils_getaddresses" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_utils_getaddresses",
            crate::molt_email_utils_getaddresses as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_utils_parsedate_tz" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_utils_parsedate_tz",
            crate::molt_email_utils_parsedate_tz as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_utils_format_datetime" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_utils_format_datetime",
            crate::molt_email_utils_format_datetime as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_utils_parsedate_to_datetime" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_email_utils_parsedate_to_datetime",
                crate::molt_email_utils_parsedate_to_datetime as *const (),
            ))
        }
        #[cfg(feature = "stdlib_email")]
        "molt_email_policy_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_policy_new",
            crate::molt_email_policy_new as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_headerregistry_value" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_headerregistry_value",
            crate::molt_email_headerregistry_value as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_header_encode_word" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_header_encode_word",
            crate::molt_email_header_encode_word as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_address_addr_spec" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_address_addr_spec",
            crate::molt_email_address_addr_spec as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_address_format" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_address_format",
            crate::molt_email_address_format as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_header_check" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_header_check",
            crate::molt_email_quoprimime_header_check as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_body_check" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_body_check",
            crate::molt_email_quoprimime_body_check as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_header_length" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_header_length",
            crate::molt_email_quoprimime_header_length as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_body_length" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_body_length",
            crate::molt_email_quoprimime_body_length as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_quote" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_quote",
            crate::molt_email_quoprimime_quote as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_unquote" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_unquote",
            crate::molt_email_quoprimime_unquote as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_header_encode" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_header_encode",
            crate::molt_email_quoprimime_header_encode as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_header_decode" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_header_decode",
            crate::molt_email_quoprimime_header_decode as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_body_encode" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_body_encode",
            crate::molt_email_quoprimime_body_encode as *const (),
        )),
        #[cfg(feature = "stdlib_email")]
        "molt_email_quoprimime_decode" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_email_quoprimime_decode",
            crate::molt_email_quoprimime_decode as *const (),
        )),
        _ => None,
    }
}
