// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_enum_init_member" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_init_member",
            crate::molt_enum_init_member as *const (),
        )),
        "molt_enum_auto_value" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_auto_value",
            crate::molt_enum_auto_value as *const (),
        )),
        "molt_enum_flag_and" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_and",
            crate::molt_enum_flag_and as *const (),
        )),
        "molt_enum_flag_contains" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_contains",
            crate::molt_enum_flag_contains as *const (),
        )),
        "molt_enum_flag_decompose" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_decompose",
            crate::molt_enum_flag_decompose as *const (),
        )),
        "molt_enum_flag_invert" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_invert",
            crate::molt_enum_flag_invert as *const (),
        )),
        "molt_enum_flag_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_new",
            crate::molt_enum_flag_new as *const (),
        )),
        "molt_enum_flag_or" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_or",
            crate::molt_enum_flag_or as *const (),
        )),
        "molt_enum_flag_xor" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_flag_xor",
            crate::molt_enum_flag_xor as *const (),
        )),
        "molt_enum_str_value" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_str_value",
            crate::molt_enum_str_value as *const (),
        )),
        "molt_enum_unique_check" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_unique_check",
            crate::molt_enum_unique_check as *const (),
        )),
        "molt_enum_verify_member" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_verify_member",
            crate::molt_enum_verify_member as *const (),
        )),
        "molt_enum_is_auto" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_is_auto",
            crate::molt_enum_is_auto as *const (),
        )),
        "molt_enum_is_descriptor" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_enum_is_descriptor",
            crate::molt_enum_is_descriptor as *const (),
        )),
        _ => None,
    }
}
