// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_errno_constants" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_errno_constants",
            crate::molt_errno_constants as *const (),
        )),
        _ => None,
    }
}
