// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_fnmatch" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fnmatch",
            crate::molt_fnmatch as *const (),
        )),
        "molt_fnmatchcase" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fnmatchcase",
            crate::molt_fnmatchcase as *const (),
        )),
        "molt_fnmatch_filter" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fnmatch_filter",
            crate::molt_fnmatch_filter as *const (),
        )),
        "molt_fnmatch_translate" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fnmatch_translate",
            crate::molt_fnmatch_translate as *const (),
        )),
        "molt_fnmatch_fnmatch" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fnmatch_fnmatch",
            crate::molt_fnmatch_fnmatch as *const (),
        )),
        "molt_fnmatch_fnmatchcase" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_fnmatch_fnmatchcase",
            crate::molt_fnmatch_fnmatchcase as *const (),
        )),
        _ => None,
    }
}
