// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_glob_has_magic" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_glob_has_magic",
            crate::molt_glob_has_magic as *const (),
        )),
        "molt_glob_escape" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_glob_escape",
            crate::molt_glob_escape as *const (),
        )),
        "molt_glob_translate" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_glob_translate",
            crate::molt_glob_translate as *const (),
        )),
        "molt_glob_iter" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_glob_iter",
            crate::molt_glob_iter as *const (),
        )),
        _ => None,
    }
}
