// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_create_tensor" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_create_tensor",
            crate::molt_gpu_prim_create_tensor as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_create_tensor_raw" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_create_tensor_raw",
            crate::molt_gpu_prim_create_tensor_raw as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_zeros" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_zeros",
            crate::molt_gpu_prim_zeros as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_zeros_dtype" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_zeros_dtype",
            crate::molt_gpu_prim_zeros_dtype as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_realize" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_realize",
            crate::molt_gpu_prim_realize as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_dtype" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_dtype",
            crate::molt_gpu_prim_dtype as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_nbytes" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_nbytes",
            crate::molt_gpu_prim_nbytes as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_read_data_raw" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_read_data_raw",
            crate::molt_gpu_prim_read_data_raw as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_free" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_free",
            crate::molt_gpu_prim_free as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_unary" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_unary",
            crate::molt_gpu_prim_unary as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_cast" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_cast",
            crate::molt_gpu_prim_cast as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_binary" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_binary",
            crate::molt_gpu_prim_binary as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_ternary" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_ternary",
            crate::molt_gpu_prim_ternary as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_reduce" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_reduce",
            crate::molt_gpu_prim_reduce as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_reduce_all" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_reduce_all",
            crate::molt_gpu_prim_reduce_all as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_reshape" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_reshape",
            crate::molt_gpu_prim_reshape as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_expand" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_expand",
            crate::molt_gpu_prim_expand as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_permute" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_permute",
            crate::molt_gpu_prim_permute as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_pad" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_pad",
            crate::molt_gpu_prim_pad as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_shrink" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_shrink",
            crate::molt_gpu_prim_shrink as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_flip" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_flip",
            crate::molt_gpu_prim_flip as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_contiguous" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_contiguous",
            crate::molt_gpu_prim_contiguous as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_shape" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_shape",
            crate::molt_gpu_prim_shape as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_numel" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_numel",
            crate::molt_gpu_prim_numel as *const (),
        )),
        #[cfg(feature = "molt_gpu_primitives")]
        "molt_gpu_prim_device" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_gpu_prim_device",
            crate::molt_gpu_prim_device as *const (),
        )),
        _ => None,
    }
}
