// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_heapq_heapify" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heapify",
            crate::molt_heapq_heapify as *const (),
        )),
        "molt_heapq_heappush" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heappush",
            crate::molt_heapq_heappush as *const (),
        )),
        "molt_heapq_heappop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heappop",
            crate::molt_heapq_heappop as *const (),
        )),
        "molt_heapq_heapreplace" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heapreplace",
            crate::molt_heapq_heapreplace as *const (),
        )),
        "molt_heapq_heappushpop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heappushpop",
            crate::molt_heapq_heappushpop as *const (),
        )),
        "molt_heapq_heapify_max" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heapify_max",
            crate::molt_heapq_heapify_max as *const (),
        )),
        "molt_heapq_heappop_max" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_heappop_max",
            crate::molt_heapq_heappop_max as *const (),
        )),
        "molt_heapq_nsmallest" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_nsmallest",
            crate::molt_heapq_nsmallest as *const (),
        )),
        "molt_heapq_nlargest" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_nlargest",
            crate::molt_heapq_nlargest as *const (),
        )),
        "molt_heapq_merge" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_heapq_merge",
            crate::molt_heapq_merge as *const (),
        )),
        _ => None,
    }
}
