// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_text")]
        "molt_html_entities_codepoint2name" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_entities_codepoint2name",
            crate::molt_html_entities_codepoint2name as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_entities_html5" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_entities_html5",
            crate::molt_html_entities_html5 as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_entities_name2codepoint" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_entities_name2codepoint",
            crate::molt_html_entities_name2codepoint as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_escape" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_escape",
            crate::molt_html_escape as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_parser_close" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_parser_close",
            crate::molt_html_parser_close as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_parser_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_parser_drop",
            crate::molt_html_parser_drop as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_parser_feed" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_parser_feed",
            crate::molt_html_parser_feed as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_parser_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_parser_new",
            crate::molt_html_parser_new as *const (),
        )),
        #[cfg(feature = "stdlib_text")]
        "molt_html_unescape" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_html_unescape",
            crate::molt_html_unescape as *const (),
        )),
        _ => None,
    }
}
