// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_importlib_extension_loader_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_extension_loader_payload",
                crate::molt_importlib_extension_loader_payload as *const (),
            ))
        }
        "molt_importlib_sourceless_loader_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_sourceless_loader_payload",
                crate::molt_importlib_sourceless_loader_payload as *const (),
            ))
        }
        "molt_importlib_coerce_module_name" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_coerce_module_name",
            crate::molt_importlib_coerce_module_name as *const (),
        )),
        "molt_importlib_source_exec_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_source_exec_payload",
            crate::molt_importlib_source_exec_payload as *const (),
        )),
        "molt_importlib_zip_source_exec_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_zip_source_exec_payload",
                crate::molt_importlib_zip_source_exec_payload as *const (),
            ))
        }
        "molt_importlib_zip_read_entry" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_zip_read_entry",
            crate::molt_importlib_zip_read_entry as *const (),
        )),
        "molt_importlib_read_file" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_read_file",
            crate::molt_importlib_read_file as *const (),
        )),
        "molt_importlib_exec_restricted_source" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_exec_restricted_source",
                crate::molt_importlib_exec_restricted_source as *const (),
            ))
        }
        "molt_importlib_exec_extension" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_exec_extension",
            crate::molt_importlib_exec_extension as *const (),
        )),
        "molt_importlib_exec_sourceless" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_exec_sourceless",
            crate::molt_importlib_exec_sourceless as *const (),
        )),
        "molt_importlib_sourcefileloader_exec_module" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_sourcefileloader_exec_module",
                crate::molt_importlib_sourcefileloader_exec_module as *const (),
            ))
        }
        "molt_importlib_zip_source_loader_exec_module" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_zip_source_loader_exec_module",
                crate::molt_importlib_zip_source_loader_exec_module as *const (),
            ))
        }
        "molt_importlib_extension_loader_exec_module" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_extension_loader_exec_module",
                crate::molt_importlib_extension_loader_exec_module as *const (),
            ))
        }
        "molt_importlib_sourceless_loader_exec_module" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_sourceless_loader_exec_module",
                crate::molt_importlib_sourceless_loader_exec_module as *const (),
            ))
        }
        "molt_importlib_module_spec_is_package" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_module_spec_is_package",
                crate::molt_importlib_module_spec_is_package as *const (),
            ))
        }
        "molt_importlib_path_is_archive_member" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_path_is_archive_member",
                crate::molt_importlib_path_is_archive_member as *const (),
            ))
        }
        "molt_importlib_package_root_from_origin" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_package_root_from_origin",
                crate::molt_importlib_package_root_from_origin as *const (),
            ))
        }
        "molt_importlib_validate_resource_name" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_validate_resource_name",
                crate::molt_importlib_validate_resource_name as *const (),
            ))
        }
        "molt_importlib_cache_from_source" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_cache_from_source",
            crate::molt_importlib_cache_from_source as *const (),
        )),
        "molt_importlib_decode_source" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_decode_source",
            crate::molt_importlib_decode_source as *const (),
        )),
        "molt_importlib_source_hash" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_source_hash",
            crate::molt_importlib_source_hash as *const (),
        )),
        "molt_importlib_source_from_cache" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_source_from_cache",
            crate::molt_importlib_source_from_cache as *const (),
        )),
        "molt_importlib_resolve_name" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_resolve_name",
            crate::molt_importlib_resolve_name as *const (),
        )),
        "molt_importlib_import_module" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_import_module",
            crate::molt_importlib_import_module as *const (),
        )),
        "molt_importlib_known_absent_missing_name" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_known_absent_missing_name",
                crate::molt_importlib_known_absent_missing_name as *const (),
            ))
        }
        "molt_importlib_import_optional" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_import_optional",
            crate::molt_importlib_import_optional as *const (),
        )),
        "molt_importlib_import_or_fallback" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_import_or_fallback",
            crate::molt_importlib_import_or_fallback as *const (),
        )),
        "molt_importlib_import_required" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_import_required",
            crate::molt_importlib_import_required as *const (),
        )),
        "molt_importlib_load_module_shim" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_load_module_shim",
            crate::molt_importlib_load_module_shim as *const (),
        )),
        "molt_importlib_load_module_from_spec" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_load_module_from_spec",
                crate::molt_importlib_load_module_from_spec as *const (),
            ))
        }
        "molt_importlib_frozen_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_frozen_payload",
            crate::molt_importlib_frozen_payload as *const (),
        )),
        "molt_importlib_frozen_external_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_frozen_external_payload",
                crate::molt_importlib_frozen_external_payload as *const (),
            ))
        }
        "molt_importlib_import_transaction" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_import_transaction",
            crate::molt_importlib_import_transaction as *const (),
        )),
        "molt_importlib_find_in_path" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_find_in_path",
            crate::molt_importlib_find_in_path as *const (),
        )),
        "molt_importlib_find_in_path_package_context" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_find_in_path_package_context",
                crate::molt_importlib_find_in_path_package_context as *const (),
            ))
        }
        "molt_importlib_find_spec" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_find_spec",
            crate::molt_importlib_find_spec as *const (),
        )),
        "molt_importlib_find_spec_orchestrate" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_find_spec_orchestrate",
                crate::molt_importlib_find_spec_orchestrate as *const (),
            ))
        }
        "molt_importlib_pathfinder_find_spec" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_pathfinder_find_spec",
            crate::molt_importlib_pathfinder_find_spec as *const (),
        )),
        "molt_importlib_filefinder_find_spec" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_filefinder_find_spec",
            crate::molt_importlib_filefinder_find_spec as *const (),
        )),
        "molt_importlib_invalidate_caches" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_invalidate_caches",
            crate::molt_importlib_invalidate_caches as *const (),
        )),
        "molt_importlib_filefinder_invalidate" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_filefinder_invalidate",
                crate::molt_importlib_filefinder_invalidate as *const (),
            ))
        }
        "molt_importlib_reload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_reload",
            crate::molt_importlib_reload as *const (),
        )),
        "molt_importlib_bootstrap_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_bootstrap_payload",
            crate::molt_importlib_bootstrap_payload as *const (),
        )),
        "molt_importlib_runtime_modules" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_runtime_modules",
            crate::molt_importlib_runtime_modules as *const (),
        )),
        "molt_importlib_ensure_default_meta_path" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_ensure_default_meta_path",
                crate::molt_importlib_ensure_default_meta_path as *const (),
            ))
        }
        "molt_importlib_module_from_spec" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_module_from_spec",
            crate::molt_importlib_module_from_spec as *const (),
        )),
        "molt_importlib_spec_from_loader" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_spec_from_loader",
            crate::molt_importlib_spec_from_loader as *const (),
        )),
        "molt_importlib_spec_from_file_location" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_spec_from_file_location",
                crate::molt_importlib_spec_from_file_location as *const (),
            ))
        }
        "molt_importlib_set_module_state" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_set_module_state",
            crate::molt_importlib_set_module_state as *const (),
        )),
        "molt_importlib_stabilize_module_state" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_stabilize_module_state",
                crate::molt_importlib_stabilize_module_state as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_normalize_path" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_normalize_path",
                crate::molt_importlib_resources_normalize_path as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_only" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_resources_only",
            crate::molt_importlib_resources_only as *const (),
        )),
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_contents_from_package" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_contents_from_package",
                crate::molt_importlib_resources_contents_from_package as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_is_resource_from_package" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_is_resource_from_package",
                crate::molt_importlib_resources_is_resource_from_package as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_resource_path_from_package" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_resource_path_from_package",
                crate::molt_importlib_resources_resource_path_from_package as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_read_text_from_package" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_read_text_from_package",
                crate::molt_importlib_resources_read_text_from_package as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_resource_path_from_roots" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_resource_path_from_roots",
                crate::molt_importlib_resources_reader_resource_path_from_roots as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_open_resource_bytes_from_roots" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_open_resource_bytes_from_roots",
                crate::molt_importlib_resources_reader_open_resource_bytes_from_roots as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_is_resource_from_roots" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_is_resource_from_roots",
                crate::molt_importlib_resources_reader_is_resource_from_roots as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_contents_from_roots" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_contents_from_roots",
                crate::molt_importlib_resources_reader_contents_from_roots as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_path_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_path_payload",
                crate::molt_importlib_resources_path_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_package_info" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_package_info",
                crate::molt_importlib_resources_package_info as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_open_resource_bytes_from_package" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_open_resource_bytes_from_package",
                crate::molt_importlib_resources_open_resource_bytes_from_package as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_open_resource_bytes_from_package_parts" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_open_resource_bytes_from_package_parts",
                crate::molt_importlib_resources_open_resource_bytes_from_package_parts as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_read_text_from_package_parts" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_read_text_from_package_parts",
                crate::molt_importlib_resources_read_text_from_package_parts as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_contents_from_package_parts" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_contents_from_package_parts",
                crate::molt_importlib_resources_contents_from_package_parts as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_is_resource_from_package_parts" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_is_resource_from_package_parts",
                crate::molt_importlib_resources_is_resource_from_package_parts as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_resource_path_from_package_parts" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_resource_path_from_package_parts",
                crate::molt_importlib_resources_resource_path_from_package_parts as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_as_file_enter" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_as_file_enter",
                crate::molt_importlib_resources_as_file_enter as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_as_file_exit" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_as_file_exit",
                crate::molt_importlib_resources_as_file_exit as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_joinpath" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_resources_joinpath",
            crate::molt_importlib_resources_joinpath as *const (),
        )),
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_open_mode_is_text" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_open_mode_is_text",
                crate::molt_importlib_resources_open_mode_is_text as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_package_leaf_name" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_package_leaf_name",
                crate::molt_importlib_resources_package_leaf_name as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_module_name" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_module_name",
                crate::molt_importlib_resources_module_name as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_loader_reader" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_loader_reader",
                crate::molt_importlib_resources_loader_reader as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_files_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_files_payload",
                crate::molt_importlib_resources_files_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_files_traversable" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_files_traversable",
                crate::molt_importlib_resources_reader_files_traversable as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_roots" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_roots",
                crate::molt_importlib_resources_reader_roots as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_contents" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_contents",
                crate::molt_importlib_resources_reader_contents as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_resource_path" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_resource_path",
                crate::molt_importlib_resources_reader_resource_path as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_is_resource" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_is_resource",
                crate::molt_importlib_resources_reader_is_resource as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_open_resource_bytes" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_open_resource_bytes",
                crate::molt_importlib_resources_reader_open_resource_bytes as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_child_names" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_child_names",
                crate::molt_importlib_resources_reader_child_names as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_exists" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_exists",
                crate::molt_importlib_resources_reader_exists as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_resources_reader_is_dir" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_resources_reader_is_dir",
                crate::molt_importlib_resources_reader_is_dir as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_dist_paths" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_metadata_dist_paths",
            crate::molt_importlib_metadata_dist_paths as *const (),
        )),
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_entry_points_select_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_entry_points_select_payload",
                crate::molt_importlib_metadata_entry_points_select_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_entry_points_filter_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_entry_points_filter_payload",
                crate::molt_importlib_metadata_entry_points_filter_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_normalize_name" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_normalize_name",
                crate::molt_importlib_metadata_normalize_name as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_importlib_metadata_payload",
            crate::molt_importlib_metadata_payload as *const (),
        )),
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_distributions_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_distributions_payload",
                crate::molt_importlib_metadata_distributions_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_record_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_record_payload",
                crate::molt_importlib_metadata_record_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_packages_distributions_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_packages_distributions_payload",
                crate::molt_importlib_metadata_packages_distributions_payload as *const (),
            ))
        }
        #[cfg(feature = "stdlib_importlib_extra")]
        "molt_importlib_metadata_types_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_importlib_metadata_types_payload",
                crate::molt_importlib_metadata_types_payload as *const (),
            ))
        }
        _ => None,
    }
}
