// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_itertools_kwd_mark" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_kwd_mark",
            crate::molt_itertools_kwd_mark as *const (),
        )),
        "molt_itertools_chain" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_chain",
            crate::molt_itertools_chain as *const (),
        )),
        "molt_itertools_chain_from_iterable" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_chain_from_iterable",
            crate::molt_itertools_chain_from_iterable as *const (),
        )),
        "molt_itertools_islice" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_islice",
            crate::molt_itertools_islice as *const (),
        )),
        "molt_itertools_repeat" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_repeat",
            crate::molt_itertools_repeat as *const (),
        )),
        "molt_itertools_repeat_type" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_repeat_type",
            crate::molt_itertools_repeat_type as *const (),
        )),
        "molt_itertools_count" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_count",
            crate::molt_itertools_count as *const (),
        )),
        "molt_itertools_cycle" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_cycle",
            crate::molt_itertools_cycle as *const (),
        )),
        "molt_itertools_accumulate" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_accumulate",
            crate::molt_itertools_accumulate as *const (),
        )),
        "molt_itertools_batched" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_batched",
            crate::molt_itertools_batched as *const (),
        )),
        "molt_itertools_compress" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_compress",
            crate::molt_itertools_compress as *const (),
        )),
        "molt_itertools_combinations_with_replacement" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_itertools_combinations_with_replacement",
                crate::molt_itertools_combinations_with_replacement as *const (),
            ))
        }
        "molt_itertools_dropwhile" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_dropwhile",
            crate::molt_itertools_dropwhile as *const (),
        )),
        "molt_itertools_filterfalse" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_filterfalse",
            crate::molt_itertools_filterfalse as *const (),
        )),
        "molt_itertools_pairwise" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_pairwise",
            crate::molt_itertools_pairwise as *const (),
        )),
        "molt_itertools_product" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_product",
            crate::molt_itertools_product as *const (),
        )),
        "molt_itertools_permutations" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_permutations",
            crate::molt_itertools_permutations as *const (),
        )),
        "molt_itertools_combinations" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_combinations",
            crate::molt_itertools_combinations as *const (),
        )),
        "molt_itertools_groupby" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_groupby",
            crate::molt_itertools_groupby as *const (),
        )),
        "molt_itertools_starmap" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_starmap",
            crate::molt_itertools_starmap as *const (),
        )),
        "molt_itertools_takewhile" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_takewhile",
            crate::molt_itertools_takewhile as *const (),
        )),
        "molt_itertools_tee" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_tee",
            crate::molt_itertools_tee as *const (),
        )),
        "molt_itertools_zip_longest" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_itertools_zip_longest",
            crate::molt_itertools_zip_longest as *const (),
        )),
        _ => None,
    }
}
