// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_record_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_record_new",
            crate::molt_logging_record_new as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_record_get_message" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_record_get_message",
            crate::molt_logging_record_get_message as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_record_get_attr" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_record_get_attr",
            crate::molt_logging_record_get_attr as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_record_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_record_drop",
            crate::molt_logging_record_drop as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_formatter_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_formatter_new",
            crate::molt_logging_formatter_new as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_formatter_format" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_formatter_format",
            crate::molt_logging_formatter_format as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_formatter_format_time" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_formatter_format_time",
            crate::molt_logging_formatter_format_time as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_formatter_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_formatter_drop",
            crate::molt_logging_formatter_drop as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_new",
            crate::molt_logging_handler_new as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_emit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_emit",
            crate::molt_logging_handler_emit as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_set_level" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_set_level",
            crate::molt_logging_handler_set_level as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_set_formatter" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_set_formatter",
            crate::molt_logging_handler_set_formatter as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_flush" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_flush",
            crate::molt_logging_handler_flush as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_close" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_close",
            crate::molt_logging_handler_close as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_handler_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_handler_drop",
            crate::molt_logging_handler_drop as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_stream_handler_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_stream_handler_new",
            crate::molt_logging_stream_handler_new as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_stream_handler_emit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_stream_handler_emit",
            crate::molt_logging_stream_handler_emit as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_new",
            crate::molt_logging_logger_new as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_set_level" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_set_level",
            crate::molt_logging_logger_set_level as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_add_handler" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_add_handler",
            crate::molt_logging_logger_add_handler as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_remove_handler" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_remove_handler",
            crate::molt_logging_logger_remove_handler as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_log" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_log",
            crate::molt_logging_logger_log as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_is_enabled_for" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_is_enabled_for",
            crate::molt_logging_logger_is_enabled_for as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_get_effective_level" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_logging_logger_get_effective_level",
                crate::molt_logging_logger_get_effective_level as *const (),
            ))
        }
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_logger_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_logger_drop",
            crate::molt_logging_logger_drop as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_manager_get_logger" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_manager_get_logger",
            crate::molt_logging_manager_get_logger as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_root_logger" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_root_logger",
            crate::molt_logging_root_logger as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_basic_config" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_basic_config",
            crate::molt_logging_basic_config as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_shutdown" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_shutdown",
            crate::molt_logging_shutdown as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_get_level_name" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_get_level_name",
            crate::molt_logging_get_level_name as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_add_level_name" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_add_level_name",
            crate::molt_logging_add_level_name as *const (),
        )),
        #[cfg(feature = "stdlib_logging_ext")]
        "molt_logging_level_to_int" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_logging_level_to_int",
            crate::molt_logging_level_to_int as *const (),
        )),
        _ => None,
    }
}
