// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_memoryview_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_new",
            crate::molt_memoryview_new as *const (),
        )),
        "molt_memoryview_from_flags" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_from_flags",
            crate::molt_memoryview_from_flags as *const (),
        )),
        "molt_memoryview_cast" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_cast",
            crate::molt_memoryview_cast as *const (),
        )),
        "molt_memoryview_tobytes" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_tobytes",
            crate::molt_memoryview_tobytes as *const (),
        )),
        "molt_memoryview_tolist" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_tolist",
            crate::molt_memoryview_tolist as *const (),
        )),
        "molt_memoryview_count" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_count",
            crate::molt_memoryview_count as *const (),
        )),
        "molt_memoryview_index" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_index",
            crate::molt_memoryview_index as *const (),
        )),
        "molt_memoryview_hex" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_hex",
            crate::molt_memoryview_hex as *const (),
        )),
        "molt_memoryview_release" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_release",
            crate::molt_memoryview_release as *const (),
        )),
        "molt_memoryview_toreadonly" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_memoryview_toreadonly",
            crate::molt_memoryview_toreadonly as *const (),
        )),
        _ => None,
    }
}
