// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_platform_architecture" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_architecture",
            crate::molt_platform_architecture as *const (),
        )),
        "molt_platform_machine" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_machine",
            crate::molt_platform_machine as *const (),
        )),
        "molt_platform_node" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_node",
            crate::molt_platform_node as *const (),
        )),
        "molt_platform_platform" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_platform",
            crate::molt_platform_platform as *const (),
        )),
        "molt_platform_processor" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_processor",
            crate::molt_platform_processor as *const (),
        )),
        "molt_platform_python_compiler" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_python_compiler",
            crate::molt_platform_python_compiler as *const (),
        )),
        "molt_platform_python_implementation" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_python_implementation",
            crate::molt_platform_python_implementation as *const (),
        )),
        "molt_platform_python_version" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_python_version",
            crate::molt_platform_python_version as *const (),
        )),
        "molt_platform_python_version_tuple" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_python_version_tuple",
            crate::molt_platform_python_version_tuple as *const (),
        )),
        "molt_platform_release" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_release",
            crate::molt_platform_release as *const (),
        )),
        "molt_platform_system" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_system",
            crate::molt_platform_system as *const (),
        )),
        "molt_platform_uname" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_uname",
            crate::molt_platform_uname as *const (),
        )),
        "molt_platform_version" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_platform_version",
            crate::molt_platform_version as *const (),
        )),
        _ => None,
    }
}
