// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_queue_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_new",
            crate::molt_queue_new as *const (),
        )),
        "molt_queue_lifo_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_lifo_new",
            crate::molt_queue_lifo_new as *const (),
        )),
        "molt_queue_priority_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_priority_new",
            crate::molt_queue_priority_new as *const (),
        )),
        "molt_queue_qsize" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_qsize",
            crate::molt_queue_qsize as *const (),
        )),
        "molt_queue_empty" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_empty",
            crate::molt_queue_empty as *const (),
        )),
        "molt_queue_full" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_full",
            crate::molt_queue_full as *const (),
        )),
        "molt_queue_put" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_put",
            crate::molt_queue_put as *const (),
        )),
        "molt_queue_get" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_get",
            crate::molt_queue_get as *const (),
        )),
        "molt_queue_shutdown" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_shutdown",
            crate::molt_queue_shutdown as *const (),
        )),
        "molt_queue_is_shutdown" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_is_shutdown",
            crate::molt_queue_is_shutdown as *const (),
        )),
        "molt_queue_task_done" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_task_done",
            crate::molt_queue_task_done as *const (),
        )),
        "molt_queue_join" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_join",
            crate::molt_queue_join as *const (),
        )),
        "molt_queue_drop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_queue_drop",
            crate::molt_queue_drop as *const (),
        )),
        _ => None,
    }
}
