// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    #[cfg(feature = "stdlib_math")]
    {
        molt_runtime_math::intrinsics_generated::random_resolver::resolve_symbol_with(
            symbol,
            crate::builtins::functions::runtime_fn_addr,
        )
    }
    #[cfg(not(feature = "stdlib_math"))]
    {
        let _ = symbol;
        None
    }
}
