// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_scipy_ndimage_distance_transform_edt" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_scipy_ndimage_distance_transform_edt",
                crate::molt_scipy_ndimage_distance_transform_edt as *const (),
            ))
        }
        _ => None,
    }
}
