// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_this_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_this_payload",
            crate::molt_this_payload as *const (),
        )),
        _ => None,
    }
}
