// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_available" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_available",
            crate::molt_tk_available as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_app_new" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_app_new",
            crate::molt_tk_app_new as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_quit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_quit",
            crate::molt_tk_quit as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_mainloop" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_mainloop",
            crate::molt_tk_mainloop as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_do_one_event" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_do_one_event",
            crate::molt_tk_do_one_event as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_after" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_after",
            crate::molt_tk_after as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_after_idle" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_after_idle",
            crate::molt_tk_after_idle as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_after_cancel" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_after_cancel",
            crate::molt_tk_after_cancel as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_after_info" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_after_info",
            crate::molt_tk_after_info as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_call" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_call",
            crate::molt_tk_call as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_trace_add" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_trace_add",
            crate::molt_tk_trace_add as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_trace_remove" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_trace_remove",
            crate::molt_tk_trace_remove as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_trace_info" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_trace_info",
            crate::molt_tk_trace_info as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_trace_clear" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_trace_clear",
            crate::molt_tk_trace_clear as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_tkwait_variable" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_tkwait_variable",
            crate::molt_tk_tkwait_variable as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_tkwait_window" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_tkwait_window",
            crate::molt_tk_tkwait_window as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_tkwait_visibility" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_tkwait_visibility",
            crate::molt_tk_tkwait_visibility as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_bind_callback_register" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_bind_callback_register",
            crate::molt_tk_bind_callback_register as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_bind_callback_unregister" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_bind_callback_unregister",
            crate::molt_tk_bind_callback_unregister as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_widget_bind_callback_register" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_tk_widget_bind_callback_register",
                crate::molt_tk_widget_bind_callback_register as *const (),
            ))
        }
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_widget_bind_callback_unregister" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_tk_widget_bind_callback_unregister",
                crate::molt_tk_widget_bind_callback_unregister as *const (),
            ))
        }
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_text_tag_bind_callback_register" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_tk_text_tag_bind_callback_register",
                crate::molt_tk_text_tag_bind_callback_register as *const (),
            ))
        }
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_text_tag_bind_callback_unregister" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_tk_text_tag_bind_callback_unregister",
                crate::molt_tk_text_tag_bind_callback_unregister as *const (),
            ))
        }
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_treeview_tag_bind_callback_register" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_tk_treeview_tag_bind_callback_register",
                crate::molt_tk_treeview_tag_bind_callback_register as *const (),
            ))
        }
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_treeview_tag_bind_callback_unregister" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_tk_treeview_tag_bind_callback_unregister",
                crate::molt_tk_treeview_tag_bind_callback_unregister as *const (),
            ))
        }
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_bind_command" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_bind_command",
            crate::molt_tk_bind_command as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_unbind_command" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_unbind_command",
            crate::molt_tk_unbind_command as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_filehandler_create" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_filehandler_create",
            crate::molt_tk_filehandler_create as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_filehandler_delete" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_filehandler_delete",
            crate::molt_tk_filehandler_delete as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_destroy_widget" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_destroy_widget",
            crate::molt_tk_destroy_widget as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_last_error" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_last_error",
            crate::molt_tk_last_error as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_getboolean" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_getboolean",
            crate::molt_tk_getboolean as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_getdouble" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_getdouble",
            crate::molt_tk_getdouble as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_splitlist" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_splitlist",
            crate::molt_tk_splitlist as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_event_subst_parse" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_event_subst_parse",
            crate::molt_tk_event_subst_parse as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_bind_script_remove_command" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_bind_script_remove_command",
            crate::molt_tk_bind_script_remove_command as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_errorinfo_append" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_errorinfo_append",
            crate::molt_tk_errorinfo_append as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_dialog_show" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_dialog_show",
            crate::molt_tk_dialog_show as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_commondialog_show" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_commondialog_show",
            crate::molt_tk_commondialog_show as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_messagebox_show" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_messagebox_show",
            crate::molt_tk_messagebox_show as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_filedialog_show" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_filedialog_show",
            crate::molt_tk_filedialog_show as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_simpledialog_query" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_simpledialog_query",
            crate::molt_tk_simpledialog_query as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_event_build_from_args" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_event_build_from_args",
            crate::molt_tk_event_build_from_args as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_event_int" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_event_int",
            crate::molt_tk_event_int as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_event_state_decode" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_event_state_decode",
            crate::molt_tk_event_state_decode as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_splitdict" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_splitdict",
            crate::molt_tk_splitdict as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_flatten_args" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_flatten_args",
            crate::molt_tk_flatten_args as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_cnfmerge" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_cnfmerge",
            crate::molt_tk_cnfmerge as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_normalize_option" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_normalize_option",
            crate::molt_tk_normalize_option as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_hex_to_rgb" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_hex_to_rgb",
            crate::molt_tk_hex_to_rgb as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_normalize_delay_ms" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_normalize_delay_ms",
            crate::molt_tk_normalize_delay_ms as *const (),
        )),
        #[cfg(feature = "stdlib_tk")]
        "molt_tk_convert_stringval" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_tk_convert_stringval",
            crate::molt_tk_convert_stringval as *const (),
        )),
        _ => None,
    }
}
