// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_traceback_source_line" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_source_line",
            crate::molt_traceback_source_line as *const (),
        )),
        "molt_traceback_infer_col_offsets" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_infer_col_offsets",
            crate::molt_traceback_infer_col_offsets as *const (),
        )),
        "molt_traceback_format_caret_line" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_format_caret_line",
            crate::molt_traceback_format_caret_line as *const (),
        )),
        "molt_traceback_format_exception_only" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_traceback_format_exception_only",
                crate::molt_traceback_format_exception_only as *const (),
            ))
        }
        "molt_traceback_format_exception" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_format_exception",
            crate::molt_traceback_format_exception as *const (),
        )),
        "molt_traceback_format_tb" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_format_tb",
            crate::molt_traceback_format_tb as *const (),
        )),
        "molt_traceback_format_stack" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_format_stack",
            crate::molt_traceback_format_stack as *const (),
        )),
        "molt_traceback_extract_tb" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_extract_tb",
            crate::molt_traceback_extract_tb as *const (),
        )),
        "molt_traceback_exception_components" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_exception_components",
            crate::molt_traceback_exception_components as *const (),
        )),
        "molt_traceback_exception_chain_payload" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_traceback_exception_chain_payload",
                crate::molt_traceback_exception_chain_payload as *const (),
            ))
        }
        "molt_traceback_exception_suppress_context" => {
            Some(crate::builtins::functions::runtime_fn_addr(
                "crate::molt_traceback_exception_suppress_context",
                crate::molt_traceback_exception_suppress_context as *const (),
            ))
        }
        "molt_traceback_payload" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_traceback_payload",
            crate::molt_traceback_payload as *const (),
        )),
        _ => None,
    }
}
