// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub(super) fn resolve_symbol(symbol: &str) -> Option<u64> {
    match symbol {
        "molt_warnings_warn" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_warn",
            crate::molt_warnings_warn as *const (),
        )),
        "molt_warnings_warn_explicit" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_warn_explicit",
            crate::molt_warnings_warn_explicit as *const (),
        )),
        "molt_warnings_formatwarning" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_formatwarning",
            crate::molt_warnings_formatwarning as *const (),
        )),
        "molt_warnings_showwarning" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_showwarning",
            crate::molt_warnings_showwarning as *const (),
        )),
        "molt_warnings_simplefilter" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_simplefilter",
            crate::molt_warnings_simplefilter as *const (),
        )),
        "molt_warnings_filterwarnings" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_filterwarnings",
            crate::molt_warnings_filterwarnings as *const (),
        )),
        "molt_warnings_resetwarnings" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_resetwarnings",
            crate::molt_warnings_resetwarnings as *const (),
        )),
        "molt_warnings_filters_get" => Some(crate::builtins::functions::runtime_fn_addr(
            "crate::molt_warnings_filters_get",
            crate::molt_warnings_filters_get as *const (),
        )),
        _ => None,
    }
}
