"""Capability-gated stdlib stubs for Molt."""

from __future__ import annotations

__all__ = [
    "asyncio",
    "bisect",
    "builtins",
    "collections",
    "contextlib",
    "contextvars",
    "copy",
    "dataclasses",
    "doctest",
    "__future__",
    "fnmatch",
    "functools",
    "gc",
    "importlib",
    "inspect",
    "io",
    "itertools",
    "heapq",
    "json",
    "os",
    "operator",
    "pathlib",
    "pickle",
    "pprint",
    "select",
    "random",
    "re",
    "socket",
    "selectors",
    "string",
    "sys",
    "time",
    "tempfile",
    "test",
    "threading",
    "traceback",
    "types",
    "typing",
    "unittest",
    "warnings",
]
