"""Capability-gated stdlib stubs for Molt."""

from __future__ import annotations

import sys as _sys

import _intrinsics as _stdlib_intrinsics
from _intrinsics import require_intrinsic as _require_intrinsic

_intrinsics = _stdlib_intrinsics

_require_intrinsic("molt_stdlib_probe", globals())
_MOLT_STDLIB_CAP_HAS = _require_intrinsic("molt_capabilities_has", globals())

_modules = getattr(_sys, "modules", None)
if isinstance(_modules, dict):
    _modules.setdefault("_intrinsics", _stdlib_intrinsics)

__all__ = [
    "abc",
    "asyncio",
    "ast",
    "base64",
    "bisect",
    "builtins",
    "collections",
    "concurrent",
    "contextlib",
    "contextvars",
    "codecs",
    "compileall",
    "copy",
    "copyreg",
    "py_compile",
    "queue",
    "csv",
    "datetime",
    "ctypes",
    "dataclasses",
    "decimal",
    "dis",
    "doctest",
    "encodings",
    "enum",
    "__future__",
    "fnmatch",
    "functools",
    "gc",
    "gettext",
    "glob",
    "hashlib",
    "importlib",
    "inspect",
    "io",
    "itertools",
    "heapq",
    "hmac",
    "ipaddress",
    "json",
    "marshal",
    "keyword",
    "linecache",
    "logging",
    "locale",
    "multiprocessing",
    "molt_db",
    "os",
    "operator",
    "opcode",
    "pathlib",
    "pickle",
    "pkgutil",
    "pprint",
    "select",
    "random",
    "profile",
    "pstats",
    "runpy",
    "re",
    "reprlib",
    "statistics",
    "subprocess",
    "symtable",
    "shutil",
    "socket",
    "selectors",
    "signal",
    "string",
    "struct",
    "stat",
    "sys",
    "time",
    "tempfile",
    "test",
    "tabnanny",
    "textwrap",
    "this",
    "threading",
    "tokenize",
    "token",
    "tomllib",
    "trace",
    "traceback",
    "types",
    "unicodedata",
    "urllib",
    "uuid",
    "xmlrpc",
    "zipapp",
    "zipfile",
    "zipimport",
    "zoneinfo",
    "zlib",
    "_abc",
    "_collections_abc",
    "_asyncio",
    "_bz2",
    "_weakref",
    "_weakrefset",
    "weakref",
    "typing",
    "unittest",
    "warnings",
    "wsgiref",
    "timeit",
    "quopri",
    "pickletools",
    "faulthandler",
    "tracemalloc",
    "pyexpat",
    "codeop",
    "cProfile",
    "sre_compile",
    "sre_constants",
    "sre_parse",
]
