"""Intrinsic-first stdlib module stub for `_apple_support`.

Generated by tools/gen_stdlib_stubs.py; lowering the module replaces this file.
"""


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `_apple_support` module stub with a full lowering.
def __getattr__(attr: str):
    raise RuntimeError(
        'stdlib module "_apple_support" is not fully lowered yet; only an intrinsic-first stub is available.'
    )
