"""Intrinsic-backed CPython compatibility outcomes; generated by tools/compatibility_error_protocol.py."""
from _intrinsics import require_intrinsic as _require_intrinsic

_MOLT_COMPATIBILITY_ERROR = _require_intrinsic("molt_compatibility_error")


def counter_fromkeys_error():
    return _MOLT_COMPATIBILITY_ERROR(1)


def windows_add_signal_handler_error():
    return _MOLT_COMPATIBILITY_ERROR(2)


def windows_remove_signal_handler_error():
    return _MOLT_COMPATIBILITY_ERROR(2)


def abstract_add_signal_handler_error():
    return _MOLT_COMPATIBILITY_ERROR(3)


def abstract_remove_signal_handler_error():
    return _MOLT_COMPATIBILITY_ERROR(3)


del _require_intrinsic
