# Shim churn audit: 41 intrinsic-direct / 41 total exports (via _operator)
"""Operator helpers for Molt.

Operator helpers are backed by runtime intrinsics; missing intrinsics are a hard error.
All exports are intrinsic-direct bindings from _operator (MOL-215).
"""

from __future__ import annotations

from _intrinsics import require_intrinsic as _require_intrinsic
from _operator import (
    abs,
    add,
    and_,
    attrgetter,
    concat,
    contains,
    countOf,
    delitem,
    eq,
    floordiv,
    ge,
    getitem,
    gt,
    iadd,
    iand,
    iconcat,
    ifloordiv,
    ilshift,
    imatmul,
    imod,
    imul,
    index,
    inv,
    invert,
    ior,
    ipow,
    irshift,
    is_,
    is_not,
    isub,
    itemgetter,
    itruediv,
    ixor,
    le,
    length_hint,
    lshift,
    lt,
    matmul,
    methodcaller,
    mod,
    mul,
    ne,
    neg,
    not_,
    or_,
    pos,
    pow,
    rshift,
    setitem,
    sub,
    truediv,
    truth,
    xor,
)

# Keep this top-level wrapper explicitly intrinsic-gated so strict stdlib
# enforcement never classifies `operator` as python-only.
_MOLT_OPERATOR_MODULE_MARKER = _require_intrinsic("molt_operator_truth")

__all__ = [
    "abs",
    "add",
    "and_",
    "attrgetter",
    "concat",
    "contains",
    "countOf",
    "delitem",
    "eq",
    "floordiv",
    "ge",
    "getitem",
    "gt",
    "iadd",
    "iand",
    "iconcat",
    "ifloordiv",
    "ilshift",
    "imatmul",
    "imod",
    "imul",
    "index",
    "inv",
    "invert",
    "ior",
    "ipow",
    "irshift",
    "is_",
    "is_not",
    "isub",
    "itemgetter",
    "itruediv",
    "ixor",
    "le",
    "length_hint",
    "lshift",
    "lt",
    "matmul",
    "methodcaller",
    "mod",
    "mul",
    "ne",
    "neg",
    "not_",
    "or_",
    "pos",
    "pow",
    "rshift",
    "setitem",
    "sub",
    "truediv",
    "truth",
    "xor",
]
