"""DFlash adapter and contract surface for Molt GPU generation."""

from .adapters import (
    DFLASH_ALGORITHM_FAMILIES,
    DFLASH_ALGORITHM_DRAFT_OUTPUT_CONTRACTS,
    DFlashAdapterMetadata,
    DFlashAdapterSpec,
    get_dflash_adapter,
    list_dflash_adapters,
    register_dflash_adapter,
    clear_dflash_adapters,
    build_dflash_runtime,
    restore_dflash_adapters,
    resolve_dflash_adapter,
    resolve_default_dflash_adapter,
    resolve_dflash_runtime,
    snapshot_dflash_adapters,
)
from .contracts import (
    DFLASH_DRAFT_OUTPUT_CONTRACTS,
    DFLASH_SUPPORTED_BACKENDS,
    DFlashConditioning,
    DFlashRuntime,
    DFlashSelectionContext,
    has_dflash_backend,
    require_dflash_conditioning,
    require_dflash_draft_output_contract,
)

__all__ = [
    "DFlashConditioning",
    "DFlashRuntime",
    "DFlashSelectionContext",
    "DFLASH_ALGORITHM_FAMILIES",
    "DFLASH_ALGORITHM_DRAFT_OUTPUT_CONTRACTS",
    "DFLASH_DRAFT_OUTPUT_CONTRACTS",
    "DFLASH_SUPPORTED_BACKENDS",
    "DFlashAdapterMetadata",
    "DFlashAdapterSpec",
    "require_dflash_conditioning",
    "require_dflash_draft_output_contract",
    "register_dflash_adapter",
    "clear_dflash_adapters",
    "get_dflash_adapter",
    "snapshot_dflash_adapters",
    "restore_dflash_adapters",
    "build_dflash_runtime",
    "resolve_dflash_adapter",
    "resolve_default_dflash_adapter",
    "resolve_dflash_runtime",
    "has_dflash_backend",
    "list_dflash_adapters",
]
