"""DFlash adapter and contract surface for Molt GPU generation."""

from .adapters import (
    DFlashAdapterSpec,
    get_dflash_adapter,
    has_dflash_backend,
    list_dflash_adapters,
    register_dflash_adapter,
    clear_dflash_adapters,
    build_dflash_runtime,
    restore_dflash_adapters,
    resolve_dflash_adapter,
    resolve_default_dflash_adapter,
    resolve_dflash_runtime,
    snapshot_dflash_adapters,
)
from .contracts import (
    DFlashConditioning,
    DFlashRuntime,
    DFlashSelectionContext,
    SpeculativeConditioning,
    SpeculativeDraftRequest,
    SpeculativeDraftResult,
    SpeculativeVerifyRequest,
    SpeculativeVerifyResult,
    require_dflash_conditioning,
)

__all__ = [
    "SpeculativeConditioning",
    "DFlashConditioning",
    "DFlashRuntime",
    "DFlashSelectionContext",
    "DFlashAdapterSpec",
    "SpeculativeDraftRequest",
    "SpeculativeDraftResult",
    "SpeculativeVerifyRequest",
    "SpeculativeVerifyResult",
    "require_dflash_conditioning",
    "register_dflash_adapter",
    "clear_dflash_adapters",
    "get_dflash_adapter",
    "snapshot_dflash_adapters",
    "restore_dflash_adapters",
    "build_dflash_runtime",
    "resolve_dflash_adapter",
    "resolve_default_dflash_adapter",
    "resolve_dflash_runtime",
    "has_dflash_backend",
    "list_dflash_adapters",
]
