"""Intrinsic-first stdlib module stub for `xml.dom.minicompat`.

Generated by tools/gen_stdlib_stubs.py; lowering the module replaces this file.
"""


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `xml.dom.minicompat` module stub with a full lowering.
def __getattr__(attr: str):
    raise RuntimeError(
        'stdlib module "xml.dom.minicompat" is not fully lowered yet; only an intrinsic-first stub is available.'
    )
