//! OpenClDevice — OpenCL device backend type definitions.
//!
//! Defines the Rust-side types for an OpenCL compute backend. The actual
//! OpenCL runtime FFI (clCreateContext, clCreateBuffer, clEnqueueNDRangeKernel,
//! etc.) is not implemented here — this module provides the type scaffolding
//! and metadata that a future OpenCL FFI layer will consume.
//!
//! ## Architecture
//!
//! The Rust side provides:
//! - Buffer handle type for OpenCL (`OpenClBuffer`)
//! - Compiled program representation (`OpenClProgram`)
//! - Device capability metadata (`OpenClDeviceLimits`)
//! - DType support queries (fp64 extension, bf16 narrowing)
//!
//! The actual OpenCL calls (clCreateBuffer, clBuildProgram, clEnqueueNDRangeKernel)
//! will be added when the FFI layer is implemented. This crate defines the
//! Rust-side contract that the FFI layer must fulfill.
//!
//! ## fp64 Extension Handling
//!
//! OpenCL does not guarantee f64 support. Devices must advertise the
//! `cl_khr_fp64` extension. The `OpenClDeviceLimits::has_fp64` field
//! tracks this, and all dtype operations respect it via `DType::narrow_opencl`.

use crate::dtype::DType;

/// An OpenCL buffer handle.
///
/// Represents a `cl_mem` object on the device. The `id` is an opaque
/// handle that maps to the actual `cl_mem` pointer in the FFI layer.
#[derive(Debug, Clone)]
pub struct OpenClBuffer {
    /// Opaque buffer ID (maps to a cl_mem in the FFI layer).
    pub id: u64,
    /// Size of the buffer in bytes.
    pub size_bytes: usize,
    /// Element dtype (post-narrowing via `narrow_opencl`).
    pub dtype: DType,
    /// Number of logical elements.
    pub num_elements: usize,
}

/// A compiled OpenCL program (kernel).
///
/// Represents a `cl_kernel` extracted from a `cl_program` built from
/// the OpenCL C source generated by `OpenClRenderer`.
#[derive(Debug, Clone)]
pub struct OpenClProgram {
    /// Opaque program ID (maps to a cl_kernel in the FFI layer).
    pub id: u64,
    /// The OpenCL C kernel source code.
    pub source: String,
    /// Entry point function name (always "molt_kernel").
    pub entry: String,
}

/// Device capability limits for an OpenCL device.
///
/// Queried from the device at initialization time via
/// `clGetDeviceInfo(CL_DEVICE_MAX_WORK_GROUP_SIZE)`, etc.
#[derive(Debug, Clone, Copy)]
pub struct OpenClDeviceLimits {
    /// Maximum work-items per work-group (from `CL_DEVICE_MAX_WORK_GROUP_SIZE`).
    pub max_work_group_size: u32,
    /// Maximum work-items per dimension (from `CL_DEVICE_MAX_WORK_ITEM_SIZES`).
    pub max_work_item_sizes: [u32; 3],
    /// Maximum global work size per dimension.
    /// Derived from `CL_DEVICE_MAX_WORK_GROUP_SIZE * max_compute_units * ...`
    /// In practice, OpenCL allows very large global sizes (2^32 or more).
    pub max_global_size: [u32; 3],
    /// Whether the device supports `cl_khr_fp64` (double precision).
    pub has_fp64: bool,
    /// Whether the device supports `cl_khr_fp16` (half precision).
    pub has_fp16: bool,
    /// Maximum local (shared) memory size in bytes (from `CL_DEVICE_LOCAL_MEM_SIZE`).
    pub local_mem_size: u64,
    /// Number of compute units (from `CL_DEVICE_MAX_COMPUTE_UNITS`).
    pub max_compute_units: u32,
}

impl Default for OpenClDeviceLimits {
    /// Default limits representing a conservative OpenCL 1.2 device.
    fn default() -> Self {
        Self {
            max_work_group_size: 256,
            max_work_item_sizes: [256, 256, 256],
            max_global_size: [u32::MAX, u32::MAX, u32::MAX],
            has_fp64: false,
            has_fp16: false,
            local_mem_size: 32768, // 32 KiB (common minimum)
            max_compute_units: 1,
        }
    }
}

impl OpenClDeviceLimits {
    /// Maximum local (threadgroup/workgroup) size per dimension,
    /// matching the `Compiler` trait contract.
    pub fn max_local_size(&self) -> [u32; 3] {
        self.max_work_item_sizes
    }

    /// Maximum grid size per dimension,
    /// matching the `Compiler` trait contract.
    pub fn max_grid_size(&self) -> [u32; 3] {
        self.max_global_size
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_limits() {
        let limits = OpenClDeviceLimits::default();
        assert_eq!(limits.max_work_group_size, 256);
        assert!(!limits.has_fp64);
        assert!(!limits.has_fp16);
        assert_eq!(limits.local_mem_size, 32768);
    }

    #[test]
    fn test_buffer_metadata() {
        let buf = OpenClBuffer {
            id: 42,
            size_bytes: 4096,
            dtype: DType::Float32,
            num_elements: 1024,
        };
        assert_eq!(buf.size_bytes, 4096);
        assert_eq!(buf.num_elements, 1024);
        assert_eq!(buf.dtype, DType::Float32);
    }

    #[test]
    fn test_program_metadata() {
        let prog = OpenClProgram {
            id: 1,
            source: "__kernel void molt_kernel() {}".to_string(),
            entry: "molt_kernel".to_string(),
        };
        assert_eq!(prog.entry, "molt_kernel");
        assert!(prog.source.contains("__kernel"));
    }

    #[test]
    fn test_limits_trait_methods() {
        let limits = OpenClDeviceLimits {
            max_work_group_size: 512,
            max_work_item_sizes: [512, 512, 64],
            max_global_size: [65535, 65535, 65535],
            has_fp64: true,
            has_fp16: true,
            local_mem_size: 65536,
            max_compute_units: 32,
        };
        assert_eq!(limits.max_local_size(), [512, 512, 64]);
        assert_eq!(limits.max_grid_size(), [65535, 65535, 65535]);
    }
}
