#ifndef NPY__CPU_DISPATCHER_CONF_H_
#define NPY__CPU_DISPATCHER_CONF_H_

/*
 * Molt currently exposes a single baseline target for NumPy internal-header
 * parsing. This keeps source compatibility moving without inventing NumPy's
 * private CPU-dispatch build graph.
 */
#define NPY_WITH_CPU_BASELINE ""
#define NPY_WITH_CPU_BASELINE_N 0
#define NPY_WITH_CPU_DISPATCH ""
#define NPY_WITH_CPU_DISPATCH_N 0

#define NPY_CPU_EXPAND(x) x
#define NPY_CPU_CAT__(a, b) a##b
#define NPY_CPU_CAT_(a, b) NPY_CPU_CAT__(a, b)
#define NPY_CPU_CAT(a, b) NPY_CPU_CAT_(a, b)
#define NPY_CPU_STRINGIFY(x) #x
#define NPY_CPU_TOSTRING(x) NPY_CPU_STRINGIFY(x)

#define NPY_WITH_CPU_BASELINE_CALL(EXEC_CB, ...)
#define NPY_WITH_CPU_DISPATCH_CALL(EXEC_CB, ...)

#define NPY_MTARGETS_CONF_BASELINE(CB, ...) CB(__VA_ARGS__)
#define NPY_MTARGETS_CONF_DISPATCH(TEST_FEATURE_CB, CB, ...)

#define NPY_CPU_DISPATCH_CURFX(NAME) NPY_CPU_EXPAND(NAME)

#define NPY_CPU_DISPATCH_DECLARE(...) \
    NPY_MTARGETS_CONF_BASELINE(NPY_CPU_DISPATCH_DECLARE_BASE_CB_, __VA_ARGS__)
#define NPY_CPU_DISPATCH_DECLARE_CB_(DUMMY, TARGET_NAME, LEFT, ...) \
    NPY_CPU_CAT(NPY_CPU_CAT(LEFT, _), TARGET_NAME) __VA_ARGS__;
#define NPY_CPU_DISPATCH_DECLARE_BASE_CB_(LEFT, ...) LEFT __VA_ARGS__;
#define NPY_CPU_DISPATCH_DECLARE_CHK_(FEATURE_NAME)
#define NPY_CPU_DISPATCH_DECLARE_XB(...)

#define NPY_CPU_DISPATCH_CALL(...) \
    NPY_MTARGETS_CONF_BASELINE(NPY_CPU_DISPATCH_CALL_BASE_CB_, __VA_ARGS__)
#define NPY_CPU_DISPATCH_CALL_CB_(TESTED_FEATURES, TARGET_NAME, LEFT, ...) \
    (TESTED_FEATURES) ? (NPY_CPU_CAT(NPY_CPU_CAT(LEFT, _), TARGET_NAME) __VA_ARGS__) :
#define NPY_CPU_DISPATCH_CALL_BASE_CB_(LEFT, ...) (LEFT __VA_ARGS__)

#define NPY_CPU_DISPATCH_CALL_XB(...) ((void)0)

#define NPY_CPU_DISPATCH_INFO() {"baseline()", "baseline()"}
#define NPY_CPU_DISPATCH_INFO_HIGH_CB_(TESTED_FEATURES, TARGET_NAME, ...)
#define NPY_CPU_DISPATCH_INFO_BASE_HIGH_CB_(...) "baseline()"
#define NPY_CPU_DISPATCH_INFO_CB_(TESTED_FEATURES, TARGET_NAME, ...)
#define NPY_CPU_DISPATCH_INFO_BASE_CB_(...) "baseline()"

#define NPY_CPU_DISPATCH_CALL_ALL(...) \
    (NPY_MTARGETS_CONF_BASELINE(NPY_CPU_DISPATCH_CALL_ALL_BASE_CB_, __VA_ARGS__))
#define NPY_CPU_DISPATCH_CALL_ALL_CB_(TESTED_FEATURES, TARGET_NAME, LEFT, ...) \
    ((TESTED_FEATURES) ? (NPY_CPU_CAT(NPY_CPU_CAT(LEFT, _), TARGET_NAME) __VA_ARGS__) : (void)0),
#define NPY_CPU_DISPATCH_CALL_ALL_BASE_CB_(LEFT, ...) (LEFT __VA_ARGS__)

#endif
