use super::super::RustBackend;

impl RustBackend {
    pub(super) fn emit_callable_runtime_prelude(&mut self, func_body: &str) {
        let used = |name: &str| func_body.contains(name);
        // Runtime lifecycle hooks are no-ops for standalone binaries.
        if used("molt_runtime_init(") {
            self.output.push_str(concat!(
                "fn molt_runtime_init(_args: &mut Vec<MoltValue>) -> MoltValue { MoltValue::None }\n",
                "fn molt_runtime_shutdown(_args: &mut Vec<MoltValue>) -> MoltValue { MoltValue::None }\n\n",
            ));
        }

        // Dynamic call dispatch
        if used("molt_call(") {
            self.output.push_str(concat!(
                "fn molt_call(f: &MoltValue, args: &mut Vec<MoltValue>) -> MoltValue {\n",
                "    if let MoltValue::Func(func) = f { func(args) } else { panic!(\"TypeError: object is not callable\") }\n",
                "}\n\n",
            ));
        }
        if used("molt_builtin_func(") {
            self.output.push_str(concat!(
                "fn molt_builtin_positional(args: &[MoltValue]) -> Vec<MoltValue> {\n",
                "    if let Some(MoltValue::List(v)) = args.first() {\n",
                "        let rest_is_none = args.get(1..).is_some_and(|rest| rest.iter().all(|x| matches!(x, MoltValue::None)));\n",
                "        if args.len() == 1 || rest_is_none {\n",
                "            return v.clone();\n",
                "        }\n",
                "    }\n",
                "    args.to_vec()\n",
                "}\n\n",
                "fn molt_builtin_func(name: &str) -> MoltValue {\n",
                "    let canonical = match name {\n",
                "        \"int\" => \"molt_int_builtin\",\n",
                "        \"float\" => \"molt_float_builtin\",\n",
                "        \"bool\" => \"molt_bool_builtin\",\n",
                "        \"str\" => \"molt_str_builtin\",\n",
                "        \"len\" => \"molt_len_builtin\",\n",
                "        \"min\" => \"molt_min_builtin\",\n",
                "        \"max\" => \"molt_max_builtin\",\n",
                "        \"sum\" => \"molt_sum_builtin\",\n",
                "        \"enumerate\" => \"molt_enumerate_builtin\",\n",
                "        \"zip\" => \"molt_zip_builtin\",\n",
                "        \"range\" => \"molt_range_builtin\",\n",
                "        other => other,\n",
                "    };\n",
                "    match canonical {\n",
                "        \"molt_function_init_metadata_packed\" | \"molt_function_set_defaults\" => MoltValue::Func(Arc::new(|_args: &mut Vec<MoltValue>| {\n",
                "            MoltValue::None\n",
                "        })),\n",
                "        \"molt_function_set_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            molt_builtin_positional(args).into_iter().next().unwrap_or(MoltValue::None)\n",
                "        })),\n",
                "        \"molt_int_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            MoltValue::Int(pos.first().map_or(0, molt_int))\n",
                "        })),\n",
                "        \"molt_float_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            MoltValue::Float(pos.first().map_or(0.0, molt_float))\n",
                "        })),\n",
                "        \"molt_bool_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            MoltValue::Bool(pos.first().is_some_and(molt_bool))\n",
                "        })),\n",
                "        \"molt_str_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            MoltValue::Str(pos.first().map_or_else(String::new, molt_str))\n",
                "        })),\n",
                "        \"molt_len_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            if let Some(v) = pos.first() {\n",
                "                match v {\n",
                "                    MoltValue::Str(s) => MoltValue::Int(s.chars().count() as i64),\n",
                "                    MoltValue::List(items) => MoltValue::Int(items.len() as i64),\n",
                "                    MoltValue::Dict(items) => MoltValue::Int(items.len() as i64),\n",
                "                    _ => panic!(\"TypeError: object has no len()\"),\n",
                "                }\n",
                "            } else {\n",
                "                panic!(\"TypeError: len() missing required argument\")\n",
                "            }\n",
                "        })),\n",
                "        \"molt_min_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let mut pos = molt_builtin_positional(args);\n",
                "            if pos.len() == 1 { if let MoltValue::List(items) = &pos[0] { pos = items.clone(); } }\n",
                "            if pos.is_empty() {\n",
                "                panic!(\"ValueError: min() arg is an empty sequence\");\n",
                "            }\n",
                "            let mut best = pos[0].clone();\n",
                "            for value in pos.into_iter().skip(1) {\n",
                "                if molt_int(&value) < molt_int(&best) {\n",
                "                    best = value;\n",
                "                }\n",
                "            }\n",
                "            best\n",
                "        })),\n",
                "        \"molt_max_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let mut pos = molt_builtin_positional(args);\n",
                "            if pos.len() == 1 { if let MoltValue::List(items) = &pos[0] { pos = items.clone(); } }\n",
                "            if pos.is_empty() {\n",
                "                panic!(\"ValueError: max() arg is an empty sequence\");\n",
                "            }\n",
                "            let mut best = pos[0].clone();\n",
                "            for value in pos.into_iter().skip(1) {\n",
                "                if molt_int(&value) > molt_int(&best) {\n",
                "                    best = value;\n",
                "                }\n",
                "            }\n",
                "            best\n",
                "        })),\n",
                "        \"molt_sum_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            let mut acc = if pos.len() > 1 { pos[1].clone() } else { MoltValue::Int(0) };\n",
                "            if let Some(MoltValue::List(items)) = pos.first() {\n",
                "                for value in items {\n",
                "                    let next = molt_int_add(molt_int(&acc), molt_int(value));\n",
                "                    acc = MoltValue::Int(next);\n",
                "                }\n",
                "            }\n",
                "            acc\n",
                "        })),\n",
                "        \"molt_enumerate_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            if let Some(iterable) = pos.first() {\n",
                "                let start = pos.get(1).map_or(0, molt_int);\n",
                "                molt_enumerate(iterable, start)\n",
                "            } else {\n",
                "                panic!(\"TypeError: enumerate() missing required argument\")\n",
                "            }\n",
                "        })),\n",
                "        \"molt_zip_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            if pos.len() >= 2 {\n",
                "                molt_zip(&pos[0], &pos[1])\n",
                "            } else {\n",
                "                MoltValue::List(vec![])\n",
                "            }\n",
                "        })),\n",
                "        \"molt_range_builtin\" => MoltValue::Func(Arc::new(|args: &mut Vec<MoltValue>| {\n",
                "            let pos = molt_builtin_positional(args);\n",
                "            let (start, stop, step) = match pos.len() {\n",
                "                0 => panic!(\"TypeError: range expected at least 1 argument\"),\n",
                "                1 => (0, molt_int(&pos[0]), 1),\n",
                "                2 => (molt_int(&pos[0]), molt_int(&pos[1]), 1),\n",
                "                _ => (molt_int(&pos[0]), molt_int(&pos[1]), molt_int(&pos[2])),\n",
                "            };\n",
                "            molt_range(start, stop, step)\n",
                "        })),\n",
                "        _ => panic!(\"unsupported builtin in Rust backend: {canonical}\"),\n",
                "    }\n",
                "}\n\n",
            ));
        }

        // Math module shim
        if used("molt_math_") {
            self.output.push_str(concat!(
                "mod molt_math {\n",
                "    pub fn floor(x: f64) -> f64 { x.floor() }\n",
                "    pub fn ceil(x: f64) -> f64 { x.ceil() }\n",
                "    pub fn sqrt(x: f64) -> f64 { x.sqrt() }\n",
                "    pub fn abs_f(x: f64) -> f64 { x.abs() }\n",
                "    pub fn sin(x: f64) -> f64 { x.sin() }\n",
                "    pub fn cos(x: f64) -> f64 { x.cos() }\n",
                "    pub fn tan(x: f64) -> f64 { x.tan() }\n",
                "    pub fn log(x: f64) -> f64 { x.ln() }\n",
                "    pub fn log10(x: f64) -> f64 { x.log10() }\n",
                "    pub fn exp(x: f64) -> f64 { x.exp() }\n",
                "    pub fn atan2(y: f64, x: f64) -> f64 { y.atan2(x) }\n",
                "    pub const PI: f64 = std::f64::consts::PI;\n",
                "    pub const E: f64 = std::f64::consts::E;\n",
                "    pub const INF: f64 = f64::INFINITY;\n",
                "}\n\n",
            ));
        }
    }
}
