use super::super::RustBackend;

impl RustBackend {
    pub(super) fn emit_stateful_runtime_prelude(&mut self, func_body: &str) {
        let used = |name: &str| func_body.contains(name);
        if used("molt_code_new(") || used("molt_code_slot_set(") || used("molt_code_slots_init(") {
            self.output.push_str(concat!(
                "thread_local! {\n",
                "    static MOLT_CODE_SLOTS: std::cell::RefCell<Vec<Option<MoltValue>>> = const { std::cell::RefCell::new(Vec::new()) };\n",
                "}\n\n",
                "fn molt_expect_code_str(value: &MoltValue, field: &str) -> String {\n",
                "    if let MoltValue::Str(s) = value { s.clone() } else { panic!(\"TypeError: code {field} must be str\") }\n",
                "}\n\n",
                "fn molt_expect_code_count(value: &MoltValue, field: &str) -> i64 {\n",
                "    let n = molt_int(value);\n",
                "    if n < 0 { panic!(\"ValueError: code {field} must be >= 0\") }\n",
                "    n\n",
                "}\n\n",
                "fn molt_code_is_code(value: &MoltValue) -> bool {\n",
                "    if let MoltValue::Dict(fields) = value {\n",
                "        fields.iter().any(|(key, value)| matches!((key, value), (MoltValue::Str(k), MoltValue::Str(v)) if k == \"__molt_type__\" && v == \"code\"))\n",
                "    } else { false }\n",
                "}\n\n",
                "fn molt_code_new(filename: &MoltValue, name: &MoltValue, firstlineno: &MoltValue, linetable: &MoltValue, varnames: &MoltValue, names: &MoltValue, argcount: &MoltValue, posonlyargcount: &MoltValue, kwonlyargcount: &MoltValue) -> MoltValue {\n",
                "    let filename = molt_expect_code_str(filename, \"filename\");\n",
                "    let name = molt_expect_code_str(name, \"name\");\n",
                "    let firstlineno = molt_int(firstlineno);\n",
                "    let argcount = molt_expect_code_count(argcount, \"argcount\");\n",
                "    let posonlyargcount = molt_expect_code_count(posonlyargcount, \"posonlyargcount\");\n",
                "    let kwonlyargcount = molt_expect_code_count(kwonlyargcount, \"kwonlyargcount\");\n",
                "    MoltValue::Dict(vec![\n",
                "        (MoltValue::Str(\"__molt_type__\".to_string()), MoltValue::Str(\"code\".to_string())),\n",
                "        (MoltValue::Str(\"co_filename\".to_string()), MoltValue::Str(filename)),\n",
                "        (MoltValue::Str(\"co_name\".to_string()), MoltValue::Str(name)),\n",
                "        (MoltValue::Str(\"co_firstlineno\".to_string()), MoltValue::Int(firstlineno)),\n",
                "        (MoltValue::Str(\"co_linetable\".to_string()), linetable.clone()),\n",
                "        (MoltValue::Str(\"co_varnames\".to_string()), varnames.clone()),\n",
                "        (MoltValue::Str(\"co_names\".to_string()), names.clone()),\n",
                "        (MoltValue::Str(\"co_argcount\".to_string()), MoltValue::Int(argcount)),\n",
                "        (MoltValue::Str(\"co_posonlyargcount\".to_string()), MoltValue::Int(posonlyargcount)),\n",
                "        (MoltValue::Str(\"co_kwonlyargcount\".to_string()), MoltValue::Int(kwonlyargcount)),\n",
                "    ])\n",
                "}\n\n",
                "fn molt_code_slots_init(count: i64) -> MoltValue {\n",
                "    if count < 0 { panic!(\"MemoryError: code slot count too large\") }\n",
                "    MOLT_CODE_SLOTS.with(|slots| {\n",
                "        let mut slots = slots.borrow_mut();\n",
                "        if slots.is_empty() {\n",
                "            slots.resize(count as usize, None);\n",
                "        }\n",
                "    });\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_code_slot_set(code_id: i64, code: &MoltValue) -> MoltValue {\n",
                "    if !molt_code_is_code(code) { panic!(\"TypeError: code slot expects code object\") }\n",
                "    let Some(idx) = usize::try_from(code_id).ok() else { panic!(\"IndexError: code slot out of range\") };\n",
                "    MOLT_CODE_SLOTS.with(|slots| {\n",
                "        let mut slots = slots.borrow_mut();\n",
                "        if idx >= slots.len() { panic!(\"IndexError: code slot out of range\") }\n",
                "        slots[idx] = Some(code.clone());\n",
                "    });\n",
                "    MoltValue::None\n",
                "}\n\n",
            ));
        }
        if used("molt_trace_enter_slot(")
            || used("molt_trace_exit(")
            || used("molt_frame_locals_set(")
        {
            self.output.push_str(concat!(
                "#[derive(Clone)]\n",
                "struct MoltFrame {\n",
                "    code_id: i64,\n",
                "    locals: Option<MoltValue>,\n",
                "}\n\n",
                "thread_local! {\n",
                "    static MOLT_FRAME_STACK: std::cell::RefCell<Vec<MoltFrame>> = const { std::cell::RefCell::new(Vec::new()) };\n",
                "}\n\n",
                "fn molt_trace_enter_slot(code_id: i64) -> MoltValue {\n",
                "    MOLT_FRAME_STACK.with(|stack| stack.borrow_mut().push(MoltFrame { code_id, locals: None }));\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_trace_exit() -> MoltValue {\n",
                "    MOLT_FRAME_STACK.with(|stack| { stack.borrow_mut().pop(); });\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_frame_locals_set(locals: &MoltValue) -> MoltValue {\n",
                "    MOLT_FRAME_STACK.with(|stack| {\n",
                "        if let Some(frame) = stack.borrow_mut().last_mut() {\n",
                "            frame.locals = Some(locals.clone());\n",
                "        }\n",
                "    });\n",
                "    MoltValue::None\n",
                "}\n\n",
            ));
        }
        if used("molt_exception_") {
            self.output.push_str(concat!(
                "thread_local! {\n",
                "    static MOLT_EXCEPTION_LAST: std::cell::RefCell<Option<MoltValue>> = const { std::cell::RefCell::new(None) };\n",
                "    static MOLT_EXCEPTION_CONTEXT: std::cell::RefCell<Option<MoltValue>> = const { std::cell::RefCell::new(None) };\n",
                "    static MOLT_EXCEPTION_STACK_DEPTH: std::cell::RefCell<usize> = const { std::cell::RefCell::new(0) };\n",
                "    static MOLT_EXCEPTION_STACK_BASELINE: std::cell::RefCell<usize> = const { std::cell::RefCell::new(0) };\n",
                "}\n\n",
                "fn molt_exception_is_exception(value: &MoltValue) -> bool {\n",
                "    if let MoltValue::Dict(fields) = value {\n",
                "        fields.iter().any(|(key, value)| matches!((key, value), (MoltValue::Str(k), MoltValue::Str(v)) if k == \"__molt_type__\" && v == \"exception\"))\n",
                "    } else { false }\n",
                "}\n\n",
                "fn molt_exception_last() -> MoltValue {\n",
                "    if let Some(exc) = MOLT_EXCEPTION_LAST.with(|slot| slot.borrow().clone()) {\n",
                "        return exc;\n",
                "    }\n",
                "    MOLT_EXCEPTION_CONTEXT.with(|slot| slot.borrow().clone().unwrap_or(MoltValue::None))\n",
                "}\n\n",
                "fn molt_exception_last_pending() -> MoltValue {\n",
                "    MOLT_EXCEPTION_LAST.with(|slot| slot.borrow().clone().unwrap_or(MoltValue::None))\n",
                "}\n\n",
                "fn molt_exception_active() -> MoltValue {\n",
                "    MOLT_EXCEPTION_CONTEXT.with(|slot| slot.borrow().clone().unwrap_or(MoltValue::None))\n",
                "}\n\n",
                "fn molt_exception_clear() -> MoltValue {\n",
                "    MOLT_EXCEPTION_LAST.with(|slot| *slot.borrow_mut() = None);\n",
                "    MOLT_EXCEPTION_CONTEXT.with(|slot| *slot.borrow_mut() = None);\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_exception_set_last(exc: &MoltValue) -> MoltValue {\n",
                "    if matches!(exc, MoltValue::None) || !molt_exception_is_exception(exc) {\n",
                "        return molt_exception_clear();\n",
                "    }\n",
                "    MOLT_EXCEPTION_LAST.with(|slot| *slot.borrow_mut() = Some(exc.clone()));\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_exception_stack_enter() -> MoltValue {\n",
                "    let prev = MOLT_EXCEPTION_STACK_BASELINE.with(|baseline| *baseline.borrow());\n",
                "    let depth = MOLT_EXCEPTION_STACK_DEPTH.with(|depth| *depth.borrow());\n",
                "    MOLT_EXCEPTION_STACK_BASELINE.with(|baseline| *baseline.borrow_mut() = depth);\n",
                "    MoltValue::Int(prev as i64)\n",
                "}\n\n",
                "fn molt_exception_stack_depth() -> MoltValue {\n",
                "    let depth = MOLT_EXCEPTION_STACK_DEPTH.with(|depth| *depth.borrow());\n",
                "    MoltValue::Int(depth as i64)\n",
                "}\n\n",
                "fn molt_exception_stack_exit(prev: &MoltValue) -> MoltValue {\n",
                "    let prev = molt_int(prev);\n",
                "    MOLT_EXCEPTION_STACK_BASELINE.with(|baseline| *baseline.borrow_mut() = if prev >= 0 { prev as usize } else { 0 });\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_exception_stack_set_depth(depth: &MoltValue) -> MoltValue {\n",
                "    let depth = molt_int(depth);\n",
                "    MOLT_EXCEPTION_STACK_DEPTH.with(|slot| *slot.borrow_mut() = if depth >= 0 { depth as usize } else { 0 });\n",
                "    MoltValue::None\n",
                "}\n\n",
                "fn molt_exception_stack_clear() -> MoltValue {\n",
                "    MOLT_EXCEPTION_STACK_DEPTH.with(|depth| *depth.borrow_mut() = 0);\n",
                "    MOLT_EXCEPTION_STACK_BASELINE.with(|baseline| *baseline.borrow_mut() = 0);\n",
                "    MoltValue::None\n",
                "}\n\n",
            ));
        }
    }
}
