#!/usr/bin/env python3
"""Check generated runtime satellite bridge test stubs.

Bridge-backed runtime satellite crates link against `molt-runtime` in
production, but their unit-test binaries need local symbols for pure tests.
The shared stub file is intentionally generated from the real extern
declarations so link-only test support cannot drift from the bridge surface.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
STUB_PATH = REPO_ROOT / "runtime/molt-runtime-core/src/bridge_test_stubs.rs"

EXTERN_START_RE = re.compile(r'\bextern\s+"C"\s*\{')
FN_DECL_RE = re.compile(
    r"^\s*(?:pub(?:\([^)]*\))?\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\("
)
STUB_RE = re.compile(r"aborting_bridge_stub!\(([A-Za-z_][A-Za-z0-9_]*)\);")


def bridge_sources() -> list[Path]:
    sources = [REPO_ROOT / "runtime/molt-runtime-core/src/lib.rs"]
    sources.extend(sorted((REPO_ROOT / "runtime").glob("molt-runtime-*/src/bridge.rs")))
    return sources


def strip_line_comment(line: str) -> str:
    in_string = False
    escaped = False
    for index, char in enumerate(line):
        if escaped:
            escaped = False
            continue
        if char == "\\" and in_string:
            escaped = True
            continue
        if char == '"':
            in_string = not in_string
            continue
        if not in_string and line[index : index + 2] == "//":
            return line[:index]
    return line


def declared_bridge_symbols() -> list[str]:
    symbols: set[str] = set()
    for source in bridge_sources():
        in_extern = False
        brace_depth = 0
        for raw_line in source.read_text(encoding="utf-8").splitlines():
            line = strip_line_comment(raw_line)
            if not in_extern and EXTERN_START_RE.search(line):
                in_extern = True
                brace_depth = line.count("{") - line.count("}")
                continue
            if not in_extern:
                continue

            match = FN_DECL_RE.match(line)
            if match:
                symbols.add(match.group(1))

            brace_depth += line.count("{") - line.count("}")
            if brace_depth <= 0:
                in_extern = False
                brace_depth = 0
    return sorted(symbols)


def rendered_stub(symbols: list[str]) -> str:
    lines = [
        "//! Test-only aborting bridge symbols for runtime satellite unit tests.",
        "//!",
        "//! Generated by `tools/check_runtime_bridge_test_stubs.py --fix` from",
        "//! `molt-runtime-core/src/lib.rs` and satellite `src/bridge.rs` extern",
        "//! declarations. Bridge-backed satellite crates resolve these symbols from",
        "//! `molt-runtime` in production and integration builds; pure unit tests",
        "//! receive link-only stubs that fail closed if bridge behavior is exercised.",
        "",
        "#![allow(dead_code)]",
        "",
        "fn abort_bridge_stub(symbol: &str) -> ! {",
        "    eprintln!(",
        '        "runtime satellite unit test attempted to call bridge symbol `{symbol}`; use an integrated molt-runtime test for bridge behavior"',
        "    );",
        "    std::process::abort();",
        "}",
        "",
        "macro_rules! aborting_bridge_stub {",
        "    ($name:ident) => {",
        "        #[unsafe(no_mangle)]",
        '        pub extern "C" fn $name() -> usize {',
        "            abort_bridge_stub(stringify!($name))",
        "        }",
        "    };",
        "}",
        "",
    ]
    lines.extend(f"aborting_bridge_stub!({symbol});" for symbol in symbols)
    return "\n".join(lines) + "\n"


def existing_stub_symbols() -> list[str]:
    if not STUB_PATH.exists():
        return []
    return sorted(STUB_RE.findall(STUB_PATH.read_text(encoding="utf-8")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fix",
        action="store_true",
        help="rewrite the generated stub file instead of only checking it",
    )
    args = parser.parse_args(argv)

    expected_symbols = declared_bridge_symbols()
    expected = rendered_stub(expected_symbols)

    if args.fix:
        STUB_PATH.write_text(expected, encoding="utf-8")
        print(
            f"wrote {STUB_PATH.relative_to(REPO_ROOT)} ({len(expected_symbols)} symbols)"
        )
        return 0

    actual = STUB_PATH.read_text(encoding="utf-8") if STUB_PATH.exists() else ""
    if actual == expected:
        print(
            f"runtime bridge test stubs are in sync ({len(expected_symbols)} symbols)"
        )
        return 0

    actual_symbols = set(existing_stub_symbols())
    expected_set = set(expected_symbols)
    missing = sorted(expected_set - actual_symbols)
    extra = sorted(actual_symbols - expected_set)
    if missing:
        print("missing bridge test stubs:")
        for symbol in missing:
            print(f"  {symbol}")
    if extra:
        print("extra bridge test stubs:")
        for symbol in extra:
            print(f"  {symbol}")
    if not missing and not extra:
        print("bridge test stub file content is not canonical; run with --fix")
    return 1


if __name__ == "__main__":
    sys.exit(main())
