#!/usr/bin/env python3
"""Project one closed numeric-exception policy into runtime and transpiler consumers."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re
import sys
import tomllib

from generator_io import generator_main

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from molt.target_python import SUPPORTED_TARGET_PYTHON_SHORT_VERSIONS  # noqa: E402

SOURCE = ROOT / "config/python_numeric_errors.toml"
OUTPUTS = tuple(
    ROOT / p
    for p in (
        "runtime/molt-runtime-core/src/numeric_error_policy_generated.rs",
        "runtime/molt-backend-luau/src/luau/numeric_error_policy_generated.rs",
        "runtime/molt-backend-rust/src/rust/numeric_error_policy_generated.rs",
    )
)
TARGETS = SUPPORTED_TARGET_PYTHON_SHORT_VERSIONS
CONTEXT_FIELDS = frozenset(
    {
        "name",
        "operation",
        "operand_kind",
        "error_class",
        "python_3_12",
        "python_3_13",
        "python_3_14",
    }
)
OPERAND_DOMAINS = {
    "truediv": {"int", "float", "complex"},
    "floordiv": {"int", "float"},
    "mod": {"int", "float"},
    "divmod": {"int", "float"},
    "pow": {"real", "complex"},
    "pow_mod": {"int"},
}


class SchemaError(ValueError):
    pass


@dataclass(frozen=True)
class Context:
    name: str
    operation: str
    operand_kind: str
    error_class: str
    messages: tuple[str, str, str]

    @property
    def wire_key(self) -> str:
        return f"{self.operation}:{self.operand_kind}"


def load_policy(path: Path = SOURCE) -> tuple[Context, ...]:
    observed_coordinates = {
        field.removeprefix("python_").replace("_", ".")
        for field in CONTEXT_FIELDS
        if field.startswith("python_")
    }
    if set(TARGETS) != observed_coordinates:
        raise SchemaError("admitted target catalog needs observed numeric coordinates")
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    if set(data) != {"schema_version", "supported_targets", "context"}:
        raise SchemaError("numeric policy fields are not the closed schema")
    if type(data["schema_version"]) is not int or data["schema_version"] != 1:
        raise SchemaError("unsupported numeric policy schema")
    if data["supported_targets"] != list(TARGETS):
        raise SchemaError(
            "numeric policy requires exact ordered 3.12/3.13/3.14 coordinates"
        )
    contexts = data["context"]
    if not isinstance(contexts, list) or not contexts:
        raise SchemaError("numeric context domain must be nonempty")
    result = []
    seen_names: set[str] = set()
    seen_pairs: set[tuple[str, str]] = set()
    for row in contexts:
        if not isinstance(row, dict) or set(row) != CONTEXT_FIELDS:
            raise SchemaError(
                "numeric context fields or target rows are incomplete/unknown"
            )
        if any(not isinstance(v, str) or not v for v in row.values()):
            raise SchemaError("numeric context facts must be nonempty strings")
        name, operation, kind = row["name"], row["operation"], row["operand_kind"]
        if re.fullmatch(r"[A-Z][A-Za-z0-9]*", name) is None or name in seen_names:
            raise SchemaError("numeric context names must be unique Rust identifiers")
        if operation not in OPERAND_DOMAINS or kind not in OPERAND_DOMAINS[operation]:
            raise SchemaError(
                "numeric operand context is not an admitted semantic domain"
            )
        if (operation, kind) in seen_pairs:
            raise SchemaError("duplicate numeric operation/operand context")
        expected_class = "ValueError" if operation == "pow_mod" else "ZeroDivisionError"
        if row["error_class"] != expected_class:
            raise SchemaError("numeric context changed its exception-class domain")
        seen_names.add(name)
        seen_pairs.add((operation, kind))
        result.append(
            Context(
                name,
                operation,
                kind,
                row["error_class"],
                tuple(row[f"python_3_{v}"] for v in (12, 13, 14)),
            )
        )
    expected_pairs = {
        (op, kind) for op, kinds in OPERAND_DOMAINS.items() for kind in kinds
    }
    if seen_pairs != expected_pairs:
        raise SchemaError("numeric semantic operand family is incomplete")
    return tuple(result)


def render(
    contexts: tuple[Context, ...],
    *,
    integer_helper: bool = True,
) -> str:
    lines = [
        "// @generated by tools/gen_python_numeric_errors.py; DO NOT EDIT.",
        "// Source: config/python_numeric_errors.toml. Unknown target coordinates fail closed.",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub enum NumericErrorContext {",
        *(f"    {c.name}," for c in contexts),
        "}",
        "",
        "impl NumericErrorContext {",
        f"    pub const ALL: [Self; {len(contexts)}] = [",
        *(f"        Self::{c.name}," for c in contexts),
        "    ];",
        "",
        "    pub const fn wire_key(self) -> &'static str {",
        "        match self {",
        *(f"            Self::{c.name} => {json.dumps(c.wire_key)}," for c in contexts),
        "        }",
        "    }",
        "",
        "    pub const fn error_class(self) -> &'static str {",
        "        match self {",
        *(
            f"            Self::{c.name} => {json.dumps(c.error_class)},"
            for c in contexts
        ),
        "        }",
        "    }",
        "",
        "    pub const fn message(self, major: i64, minor: i64) -> Option<&'static str> {",
        "        match (major, minor) {",
    ]
    for index, minor in enumerate((12, 13, 14)):
        lines += [f"            (3, {minor}) => Some(match self {{"]
        lines += [
            f"                Self::{c.name} => {json.dumps(c.messages[index], ensure_ascii=False)},"
            for c in contexts
        ]
        lines += ["            }),"]
    lines += ["            _ => None,", "        }", "    }", "}"]
    if integer_helper:
        lines += ["", INTEGER_DIVMOD, FLOAT_DIVMOD]
    else:
        lines += ["", 'pub const FLOAT_DIVMOD_LUA: &str = r#"' + LUA_DIVMOD + '"#;']
    return "\n".join(lines).rstrip() + "\n"


# This integer algorithm is projected with the policy so host and standalone
# transpilers share Python's sign convention, never Euclidean/truncating division.
INTEGER_DIVMOD = """/// Python floor quotient and divisor-signed remainder for bounded integer operands.
/// None preserves explicit zero/representation-overflow admission boundaries.
pub const fn python_integer_divmod(a: i128, b: i128) -> Option<(i128, i128)> {
    let Some(mut q) = a.checked_div(b) else {
        return None;
    };
    let Some(mut r) = a.checked_rem(b) else {
        return None;
    };
    if r != 0 && (r < 0) != (b < 0) {
        q -= 1;
        r += b;
    }
    Some((q, r))
}
"""


def generated_outputs() -> dict[Path, str]:
    """Each output path mapped to its exact generated text."""
    contexts = load_policy()
    return {
        path: render(contexts, integer_helper="molt-backend-luau" not in path.parts)
        for path in OUTPUTS
    }


def main(argv: list[str] | None = None) -> int:
    return generator_main(generated_outputs, argv, description=__doc__)


FLOAT_DIVMOD = r"""/// CPython-compatible fmod-derived floor quotient and divisor-signed remainder.
/// The zero divisor remains a typed caller-owned exception boundary.
pub fn python_float_divmod(a: f64, b: f64) -> Option<(f64, f64)> {
    if b == 0.0 {
        return None;
    }
    let mut remainder = a % b;
    let mut quotient = (a - remainder) / b;
    if remainder != 0.0 {
        if (remainder < 0.0) != (b < 0.0) {
            remainder += b;
            quotient -= 1.0;
        }
    } else {
        remainder = 0.0f64.copysign(b);
    }
    let floor = if quotient != 0.0 {
        let q = quotient.floor();
        if quotient - q > 0.5 { q + 1.0 } else { q }
    } else {
        0.0f64.copysign(a / b)
    };
    Some((floor, remainder))
}

"""

LUA_DIVMOD = r"""local function molt_float_divmod(a: number, b: number): (number, number)
    local remainder = math.fmod(a, b)
    local quotient = (a - remainder) / b
    if remainder ~= 0 then
        if (remainder < 0) ~= (b < 0) then remainder += b; quotient -= 1 end
    else remainder = if b < 0 then -0.0 else 0.0 end
    local floor
    if quotient ~= 0 then
        floor = math.floor(quotient)
        if quotient - floor > 0.5 then floor += 1 end
    else
        local real_quotient = a / b
        floor = if real_quotient < 0 or 1 / real_quotient < 0 then -0.0 else 0.0
    end
    return floor, remainder
end
local function molt_float_floor_div(a: number, b: number): number
    local quotient = molt_float_divmod(a, b)
    return quotient
end
local function molt_float_mod(a: number, b: number): number
    local _, remainder = molt_float_divmod(a, b)
    return remainder
end
"""

if __name__ == "__main__":
    raise SystemExit(main())
