#!/usr/bin/env python3
"""Generate the differential-lane test manifests from COVERAGE_INDEX.yaml.

Single source of truth: ``tests/differential/COVERAGE_INDEX.yaml`` plus the
on-disk stdlib/pyperformance test files. Renders the three lane manifests so the
runner's lane membership cannot silently drift from the coverage index.

Usage::

    uv run --python 3.12 python tools/gen_diff_lanes.py --write
    uv run --python 3.12 python tools/gen_diff_lanes.py --check
"""

from __future__ import annotations

from pathlib import Path

from generator_io import generator_main

ROOT = Path(__file__).resolve().parents[1]
COVERAGE_INDEX = ROOT / "tests" / "differential" / "COVERAGE_INDEX.yaml"
CORE_MANIFEST = ROOT / "tests" / "differential" / "basic" / "CORE_TESTS.txt"
STDLIB_MANIFEST = ROOT / "tests" / "differential" / "stdlib" / "TESTS.txt"
PYPERFORMANCE_MANIFEST = ROOT / "tests" / "differential" / "pyperformance" / "TESTS.txt"

CORE_EXTRA = {
    "tests/differential/basic/try_except.py",
}


def _parse_coverage_lists() -> tuple[set[str], set[str], set[str]]:
    core: set[str] = set()
    stdlib: set[str] = set()
    pyperformance: set[str] = set()
    section: str | None = None
    for raw in COVERAGE_INDEX.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw.startswith("core:"):
            section = "core"
            continue
        if raw.startswith("pyperformance:"):
            section = "pyperformance"
            continue
        if raw.startswith("stdlib:"):
            section = "stdlib"
            continue
        stripped = raw.lstrip()
        if not stripped.startswith("- "):
            continue
        path = stripped[2:].strip()
        if not path.endswith(".py"):
            continue
        if section == "core":
            core.add(path)
        elif section == "stdlib":
            stdlib.add(path)
        elif section == "pyperformance":
            pyperformance.add(path)
    return core, stdlib, pyperformance


def _render_manifest(title: str, tests: list[str]) -> str:
    lines = [
        f"# {title}",
        "# Generated by: uv run --python 3.12 python tools/gen_diff_lanes.py --write",
        "# One test path per line, repo-root-relative.",
        "",
    ]
    lines.extend(tests)
    lines.append("")
    return "\n".join(lines)


def generated_outputs() -> dict[Path, str]:
    """Each output path mapped to its exact generated text.

    The three lane manifests, rendered from the coverage index + on-disk tests.
    """
    core, stdlib, pyperformance = _parse_coverage_lists()
    stdlib_dir = ROOT / "tests" / "differential" / "stdlib"
    # Emit POSIX-style repo-relative paths so the rendered manifest is identical
    # on every OS (str(Path) yields backslashes on Windows — the manifest must
    # be byte-stable cross-platform for the --check gate to mean anything).
    stdlib_existing = {
        path.relative_to(ROOT).as_posix() for path in stdlib_dir.rglob("*.py")
    }
    basic_existing = {
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "tests" / "differential" / "basic").glob("*.py")
    }
    pyperformance_dir = ROOT / "tests" / "differential" / "pyperformance"
    pyperformance_existing = {
        path.relative_to(ROOT).as_posix()
        for path in pyperformance_dir.glob("*.py")
        if path.name != "TESTS.txt"
    }
    stdlib |= stdlib_existing
    # A physical test has one execution-lane owner. Coverage-index stdlib labels
    # may point at basic-language files, but duplicating those paths into the
    # stdlib execution manifest caused the same source to run twice.
    stdlib -= basic_existing
    pyperformance |= pyperformance_existing
    core |= CORE_EXTRA
    core -= stdlib
    return {
        CORE_MANIFEST: _render_manifest("Core Differential Lane", sorted(core)),
        STDLIB_MANIFEST: _render_manifest("Stdlib Differential Lane", sorted(stdlib)),
        PYPERFORMANCE_MANIFEST: _render_manifest(
            "PyPerformance Differential Lane", sorted(pyperformance)
        ),
    }


def main(argv: list[str] | None = None) -> int:
    return generator_main(generated_outputs, argv, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
