#!/usr/bin/env python3
"""Project Molt's CPython type-slot id authority into the public C header."""

from __future__ import annotations

import re
from pathlib import Path

from generator_io import generator_main


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "runtime/molt-cpython-abi/src/type_slots.rs"
STABLE_ABI = ROOT / "config/cpython_stable_abi_3_12.toml"
OUTPUT = ROOT / "include/molt/shared/_molt_typeslots.generated.h"
CONST_RE = re.compile(
    r"^pub const (?P<name>Py_(?:am|bf|mp|nb|sq|tp)_[A-Za-z0-9_]+): "
    r"c_int = (?P<value>[0-9]+);$",
    re.MULTILINE,
)


def load_slots() -> tuple[tuple[str, int], ...]:
    text = SOURCE.read_text(encoding="utf-8")
    slots = tuple(
        (match.group("name"), int(match.group("value")))
        for match in CONST_RE.finditer(text)
    )
    if not slots:
        raise ValueError(f"no CPython type slots found in {SOURCE}")
    values = tuple(value for _name, value in slots)
    expected = tuple(range(1, len(slots) + 1))
    if values != expected:
        raise ValueError(
            "CPython type-slot ids must be ordered, contiguous, and append-only: "
            f"expected {expected}, got {values}"
        )
    names = tuple(name for name, _value in slots)
    if len(names) != len(set(names)):
        raise ValueError("CPython type-slot names must be unique")
    stable_abi = STABLE_ABI.read_text(encoding="utf-8")
    missing = [name for name in names if f"[const.{name}]" not in stable_abi]
    if missing:
        raise ValueError(
            "type-slot authority is absent from the CPython 3.12 Stable ABI "
            "manifest: " + ", ".join(missing)
        )
    return slots


def render(slots: tuple[tuple[str, int], ...]) -> str:
    lines = [
        "/* @generated by tools/gen_cpython_type_slots.py from",
        " * runtime/molt-cpython-abi/src/type_slots.rs.",
        " * DO NOT EDIT BY HAND. */",
        "#ifndef MOLT_CPYTHON_TYPESLOTS_GENERATED_H",
        "#define MOLT_CPYTHON_TYPESLOTS_GENERATED_H",
        "",
    ]
    lines.extend(f"#define {name} {value}" for name, value in slots)
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def generated_outputs() -> dict[Path, str]:
    """Each output path mapped to its exact generated text."""
    return {OUTPUT: render(load_slots())}


def main(argv: list[str] | None = None) -> int:
    return generator_main(generated_outputs, argv, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
