#!/usr/bin/env python3
"""Generate intrinsics registry artifacts from the canonical manifest."""

from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "runtime/molt-runtime/src/intrinsics/manifest.pyi"
OUT_PYI = ROOT / "src/molt/_intrinsics.pyi"
OUT_RS = ROOT / "runtime/molt-runtime/src/intrinsics/generated.rs"

SYMBOL_OVERRIDES = {
    "molt_async_sleep": "molt_async_sleep_new",
}


_DEF_RE = re.compile(
    r"^def\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\((?P<params>.*)\)\s*->\s*(?P<ret>[^:]+):\s*\.\.\.\s*$"
)


def _strip_manifest_header(text: str) -> str:
    lines = text.splitlines()
    idx = 0
    while idx < len(lines) and lines[idx].lstrip().startswith("#"):
        idx += 1
    if idx < len(lines) and lines[idx].strip() == "":
        idx += 1
    return "\n".join(lines[idx:]).rstrip() + "\n"


def _iter_defs(text: str) -> list[str]:
    lines = text.splitlines()
    defs: list[str] = []
    buf: list[str] = []
    in_def = False
    for raw in lines:
        line = raw.strip()
        if not in_def:
            if line.startswith("def "):
                in_def = True
                buf = [line]
                if line.endswith("..."):
                    defs.append(" ".join(buf))
                    in_def = False
            continue
        if not line:
            continue
        buf.append(line)
        if line.endswith("..."):
            defs.append(" ".join(buf))
            in_def = False
    if in_def:
        raise RuntimeError("unterminated def block in manifest")
    return defs


def _split_params(raw: str) -> list[str]:
    params = raw.strip()
    if not params:
        return []
    out: list[str] = []
    cur: list[str] = []
    depth = 0
    for ch in params:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        if ch == "," and depth == 0:
            part = "".join(cur).strip()
            out.append(part)
            cur = []
            continue
        cur.append(ch)
    tail = "".join(cur).strip()
    if tail:
        out.append(tail)
    return [p for p in out if p and p != "*"]


def _load_manifest() -> tuple[str, list[tuple[str, str, int]]]:
    if not MANIFEST.exists():
        raise FileNotFoundError(f"manifest missing: {MANIFEST}")
    raw = MANIFEST.read_text()
    defs = _iter_defs(raw)
    entries: list[tuple[str, str, int]] = []
    seen: set[str] = set()
    for item in defs:
        m = _DEF_RE.match(item)
        if not m:
            raise RuntimeError(f"failed to parse def: {item}")
        name = m.group("name")
        if name in seen:
            raise RuntimeError(f"duplicate intrinsic name: {name}")
        seen.add(name)
        params = _split_params(m.group("params"))
        arity = len(params)
        symbol = SYMBOL_OVERRIDES.get(name, name)
        entries.append((name, symbol, arity))
    return raw, entries


def _validate_symbols(entries: list[tuple[str, str, int]]) -> None:
    src_root = ROOT / "runtime/molt-runtime/src"
    rs_files = list(src_root.rglob("*.rs"))
    corpus = "\n".join(path.read_text() for path in rs_files)
    missing = []
    for _name, symbol, _arity in entries:
        if re.search(rf"\bfn\s+{re.escape(symbol)}\b", corpus) is None:
            missing.append(symbol)
    if missing:
        missing_list = ", ".join(sorted(set(missing)))
        raise RuntimeError(f"missing intrinsic symbols in runtime: {missing_list}")


def _write_generated_rs(entries: list[tuple[str, str, int]]) -> None:
    lines: list[str] = []
    lines.append("// @generated by tools/gen_intrinsics.py. DO NOT EDIT.\n")
    lines.append("#[derive(Clone, Copy)]\n")
    lines.append("pub(crate) struct IntrinsicSpec {\n")
    lines.append("    pub name: &'static str,\n")
    lines.append("    pub symbol: &'static str,\n")
    lines.append("    pub arity: u8,\n")
    lines.append("}\n\n")
    lines.append("pub(crate) const INTRINSICS: &[IntrinsicSpec] = &[\n")
    for name, symbol, arity in entries:
        lines.append(
            f'    IntrinsicSpec {{ name: "{name}", symbol: "{symbol}", arity: {arity} }},\n'
        )
    lines.append("];\n\n")
    lines.append("pub(crate) fn resolve_symbol(symbol: &str) -> Option<u64> {\n")
    lines.append("    match symbol {\n")
    seen_symbols: set[str] = set()
    for _name, symbol, _arity in entries:
        if symbol in seen_symbols:
            continue
        seen_symbols.add(symbol)
        lines.append(
            f'        "{symbol}" => Some(crate::{symbol} as *const () as usize as u64),\n'
        )
    lines.append("        _ => None,\n")
    lines.append("    }\n")
    lines.append("}\n")
    OUT_RS.write_text("".join(lines))


def _write_pyi(raw_manifest: str) -> None:
    body = _strip_manifest_header(raw_manifest)
    header = (
        "# @generated by tools/gen_intrinsics.py from "
        "runtime/molt-runtime/src/intrinsics/manifest.pyi\n"
    )
    OUT_PYI.write_text(header + body)


def main() -> int:
    raw, entries = _load_manifest()
    _validate_symbols(entries)
    _write_generated_rs(entries)
    _write_pyi(raw)
    return 0


if __name__ == "__main__":
    sys.exit(main())
