#!/usr/bin/env python3
"""Generate Molt's Rust-native StringPrep tables from CPython's oracle."""

from __future__ import annotations

import stringprep
from pathlib import Path

from generator_io import generator_main, rustfmt_source

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "runtime/molt-runtime-stringprep/src/tables.rs"

TABLE_FUNCS: tuple[tuple[str, str], ...] = (
    ("A1_RANGES", "in_table_a1"),
    ("B1_RANGES", "in_table_b1"),
    ("C11_RANGES", "in_table_c11"),
    ("C12_RANGES", "in_table_c12"),
    ("C21_RANGES", "in_table_c21"),
    ("C22_RANGES", "in_table_c22"),
    ("C3_RANGES", "in_table_c3"),
    ("C4_RANGES", "in_table_c4"),
    ("C5_RANGES", "in_table_c5"),
    ("C6_RANGES", "in_table_c6"),
    ("C7_RANGES", "in_table_c7"),
    ("C8_RANGES", "in_table_c8"),
    ("C9_RANGES", "in_table_c9"),
    ("D1_RANGES", "in_table_d1"),
    ("D2_RANGES", "in_table_d2"),
)

MAP_FUNCS: tuple[tuple[str, str], ...] = (
    ("B2_MAPPINGS", "map_table_b2"),
    ("B3_MAPPINGS", "map_table_b3"),
)


_LAST_CODE_POINT = 0x10FFFF


def _ranges_for(func_name: str, chars: list[str]) -> list[tuple[int, int]]:
    """Maximal runs of consecutive code points the table function accepts."""
    func = getattr(stringprep, func_name)
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for cp, matched in enumerate(map(func, chars)):
        if matched:
            if start is None:
                start = cp
        elif start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, _LAST_CODE_POINT))
    return ranges


def _mappings_for(func_name: str, chars: list[str]) -> list[tuple[int, str]]:
    func = getattr(stringprep, func_name)
    return [
        (cp, mapped)
        for cp, (ch, mapped) in enumerate(zip(chars, map(func, chars)))
        if mapped != ch
    ]


def _rust_str_literal(value: str) -> str:
    chunks: list[str] = ['"']
    for ch in value:
        cp = ord(ch)
        if ch == "\\":
            chunks.append("\\\\")
        elif ch == '"':
            chunks.append('\\"')
        elif ch == "\n":
            chunks.append("\\n")
        elif ch == "\r":
            chunks.append("\\r")
        elif ch == "\t":
            chunks.append("\\t")
        elif 0x20 <= cp <= 0x7E:
            chunks.append(ch)
        else:
            chunks.append(f"\\u{{{cp:X}}}")
    chunks.append('"')
    return "".join(chunks)


def _render_ranges(name: str, ranges: list[tuple[int, int]]) -> list[str]:
    lines = [f"pub(crate) const {name}: &[(u32, u32)] = &[\n"]
    for start, end in ranges:
        lines.append(f"    (0x{start:06X}, 0x{end:06X}),\n")
    lines.append("];\n\n")
    return lines


def _render_mappings(name: str, mappings: list[tuple[int, str]]) -> list[str]:
    lines = [f"pub(crate) const {name}: &[(u32, &str)] = &[\n"]
    for cp, mapped in mappings:
        lines.append(f"    (0x{cp:06X}, {_rust_str_literal(mapped)}),\n")
    lines.append("];\n\n")
    return lines


def render() -> str:
    lines = [
        "// @generated by tools/gen_stringprep_tables.py. DO NOT EDIT.\n",
        "// Source authority: CPython's `stringprep` module behavior for RFC 3454\n",
        "// StringPrep. The generated data is runtime-native and has no host-Python\n",
        "// dependency in compiled binaries.\n\n",
    ]
    chars = list(map(chr, range(_LAST_CODE_POINT + 1)))
    for rust_name, func_name in TABLE_FUNCS:
        lines.extend(_render_ranges(rust_name, _ranges_for(func_name, chars)))
    for rust_name, func_name in MAP_FUNCS:
        lines.extend(_render_mappings(rust_name, _mappings_for(func_name, chars)))
    return "".join(lines)


def generated_outputs() -> dict[Path, str]:
    """Each output path mapped to its exact generated text."""
    return {OUT: rustfmt_source(render(), label="stringprep tables")}


def main(argv: list[str] | None = None) -> int:
    return generator_main(generated_outputs, argv, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
