#!/usr/bin/env python3
"""Intrinsic-first stdlib stubs: one template for every stub.

A stub stands in for a CPython stdlib module or package that Molt has not
lowered. Importing it binds nothing it does not need, and requires no
intrinsic: the audit gives a stub its own ``stub`` status (spec 0016), so it
needs no anchor. Any attribute raises the canonical gap error. This generator
owns that template. It writes a stub for every module the stdlib union
requires and Molt lacks (with the parent packages it needs), and it holds every
existing stub to the template, so a stub cannot drift. A stub is any module
whose ``__getattr__`` raises the gap error, the same structural test the audit
uses (``molt.stdlib_intrinsic_policy.is_stdlib_stub_source``). A stub must name
a union module of the union's kind; the generator refuses one that does not and
names the fix. Lowering a module replaces its stub file entirely.

Usage::

    python3 tools/gen_stdlib_stubs.py --check
    python3 tools/gen_stdlib_stubs.py --write
"""

from __future__ import annotations

from collections.abc import Sequence
import runpy
from pathlib import Path

from generator_io import generator_main
from molt.stdlib_intrinsic_policy import STDLIB_STUB_MARKER, is_stdlib_stub_source

ROOT = Path(__file__).resolve().parents[1]
STDLIB_ROOT = ROOT / "src" / "molt" / "stdlib"
UNION = ROOT / "tools" / "stdlib_module_union.py"
# Modules CPython ships on one platform only: elsewhere their import fails as
# it does in CPython.
PLATFORM_ONLY = {"encodings._win_cp_codecs": "win32"}


def stub_source(name: str, *, package: bool, submodules: Sequence[str] = ()) -> str:
    """The stub for ``name``; a package lists its union ``submodules``."""

    if submodules and not package:
        raise ValueError(f"module stub `{name}` cannot have submodules")
    kind = "package" if package else "module"
    platform = PLATFORM_ONLY.get(name)
    # A platform-only module fails its import elsewhere, as CPython's does.
    gate = (
        "\n"
        "import sys as _sys\n"
        "\n"
        f'if _sys.platform != "{platform}":\n'
        "    raise ModuleNotFoundError(\n"
        f'        "No module named \'{name}\'", name="{name}"\n'
        "    )\n"
        if platform is not None
        else ""
    )
    # The import system asks a package for a submodule before it loads it, and
    # only an AttributeError lets it go on to load one.
    submodule_gate = (
        "    if attr in {\n"
        + "".join(f'        "{leaf}",\n' for leaf in submodules)
        + "    }:\n"
        '        raise AttributeError(f"module {__name__!r} has no attribute '
        '{attr!r}", name=attr)\n'
        if submodules
        else ""
    )
    release = '\n\nglobals().pop("_sys", None)\n' if platform is not None else ""
    return (
        f'"""Intrinsic-first stdlib {kind} stub for `{name}`.\n'
        "\n"
        f"Generated by tools/gen_stdlib_stubs.py; lowering the {kind} replaces "
        "this file.\n"
        '"""\n'
        f"{gate}"
        "\n"
        "\n"
        "# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, "
        f"status:planned): replace `{name}` {kind} stub with a full lowering.\n"
        "def __getattr__(attr: str):\n"
        f"{submodule_gate}"
        "    raise RuntimeError(\n"
        f"        'stdlib {kind} \"{name}\" {STDLIB_STUB_MARKER}'\n"
        "    )\n"
        f"{release}"
    )


def stub_path(name: str, *, package: bool) -> Path:
    parts = name.split(".")
    if package:
        return STDLIB_ROOT.joinpath(*parts, "__init__.py")
    return STDLIB_ROOT.joinpath(*parts[:-1], f"{parts[-1]}.py")


def _module_name(path: Path) -> str:
    parts = path.relative_to(STDLIB_ROOT).parts
    if path.name == "__init__.py":
        return ".".join(parts[:-1])
    return ".".join((*parts[:-1], path.stem))


def _union() -> tuple[frozenset[str], frozenset[str]]:
    namespace = runpy.run_path(str(UNION))
    names: set[str] = set()
    packages: set[str] = set()
    for modules, package_names in (
        ("STDLIB_MODULE_UNION", "STDLIB_PACKAGE_UNION"),
        ("STDLIB_PY_SUBMODULE_UNION", "STDLIB_PY_SUBPACKAGE_UNION"),
    ):
        module_tuple = namespace.get(modules)
        package_tuple = namespace.get(package_names)
        if not isinstance(module_tuple, tuple) or not isinstance(package_tuple, tuple):
            raise SystemExit(
                f"gen_stdlib_stubs: {UNION} lacks {modules} or {package_names}"
            )
        names.update(module_tuple)
        packages.update(package_tuple)
    return frozenset(names), frozenset(packages)


def _submodules(required: frozenset[str]) -> dict[str, tuple[str, ...]]:
    children: dict[str, list[str]] = {}
    for name in required:
        parent, dot, leaf = name.rpartition(".")
        if dot:
            children.setdefault(parent, []).append(leaf)
    return {parent: tuple(sorted(leaves)) for parent, leaves in children.items()}


def _present_modules() -> set[str]:
    return {
        _module_name(path)
        for path in STDLIB_ROOT.rglob("*.py")
        if not path.name.startswith(".")
        and not (path.name == "__init__.py" and path.parent == STDLIB_ROOT)
    }


def generated_outputs() -> dict[Path, str]:
    required, packages = _union()
    submodules = _submodules(required)

    def render(name: str, *, package: bool) -> str:
        return stub_source(name, package=package, submodules=submodules.get(name, ()))

    outputs: dict[Path, str] = {}
    errors: list[str] = []
    for path in sorted(STDLIB_ROOT.rglob("*.py")):
        if not is_stdlib_stub_source(path.read_bytes()):
            continue
        name = _module_name(path)
        package = path.name == "__init__.py"
        rel = path.relative_to(ROOT).as_posix()
        if name not in required:
            errors.append(f"{rel}: CPython ships no `{name}`; delete the stub")
        elif (name in packages) != package:
            kind = "package" if name in packages else "module"
            target = stub_path(name, package=name in packages)
            errors.append(
                f"{rel}: CPython ships `{name}` as a {kind}; "
                f"git mv it to {target.relative_to(ROOT).as_posix()}"
            )
        else:
            outputs[path] = render(name, package=package)
    if errors:
        raise SystemExit("gen_stdlib_stubs: " + "\n  ".join(["", *errors]))
    present = _present_modules()
    for name in sorted(required - present):
        parts = name.split(".")
        # A submodule needs every enclosing package to import.
        for depth in range(1, len(parts)):
            parent = ".".join(parts[:depth])
            if parent not in present:
                outputs.setdefault(
                    stub_path(parent, package=True),
                    render(parent, package=True),
                )
        package = name in packages
        outputs[stub_path(name, package=package)] = render(name, package=package)
    return outputs


def main(argv: list[str] | None = None) -> int:
    return generator_main(generated_outputs, argv, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
