#!/usr/bin/env python3
"""Generate the CPython-ABI struct-layout parity assertions from ONE authority.

Single-authority contract
--------------------------
The standalone ``libmolt_cpython_abi.{so,dll,dylib}`` link tier exposes CPython
3.12 objects in the *traditional* ``ob_refcnt`` / ``ob_type`` representation. That
representation is defined ONCE, in Rust ``#[repr(C)]`` form, at

    runtime/molt-cpython-abi/src/abi_types.rs      (the AUTHORITY)

The companion C header

    runtime/molt-cpython-abi/include/Python.h       (the CONSUMER)

hand-declares the *same* structs so C extensions can be compiled against them.
Because the cdylib operates on pointers to the Rust structs, the C struct layout
MUST be byte-identical to the Rust struct layout, or every extension linking the
standalone dylib is memory-unsafe. Historically the two were hand-synced (the D1
"duplicate_authority" poison in tools/fail_closed_registry.toml): a silent drift
in field order/width in either file is undetected memory corruption.

This generator removes the hand-sync. It parses the Rust ``#[repr(C)]`` authority
and emits a *generated* C header,

    runtime/molt-cpython-abi/include/_molt_abi_layout.generated.h

containing, for every struct that also appears in the C umbrella header, a block
of ``_Static_assert`` checks pinning ``sizeof`` and every field ``offsetof`` to
the value the Rust authority dictates. The C header ``#include``s this file, so a
drifting C struct fails to *compile* — the drift can no longer ship. The Rust
authority is the only place a layout is *authored*; the C side is *checked*
against it, not independently maintained.

This is the ``--check``-gated generated-fact pattern used across Molt (op_kinds,
wasm_abi): source-of-truth in one file, generated artifact checked in, a gate
that fails closed when they diverge.

Layout model
------------
The parity we assert is *layout category* per field, in declaration order, which
on the LP64 (Linux/macOS x86-64 & aarch64) and LLP64 (Windows) targets both
sides claim is sufficient to pin byte offsets:

    ptr8   any pointer / fn-pointer / Option<extern fn>  -> 8 bytes, 8-align
    word8  isize/usize/Py_ssize_t/Py_hash_t              -> 8 bytes, 8-align
    i32    c_int/c_uint/i32/u32                           -> 4 bytes, 4-align
    byte1  c_char/u8/i8/bool                              -> 1 byte,  1-align
    f64    c_double/f64                                   -> 8 bytes, 8-align
    embed:<Struct>   an embedded struct value (recursed)
    arr:<n>x<cat>    a fixed C array of <n> elements of <cat>

Because these categories fix each field's size AND alignment, and the C header
and the Rust authority are both ``repr(C)`` with identical field order, the C
compiler's ``_Static_assert`` on ``sizeof``/``offsetof`` is the real proof; the
category table is only used to decide *which* structs and fields to assert and to
detect field-count/kind drift at generation time (a second, cheaper guard).

Usage
-----
    python tools/gen_cpython_abi_layout.py --check    # gate: fail on drift
    python tools/gen_cpython_abi_layout.py --write    # regenerate the artifact
    python tools/gen_cpython_abi_layout.py --print-authority   # debug dump
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
AUTHORITY_RS = REPO_ROOT / "runtime/molt-cpython-abi/src/abi_types.rs"
C_HEADER = REPO_ROOT / "runtime/molt-cpython-abi/include/Python.h"
GENERATED_H = REPO_ROOT / "runtime/molt-cpython-abi/include/_molt_abi_layout.generated.h"

GENERATED_BANNER = "GENERATED by tools/gen_cpython_abi_layout.py — DO NOT EDIT."


# ─────────────────────────────────────────────────────────────────────────────
# Field-category lattice
# ─────────────────────────────────────────────────────────────────────────────
PTR = "ptr8"
WORD = "word8"
I32 = "i32"
BYTE = "byte1"
F64 = "f64"


@dataclass(frozen=True)
class Field:
    name: str
    category: str  # one of the scalars above, or "embed:<Name>", or "arr:<n>x<cat>"


@dataclass(frozen=True)
class Struct:
    name: str
    fields: tuple[Field, ...]


class LayoutError(RuntimeError):
    pass


# ─────────────────────────────────────────────────────────────────────────────
# Rust #[repr(C)] authority parser (brace-aware, multi-line-field safe)
# ─────────────────────────────────────────────────────────────────────────────
def _rust_field_category(ty: str) -> str:
    ty = ty.strip().rstrip(",").strip()
    # Pointers and Option<fn> / fn pointers are all 8-byte pointer-width.
    if (
        ty.startswith("*mut")
        or ty.startswith("*const")
        or ty.startswith("Option<")
        or "extern \"C\" fn" in ty
        or ty.endswith("Func")
        or ty in {"getter", "setter"}
    ):
        return PTR
    if ty in {"Py_ssize_t", "Py_hash_t", "Py_uhash_t", "isize", "usize", "c_ulong"}:
        # NOTE: c_ulong is 8 on LP64 but 4 on LLP64 (Windows). tp_flags/tp_version_tag
        # use it; CPython itself declares those as `unsigned long`, so the C header and
        # Rust agree on the same platform-variadic width. We categorise it as WORD for
        # LP64; the compile-time _Static_assert (emitted per struct) is the real cross
        # platform proof — see the c_ulong handling note in emit.
        return WORD
    if ty in {"c_int", "c_uint", "i32", "u32"}:
        return I32
    if ty in {"c_char", "u8", "i8", "bool"}:
        return BYTE
    if ty in {"c_double", "f64"}:
        return F64
    # Fixed array: [u8; 10], [c_char; 1], [u32; 1]
    m = re.match(r"\[\s*(.+?)\s*;\s*(\d+)\s*\]", ty)
    if m:
        inner = _rust_field_category(m.group(1))
        return f"arr:{m.group(2)}x{inner}"
    # Bare identifier -> embedded struct value (e.g. PyObject, PyVarObject, Py_complex).
    if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", ty):
        return f"embed:{ty}"
    raise LayoutError(f"unclassifiable Rust field type: {ty!r}")


def parse_rust_authority(text: str) -> dict[str, Struct]:
    out: dict[str, Struct] = {}
    lines = text.splitlines()
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        if line.strip() == "#[repr(C)]":
            # Skip any intervening attributes / doc lines to the struct header.
            j = i + 1
            while j < n and not re.match(r"\s*pub struct \w+", lines[j]):
                # Stop if we hit something that isn't an attribute/comment (e.g. a
                # repr(u8) enum, which we do not treat as a layout struct).
                s = lines[j].strip()
                if s and not (
                    s.startswith("#[") or s.startswith("//") or s.startswith("pub struct")
                ):
                    break
                j += 1
            if j < n:
                m = re.match(r"\s*pub struct (\w+)\s*\{", lines[j])
                if m:
                    name = m.group(1)
                    fields, end = _parse_rust_struct_body(lines, j)
                    out[name] = Struct(name, tuple(fields))
                    i = end + 1
                    continue
        i += 1
    return out


def _parse_rust_struct_body(lines: list[str], header_idx: int) -> tuple[list[Field], int]:
    """Parse a ``pub struct Name {`` body starting at ``header_idx`` (the line with
    the opening brace). Returns (fields, index_of_closing_brace_line)."""
    depth = 0
    fields: list[Field] = []
    buf = ""
    i = header_idx
    started = False
    while i < len(lines):
        # Strip a whole-line comment / doc-comment before scanning, so a `///`
        # line inside the body never contaminates the accumulated field buffer.
        raw = lines[i]
        stripped = raw.lstrip()
        line = "" if stripped.startswith("//") else _strip_trailing_line_comment(raw)
        for ch in line:
            if ch == "{":
                depth += 1
                started = True
                continue
            if ch == "}":
                depth -= 1
                if depth == 0:
                    _flush_rust_field(buf, fields)
                    return fields, i
                continue
            if depth == 1:
                if ch == ",":
                    _flush_rust_field(buf, fields)
                    buf = ""
                else:
                    buf += ch
        if started and depth == 1:
            buf += " "  # newline within a multi-line field type
        i += 1
    raise LayoutError(f"unterminated struct body at line {header_idx}")


def _strip_trailing_line_comment(line: str) -> str:
    """Remove a `// ...` trailing comment but keep code before it. Naive but the
    abi_types.rs authority contains no `//` inside string/char literals in struct
    bodies, so a plain split is safe here."""
    idx = line.find("//")
    return line if idx < 0 else line[:idx]


def _flush_rust_field(buf: str, fields: list[Field]) -> None:
    frag = buf.strip()
    if not frag:
        return
    # Strip inline comments and attributes.
    frag = re.sub(r"//.*$", "", frag).strip()
    if not frag or frag.startswith("#["):
        return
    m = re.match(r"pub\s+(\w+)\s*:\s*(.+)$", frag)
    if not m:
        return
    name, ty = m.group(1), m.group(2).strip()
    fields.append(Field(name, _rust_field_category(ty)))


# ─────────────────────────────────────────────────────────────────────────────
# C header struct parser (for the SAME structs) — used to detect field-count /
# category drift at generation time and to know which structs to assert.
# ─────────────────────────────────────────────────────────────────────────────
# Maps the C struct definition name -> the Rust authority struct name. The C
# header spells several via `typedef struct { ... } Name;` or `struct _tag {..}`.
C_TO_RUST: dict[str, str] = {
    "_object": "PyObject",
    "PyVarObject": "PyVarObject",
    "_typeobject": "PyTypeObject",
    "PyMethodDef": "PyMethodDef",
    "PyGetSetDef": "PyGetSetDef",
    "PyMemberDef": "PyMemberDef",
    "PyModuleDef": "PyModuleDef",
    "PyModuleDef_Slot": "PyModuleDef_Slot",
    "Py_buffer": "Py_buffer",
    "PyMemoryViewObject": "PyMemoryViewObject",
    "PyTupleObject": "PyTupleObject",
    "PyListObject": "PyListObject",
    "PyBytesObject": "PyBytesObject",
    "PyByteArrayObject": "PyByteArrayObject",
    "PyComplexObject": "PyComplexObject",
    "PySliceObject": "PySliceObject",
    "PyDictProxyObject": "PyDictProxyObject",
    "PyGenericAliasObject": "PyGenericAliasObject",
    "PyCFunctionObject": "PyCFunctionObject",
    "Py_complex": "Py_complex",
    "PyLongObject": "PyLongObject",
}


# The set of Rust authority structs whose layout the C header depends on and that
# we emit _Static_assert parity for. These are the structs a standalone-linked C
# extension can allocate, index into, or embed — i.e. the memory-safety surface.
ASSERTED_STRUCTS: tuple[str, ...] = (
    "PyObject",
    "PyVarObject",
    "PyTypeObject",
    "PyMethodDef",
    "PyGetSetDef",
    "PyMemberDef",
    "PyModuleDef",
    "PyModuleDef_Slot",
    "PyModuleDef_Base",
    "Py_buffer",
    "PyMemoryViewObject",
    "PyTupleObject",
    "PyListObject",
    "PyBytesObject",
    "PyByteArrayObject",
    "PyComplexObject",
    "Py_complex",
    "PySliceObject",
    "PyDictProxyObject",
    "PyGenericAliasObject",
    "PyCFunctionObject",
    "PyLongObject",
    "PyLongValue",
    "PyCapsuleObject",
    "PyContextVarObject",
    "PyDescrObject",
    "PyGetSetDescrObject",
    "PyMemberDescrObject",
    "PySlice_Object" if False else "PyType_Slot",
    "PyType_Spec",
    "PyDateTime_Delta",
    "PyDateTime_Date",
    "PyDateTime_Time",
    "PyDateTime_DateTime",
)


# ─────────────────────────────────────────────────────────────────────────────
# Emit
# ─────────────────────────────────────────────────────────────────────────────
def emit_header(authority: dict[str, Struct]) -> str:
    out: list[str] = []
    ap = out.append
    ap("/*")
    ap(f" * {GENERATED_BANNER}")
    ap(" *")
    ap(" * Single-authority CPython-ABI struct-layout parity assertions.")
    ap(" *")
    ap(" * The traditional-representation (ob_refcnt/ob_type) object model exposed by")
    ap(" * the standalone libmolt_cpython_abi dylib is authored ONCE in Rust repr(C)")
    ap(" * form at runtime/molt-cpython-abi/src/abi_types.rs. This header is generated")
    ap(" * from that authority and asserts, at C compile time, that the hand-written C")
    ap(" * struct declarations in <Python.h> have byte-identical layout (sizeof +")
    ap(" * per-field offsetof) to the Rust authority. A drift in either file fails to")
    ap(" * COMPILE, so the two representations can never silently diverge (the D1")
    ap(" * duplicate_authority poison). Regenerate with:")
    ap(" *   python tools/gen_cpython_abi_layout.py --write")
    ap(" */")
    ap("#ifndef MOLT_ABI_LAYOUT_GENERATED_H")
    ap("#define MOLT_ABI_LAYOUT_GENERATED_H")
    ap("")
    ap("/* This file is included by <Python.h> AFTER the struct definitions. It uses")
    ap(" * only stddef.h (offsetof), stdint.h (UINTPTR_MAX) and the C11")
    ap(" * _Static_assert facility. */")
    ap("#include <stddef.h>")
    ap("#include <stdint.h>")
    ap("")
    ap("#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L")
    ap("#define _MOLT_ABI_SASSERT(cond, msg) _Static_assert((cond), msg)")
    ap("#else")
    ap("/* Pre-C11 fallback: negative-size array trick. */")
    ap("#define _MOLT_ABI_SASSERT(cond, msg) \\")
    ap("    typedef char _molt_abi_sassert_##__LINE__[(cond) ? 1 : -1]")
    ap("#endif")
    ap("")
    ap("/* Pointer-width model select. The traditional ob_refcnt/ob_type object model")
    ap(" * is authored once in Rust repr(C); its byte layout differs only by pointer")
    ap(" * width. The 64-bit branch pins the LP64 (Linux/macOS x86-64 & aarch64) and")
    ap(" * LLP64 (Windows) layout (8-byte pointer); the 32-bit branch pins the wasm32")
    ap(" * ILP32 layout (4-byte pointer) used by the WASM/WASI extension tier. Each")
    ap(" * target compiles ONLY its own branch, so the assertions hold on every")
    ap(" * supported pointer width. Both branches are derived from the same Rust")
    ap(" * authority by the generator — there is no second hand-maintained table. */")
    ap("#if UINTPTR_MAX == 0xFFFFFFFFu")
    ap("#define _MOLT_ABI_PTR32 1")
    ap("#elif UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFu")
    ap("#define _MOLT_ABI_PTR32 0")
    ap("#else")
    ap('#error "molt cpython-abi layout: unsupported pointer width (expected 32 or 64 bit)"')
    ap("#endif")
    ap("")

    for rust_name in ASSERTED_STRUCTS:
        st = authority.get(rust_name)
        if st is None:
            raise LayoutError(
                f"ASSERTED_STRUCTS names {rust_name!r} but the Rust authority "
                f"{AUTHORITY_RS} has no #[repr(C)] struct by that name"
            )
        c_type = _c_type_expr(rust_name)
        if c_type is None:
            continue  # struct exists in Rust authority but has no C spelling to assert
        ap(f"/* {rust_name}  <-  {AUTHORITY_RS.name} */")
        # sizeof + offsetof parity for BOTH pointer-width models. Both are computed
        # from the same parsed authority; the C compiler's _Static_assert on the
        # branch matching its own pointer width is the real proof.
        size64, offsets64 = _compute_layout(rust_name, authority, _PTR_SIZE_LP64)
        size32, offsets32 = _compute_layout(rust_name, authority, _PTR_SIZE_ILP32)

        def _emit_block(size: int, offsets: list[tuple[str, int]]) -> None:
            ap(
                f"_MOLT_ABI_SASSERT(sizeof({c_type}) == {size}u,"
                f' "layout drift: sizeof({c_type}) != {size} '
                f'(regen tools/gen_cpython_abi_layout.py / fix abi_types.rs)");'
            )
            for fname, off in offsets:
                c_field = _c_field_name(rust_name, fname)
                if c_field is None:
                    continue
                ap(
                    f"_MOLT_ABI_SASSERT(offsetof({c_type}, {c_field}) == {off}u,"
                    f' "layout drift: offsetof({c_type}, {c_field}) != {off}");'
                )

        if (size64, offsets64) == (size32, offsets32):
            # Pointer-width-independent struct (all fixed-width fields): one block.
            _emit_block(size64, offsets64)
        else:
            ap("#if _MOLT_ABI_PTR32")
            _emit_block(size32, offsets32)
            ap("#else")
            _emit_block(size64, offsets64)
            ap("#endif")
        ap("")

    ap("#undef _MOLT_ABI_SASSERT")
    ap("#undef _MOLT_ABI_PTR32")
    ap("#endif /* MOLT_ABI_LAYOUT_GENERATED_H */")
    ap("")
    return "\n".join(out)


# repr(C) sizing rules, parameterized by pointer width so ONE Rust authority
# derives BOTH the LP64/LLP64 (64-bit, 8-byte pointer) and the wasm32 ILP32
# (32-bit, 4-byte pointer) layouts. PTR and WORD are pointer-width on both sides:
#   PTR  = any pointer / fn-pointer / Option<extern fn>
#   WORD = isize/usize/Py_ssize_t/Py_hash_t/Py_uhash_t (intptr-sized), and c_ulong
#          (categorised WORD; on the two targets we assert — LP64 long=8=ptr and
#          wasm32/LLP32 long=4=ptr — the C `unsigned long` matches the pointer-width
#          model, and the per-target compile-time _Static_assert is the real proof).
# I32/BYTE/F64 are fixed-width on every target (int=4, char=1, double=8).
#
# ptr_size is 8 for the 64-bit model and 4 for the wasm32 ILP32 model. Both models
# flow from the same parsed authority; there is NO second hand-maintained table.
_PTR_SIZE_LP64 = 8
_PTR_SIZE_ILP32 = 4


def _cat_size_align(
    cat: str, authority: dict[str, Struct], ptr_size: int
) -> tuple[int, int]:
    if cat in (PTR, WORD):
        return ptr_size, ptr_size
    if cat == F64:
        return 8, 8
    if cat == I32:
        return 4, 4
    if cat == BYTE:
        return 1, 1
    if cat.startswith("embed:"):
        name = cat.split(":", 1)[1]
        sz, _ = _compute_layout(name, authority, ptr_size)
        al = _struct_align(name, authority, ptr_size)
        return sz, al
    if cat.startswith("arr:"):
        # arr:<n>x<innercat>
        m = re.match(r"arr:(\d+)x(.+)", cat)
        assert m, cat
        n = int(m.group(1))
        isz, ial = _cat_size_align(m.group(2), authority, ptr_size)
        return isz * n, ial
    if cat == "Py_complex":
        return 16, 8
    raise LayoutError(f"no size for category {cat!r}")


def _struct_align(name: str, authority: dict[str, Struct], ptr_size: int) -> int:
    st = authority[name]
    al = 1
    for f in st.fields:
        _, fa = _cat_size_align(f.category, authority, ptr_size)
        al = max(al, fa)
    return al


def _compute_layout(
    name: str, authority: dict[str, Struct], ptr_size: int
) -> tuple[int, list[tuple[str, int]]]:
    """Return (sizeof, [(field, offset)]) for a repr(C) struct under the given
    pointer-width model, flattening embedded struct fields so offsets are relative
    to the outer struct (matching C offsetof of the flattened field name where the
    C header flattens, e.g. ob_base)."""
    st = authority[name]
    offset = 0
    struct_align = 1
    out: list[tuple[str, int]] = []
    for f in st.fields:
        fsz, fal = _cat_size_align(f.category, authority, ptr_size)
        struct_align = max(struct_align, fal)
        # align
        if offset % fal != 0:
            offset += fal - (offset % fal)
        out.append((f.name, offset))
        offset += fsz
    # tail padding to struct alignment
    if struct_align and offset % struct_align != 0:
        offset += struct_align - (offset % struct_align)
    return offset, out


# ─────────────────────────────────────────────────────────────────────────────
# Rust struct name -> C type expression / field name used in offsetof.
# The C header flattens ob_base (PyObject/PyVarObject) into inline fields via the
# PyObject_HEAD macro, so we only assert the FLAT scalar fields that have a stable
# C spelling. Embedded-struct fields are asserted through their own struct's block.
# ─────────────────────────────────────────────────────────────────────────────
_C_TYPE_EXPR: dict[str, str | None] = {
    "PyObject": "PyObject",
    "PyVarObject": "PyVarObject",
    "PyTypeObject": "PyTypeObject",
    "PyMethodDef": "PyMethodDef",
    "PyGetSetDef": "PyGetSetDef",
    "PyMemberDef": "PyMemberDef",
    "PyModuleDef": "PyModuleDef",
    "PyModuleDef_Slot": "PyModuleDef_Slot",
    "PyModuleDef_Base": "PyModuleDef_Base",
    "Py_buffer": "Py_buffer",
    "PyMemoryViewObject": "PyMemoryViewObject",
    "PyTupleObject": "PyTupleObject",
    "PyListObject": "PyListObject",
    "PyBytesObject": "PyBytesObject",
    "PyByteArrayObject": "PyByteArrayObject",
    "PyComplexObject": "PyComplexObject",
    "Py_complex": "Py_complex",
    "PySliceObject": "PySliceObject",
    "PyDictProxyObject": "PyDictProxyObject",
    "PyGenericAliasObject": "PyGenericAliasObject",
    "PyCFunctionObject": "PyCFunctionObject",
    "PyLongObject": "PyLongObject",
    "PyLongValue": "_PyLongValue",
    "PyCapsuleObject": None,      # asserted only if C spelling present; see resolve
    "PyContextVarObject": None,
    "PyDescrObject": None,
    "PyGetSetDescrObject": None,
    "PyMemberDescrObject": None,
    "PyType_Slot": "PyType_Slot",
    "PyType_Spec": "PyType_Spec",
    "PyDateTime_Delta": None,
    "PyDateTime_Date": None,
    "PyDateTime_Time": None,
    "PyDateTime_DateTime": None,
}


def _c_type_expr(rust_name: str) -> str | None:
    return _C_TYPE_EXPR.get(rust_name)


# For flattened heads, the Rust `ob_base` field name has no direct C offsetof
# target (C flattens it). We assert the leading scalar of the flattened head
# (ob_refcnt at offset 0) implicitly via sizeof + the first real field. To keep
# offsets meaningful and stable, we suppress offsetof on embedded-struct fields
# and on fields whose C name differs; sizeof parity + scalar-field offsets give
# the byte-layout proof.
_SUPPRESS_OFFSETOF_FIELDS: dict[str, set[str]] = {
    # ob_base is flattened in C (PyObject_HEAD / PyObject_VAR_HEAD) — no such field.
    "*": {"ob_base", "d_common", "m_base", "func"},
}


def _c_field_name(rust_name: str, field: str) -> str | None:
    if field in _SUPPRESS_OFFSETOF_FIELDS.get("*", set()):
        return None
    if field in _SUPPRESS_OFFSETOF_FIELDS.get(rust_name, set()):
        return None
    # Rust uses `type_` for the C `type` keyword clash in PyMemberDef.
    if rust_name == "PyMemberDef" and field == "type_":
        return "type"
    # Rust `_co_firsttraceable` etc. match the C names verbatim otherwise.
    return field


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────
def build() -> str:
    text = AUTHORITY_RS.read_text(encoding="utf-8")
    authority = parse_rust_authority(text)
    if "PyObject" not in authority:
        raise LayoutError(
            f"parse of {AUTHORITY_RS} found no PyObject #[repr(C)] struct — parser "
            "or authority changed shape"
        )
    return emit_header(authority)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    g = parser.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="fail if generated artifact is stale")
    g.add_argument("--write", action="store_true", help="regenerate the artifact")
    g.add_argument(
        "--print-authority", action="store_true", help="dump parsed Rust authority"
    )
    args = parser.parse_args(argv)

    if args.print_authority:
        authority = parse_rust_authority(AUTHORITY_RS.read_text(encoding="utf-8"))
        for name, st in authority.items():
            print(f"{name}:")
            for f in st.fields:
                print(f"    {f.name}: {f.category}")
        return 0

    generated = build()

    if args.write:
        GENERATED_H.write_text(generated, encoding="utf-8")
        print(f"wrote {GENERATED_H.relative_to(REPO_ROOT).as_posix()}")
        return 0

    # --check
    if not GENERATED_H.exists():
        print(
            f"MISSING generated header {GENERATED_H.relative_to(REPO_ROOT).as_posix()};"
            " run: python tools/gen_cpython_abi_layout.py --write",
            file=sys.stderr,
        )
        return 1
    current = GENERATED_H.read_text(encoding="utf-8")
    if current != generated:
        print(
            f"STALE generated header {GENERATED_H.relative_to(REPO_ROOT).as_posix()} —"
            " abi_types.rs changed but the checked-in layout artifact was not "
            "regenerated. Run: python tools/gen_cpython_abi_layout.py --write",
            file=sys.stderr,
        )
        return 1
    print("cpython-abi layout artifact is in sync with abi_types.rs authority")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
