#!/usr/bin/env python3
"""Generate and verify projections of the canonical Molt proof plan."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from proof_plan import DEFAULT_MANIFEST, ProofPlan, _authority_sha256
from generator_io import generated_file_matches, write_generated_text


ROOT = Path(__file__).resolve().parents[1]
JSON_OUTPUT = ROOT / ".github" / "proof-plan.generated.json"
DOC_OUTPUT = ROOT / "docs" / "agent" / "PROOF_PLAN.generated.md"


def _timeout_envelope_projection(plan: ProofPlan) -> dict[str, dict[str, object]]:
    projection: dict[str, dict[str, object]] = {}
    for family in plan.families:
        if family.data["executor"] != "github-job":
            continue
        envelope = plan.timeout_envelope(family.name)
        budget = int(family.data["timeout_minutes"]) * 60
        projection[family.name] = {
            "budget_seconds": budget,
            "projected_makespan_seconds": envelope.projected_makespan_seconds,
            "critical_path_seconds": envelope.critical_path_seconds,
            "resource_capacity_floor_seconds": (
                envelope.resource_capacity_floor_seconds
            ),
            "headroom_seconds": budget - envelope.projected_makespan_seconds,
        }
    return projection


def _json_projection(plan: ProofPlan) -> str:
    local_commands = {
        **{
            f"local.always.{index}": command
            for index, command in enumerate(plan.always)
        },
        **{
            f"local.{rule['name']}.{index}": command
            for rule in plan.local_rules
            for index, command in enumerate(rule.get("gates", []))
        },
    }
    local_rules = [
        {
            **rule,
            "command_ids": [
                f"local.{rule['name']}.{index}"
                for index, _command in enumerate(rule.get("gates", []))
            ],
        }
        for rule in plan.local_rules
    ]
    payload = {
        "schema": "molt.proof-plan-projection.v3",
        "authority": str(plan.path.relative_to(ROOT)).replace("\\", "/"),
        "authority_inputs": list(plan.authority_inputs),
        "authority_sha256": _authority_sha256(plan),
        "receipt_schema": plan.receipt_schema,
        "executor": {
            "max_workers": plan.executor_max_workers,
            "resource_policies": [
                {"name": policy.name, "max_parallel": policy.max_parallel}
                for policy in plan.resource_policies
            ],
            "github_job_timeout_envelopes": _timeout_envelope_projection(plan),
        },
        "ci_families": [family.data for family in plan.families],
        "matrix_cells": [cell.data for cell in plan.matrix_cells],
        "commands": [command.data for command in plan.commands],
        "toolchain_policies": [policy.data for policy in plan.toolchain_policies],
        "local": {
            "always": list(plan.always),
            "always_command_ids": [
                f"local.always.{index}" for index, _command in enumerate(plan.always)
            ],
            "commands": local_commands,
            "rules": local_rules,
        },
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _markdown_projection(plan: ProofPlan) -> str:
    unique_local_commands = {
        command for rule in plan.local_rules for command in rule.get("gates", [])
    } | set(plan.always)
    lines = [
        "# Generated proof plan",
        "",
        "> Generated by `tools/gen_proof_plan.py` from "
        "`tools/proof_plan.toml`; do not edit.",
        "",
        "## Authority compression",
        "",
        "| Metric | Before report 001 | Current |",
        "|---|---:|---:|",
        "| Hand-maintained path-to-proof authorities | 4 | 1 |",
        f"| CI selection families | 5 | {len(plan.families)} |",
        f"| Hashed executable authority inputs | 1 | {len(plan.authority_inputs)} |",
        f"| Local path rules | 35 | {len(plan.local_rules)} |",
        f"| Unique local commands | 73 | {len(unique_local_commands)} |",
        "| Handwritten Python classifier rule tables | 5 | 0 |",
        "",
        "## CI families",
        "",
        "Every selected family expands to stable command IDs. Each command binds "
        "an exact OS/architecture/Python/backend/target/profile cell, timeout, "
        "resource class, cache domain, and DAG parents. CI admission requires "
        "receipts whose canonical LF-normalized authority-closure digest, source "
        "commit, command, cell, execution partition, duration, peak RSS, cache "
        "disposition, and version-constrained toolchain identities validate.",
        "",
        "Proof-family selection parents and GitHub admission edges are distinct "
        "authorities. A family may depend on another family only when it consumes "
        "that family's data or control result. Independent admissions depend only "
        "on the changed-path classifier, so a selected sibling failure cannot mask "
        "their execution; the Proof Plan Verdict remains the sole conjunction.",
        "",
        "The canonical executor admits dependency-ready commands in manifest "
        "order, bounds global fanout at "
        f"{plan.executor_max_workers}, and enforces these per-resource limits:",
        "",
        "| Resource | Max parallel commands |",
        "|---|---:|",
        *[
            f"| `{policy.name}` | {policy.max_parallel} |"
            for policy in plan.resource_policies
        ],
        "",
        "GitHub job budgets are validated against a deterministic worst-case "
        "DAG schedule in which every admitted command consumes its full declared "
        "timeout. The projection accounts for dependencies, the global worker "
        "ceiling, and per-resource capacity.",
        "",
        "| Family | Tiers | Required | Executor | Timeout | Projected | Headroom | Resource | Selection parents | Admission | Inputs |",
        "|---|---|---:|---|---:|---:|---:|---|---|---|---:|",
    ]
    for family in plan.families:
        data = family.data
        if data["executor"] == "github-job":
            projected = plan.timeout_envelope(family.name).projected_makespan_seconds
            projected_cell = f"{projected} s"
            headroom_cell = f"{int(data['timeout_minutes']) * 60 - projected} s"
        else:
            projected_cell = "n/a"
            headroom_cell = "n/a"
        lines.append(
            f"| `{family.name}` | {', '.join(data['tiers'])} | "
            f"{'yes' if data['required'] else 'no'} | `{data['executor']}` | "
            f"{data['timeout_minutes']} min | {projected_cell} | {headroom_cell} | "
            f"`{data['resource_class']}` | "
            f"{', '.join(f'`{name}`' for name in data['dependencies']) or 'none'} | "
            f"`{data['admission_job']}` needs "
            f"{', '.join(f'`{name}`' for name in data['admission_needs']) or 'none'} | "
            f"{len(data['inputs'])} |"
        )
    lines.extend(
        [
            "",
            "## Matrix cells",
            "",
            "`github-matrix` families project these cells directly into the "
            "workflow strategy. The runner is therefore generated policy, not "
            "a second handwritten OS list.",
            "",
            "| Cell | Runner | OS | Architecture | Python | Backend | Target | Profile |",
            "|---|---|---|---|---|---|---|---|",
            *[
                f"| `{cell.id}` | `{cell.data['runner']}` | `{cell.data['os']}` | "
                f"`{cell.data['arch']}` | `{cell.data['python']}` | "
                f"`{cell.data['backend']}` | `{cell.data['target']}` | "
                f"`{cell.data['profile']}` |"
                for cell in plan.matrix_cells
            ],
            "",
            "## Toolchain contracts",
            "",
            "Receipts record resolved path, version text, and the repository-relative "
            "probe working directory, bind their identity hash to all three, and fail "
            "unless the version satisfies this authority.",
            "",
            "| Toolchain | Required version | Probe cwd | Setup value | Setup evidence |",
            "|---|---|---|---|---:|",
        ]
    )
    for policy in plan.toolchain_policies:
        data = policy.data
        lines.append(
            f"| `{policy.name}` | `{data['version_pattern']}` | "
            f"`{data.get('probe_cwd', '.')}` | `{data['setup_value']}` | "
            f"{len(data['setup_evidence'])} |"
        )
    lines.extend(
        [
            "",
            "## Executable partitions",
            "",
            "| Command ID | Family | Cell | Timeout | Resource | Parents |",
            "|---|---|---|---:|---|---:|",
        ]
    )
    for command in plan.commands:
        data = command.data
        lines.append(
            f"| `{command.id}` | `{data['family']}` | `{data['cell']}` | "
            f"{data['timeout_seconds']} s | `{data['resource_class']}` | "
            f"{len(data['dependencies'])} |"
        )
    lines.extend(
        [
            "",
            "## Local integration families",
            "",
            "| Rule | Input globs | Commands | Fresh toolchain |",
            "|---|---:|---:|---:|",
        ]
    )
    for rule in plan.local_rules:
        lines.append(
            f"| `{rule['name']}` | {len(rule['globs'])} | {len(rule['gates'])} | "
            f"{'yes' if rule.get('require_fresh_toolchain', False) else 'no'} |"
        )
    lines.extend(
        [
            "",
            "## Selection contract",
            "",
            "Pull requests use the merge-base diff. Pushes use the event's "
            "`before..after` identities. Forced pushes, null SHAs, missing refs, "
            "and unknown events fail closed to the full plan. Merge-group, "
            "scheduled, and manual runs intentionally select the full plan. The "
            "topology projection "
            "records why every family was selected; the executable matrix expands "
            "selected `github-matrix` families into exact runner cells.",
            "",
        ]
    )
    return "\n".join(lines)


def _check_or_write(path: Path, content: str, *, check: bool) -> bool:
    if check:
        if not generated_file_matches(path, content):
            print(
                f"proof-plan projection stale: {path.relative_to(ROOT)}",
                file=sys.stderr,
            )
            return False
        return True
    write_generated_text(path, content)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args(argv)
    plan = ProofPlan.load(args.manifest)
    ok = all(
        (
            _check_or_write(JSON_OUTPUT, _json_projection(plan), check=args.check),
            _check_or_write(DOC_OUTPUT, _markdown_projection(plan), check=args.check),
        )
    )
    if ok:
        mode = "verified" if args.check else "generated"
        print(
            f"proof-plan: {mode} families={len(plan.families)} "
            f"commands={len(plan.commands)} cells={len(plan.matrix_cells)} "
            f"local_rules={len(plan.local_rules)}"
        )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
