#!/usr/bin/env python3
"""Generate Molt's Rust-native StringPrep tables from CPython's oracle."""

from __future__ import annotations

import argparse
import difflib
import stringprep
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "runtime/molt-runtime-stringprep/src/tables.rs"

TABLE_FUNCS: tuple[tuple[str, str], ...] = (
    ("A1_RANGES", "in_table_a1"),
    ("B1_RANGES", "in_table_b1"),
    ("C11_RANGES", "in_table_c11"),
    ("C12_RANGES", "in_table_c12"),
    ("C21_RANGES", "in_table_c21"),
    ("C22_RANGES", "in_table_c22"),
    ("C3_RANGES", "in_table_c3"),
    ("C4_RANGES", "in_table_c4"),
    ("C5_RANGES", "in_table_c5"),
    ("C6_RANGES", "in_table_c6"),
    ("C7_RANGES", "in_table_c7"),
    ("C8_RANGES", "in_table_c8"),
    ("C9_RANGES", "in_table_c9"),
    ("D1_RANGES", "in_table_d1"),
    ("D2_RANGES", "in_table_d2"),
)

MAP_FUNCS: tuple[tuple[str, str], ...] = (
    ("B2_MAPPINGS", "map_table_b2"),
    ("B3_MAPPINGS", "map_table_b3"),
)


def _ranges_for(func_name: str) -> list[tuple[int, int]]:
    func = getattr(stringprep, func_name)
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    prev: int | None = None
    for cp in range(0x110000):
        matched = bool(func(chr(cp)))
        if matched:
            if start is None:
                start = prev = cp
            elif prev is not None and cp == prev + 1:
                prev = cp
            else:
                ranges.append((start, prev if prev is not None else start))
                start = prev = cp
        elif start is not None:
            ranges.append((start, prev if prev is not None else start))
            start = prev = None
    if start is not None:
        ranges.append((start, prev if prev is not None else start))
    return ranges


def _mappings_for(func_name: str) -> list[tuple[int, str]]:
    func = getattr(stringprep, func_name)
    mappings: list[tuple[int, str]] = []
    for cp in range(0x110000):
        ch = chr(cp)
        mapped = func(ch)
        if mapped != ch:
            mappings.append((cp, mapped))
    return mappings


def _rust_str_literal(value: str) -> str:
    chunks: list[str] = ['"']
    for ch in value:
        cp = ord(ch)
        if ch == "\\":
            chunks.append("\\\\")
        elif ch == '"':
            chunks.append('\\"')
        elif ch == "\n":
            chunks.append("\\n")
        elif ch == "\r":
            chunks.append("\\r")
        elif ch == "\t":
            chunks.append("\\t")
        elif 0x20 <= cp <= 0x7E:
            chunks.append(ch)
        else:
            chunks.append(f"\\u{{{cp:X}}}")
    chunks.append('"')
    return "".join(chunks)


def _render_ranges(name: str, ranges: list[tuple[int, int]]) -> list[str]:
    lines = [f"pub(crate) const {name}: &[(u32, u32)] = &[\n"]
    for start, end in ranges:
        lines.append(f"    (0x{start:06X}, 0x{end:06X}),\n")
    lines.append("];\n\n")
    return lines


def _render_mappings(name: str, mappings: list[tuple[int, str]]) -> list[str]:
    lines = [f"pub(crate) const {name}: &[(u32, &str)] = &[\n"]
    for cp, mapped in mappings:
        lines.append(f"    (0x{cp:06X}, {_rust_str_literal(mapped)}),\n")
    lines.append("];\n\n")
    return lines


def render() -> str:
    lines = [
        "// @generated by tools/gen_stringprep_tables.py. DO NOT EDIT.\n",
        "// Source authority: CPython's `stringprep` module behavior for RFC 3454\n",
        "// StringPrep. The generated data is runtime-native and has no host-Python\n",
        "// dependency in compiled binaries.\n\n",
    ]
    for rust_name, func_name in TABLE_FUNCS:
        lines.extend(_render_ranges(rust_name, _ranges_for(func_name)))
    for rust_name, func_name in MAP_FUNCS:
        lines.extend(_render_mappings(rust_name, _mappings_for(func_name)))
    return "".join(lines)


def _rustfmt_text(text: str) -> str:
    tmp_dir = ROOT / "tmp"
    tmp_dir.mkdir(exist_ok=True)
    tmp = tmp_dir / "stringprep_tables.generated.rs"
    tmp.write_text(text, encoding="utf-8")
    try:
        result = subprocess.run(
            ["rustfmt", str(tmp)],
            check=False,
            capture_output=True,
            text=True,
            timeout=60.0,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "rustfmt failed while formatting generated stringprep tables:\n"
                f"stdout:\n{result.stdout}\n"
                f"stderr:\n{result.stderr}"
            )
        return tmp.read_text(encoding="utf-8")
    finally:
        tmp.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check without writing")
    args = parser.parse_args()

    rendered = _rustfmt_text(render())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            diff = difflib.unified_diff(
                current.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile=str(OUT),
                tofile=f"{OUT} (generated)",
            )
            sys.stderr.writelines(diff)
            return 1
        print("stringprep tables: in sync")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
