#!/usr/bin/env python3
"""Generate the differential-lane test manifests from COVERAGE_INDEX.yaml.

Single source of truth: ``tests/differential/COVERAGE_INDEX.yaml`` plus the
on-disk stdlib/pyperformance test files. Renders the three lane manifests so the
runner's lane membership cannot silently drift from the coverage index.

Usage::

    python3 tools/gen_diff_lanes.py            # (re)write the lane manifests
    python3 tools/gen_diff_lanes.py --check    # exit 1 if a manifest is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COVERAGE_INDEX = ROOT / "tests" / "differential" / "COVERAGE_INDEX.yaml"
CORE_MANIFEST = ROOT / "tests" / "differential" / "basic" / "CORE_TESTS.txt"
STDLIB_MANIFEST = ROOT / "tests" / "differential" / "stdlib" / "TESTS.txt"
PYPERFORMANCE_MANIFEST = ROOT / "tests" / "differential" / "pyperformance" / "TESTS.txt"

CORE_EXTRA = {
    "tests/differential/basic/try_except.py",
}


def _parse_coverage_lists() -> tuple[set[str], set[str], set[str]]:
    core: set[str] = set()
    stdlib: set[str] = set()
    pyperformance: set[str] = set()
    section: str | None = None
    for raw in COVERAGE_INDEX.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw.startswith("core:"):
            section = "core"
            continue
        if raw.startswith("pyperformance:"):
            section = "pyperformance"
            continue
        if raw.startswith("stdlib:"):
            section = "stdlib"
            continue
        stripped = raw.lstrip()
        if not stripped.startswith("- "):
            continue
        path = stripped[2:].strip()
        if not path.endswith(".py"):
            continue
        if section == "core":
            core.add(path)
        elif section == "stdlib":
            stdlib.add(path)
        elif section == "pyperformance":
            pyperformance.add(path)
    return core, stdlib, pyperformance


def _render_manifest(title: str, tests: list[str]) -> str:
    lines = [
        f"# {title}",
        "# Generated by: python3 tools/gen_diff_lanes.py",
        "# One test path per line, repo-root-relative.",
        "",
    ]
    lines.extend(tests)
    lines.append("")
    return "\n".join(lines)


def _render_all() -> dict[Path, str]:
    """Render the three lane manifests from the coverage index + on-disk tests."""
    core, stdlib, pyperformance = _parse_coverage_lists()
    stdlib_dir = ROOT / "tests" / "differential" / "stdlib"
    # Emit POSIX-style repo-relative paths so the rendered manifest is identical
    # on every OS (str(Path) yields backslashes on Windows — the manifest must
    # be byte-stable cross-platform for the --check gate to mean anything).
    stdlib_existing = {
        path.relative_to(ROOT).as_posix() for path in stdlib_dir.rglob("*.py")
    }
    pyperformance_dir = ROOT / "tests" / "differential" / "pyperformance"
    pyperformance_existing = {
        path.relative_to(ROOT).as_posix()
        for path in pyperformance_dir.glob("*.py")
        if path.name != "TESTS.txt"
    }
    stdlib |= stdlib_existing
    pyperformance |= pyperformance_existing
    core |= CORE_EXTRA
    core -= stdlib
    return {
        CORE_MANIFEST: _render_manifest("Core Differential Lane", sorted(core)),
        STDLIB_MANIFEST: _render_manifest("Stdlib Differential Lane", sorted(stdlib)),
        PYPERFORMANCE_MANIFEST: _render_manifest(
            "PyPerformance Differential Lane", sorted(pyperformance)
        ),
    }


def _check(rendered: dict[Path, str]) -> bool:
    ok = True
    for path, text in rendered.items():
        rel = path.relative_to(ROOT)
        if not path.exists():
            print(f"MISSING generated file: {rel}", file=sys.stderr)
            ok = False
            continue
        if path.read_text(encoding="utf-8") != text:
            print(
                f"STALE generated file: {rel}\n"
                "  run `python3 tools/gen_diff_lanes.py` to regenerate",
                file=sys.stderr,
            )
            ok = False
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if a generated manifest is stale (CI mode); do not write",
    )
    args = parser.parse_args()

    rendered = _render_all()

    if args.check:
        if _check(rendered):
            print("differential lane manifests: in sync")
            return 0
        return 1

    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        # Test lines are the non-comment, non-blank lines of the manifest body.
        n_tests = sum(
            1 for line in text.splitlines() if line and not line.startswith("#")
        )
        print(f"wrote {path.relative_to(ROOT)} ({n_tests} tests)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
