#!/usr/bin/env python3
"""
Generate the versioned CPython stdlib top-level union baseline.

This script is the single writer for `tools/stdlib_module_union.py` and its
per-version generated siblings (`tools/stdlib_module_union_*.py`). It derives
the data for each supported version from the CPython source revision pinned in
`config/cpython_regrtest_sources.toml`, never from a host interpreter, whose
build may drop or add files:

1. module names: `Python/stdlib_module_names.h`, the list CPython compiles
   into `sys.stdlib_module_names`;
2. packages: the module names that are directories under `Lib/`, which is
   where `importlib.util.find_spec(name).submodule_search_locations` points on
   an unmodified install;
3. `.py` modules and packages: every `.py` file under `Lib/` whose top-level
   name is a module name; an `__init__.py` names its package.

`config/cpython_stdlib_snapshot.json` holds those inputs with a receipt per
input (tag, revision, path, git object id, sha256), so `--check` and `--write`
run offline. `--refresh-sources` fetches the pinned tags with git, requires
each tag to resolve to its pinned revision, and fails closed, writing nothing,
when the content at an unchanged revision differs from its receipt.

The selected versions are the supported target-Python authority
(`src/molt/target_python.py`); each needs a pinned source row.

Usage::

    python3 tools/gen_stdlib_module_union.py --refresh-sources   # network
    python3 tools/gen_stdlib_module_union.py --write
    python3 tools/gen_stdlib_module_union.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for _import_root in (ROOT, ROOT / "src", ROOT / "tools"):
    if str(_import_root) not in sys.path:
        sys.path.insert(0, str(_import_root))

from tools import harness_memory_guard  # noqa: E402
from tools.cpython_regrtest import (  # noqa: E402
    CPYTHON_SOURCES,
    CPythonSource,
    load_cpython_sources,
)
from tools.generator_io import (  # noqa: E402
    canonical_generated_bytes,
    display_path,
    generator_main,
    write_generated_text,
)

from molt.target_python import (  # noqa: E402
    SUPPORTED_TARGET_PYTHON_SHORT_VERSIONS,
)

OUT_PATH = ROOT / "tools" / "stdlib_module_union.py"
SNAPSHOT_PATH = ROOT / "config" / "cpython_stdlib_snapshot.json"
PINS_PATH = CPYTHON_SOURCES
# Derived from the single `TargetPythonVersion` authority
# (src/molt/target_python.py) so a supported-version bump lands in exactly
# one place. tools/check_table_drift.py gates the derivation.
DEFAULT_PYTHONS = SUPPORTED_TARGET_PYTHON_SHORT_VERSIONS
GENERATED_DATA_MARKER = "Autogenerated CPython stdlib union baseline data."
SNAPSHOT_SCHEMA = "molt.cpython-stdlib-snapshot.v1"
HEADER_PATH = "Python/stdlib_module_names.h"
LIB_PATH = "Lib"
REFRESH_COMMAND = "python3 tools/gen_stdlib_module_union.py --refresh-sources"

_HEADER_ARRAY = "static const char* _Py_stdlib_module_names[] = {"
_HEADER_NAME = re.compile(r'"([A-Za-z_][A-Za-z0-9_]*)",')
_GIT_OBJECT_ID = re.compile(r"[0-9a-f]{40}")
_GIT_TIMEOUT_SECONDS = 300.0


@dataclass(frozen=True)
class SourceSnapshot:
    """The pinned inputs of one version and their receipts.

    ``lib_entries`` lists, relative to ``Lib/``, every directory (with a
    trailing ``/``) and every ``.py`` file whose top-level name is in the
    header; nothing else under ``Lib/`` can enter the union.
    """

    python: str
    tag: str
    revision: str
    header_object: str
    header_lines: tuple[str, ...]
    lib_object: str
    lib_entries: tuple[str, ...]

    def header_bytes(self) -> bytes:
        return ("\n".join(self.header_lines) + "\n").encode("utf-8")

    def lib_listing_bytes(self) -> bytes:
        return ("\n".join(self.lib_entries) + "\n").encode("utf-8")

    def receipts(self) -> dict[str, tuple[str, str]]:
        """Each input path mapped to its (git object id, sha256)."""
        return {
            HEADER_PATH: (self.header_object, _sha256(self.header_bytes())),
            LIB_PATH: (self.lib_object, _sha256(self.lib_listing_bytes())),
        }


@dataclass(frozen=True)
class VersionData:
    """The union baseline of one version and the source it came from."""

    tag: str
    revision: str
    modules: tuple[str, ...]
    packages: tuple[str, ...]
    py_modules: tuple[str, ...]
    py_packages: tuple[str, ...]


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _git_blob_id(payload: bytes) -> str:
    return hashlib.sha1(b"blob %d\0" % len(payload) + payload).hexdigest()


def _version_key(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


# ---------------------------------------------------------------------------
# Derivation: the semantics of `sys.stdlib_module_names`, `find_spec` and a
# walk of the installed stdlib directory, computed from the source tree.
# ---------------------------------------------------------------------------


def parse_stdlib_module_names(lines: Sequence[str]) -> tuple[str, ...]:
    """The sorted names in CPython's `_Py_stdlib_module_names` array."""
    try:
        start = list(lines).index(_HEADER_ARRAY)
    except ValueError:
        raise ValueError(f"{HEADER_PATH}: no {_HEADER_ARRAY!r} line") from None
    names: list[str] = []
    for line in lines[start + 1 :]:
        if line == "};":
            break
        match = _HEADER_NAME.fullmatch(line)
        if match is None:
            raise ValueError(f"{HEADER_PATH}: unexpected array line {line!r}")
        names.append(match.group(1))
    else:
        raise ValueError(f"{HEADER_PATH}: the module-name array is not closed")
    if not names:
        raise ValueError(f"{HEADER_PATH}: the module-name array is empty")
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise ValueError(f"{HEADER_PATH}: duplicate module names {duplicates}")
    return tuple(sorted(names))


def _top_level_name(entry: str) -> str:
    first, _, rest = entry.partition("/")
    if not rest and first.endswith(".py"):
        return first[: -len(".py")]
    return first


def derive_version_data(
    modules: Sequence[str], lib_entries: Iterable[str]
) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """(packages, py_modules, py_packages) of one stdlib tree.

    ``lib_entries`` are paths relative to the stdlib directory: a directory
    ends with ``/``. The `.py` rules match a walk of an installed stdlib
    directory exactly, including the exclusions only an install can hold
    (``__pycache__``, ``site-packages``, ``config-*``). A module name is a
    package exactly when it names a directory: CPython has no extension or
    frozen package in `sys.stdlib_module_names`, so `find_spec` reports
    `submodule_search_locations` for that directory and for nothing else.
    """
    module_set = frozenset(modules)
    directories: set[str] = set()
    py_modules: set[str] = set()
    py_packages: set[str] = set()
    for entry in lib_entries:
        if entry.endswith("/"):
            directories.add(entry[:-1])
            continue
        if not entry.endswith(".py"):
            continue
        parts = tuple(entry.split("/"))
        if "__pycache__" in parts:
            continue
        if any(part in {"site-packages", "dist-packages"} for part in parts):
            continue
        if parts[0].startswith("config-"):
            continue
        if parts[-1] == "__init__.py":
            if len(parts) == 1:
                continue
            name = ".".join(parts[:-1])
            if name.split(".", 1)[0] not in module_set:
                continue
            py_packages.add(name)
            py_modules.add(name)
        else:
            name = ".".join((*parts[:-1], parts[-1][: -len(".py")]))
            if name.split(".", 1)[0] not in module_set:
                continue
            py_modules.add(name)
    packages = tuple(name for name in sorted(module_set) if name in directories)
    return packages, tuple(sorted(py_modules)), tuple(sorted(py_packages))


def version_data(snapshot: SourceSnapshot) -> VersionData:
    modules = parse_stdlib_module_names(snapshot.header_lines)
    packages, py_modules, py_packages = derive_version_data(
        modules, snapshot.lib_entries
    )
    if not py_modules:
        raise RuntimeError(f"empty stdlib python-module list for {snapshot.python}")
    return VersionData(
        tag=snapshot.tag,
        revision=snapshot.revision,
        modules=modules,
        packages=packages,
        py_modules=py_modules,
        py_packages=py_packages,
    )


# ---------------------------------------------------------------------------
# The committed snapshot: offline inputs with receipts.
# ---------------------------------------------------------------------------


def render_snapshot(snapshots: Mapping[str, SourceSnapshot]) -> str:
    sources = []
    for version in sorted(snapshots, key=_version_key):
        snapshot = snapshots[version]
        receipts = snapshot.receipts()
        sources.append(
            {
                "python": snapshot.python,
                "tag": snapshot.tag,
                "revision": snapshot.revision,
                "header": {
                    "path": HEADER_PATH,
                    "git_object": receipts[HEADER_PATH][0],
                    "sha256": receipts[HEADER_PATH][1],
                    "lines": list(snapshot.header_lines),
                },
                "lib": {
                    "path": LIB_PATH,
                    "git_object": receipts[LIB_PATH][0],
                    "sha256": receipts[LIB_PATH][1],
                    "entries": list(snapshot.lib_entries),
                },
            }
        )
    return json.dumps({"schema": SNAPSHOT_SCHEMA, "sources": sources}, indent=2) + "\n"


def _exact_keys(row: object, keys: set[str], where: str) -> dict[str, object]:
    if not isinstance(row, dict) or set(row) != keys:
        raise ValueError(f"{where}: expected exactly the keys {sorted(keys)}")
    return row


def _string(row: Mapping[str, object], key: str, where: str) -> str:
    value = row[key]
    if not isinstance(value, str):
        raise ValueError(f"{where}: {key} must be a string")
    return value


def _strings(row: Mapping[str, object], key: str, where: str) -> tuple[str, ...]:
    value = row[key]
    if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
        raise ValueError(f"{where}: {key} must be a list of strings")
    return tuple(value)


def _snapshot_from_row(row: object, where: str) -> SourceSnapshot:
    source = _exact_keys(row, {"python", "tag", "revision", "header", "lib"}, where)
    header = _exact_keys(
        source["header"], {"path", "git_object", "sha256", "lines"}, f"{where}.header"
    )
    lib = _exact_keys(
        source["lib"], {"path", "git_object", "sha256", "entries"}, f"{where}.lib"
    )
    if header["path"] != HEADER_PATH or lib["path"] != LIB_PATH:
        raise ValueError(f"{where}: input paths must be {HEADER_PATH} and {LIB_PATH}")
    snapshot = SourceSnapshot(
        python=_string(source, "python", where),
        tag=_string(source, "tag", where),
        revision=_string(source, "revision", where),
        header_object=_string(header, "git_object", f"{where}.header"),
        header_lines=_strings(header, "lines", f"{where}.header"),
        lib_object=_string(lib, "git_object", f"{where}.lib"),
        lib_entries=_strings(lib, "entries", f"{where}.lib"),
    )
    for object_id in (snapshot.revision, snapshot.header_object, snapshot.lib_object):
        if _GIT_OBJECT_ID.fullmatch(object_id) is None:
            raise ValueError(f"{where}: {object_id!r} is not a full git object id")
    if list(snapshot.lib_entries) != sorted(set(snapshot.lib_entries)):
        raise ValueError(f"{where}.lib: entries must be sorted and unique")
    recorded = {HEADER_PATH: header["sha256"], LIB_PATH: lib["sha256"]}
    mismatched = [
        f"{path} (sha256)"
        for path, (_object_id, sha256) in snapshot.receipts().items()
        if sha256 != recorded[path]
    ]
    if _git_blob_id(snapshot.header_bytes()) != snapshot.header_object:
        mismatched.append(f"{HEADER_PATH} (git blob id)")
    if mismatched:
        raise ValueError(
            f"{where}: content does not match its receipt for " + ", ".join(mismatched)
        )
    return snapshot


def load_snapshot(path: Path) -> dict[str, SourceSnapshot]:
    """Every version's inputs, each verified against its receipt."""
    try:
        text = canonical_generated_bytes(path.read_bytes()).decode("utf-8")
    except FileNotFoundError:
        raise RuntimeError(
            f"{display_path(path)} is missing; run `{REFRESH_COMMAND}`"
        ) from None
    data = _exact_keys(json.loads(text), {"schema", "sources"}, display_path(path))
    if data["schema"] != SNAPSHOT_SCHEMA:
        raise ValueError(f"{display_path(path)}: schema must be {SNAPSHOT_SCHEMA!r}")
    rows = data["sources"]
    if not isinstance(rows, list):
        raise ValueError(f"{display_path(path)}: sources must be a list")
    snapshots: dict[str, SourceSnapshot] = {}
    for index, row in enumerate(rows):
        snapshot = _snapshot_from_row(row, f"{display_path(path)} sources[{index}]")
        if snapshot.python in snapshots:
            raise ValueError(
                f"{display_path(path)}: duplicate source for {snapshot.python}"
            )
        snapshots[snapshot.python] = snapshot
    if text != render_snapshot(snapshots):
        raise ValueError(
            f"{display_path(path)} is not in canonical form; run `{REFRESH_COMMAND}`"
        )
    return snapshots


def pinned_snapshots(versions: Sequence[str]) -> dict[str, SourceSnapshot]:
    """The snapshot of each version, bound to the pinned source authority."""
    pins = load_cpython_sources(PINS_PATH)
    unpinned = [version for version in versions if version not in pins]
    if unpinned:
        raise RuntimeError(
            f"{display_path(PINS_PATH)} pins no CPython source for {unpinned}"
        )
    snapshots = load_snapshot(SNAPSHOT_PATH)
    problems = [
        f"{version} is missing" for version in versions if version not in snapshots
    ]
    for version in versions:
        snapshot = snapshots.get(version)
        pin = pins[version]
        if snapshot is not None and (snapshot.tag, snapshot.revision) != (
            pin.tag,
            pin.revision,
        ):
            problems.append(
                f"{version} holds {snapshot.tag} ({snapshot.revision}) but the pin "
                f"is {pin.tag} ({pin.revision})"
            )
    problems.extend(
        f"{version} is not a supported version"
        for version in sorted(set(snapshots) - set(versions), key=_version_key)
    )
    if problems:
        raise RuntimeError(
            f"{display_path(SNAPSHOT_PATH)} does not match "
            f"{display_path(PINS_PATH)}: {'; '.join(problems)}; "
            f"run `{REFRESH_COMMAND}`"
        )
    return {version: snapshots[version] for version in versions}


# ---------------------------------------------------------------------------
# Refresh: the only network path.
# ---------------------------------------------------------------------------


def _git(args: Sequence[str], *, cwd: Path) -> bytes:
    command = ["git", *args]
    result = harness_memory_guard.guarded_completed_process(
        command,
        prefix="MOLT_GENERATOR",
        cwd=cwd,
        env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
        capture_output=True,
        text=False,
        timeout=_GIT_TIMEOUT_SECONDS,
    )
    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", "replace") if result.stderr else ""
        raise RuntimeError(
            f"`{' '.join(command)}` failed with exit code {result.returncode}: "
            f"{stderr.strip()}"
        )
    return result.stdout or b""


def _header_lines(payload: bytes) -> tuple[str, ...]:
    text = payload.decode("utf-8")
    if not text.endswith("\n") or "\r" in text:
        raise ValueError(f"{HEADER_PATH}: expected LF lines ending in a newline")
    lines = tuple(text[:-1].split("\n"))
    if ("\n".join(lines) + "\n").encode("utf-8") != payload:
        raise ValueError(f"{HEADER_PATH}: lines do not reproduce the blob")
    return lines


def _lib_entries(listing: bytes, modules: Sequence[str]) -> tuple[str, ...]:
    """Directories and `.py` files below the top-level names in ``modules``."""
    module_set = frozenset(modules)
    entries: set[str] = set()
    for record in listing.decode("utf-8").split("\0"):
        if not record:
            continue
        meta, _, path = record.partition("\t")
        _mode, kind, _object_id = meta.split(" ")
        if _top_level_name(path) not in module_set:
            continue
        if kind == "tree":
            entries.add(path + "/")
        elif kind == "blob":
            if path.endswith(".py"):
                entries.add(path)
        else:
            raise ValueError(f"{LIB_PATH}/{path}: unsupported tree entry {kind!r}")
    return tuple(sorted(entries))


def fetch_pinned_source(pin: CPythonSource) -> SourceSnapshot:
    """Fetch one pinned tag without blobs and read its stdlib inputs.

    Git verifies every object id it receives, so a tag that resolves to the
    pinned revision yields exactly the tree and header at that revision.
    """
    from molt.temporary_artifacts import OwnedTemporaryDirectory

    with OwnedTemporaryDirectory(prefix="molt-cpython-stdlib-") as scratch:
        repo = Path(scratch)
        _git(["init", "--quiet", "--bare", str(repo)], cwd=repo)

        def git(*args: str) -> bytes:
            return _git(["-C", str(repo), *args], cwd=repo)

        tag_ref = f"refs/tags/{pin.tag}"
        git("remote", "add", "origin", pin.git_url)
        git(
            "fetch",
            "--quiet",
            "--no-tags",
            "--depth=1",
            "--filter=blob:none",
            "origin",
            f"+{tag_ref}:{tag_ref}",
        )
        revision = git("rev-parse", "--verify", f"{tag_ref}^{{commit}}").decode()
        revision = revision.strip()
        if revision != pin.revision:
            raise RuntimeError(
                f"CPython tag {pin.tag} resolves to {revision}, but "
                f"{display_path(PINS_PATH)} pins {pin.revision}"
            )
        header_object = git("rev-parse", "--verify", f"{revision}:{HEADER_PATH}")
        header_object_id = header_object.decode().strip()
        header = git("cat-file", "blob", header_object_id)
        if _git_blob_id(header) != header_object_id:
            raise RuntimeError(f"{HEADER_PATH}: blob does not hash to its object id")
        lib_object = git("rev-parse", "--verify", f"{revision}:{LIB_PATH}")
        lib_object_id = lib_object.decode().strip()
        listing = git("ls-tree", "-r", "-t", "-z", lib_object_id)
    lines = _header_lines(header)
    return SourceSnapshot(
        python=pin.python,
        tag=pin.tag,
        revision=revision,
        header_object=header_object_id,
        header_lines=lines,
        lib_object=lib_object_id,
        lib_entries=_lib_entries(listing, parse_stdlib_module_names(lines)),
    )


def refresh_sources(
    fetch: Callable[[CPythonSource], SourceSnapshot] = fetch_pinned_source,
) -> int:
    """Re-fetch every pinned input; write the snapshot only if all agree.

    Content at a revision the snapshot already records must match its
    receipt; a moved pin replaces that version's inputs.
    """
    versions = tuple(dict.fromkeys(DEFAULT_PYTHONS))
    pins = load_cpython_sources(PINS_PATH)
    unpinned = [version for version in versions if version not in pins]
    if unpinned:
        raise RuntimeError(
            f"{display_path(PINS_PATH)} pins no CPython source for {unpinned}"
        )
    current = load_snapshot(SNAPSHOT_PATH) if SNAPSHOT_PATH.exists() else {}
    refreshed: dict[str, SourceSnapshot] = {}
    for version in versions:
        fetched = fetch(pins[version])
        prior = current.get(version)
        if prior is not None and prior.revision == fetched.revision:
            expected, actual = prior.receipts(), fetched.receipts()
            mismatched = [path for path in expected if expected[path] != actual[path]]
            if mismatched:
                raise RuntimeError(
                    f"CPython {version} at {fetched.revision}: fetched "
                    f"{', '.join(mismatched)} does not match the receipt in "
                    f"{display_path(SNAPSHOT_PATH)}; nothing was written"
                )
        status = "unchanged" if prior == fetched else "refreshed"
        print(f"{version}: {fetched.tag} ({fetched.revision}) {status}")
        refreshed[version] = fetched
    text = render_snapshot(refreshed)
    if SNAPSHOT_PATH.exists() and SNAPSHOT_PATH.read_text(encoding="utf-8") == text:
        print(f"{display_path(SNAPSHOT_PATH)} current")
        return 0
    write_generated_text(SNAPSHOT_PATH, text)
    print(f"wrote {display_path(SNAPSHOT_PATH)}; now run --write")
    return 0


# ---------------------------------------------------------------------------
# Rendering.
# ---------------------------------------------------------------------------


def _format_tuple(items: tuple[str, ...], *, indent: int) -> str:
    spaces = " " * indent
    lines = ["("]
    for item in items:
        lines.append(f'{spaces}"{item}",')
    lines.append(" " * (indent - 4) + ")")
    return "\n".join(lines)


def _version_module_stem(output: Path, version: str) -> str:
    safe = "".join(ch if ch.isalnum() else "_" for ch in version)
    return f"{output.stem}_{safe}"


def _format_version_module(*, version: str, data: VersionData) -> str:
    return "\n".join(
        [
            '"""',
            GENERATED_DATA_MARKER,
            "",
            f"Python baseline: {version}",
            f"CPython source: {data.tag} ({data.revision})",
            "",
            "Generated by tools/gen_stdlib_module_union.py.",
            '"""',
            "",
            f"PYTHON_VERSION = {json.dumps(version)}",
            "",
            f"STDLIB_MODULES = {_format_tuple(data.modules, indent=4)}",
            "",
            f"STDLIB_PACKAGES = {_format_tuple(data.packages, indent=4)}",
            "",
            f"STDLIB_PY_MODULES = {_format_tuple(data.py_modules, indent=4)}",
            "",
            f"STDLIB_PY_PACKAGES = {_format_tuple(data.py_packages, indent=4)}",
            "",
        ]
    )


def _format_facade_module(
    *,
    output: Path,
    versions: tuple[str, ...],
    union_modules: tuple[str, ...],
    union_packages: tuple[str, ...],
    union_py_modules: tuple[str, ...],
    union_py_packages: tuple[str, ...],
    union_py_submodules: tuple[str, ...],
    union_py_subpackages: tuple[str, ...],
) -> str:
    module_stems = {
        version: _version_module_stem(output, version) for version in versions
    }
    # A one-element tuple needs its trailing comma.
    version_items = ", ".join(json.dumps(version) for version in versions)
    version_tuple = f"({version_items}{',' if len(versions) == 1 else ''})"
    return "\n".join(
        [
            '"""',
            "Autogenerated CPython stdlib top-level union baseline.",
            "",
            "Update workflow:",
            "1. Pin each CPython tag and revision in config/cpython_regrtest_sources.toml.",
            "2. Run `python3 tools/gen_stdlib_module_union.py --refresh-sources`.",
            "3. Run `python3 tools/gen_stdlib_module_union.py --write`.",
            "4. Run `python3 tools/gen_stdlib_stubs.py --write`.",
            "5. Re-run `python3 tools/check_stdlib_intrinsics.py --update-doc`.",
            "",
            "This file is consumed by tools/check_stdlib_intrinsics.py and is the",
            "hard gate baseline for top-level + submodule stdlib coverage.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "import importlib.util as _importlib_util",
            "from pathlib import Path as _Path",
            "from types import ModuleType as _ModuleType",
            "",
            f"BASELINE_PYTHON_VERSIONS = {version_tuple}",
            "",
            "_VERSION_MODULE_STEMS = {",
            *(
                f"    {json.dumps(version)}: {json.dumps(stem)},"
                for version, stem in module_stems.items()
            ),
            "}",
            "",
            "",
            "def _load_version_data(version: str) -> _ModuleType:",
            "    stem = _VERSION_MODULE_STEMS[version]",
            '    path = _Path(__file__).with_name(f"{stem}.py")',
            "    spec = _importlib_util.spec_from_file_location(stem, path)",
            "    if spec is None or spec.loader is None:",
            '        raise ImportError(f"cannot load stdlib union data for {version}: {path}")',
            "    module = _importlib_util.module_from_spec(spec)",
            "    spec.loader.exec_module(module)",
            "    return module",
            "",
            "",
            "_VERSION_DATA = {",
            "    version: _load_version_data(version) for version in BASELINE_PYTHON_VERSIONS",
            "}",
            "",
            "STDLIB_MODULES_BY_VERSION = {",
            "    version: _VERSION_DATA[version].STDLIB_MODULES",
            "    for version in BASELINE_PYTHON_VERSIONS",
            "}",
            "STDLIB_PACKAGES_BY_VERSION = {",
            "    version: _VERSION_DATA[version].STDLIB_PACKAGES",
            "    for version in BASELINE_PYTHON_VERSIONS",
            "}",
            "STDLIB_PY_MODULES_BY_VERSION = {",
            "    version: _VERSION_DATA[version].STDLIB_PY_MODULES",
            "    for version in BASELINE_PYTHON_VERSIONS",
            "}",
            "STDLIB_PY_PACKAGES_BY_VERSION = {",
            "    version: _VERSION_DATA[version].STDLIB_PY_PACKAGES",
            "    for version in BASELINE_PYTHON_VERSIONS",
            "}",
            "",
            f"STDLIB_MODULE_UNION = {_format_tuple(union_modules, indent=4)}",
            "",
            f"STDLIB_PACKAGE_UNION = {_format_tuple(union_packages, indent=4)}",
            "",
            f"STDLIB_PY_MODULE_UNION = {_format_tuple(union_py_modules, indent=4)}",
            "",
            f"STDLIB_PY_PACKAGE_UNION = {_format_tuple(union_py_packages, indent=4)}",
            "",
            f"STDLIB_PY_SUBMODULE_UNION = {_format_tuple(union_py_submodules, indent=4)}",
            "",
            f"STDLIB_PY_SUBPACKAGE_UNION = {_format_tuple(union_py_subpackages, indent=4)}",
            "",
        ]
    )


def render_outputs(
    *,
    output: Path,
    versions: tuple[str, ...],
    data: Mapping[str, VersionData],
) -> dict[Path, str]:
    def union(field: Callable[[VersionData], tuple[str, ...]]) -> tuple[str, ...]:
        return tuple(
            sorted({name for version in versions for name in field(data[version])})
        )

    union_py_modules = union(lambda d: d.py_modules)
    union_py_packages = union(lambda d: d.py_packages)
    rendered: dict[Path, str] = {}
    for version in versions:
        path = output.with_name(f"{_version_module_stem(output, version)}.py")
        rendered[path] = _format_version_module(version=version, data=data[version])
    rendered[output] = _format_facade_module(
        output=output,
        versions=versions,
        union_modules=union(lambda d: d.modules),
        union_packages=union(lambda d: d.packages),
        union_py_modules=union_py_modules,
        union_py_packages=union_py_packages,
        union_py_submodules=tuple(name for name in union_py_modules if "." in name),
        union_py_subpackages=tuple(name for name in union_py_packages if "." in name),
    )
    return rendered


def _stale_generated_siblings(output: Path, expected: set[Path]) -> list[Path]:
    """Per-version data modules of a version no longer in the baseline."""
    stale: list[Path] = []
    for path in sorted(output.parent.glob(f"{output.stem}_*.py")):
        if path in expected:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if GENERATED_DATA_MARKER in text:
            stale.append(path)
    return stale


def generated_outputs() -> dict[Path, str]:
    """Each output path mapped to its exact generated text.

    A per-version data module for a version that left the baseline is part of
    the authority: rendering raises while one exists (before any source is
    read), so ``--check`` and ``--write`` both fail closed naming it.
    """
    versions = tuple(dict.fromkeys(DEFAULT_PYTHONS))
    expected = {OUT_PATH} | {
        OUT_PATH.with_name(f"{_version_module_stem(OUT_PATH, version)}.py")
        for version in versions
    }
    stale = _stale_generated_siblings(OUT_PATH, expected)
    if stale:
        raise RuntimeError(
            "delete generated files that tools/gen_stdlib_module_union.py no "
            "longer renders: " + ", ".join(display_path(path) for path in stale)
        )
    snapshots = pinned_snapshots(versions)
    return render_outputs(
        output=OUT_PATH,
        versions=versions,
        data={version: version_data(snapshots[version]) for version in versions},
    )


def main(argv: list[str] | None = None) -> int:
    # Refreshing the pinned inputs is this generator's own mode; checking and
    # writing the outputs stay with the shared generator command line.
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--refresh-sources", action="store_true")
    refresh, rest = parser.parse_known_args(argv)
    if refresh.refresh_sources:
        if rest:
            parser.error("--refresh-sources takes no other option")
        return refresh_sources()
    return generator_main(generated_outputs, rest, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
