#!/usr/bin/env python3
"""Generate the typed frontend rejection registry from its TOML authority."""

from __future__ import annotations

import ast
from dataclasses import dataclass
import json
from pathlib import Path
import re
import tomllib

from generator_io import generator_main


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/molt/frontend/frontend_diagnostics.toml"
OUTPUT = ROOT / "src/molt/frontend/frontend_diagnostics_generated.py"
NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
CODE_RE = re.compile(r"^MOLT-FE([0-9]{3})$")
VALID_TIERS = frozenset({"native", "guarded", "bridge", "unsupported"})
VALID_IMPACTS = frozenset({"low", "medium", "high"})


@dataclass(frozen=True, slots=True)
class Diagnostic:
    name: str
    code: str
    title: str
    tier: str
    impact: str


@dataclass(frozen=True, slots=True)
class RetiredDiagnostic:
    name: str
    code: str
    reason: str


def _code_number(name: str, code: str) -> int:
    match = CODE_RE.fullmatch(code)
    if not NAME_RE.fullmatch(name):
        raise ValueError(f"invalid diagnostic name: {name!r}")
    if match is None:
        raise ValueError(f"invalid diagnostic code: {code!r}")
    return int(match.group(1))


def load_authority(
    path: Path = SOURCE,
) -> tuple[tuple[Diagnostic, ...], tuple[RetiredDiagnostic, ...]]:
    """Active diagnostics in code order, and the retired codes they reserve.

    Active and retired codes together are MOLT-FE001..N with no gap, so a
    retired code is never reused for a different meaning.
    """
    raw = tomllib.loads(path.read_text(encoding="utf-8"))
    if raw.get("schema_version") != 1:
        raise ValueError("frontend diagnostic schema_version must be 1")
    rows = raw.get("diagnostic")
    if not isinstance(rows, list) or not rows:
        raise ValueError("frontend diagnostic authority must define diagnostics")
    retired_rows = raw.get("retired", [])
    if not isinstance(retired_rows, list):
        raise ValueError("retired frontend diagnostics must be an array of tables")
    diagnostics: list[Diagnostic] = []
    retired: list[RetiredDiagnostic] = []
    numbers: dict[int, str] = {}
    names: set[str] = set()

    def claim(name: str, code: str) -> int:
        number = _code_number(name, code)
        if name in names:
            raise ValueError(f"duplicate diagnostic name: {name}")
        if number in numbers:
            raise ValueError(f"duplicate diagnostic code: {code}")
        names.add(name)
        numbers[number] = name
        return number

    for index, row in enumerate(rows, 1):
        if not isinstance(row, dict):
            raise ValueError(f"diagnostic row {index} must be a table")
        diagnostic = Diagnostic(
            name=str(row.get("name", "")),
            code=str(row.get("code", "")),
            title=str(row.get("title", "")),
            tier=str(row.get("tier", "")),
            impact=str(row.get("impact", "")),
        )
        number = claim(diagnostic.name, diagnostic.code)
        if diagnostics and number < _code_number(
            diagnostics[-1].name, diagnostics[-1].code
        ):
            raise ValueError(f"{diagnostic.name}: diagnostics must be in code order")
        if not diagnostic.title:
            raise ValueError(f"{diagnostic.name}: title must not be empty")
        if diagnostic.tier not in VALID_TIERS:
            raise ValueError(f"{diagnostic.name}: invalid tier {diagnostic.tier!r}")
        if diagnostic.impact not in VALID_IMPACTS:
            raise ValueError(f"{diagnostic.name}: invalid impact {diagnostic.impact!r}")
        diagnostics.append(diagnostic)
    for index, row in enumerate(retired_rows, 1):
        if not isinstance(row, dict):
            raise ValueError(f"retired row {index} must be a table")
        entry = RetiredDiagnostic(
            name=str(row.get("name", "")),
            code=str(row.get("code", "")),
            reason=str(row.get("reason", "")),
        )
        claim(entry.name, entry.code)
        if not entry.reason:
            raise ValueError(f"{entry.name}: a retired diagnostic must state why")
        retired.append(entry)
    missing = sorted(set(range(1, len(numbers) + 1)) - set(numbers))
    if missing:
        raise ValueError(
            "frontend diagnostic codes must run MOLT-FE001..N without a gap; "
            f"missing {', '.join(f'MOLT-FE{number:03d}' for number in missing)}"
        )
    return tuple(diagnostics), tuple(retired)


def load_diagnostics(path: Path = SOURCE) -> tuple[Diagnostic, ...]:
    return load_authority(path)[0]


def render(
    diagnostics: tuple[Diagnostic, ...], retired: tuple[RetiredDiagnostic, ...]
) -> str:
    lines = [
        "# @generated by tools/gen_frontend_diagnostics.py from",
        "# src/molt/frontend/frontend_diagnostics.toml. DO NOT EDIT.",
        "",
        "from __future__ import annotations",
        "",
        "from enum import Enum",
        "from typing import Final, Literal, NamedTuple",
        "",
        "",
        "class FrontendDiagnostic(str, Enum):",
    ]
    lines.extend(
        f'    {diagnostic.name.upper()} = "{diagnostic.code}"'
        for diagnostic in diagnostics
    )
    lines.extend(
        [
            "",
            "",
            "class FrontendDiagnosticMetadata(NamedTuple):",
            "    title: str",
            "    detail: str",
            '    tier: Literal["native", "guarded", "bridge", "unsupported"]',
            '    impact: Literal["low", "medium", "high"]',
            "",
            "",
            "FRONTEND_DIAGNOSTIC_METADATA: Final = {",
        ]
    )
    for diagnostic in diagnostics:
        lines.append(
            "    FrontendDiagnostic."
            f"{diagnostic.name.upper()}: FrontendDiagnosticMetadata("
        )
        lines.append(f"        title={json.dumps(diagnostic.title)},")
        lines.append(
            f"        detail={json.dumps(f'{diagnostic.code}: {diagnostic.title}')},"
        )
        lines.append(f"        tier={json.dumps(diagnostic.tier)},")
        lines.append(f"        impact={json.dumps(diagnostic.impact)},")
        lines.append("    ),")
    lines.extend(["}", "", "# Reserved codes: never reuse one for a new meaning."])
    lines.extend(["RETIRED_FRONTEND_DIAGNOSTIC_CODES: Final = frozenset(", "    {"])
    lines.extend(
        f"        {json.dumps(entry.code)},  # {entry.name}" for entry in retired
    )
    lines.extend(["    }", ")", ""])
    return "\n".join(lines)


def _is_name(node: ast.AST | None, name: str) -> bool:
    return isinstance(node, ast.Name) and node.id == name


def validate_consumers(
    diagnostics: tuple[Diagnostic, ...], root: Path = ROOT
) -> tuple[int, dict[str, int]]:
    """Reject legacy stub lanes and untyped frontend rejection construction."""

    known = {diagnostic.name.upper() for diagnostic in diagnostics}
    used = {name: 0 for name in known}
    violations: list[str] = []
    total = 0
    frontend_root = root / "src/molt/frontend"
    for path in sorted(frontend_root.rglob("*.py")):
        if path.name == OUTPUT.name or path.name == "diagnostics.py":
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        relative = path.relative_to(root).as_posix()
        for node in ast.walk(tree):
            if isinstance(node, ast.Raise) and isinstance(node.exc, ast.Call):
                if _is_name(node.exc.func, "NotImplementedError"):
                    violations.append(
                        f"{relative}:{node.lineno}: direct NotImplementedError "
                        "raise bypasses the frontend diagnostic authority"
                    )
            if not isinstance(node, ast.Call):
                continue
            if (
                isinstance(node.func, ast.Attribute)
                and node.func.attr == "unsupported"
                and isinstance(node.func.value, ast.Attribute)
                and node.func.value.attr == "compat"
            ):
                violations.append(
                    f"{relative}:{node.lineno}: direct compat.unsupported call "
                    "bypasses the frontend diagnostic authority"
                )
            if not _is_name(node.func, "FrontendRejection"):
                continue
            total += 1
            first = node.args[0] if node.args else None
            if not (
                isinstance(first, ast.Attribute)
                and (
                    _is_name(first.value, "FrontendDiagnostic")
                    or _is_name(first.value, "Diagnostic")
                )
                and first.attr in known
            ):
                violations.append(
                    f"{relative}:{node.lineno}: FrontendRejection requires a "
                    "generated FrontendDiagnostic member"
                )
                continue
            if not 2 <= len(node.args) <= 4 or node.keywords:
                violations.append(
                    f"{relative}:{node.lineno}: FrontendRejection requires 2-4 "
                    "positional authority fields"
                )
            used[first.attr] += 1
    emission_core = frontend_root / "lowering/emission_core.py"
    emission_tree = ast.parse(
        emission_core.read_text(encoding="utf-8"), filename=str(emission_core)
    )
    for node in ast.walk(emission_tree):
        if not isinstance(node, ast.ExceptHandler):
            continue
        caught = node.type
        names: list[ast.AST] = (
            list(caught.elts) if isinstance(caught, ast.Tuple) else [caught]
        )
        if any(_is_name(name, "NotImplementedError") for name in names):
            violations.append(
                "src/molt/frontend/lowering/emission_core.py:"
                f"{node.lineno}: legacy NotImplementedError conversion lane"
            )
    unused = sorted(name for name, count in used.items() if count == 0)
    if unused:
        violations.append(f"unused frontend diagnostics: {', '.join(unused)}")
    if violations:
        raise ValueError(
            "frontend diagnostic consumer violations:\n" + "\n".join(violations)
        )
    return total, dict(sorted(used.items()))


def generated_outputs() -> dict[Path, str]:
    """Each output path mapped to its exact generated text."""
    diagnostics, retired = load_authority()
    validate_consumers(diagnostics)
    return {OUTPUT: render(diagnostics, retired)}


def main(argv: list[str] | None = None) -> int:
    return generator_main(generated_outputs, argv, description=__doc__)


if __name__ == "__main__":
    raise SystemExit(main())
