#!/usr/bin/env python3
"""Generate WASM ABI/import registry artifacts from the canonical manifest."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    import tomli as tomllib  # type: ignore[no-redef]

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "runtime/molt-backend/src/wasm_abi_manifest.toml"
OUT_RS = ROOT / "runtime/molt-backend/src/wasm_abi_generated.rs"
OUT_PY = ROOT / "src/molt/_wasm_abi_generated.py"


class WasmAbiManifestError(ValueError):
    pass


def load_manifest(path: Path = MANIFEST) -> dict:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    imports = data.get("import")
    if not isinstance(imports, list) or not imports:
        raise WasmAbiManifestError("manifest must define at least one [[import]]")
    seen_imports: set[str] = set()
    for idx, entry in enumerate(imports):
        if not isinstance(entry, dict):
            raise WasmAbiManifestError(f"import entry {idx} must be a table")
        name = entry.get("name")
        type_idx = entry.get("type")
        if not isinstance(name, str) or not name:
            raise WasmAbiManifestError(f"import entry {idx} has invalid name")
        if name in seen_imports:
            raise WasmAbiManifestError(f"duplicate import name {name!r}")
        seen_imports.add(name)
        if not isinstance(type_idx, int) or type_idx < 0:
            raise WasmAbiManifestError(f"import {name!r} has invalid type index")

    prefixes = data.get("pure_skip_prefix", [])
    if not isinstance(prefixes, list):
        raise WasmAbiManifestError("pure_skip_prefix must be a list of tables")
    seen_prefixes: set[str] = set()
    for idx, entry in enumerate(prefixes):
        if not isinstance(entry, dict):
            raise WasmAbiManifestError(f"pure_skip_prefix entry {idx} must be a table")
        prefix = entry.get("prefix")
        if not isinstance(prefix, str) or not prefix:
            raise WasmAbiManifestError(f"pure_skip_prefix entry {idx} has invalid prefix")
        if prefix in seen_prefixes:
            raise WasmAbiManifestError(f"duplicate Pure-profile skip prefix {prefix!r}")
        seen_prefixes.add(prefix)
    return data


def _header(comment: str) -> str:
    return (
        f"{comment} @generated by tools/gen_wasm_abi.py from\n"
        f"{comment} runtime/molt-backend/src/wasm_abi_manifest.toml\n"
        f"{comment} DO NOT EDIT BY HAND.\n\n"
    )


def render_rs(data: dict) -> str:
    lines: list[str] = [_header("//")]
    lines.append("pub(crate) const IMPORT_REGISTRY: &[(&str, u32)] = &[\n")
    for entry in data["import"]:
        lines.append(f'    ("{entry["name"]}", {entry["type"]}),\n')
    lines.append("];\n\n")
    lines.append("pub(crate) const PURE_PROFILE_SKIP_PREFIXES: &[&str] = &[\n")
    for entry in data.get("pure_skip_prefix", []):
        lines.append(f'    "{entry["prefix"]}",\n')
    lines.append("];\n\n")
    lines.extend(
        [
            "#[inline]\n",
            "pub(crate) fn pure_profile_skips_import(name: &str) -> bool {\n",
            "    PURE_PROFILE_SKIP_PREFIXES\n",
            "        .iter()\n",
            "        .any(|prefix| name.starts_with(prefix))\n",
            "}\n",
        ]
    )
    return "".join(lines)


def render_py(data: dict) -> str:
    lines: list[str] = [_header("#")]
    lines.append("WASM_IMPORT_REGISTRY: tuple[str, ...] = (\n")
    for entry in data["import"]:
        lines.append(f'    "{entry["name"]}",\n')
    lines.append(")\n\n")
    lines.append("PURE_PROFILE_SKIP_PREFIXES: tuple[str, ...] = (\n")
    for entry in data.get("pure_skip_prefix", []):
        lines.append(f'    "{entry["prefix"]}",\n')
    lines.append(")\n\n")
    lines.extend(
        [
            "def pure_profile_skips_import(name: str) -> bool:\n",
            "    return any(name.startswith(prefix) for prefix in PURE_PROFILE_SKIP_PREFIXES)\n",
        ]
    )
    return "".join(lines)


def _check(path: Path, rendered: str) -> bool:
    if not path.exists():
        print(f"MISSING generated file: {path}", file=sys.stderr)
        return False
    if path.read_text(encoding="utf-8") != rendered:
        print(
            f"STALE generated file: {path}\n"
            "  run `python tools/gen_wasm_abi.py` to regenerate.",
            file=sys.stderr,
        )
        return False
    return True


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    data = load_manifest()
    rendered_rs = render_rs(data)
    rendered_py = render_py(data)
    if args.check:
        return 0 if _check(OUT_RS, rendered_rs) and _check(OUT_PY, rendered_py) else 1
    OUT_RS.write_text(rendered_rs, encoding="utf-8", newline="\n")
    OUT_PY.write_text(rendered_py, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
