"""Canonical newline and publication primitives for generated authorities."""

from __future__ import annotations

from pathlib import Path


def canonical_generated_bytes(payload: bytes) -> bytes:
    """Return the repository-canonical LF representation of generated bytes."""

    return payload.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def generated_file_matches(path: Path, expected: bytes | str) -> bool:
    """Compare generated content independently of checkout newline policy."""

    try:
        current = path.read_bytes()
    except FileNotFoundError:
        return False
    expected_bytes = expected.encode("utf-8") if isinstance(expected, str) else expected
    return canonical_generated_bytes(current) == canonical_generated_bytes(
        expected_bytes
    )


def write_generated_text(path: Path, text: str) -> None:
    """Publish generated UTF-8 text with the repository-canonical LF encoding."""

    path.parent.mkdir(parents=True, exist_ok=True)
    canonical = canonical_generated_bytes(text.encode("utf-8")).decode("utf-8")
    path.write_text(canonical, encoding="utf-8", newline="\n")
