"""Authoritative stdlib full-coverage attestation manifest.

Any stdlib module/submodule absent from this tuple is classified as
`intrinsic-partial` by `tools/check_stdlib_intrinsics.py`.

Update workflow:
1. Add module/submodule names to `STDLIB_FULLY_COVERED_MODULES` only after full
   CPython 3.12+ API/PEP parity is landed for Molt-supported semantics.
2. Add an explicit required-intrinsics tuple for every attested module in
   `STDLIB_REQUIRED_INTRINSICS_BY_MODULE` (empty tuple is allowed only when the
   module intentionally has no direct intrinsic loads).
3. Keep `TOO_DYNAMIC_EXPECTED_FAILURE_TESTS` aligned with differential tests
   that intentionally remain unsupported under vision/break-policy constraints
   (for example `exec`/`eval` heavy semantics).
"""

from __future__ import annotations


STDLIB_FULLY_COVERED_MODULES: tuple[str, ...] = (
    "__future__",
    "_abc",
    "_asyncio",
    "_bisect",
    "_codecs",
    "_collections",
    "_collections_abc",
    "_csv",
    "_json",
    "_opcode",
    "_opcode_metadata",
    "_operator",
    "_pickle",
    "_queue",
    "contextlib",
    "email.quoprimime",
    "encodings.quopri_codec",
    "functools",
    "imghdr",
    "itertools",
    "math",
    "opcode",
    "operator",
    "quopri",
    "select",
    "selectors",
    "socket",
    "struct",
    "this",
    "time",
    "types",
    "weakref",
)

# Every module listed in STDLIB_FULLY_COVERED_MODULES must have a key here.
# Value is the canonical intrinsic contract required for full coverage.
STDLIB_REQUIRED_INTRINSICS_BY_MODULE: dict[str, tuple[str, ...]] = {
    "__future__": ("molt_future_features",),
    "_abc": (
        "molt_abc_get_cache_token",
        "molt_abc_get_dump",
        "molt_abc_init",
        "molt_abc_instancecheck",
        "molt_abc_register",
        "molt_abc_reset_caches",
        "molt_abc_reset_registry",
        "molt_abc_subclasscheck",
    ),
    "_asyncio": (
        "molt_asyncio_enter_task",
        "molt_asyncio_event_loop_get",
        "molt_asyncio_event_loop_policy_get",
        "molt_asyncio_leave_task",
        "molt_asyncio_register_task",
        "molt_asyncio_running_loop_get",
        "molt_asyncio_running_loop_set",
        "molt_asyncio_task_registry_current",
        "molt_asyncio_task_registry_current_for_loop",
        "molt_asyncio_unregister_task",
    ),
    "_bisect": (
        "molt_bisect_insort_left",
        "molt_bisect_insort_right",
        "molt_bisect_left",
        "molt_bisect_right",
    ),
    "_codecs": (
        "molt_codecs_decode",
        "molt_codecs_encode",
        "molt_codecs_lookup_name",
    ),
    "_collections": (
        "molt_ordereddict_clear",
        "molt_ordereddict_contains",
        "molt_ordereddict_copy",
        "molt_ordereddict_delitem",
        "molt_ordereddict_drop",
        "molt_ordereddict_from_pairs",
        "molt_ordereddict_getitem",
        "molt_ordereddict_items",
        "molt_ordereddict_keys",
        "molt_ordereddict_len",
        "molt_ordereddict_move_to_end",
        "molt_ordereddict_new",
        "molt_ordereddict_popitem",
        "molt_ordereddict_setitem",
        "molt_ordereddict_update",
        "molt_ordereddict_values",
    ),
    "_collections_abc": (
        "molt_abc_bootstrap",
        "molt_collections_abc_runtime_types",
    ),
    "_csv": ("molt_csv_runtime_ready",),
    "_json": (
        "molt_json_encode_basestring_ascii_obj",
        "molt_json_encode_basestring_obj",
        "molt_json_parse_scalar_obj",
        "molt_json_scanstring_obj",
    ),
    "_opcode": (
        "molt_import_smoke_runtime_ready",
        "molt_opcode_get_specialization_stats",
        "molt_opcode_stack_effect",
    ),
    "_opcode_metadata": ("molt_opcode_metadata_payload_314_json",),
    "_operator": (
        "molt_operator_abs",
        "molt_operator_add",
        "molt_operator_and",
        "molt_operator_attrgetter_type",
        "molt_operator_concat",
        "molt_operator_contains",
        "molt_operator_countof",
        "molt_operator_delitem",
        "molt_operator_eq",
        "molt_operator_floordiv",
        "molt_operator_ge",
        "molt_operator_getitem",
        "molt_operator_gt",
        "molt_operator_iadd",
        "molt_operator_iand",
        "molt_operator_iconcat",
        "molt_operator_ifloordiv",
        "molt_operator_ilshift",
        "molt_operator_imatmul",
        "molt_operator_imod",
        "molt_operator_imul",
        "molt_operator_index",
        "molt_operator_invert",
        "molt_operator_ior",
        "molt_operator_ipow",
        "molt_operator_irshift",
        "molt_operator_is",
        "molt_operator_is_not",
        "molt_operator_isub",
        "molt_operator_itemgetter_type",
        "molt_operator_itruediv",
        "molt_operator_ixor",
        "molt_operator_le",
        "molt_operator_length_hint",
        "molt_operator_lshift",
        "molt_operator_lt",
        "molt_operator_matmul",
        "molt_operator_methodcaller_type",
        "molt_operator_mod",
        "molt_operator_mul",
        "molt_operator_ne",
        "molt_operator_neg",
        "molt_operator_not",
        "molt_operator_or",
        "molt_operator_pos",
        "molt_operator_pow",
        "molt_operator_rshift",
        "molt_operator_setitem",
        "molt_operator_sub",
        "molt_operator_truediv",
        "molt_operator_truth",
        "molt_operator_xor",
    ),
    "_pickle": (
        "molt_pickle_dumps_core",
        "molt_pickle_loads_core",
    ),
    "_queue": (
        "molt_queue_drop",
        "molt_queue_empty",
        "molt_queue_get",
        "molt_queue_new",
        "molt_queue_put",
        "molt_queue_qsize",
    ),
    "contextlib": (
        "molt_context_null",
        "molt_contextlib_aclosing_enter",
        "molt_contextlib_aclosing_exit",
        "molt_contextlib_abstract_aenter",
        "molt_contextlib_abstract_async_subclasshook",
        "molt_contextlib_abstract_enter",
        "molt_contextlib_abstract_subclasshook",
        "molt_contextlib_async_exitstack_enter_context",
        "molt_contextlib_async_exitstack_exit",
        "molt_contextlib_async_exitstack_push_callback",
        "molt_contextlib_async_exitstack_push_exit",
        "molt_contextlib_asyncgen_cm_aenter",
        "molt_contextlib_asyncgen_cm_aexit",
        "molt_contextlib_asyncgen_cm_drop",
        "molt_contextlib_asyncgen_cm_new",
        "molt_contextlib_chdir_enter",
        "molt_contextlib_chdir_exit",
        "molt_contextlib_closing",
        "molt_contextlib_contextdecorator_call",
        "molt_contextlib_exitstack_drop",
        "molt_contextlib_exitstack_enter_context",
        "molt_contextlib_exitstack_exit",
        "molt_contextlib_exitstack_new",
        "molt_contextlib_exitstack_pop",
        "molt_contextlib_exitstack_pop_all",
        "molt_contextlib_exitstack_push",
        "molt_contextlib_exitstack_push_callback",
        "molt_contextlib_generator_enter",
        "molt_contextlib_generator_exit",
        "molt_contextlib_redirect_enter",
        "molt_contextlib_redirect_exit",
        "molt_contextlib_suppress_match",
    ),
    "email.quoprimime": (
        "molt_email_quoprimime_body_check",
        "molt_email_quoprimime_body_encode",
        "molt_email_quoprimime_body_length",
        "molt_email_quoprimime_decode",
        "molt_email_quoprimime_header_check",
        "molt_email_quoprimime_header_decode",
        "molt_email_quoprimime_header_encode",
        "molt_email_quoprimime_header_length",
        "molt_email_quoprimime_quote",
        "molt_email_quoprimime_unquote",
    ),
    "encodings.quopri_codec": (
        "molt_quopri_decode",
        "molt_quopri_encode",
    ),
    "functools": (
        "molt_functools_cmp_to_key",
        "molt_functools_kwd_mark",
        "molt_functools_lru_cache",
        "molt_functools_partial",
        "molt_functools_reduce",
        "molt_functools_singledispatch_call",
        "molt_functools_singledispatch_dispatch",
        "molt_functools_singledispatch_drop",
        "molt_functools_singledispatch_new",
        "molt_functools_singledispatch_register",
        "molt_functools_singledispatch_registry",
        "molt_functools_total_ordering",
        "molt_functools_update_wrapper",
        "molt_functools_wraps",
    ),
    "imghdr": (
        "molt_imghdr_test",
        "molt_imghdr_what",
    ),
    "itertools": (
        "molt_itertools_accumulate",
        "molt_itertools_batched",
        "molt_itertools_chain",
        "molt_itertools_chain_from_iterable",
        "molt_itertools_combinations",
        "molt_itertools_combinations_with_replacement",
        "molt_itertools_compress",
        "molt_itertools_count",
        "molt_itertools_cycle",
        "molt_itertools_dropwhile",
        "molt_itertools_filterfalse",
        "molt_itertools_groupby",
        "molt_itertools_islice",
        "molt_itertools_kwd_mark",
        "molt_itertools_pairwise",
        "molt_itertools_permutations",
        "molt_itertools_product",
        "molt_itertools_repeat",
        "molt_itertools_starmap",
        "molt_itertools_takewhile",
        "molt_itertools_tee",
        "molt_itertools_zip_longest",
    ),
    "math": (
        "molt_math_acos",
        "molt_math_acosh",
        "molt_math_asin",
        "molt_math_asinh",
        "molt_math_atan",
        "molt_math_atan2",
        "molt_math_atanh",
        "molt_math_ceil",
        "molt_math_comb",
        "molt_math_copysign",
        "molt_math_cos",
        "molt_math_cosh",
        "molt_math_degrees",
        "molt_math_dist",
        "molt_math_erf",
        "molt_math_erfc",
        "molt_math_exp",
        "molt_math_expm1",
        "molt_math_fabs",
        "molt_math_factorial",
        "molt_math_floor",
        "molt_math_fma",
        "molt_math_fmod",
        "molt_math_frexp",
        "molt_math_fsum",
        "molt_math_gamma",
        "molt_math_gcd",
        "molt_math_hypot",
        "molt_math_isclose",
        "molt_math_isfinite",
        "molt_math_isinf",
        "molt_math_isnan",
        "molt_math_isqrt",
        "molt_math_lcm",
        "molt_math_ldexp",
        "molt_math_lgamma",
        "molt_math_log",
        "molt_math_log10",
        "molt_math_log1p",
        "molt_math_log2",
        "molt_math_modf",
        "molt_math_nextafter",
        "molt_math_perm",
        "molt_math_prod",
        "molt_math_radians",
        "molt_math_remainder",
        "molt_math_sin",
        "molt_math_sinh",
        "molt_math_sqrt",
        "molt_math_tan",
        "molt_math_tanh",
        "molt_math_trunc",
        "molt_math_ulp",
    ),
    "opcode": (
        "molt_import_smoke_runtime_ready",
        "molt_opcode_payload_312_json",
    ),
    "operator": ("molt_operator_truth",),
    "quopri": (
        "molt_quopri_decode",
        "molt_quopri_encode",
        "molt_quopri_ishex",
        "molt_quopri_needs_quoting",
        "molt_quopri_quote",
        "molt_quopri_unhex",
    ),
    "select": (
        "molt_select_constants",
        "molt_select_devpoll",
        "molt_select_epoll",
        "molt_select_fileno",
        "molt_select_poll",
        "molt_select_select",
        "molt_select_selector_close",
        "molt_select_selector_drop",
        "molt_select_selector_events",
        "molt_select_selector_fileno",
        "molt_select_selector_len",
        "molt_select_selector_modify",
        "molt_select_selector_modify_obj",
        "molt_select_selector_new",
        "molt_select_selector_poll",
        "molt_select_selector_register",
        "molt_select_selector_register_fd",
        "molt_select_selector_unregister",
        "molt_select_selector_unregister_obj",
    ),
    "selectors": (
        "molt_select_backend_available",
        "molt_select_default_selector_kind",
        "molt_select_fileno",
        "molt_select_selector_close",
        "molt_select_selector_drop",
        "molt_select_selector_fileno",
        "molt_select_selector_modify",
        "molt_select_selector_new",
        "molt_select_selector_poll",
        "molt_select_selector_register",
        "molt_select_selector_unregister",
    ),
    "socket": (
        "molt_socket_accept",
        "molt_socket_bind",
        "molt_socket_clone",
        "molt_socket_close",
        "molt_socket_cmsg_len",
        "molt_socket_cmsg_space",
        "molt_socket_connect",
        "molt_socket_connect_ex",
        "molt_socket_constants",
        "molt_socket_detach",
        "molt_socket_drop",
        "molt_socket_fileno",
        "molt_socket_getaddrinfo",
        "molt_socket_getblocking",
        "molt_socket_getfqdn",
        "molt_socket_gethostbyaddr",
        "molt_socket_gethostbyname",
        "molt_socket_gethostbyname_ex",
        "molt_socket_gethostname",
        "molt_socket_getnameinfo",
        "molt_socket_getpeername",
        "molt_socket_getprotobyname",
        "molt_socket_getservbyname",
        "molt_socket_getservbyport",
        "molt_socket_getsockname",
        "molt_socket_getsockopt",
        "molt_socket_gettimeout",
        "molt_socket_has_dualstack_ipv6",
        "molt_socket_has_ipv6",
        "molt_socket_htonl",
        "molt_socket_htons",
        "molt_socket_if_indextoname",
        "molt_socket_if_nameindex",
        "molt_socket_if_nametoindex",
        "molt_socket_inet_ntop",
        "molt_socket_inet_pton",
        "molt_socket_listen",
        "molt_socket_new",
        "molt_socket_ntohs",
        "molt_socket_ntohl",
        "molt_socket_reader_drop",
        "molt_socket_reader_new",
        "molt_socket_reader_read",
        "molt_socket_reader_readline",
        "molt_socket_reader_readline_limit",
        "molt_socket_recv",
        "molt_socket_recv_fds",
        "molt_socket_recv_into",
        "molt_socket_recvfrom",
        "molt_socket_recvfrom_into",
        "molt_socket_recvmsg",
        "molt_socket_recvmsg_into",
        "molt_socket_send",
        "molt_socket_send_fds",
        "molt_socket_sendall",
        "molt_socket_sendfile",
        "molt_socket_sendmsg",
        "molt_socket_sendmsg_afalg",
        "molt_socket_sendto",
        "molt_socket_setblocking",
        "molt_socket_sethostname",
        "molt_socket_setsockopt",
        "molt_socket_settimeout",
        "molt_socket_shutdown",
    ),
    "struct": (
        "molt_struct_calcsize",
        "molt_struct_iter_unpack",
        "molt_struct_pack",
        "molt_struct_pack_into",
        "molt_struct_unpack",
        "molt_struct_unpack_from",
    ),
    "this": ("molt_this_payload",),
    "time": (
        "molt_async_sleep",
        "molt_block_on",
        "molt_time_altzone",
        "molt_time_asctime",
        "molt_time_daylight",
        "molt_time_get_clock_info",
        "molt_time_gmtime",
        "molt_time_localtime",
        "molt_time_mktime",
        "molt_time_monotonic",
        "molt_time_monotonic_ns",
        "molt_time_perf_counter",
        "molt_time_perf_counter_ns",
        "molt_time_process_time",
        "molt_time_process_time_ns",
        "molt_time_strftime",
        "molt_time_time",
        "molt_time_time_ns",
        "molt_time_timegm",
        "molt_time_timezone",
        "molt_time_tzname",
    ),
    "types": ("molt_types_bootstrap",),
    "weakref": (
        "molt_weakref_callback",
        "molt_weakref_collect",
        "molt_weakref_count",
        "molt_weakref_drop",
        "molt_weakref_finalize_track",
        "molt_weakref_finalize_untrack",
        "molt_weakref_find_nocallback",
        "molt_weakref_get",
        "molt_weakref_peek",
        "molt_weakref_refs",
        "molt_weakref_register",
        "molt_weakkeydict_clear",
        "molt_weakkeydict_contains",
        "molt_weakkeydict_del",
        "molt_weakkeydict_get",
        "molt_weakkeydict_items",
        "molt_weakkeydict_keyrefs",
        "molt_weakkeydict_popitem",
        "molt_weakkeydict_set",
        "molt_weakset_add",
        "molt_weakset_clear",
        "molt_weakset_contains",
        "molt_weakset_discard",
        "molt_weakset_items",
        "molt_weakset_len",
        "molt_weakset_pop",
        "molt_weakset_remove",
        "molt_weakvaluedict_clear",
        "molt_weakvaluedict_contains",
        "molt_weakvaluedict_del",
        "molt_weakvaluedict_get",
        "molt_weakvaluedict_items",
        "molt_weakvaluedict_len",
        "molt_weakvaluedict_popitem",
        "molt_weakvaluedict_set",
        "molt_weakvaluedict_valuerefs",
    ),
}

# Differential tests that are intentionally expected to fail in Molt because
# they rely on "too much dynamism" outside current supported semantics.
TOO_DYNAMIC_POLICY_DOC_REFERENCES: tuple[str, ...] = (
    "docs/spec/areas/core/0000-vision.md",
    "docs/spec/areas/core/0800_WHAT_MOLT_IS_WILLING_TO_BREAK.md",
    "docs/spec/areas/testing/0007-testing.md",
    "docs/spec/areas/compat/contracts/compatibility_fallback_contract.md",
    "docs/spec/areas/compat/contracts/dynamic_execution_policy_contract.md",
)

# Differential tests aligned with the documented policy references above.
# Keep this list focused on behavior intentionally excluded from supported
# semantics, not temporary lowering gaps.
TOO_DYNAMIC_EXPECTED_FAILURE_TESTS: tuple[str, ...] = (
    "tests/differential/basic/builtins_symbol_eval_822bc13e.py",
    "tests/differential/basic/builtins_symbol_exec_be625627.py",
    "tests/differential/basic/exec_eval_compile_capability_errors.py",
    "tests/differential/basic/exec_class_body_locals.py",
    "tests/differential/basic/exec_class_scope.py",
    "tests/differential/basic/exec_in_function_locals.py",
    "tests/differential/basic/exec_locals_mapping.py",
    "tests/differential/basic/exec_locals_scope.py",
    "tests/differential/basic/exec_locals_shadowing.py",
    "tests/differential/basic/eval_locals_scope.py",
)
