#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib import error, request


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV_FILE = REPO_ROOT / "ops" / "linear" / "runtime" / "symphony.env"
DEFAULT_EXT_ROOT = Path("E:/APDataStore/Molt")
DEFAULT_SYMPHONY_PARENT = Path("E:/APDataStore/symphony")
DEFAULT_WORKFLOW = REPO_ROOT / "WORKFLOW.md"
DEFAULT_PORT = 8089
LINEAR_MCP_URL = "https://mcp.linear.app/mcp"
DEFAULT_FLEET_MCP_URL = "http://192.168.1.170:8850/sse"
DEFAULT_FLEET_MCP_NAME = "vertigo-fleet"

REQUIRED_ENV_KEYS = (
    "LINEAR_API_KEY",
    "MOLT_LINEAR_PROJECT_SLUG",
    "MOLT_EXT_ROOT",
    "CARGO_TARGET_DIR",
    "MOLT_SYMPHONY_PARENT_ROOT",
    "MOLT_SYMPHONY_STORE_ROOT",
)


@dataclass(slots=True)
class CheckResult:
    name: str
    ok: bool
    detail: str
    fix: str | None = None

    def to_dict(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "name": self.name,
            "ok": self.ok,
            "detail": self.detail,
        }
        if self.fix:
            payload["fix"] = self.fix
        return payload


def _utc_now() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _run(
    args: list[str],
    *,
    cwd: Path | None = None,
    timeout: int = 600,
    check: bool = False,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        args,
        cwd=str(cwd or REPO_ROOT),
        check=False,
        capture_output=True,
        text=True,
        timeout=timeout,
        env=env,
    )
    if check and proc.returncode != 0:
        cmd = " ".join(shlex.quote(part) for part in args)
        raise RuntimeError(
            f"command_failed rc={proc.returncode}: {cmd}\nstdout:\n{proc.stdout}\n"
            f"stderr:\n{proc.stderr}"
        )
    return proc


def _which(name: str) -> str | None:
    resolved = shutil.which(name)
    return str(resolved) if resolved else None


def _parse_env_file(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def _render_env_value(value: str) -> str:
    if not value:
        return ""
    if any(ch.isspace() for ch in value):
        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _write_env_file(path: Path, env: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Auto-generated by tools/symphony_windows_admin.py"]
    for key in sorted(env):
        lines.append(f"{key}={_render_env_value(env[key])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _to_posix(path: Path) -> str:
    return path.as_posix()


def _coerce_ext_root(value: str | None) -> Path:
    raw = (value or "").strip()
    if raw:
        return Path(raw).expanduser()
    existing = (os.environ.get("MOLT_EXT_ROOT") or "").strip()
    if existing:
        return Path(existing).expanduser()
    return DEFAULT_EXT_ROOT


def _coerce_symphony_parent(value: str | None) -> Path:
    raw = (value or "").strip()
    if raw:
        return Path(raw).expanduser()
    existing = (os.environ.get("MOLT_SYMPHONY_PARENT_ROOT") or "").strip()
    if existing:
        return Path(existing).expanduser()
    return DEFAULT_SYMPHONY_PARENT


def _check_py_version(version: str) -> CheckResult:
    py = _which("py")
    if py is None:
        return CheckResult(
            name=f"python_{version}",
            ok=False,
            detail="py launcher missing",
            fix=f"uv python install {version}",
        )
    proc = _run(["py", f"-{version}", "--version"], timeout=30)
    ok = proc.returncode == 0
    detail = (proc.stdout or proc.stderr).strip() or "no version output"
    return CheckResult(
        name=f"python_{version}",
        ok=ok,
        detail=detail,
        fix=f"uv python install {version}" if not ok else None,
    )


def _check_cmd(name: str, *, version_args: list[str] | None = None) -> CheckResult:
    resolved = _which(name)
    if not resolved:
        return CheckResult(
            name=f"cmd_{name}",
            ok=False,
            detail="not found on PATH",
            fix=f"install {name}",
        )
    detail = resolved
    if version_args:
        proc = _run([name, *version_args], timeout=45)
        if proc.returncode == 0:
            detail = (proc.stdout or proc.stderr).strip().splitlines()[0]
        else:
            detail = (
                f"path={resolved}; version check failed rc={proc.returncode}; "
                f"{(proc.stderr or proc.stdout).strip()}"
            )
    return CheckResult(name=f"cmd_{name}", ok=True, detail=detail)


def _check_repo_sync() -> list[CheckResult]:
    results: list[CheckResult] = []
    if not (REPO_ROOT / ".git").exists():
        results.append(
            CheckResult(
                name="repo_root",
                ok=False,
                detail=f"missing git repo: {REPO_ROOT}",
                fix="run from a checked-out Molt repository",
            )
        )
        return results
    fetch = _run(["git", "fetch", "origin", "--prune"], timeout=120)
    if fetch.returncode != 0:
        results.append(
            CheckResult(
                name="git_fetch",
                ok=False,
                detail=(fetch.stderr or fetch.stdout).strip() or "git fetch failed",
                fix="check network + git credentials",
            )
        )
        return results
    head = _run(["git", "rev-parse", "HEAD"], timeout=30)
    main = _run(["git", "rev-parse", "origin/main"], timeout=30)
    ahead = _run(["git", "rev-list", "--left-right", "--count", "HEAD...origin/main"])
    status = _run(["git", "status", "--porcelain"], timeout=30)
    head_sha = head.stdout.strip()
    main_sha = main.stdout.strip()
    ahead_text = ahead.stdout.strip()
    clean = not status.stdout.strip()
    in_sync = bool(head_sha and main_sha and head_sha == main_sha)
    results.append(
        CheckResult(
            name="repo_commit_sync",
            ok=in_sync,
            detail=f"head={head_sha} origin/main={main_sha} ahead_behind={ahead_text}",
            fix="git pull --ff-only origin main" if not in_sync else None,
        )
    )
    results.append(
        CheckResult(
            name="repo_clean",
            ok=clean,
            detail="working tree clean" if clean else "working tree has local edits",
            fix="stash/commit local changes before long-running automation"
            if not clean
            else None,
        )
    )
    return results


def _check_mcp_status() -> list[CheckResult]:
    list_proc = _run(["codex", "--yolo", "mcp", "list"], timeout=60)
    if list_proc.returncode != 0:
        detail = (
            list_proc.stderr or list_proc.stdout
        ).strip() or "codex mcp list failed"
        return [
            CheckResult(
                name="codex_mcp_list",
                ok=False,
                detail=detail,
                fix="verify codex-cli installation and auth",
            )
        ]
    text = (list_proc.stdout or "").lower()
    has_linear = "linear" in text
    has_fleet = "vertigo-fleet" in text or "fleet" in text
    linear_logged_in = "linear" in text and "not logged in" not in text
    results = [
        CheckResult(
            name="codex_mcp_linear_present",
            ok=has_linear,
            detail="linear MCP configured" if has_linear else "linear MCP missing",
            fix=f"codex --yolo mcp add linear {LINEAR_MCP_URL}"
            if not has_linear
            else None,
        ),
        CheckResult(
            name="codex_mcp_fleet_present",
            ok=has_fleet,
            detail="fleet MCP configured" if has_fleet else "fleet MCP missing",
            fix=(
                f"codex --yolo mcp add {DEFAULT_FLEET_MCP_NAME} {DEFAULT_FLEET_MCP_URL}"
                if not has_fleet
                else None
            ),
        ),
        CheckResult(
            name="codex_mcp_linear_auth",
            ok=linear_logged_in,
            detail=(
                "linear MCP authenticated"
                if linear_logged_in
                else "linear MCP not logged in for this shell profile"
            ),
            fix="codex --yolo mcp login linear" if not linear_logged_in else None,
        ),
    ]
    return results


def _check_env_file(env_file: Path) -> list[CheckResult]:
    if not env_file.exists():
        return [
            CheckResult(
                name="symphony_env_file",
                ok=False,
                detail=f"missing env file: {env_file}",
                fix="run repair command to generate env file",
            )
        ]
    env_map = _parse_env_file(env_file)
    missing = [key for key in REQUIRED_ENV_KEYS if not env_map.get(key, "").strip()]
    if missing:
        return [
            CheckResult(
                name="symphony_env_required_keys",
                ok=False,
                detail=f"missing required env keys: {', '.join(missing)}",
                fix=f"edit {env_file} and fill required values",
            )
        ]
    return [
        CheckResult(
            name="symphony_env_required_keys",
            ok=True,
            detail=f"required keys present ({len(REQUIRED_ENV_KEYS)})",
        )
    ]


def _collect_doctor_report(env_file: Path) -> dict[str, Any]:
    checks: list[CheckResult] = []
    checks.append(
        CheckResult(
            name="platform_windows",
            ok=sys.platform.startswith("win"),
            detail=f"platform={sys.platform}",
            fix="run this command on BAT00 (Windows host)",
        )
    )
    checks.extend(
        [
            _check_cmd("git", version_args=["--version"]),
            _check_cmd("uv", version_args=["--version"]),
            _check_cmd("cargo", version_args=["--version"]),
            _check_cmd("rustup", version_args=["--version"]),
            _check_cmd("codex", version_args=["--yolo", "--version"]),
            _check_cmd("winget", version_args=["--version"]),
            _check_cmd("clang", version_args=["--version"]),
            _check_cmd("wasm-ld", version_args=["--version"]),
            _check_cmd("wasm-tools", version_args=["--version"]),
            _check_cmd("wasmtime", version_args=["--version"]),
            _check_py_version("3.12"),
            _check_py_version("3.13"),
            _check_py_version("3.14"),
        ]
    )
    checks.extend(_check_repo_sync())
    checks.extend(_check_env_file(env_file))
    checks.extend(_check_mcp_status())

    required_files = (
        REPO_ROOT / "WORKFLOW.md",
        REPO_ROOT / "tools" / "symphony_run.py",
        REPO_ROOT / ".mcp.json",
    )
    for file_path in required_files:
        checks.append(
            CheckResult(
                name=f"file_{file_path.name}",
                ok=file_path.exists(),
                detail=str(file_path),
                fix=f"restore {file_path.name}" if not file_path.exists() else None,
            )
        )

    failed = [item for item in checks if not item.ok]
    return {
        "generated_at": _utc_now(),
        "repo_root": str(REPO_ROOT),
        "env_file": str(env_file),
        "ok": not failed,
        "failed_count": len(failed),
        "checks": [item.to_dict() for item in checks],
    }


def _print_report(report: dict[str, Any], *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(report, indent=2, sort_keys=True))
        return
    summary = "PASS" if report.get("ok") else "FAIL"
    print(f"symphony_windows_admin doctor: {summary}")
    print(f"repo_root: {report.get('repo_root')}")
    print(f"env_file: {report.get('env_file')}")
    print(f"failed_count: {report.get('failed_count')}")
    for item in report.get("checks", []):
        status = "OK" if item.get("ok") else "FAIL"
        detail = item.get("detail", "")
        print(f"- [{status}] {item.get('name')}: {detail}")
        fix = item.get("fix")
        if fix and not item.get("ok"):
            print(f"  fix: {fix}")


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _build_env_values(
    existing: dict[str, str],
    *,
    ext_root: Path,
    symphony_parent: Path,
    project_key: str,
    linear_project_slug: str | None,
    linear_api_key: str | None,
) -> dict[str, str]:
    env = dict(existing)
    ext = _to_posix(ext_root)
    parent = _to_posix(symphony_parent)
    store = _to_posix(symphony_parent / project_key)
    state = f"{store}/state"
    logs = f"{store}/logs"
    env.setdefault("MOLT_SOURCE_REPO_URL", "git@github.com:adpena/molt.git")
    env.setdefault("MOLT_SYMPHONY_SYNC_REMOTE", "origin")
    env.setdefault("MOLT_SYMPHONY_SYNC_BRANCH", "main")
    env.setdefault("MOLT_SYMPHONY_AUTOMERGE_ALLOWED_AUTHORS", "adpena,symphony")

    env["MOLT_EXT_ROOT"] = ext
    env["CARGO_TARGET_DIR"] = f"{ext}/cargo-target"
    env["MOLT_DIFF_CARGO_TARGET_DIR"] = f"{ext}/cargo-target"
    env["MOLT_CACHE"] = f"{ext}/molt_cache"
    env["MOLT_DIFF_ROOT"] = f"{ext}/diff"
    env["MOLT_DIFF_TMPDIR"] = f"{ext}/tmp"
    env["MOLT_APALACHE_WORK_DIR"] = f"{ext}/tmp/apalache"
    env["UV_CACHE_DIR"] = f"{ext}/uv-cache"
    env["TMPDIR"] = f"{ext}/tmp"

    env["MOLT_SYMPHONY_PARENT_ROOT"] = parent
    env["MOLT_SYMPHONY_PROJECT_KEY"] = project_key
    env["MOLT_SYMPHONY_STORE_ROOT"] = store
    env["MOLT_SYMPHONY_LOG_ROOT"] = logs
    env["MOLT_SYMPHONY_STATE_ROOT"] = state
    env["MOLT_SYMPHONY_ARTIFACT_ROOT"] = f"{store}/artifacts"
    env["MOLT_SYMPHONY_WORKSPACE_ROOT"] = f"{store}/sessions/workspaces"
    env["MOLT_SYMPHONY_DURABLE_ROOT"] = f"{state}/durable_memory"
    env["MOLT_SYMPHONY_DLQ_EVENTS_FILE"] = f"{state}/dlq/events.jsonl"
    env["MOLT_SYMPHONY_TASTE_MEMORY_EVENTS_FILE"] = f"{state}/taste_memory/events.jsonl"
    env["MOLT_SYMPHONY_TASTE_MEMORY_DISTILLATIONS_DIR"] = (
        f"{state}/taste_memory/distillations"
    )
    env["MOLT_SYMPHONY_TOOL_PROMOTION_EVENTS_FILE"] = (
        f"{state}/tool_promotion/events.jsonl"
    )
    env["MOLT_SYMPHONY_TOOL_PROMOTION_DISTILLATIONS_DIR"] = (
        f"{state}/tool_promotion/distillations"
    )
    env["MOLT_SYMPHONY_API_TOKEN_FILE"] = f"{state}/secrets/dashboard_api_token"
    env["MOLT_SYMPHONY_SECURITY_EVENTS_FILE"] = f"{logs}/security/events.jsonl"

    env.setdefault("MOLT_SYMPHONY_BIND_HOST", "127.0.0.1")
    env.setdefault("MOLT_SYMPHONY_SECURITY_PROFILE", "local")
    env.setdefault("MOLT_SYMPHONY_ALLOW_NONLOCAL_BIND", "0")
    env.setdefault("MOLT_SYMPHONY_ALLOW_QUERY_TOKEN", "1")
    env.setdefault("MOLT_SYMPHONY_DISABLE_DASHBOARD_UI", "0")
    env.setdefault("MOLT_SYMPHONY_ENFORCE_ORIGIN", "1")
    env.setdefault("MOLT_SYMPHONY_REQUIRE_CSRF_HEADER", "1")
    env.setdefault("MOLT_QUINT_NODE_FALLBACK", "npx -y node@22")
    env.setdefault("MOLT_SYMPHONY_MAX_HTTP_CONNECTIONS", "96")
    env.setdefault("MOLT_SYMPHONY_MAX_STREAM_CLIENTS", "16")
    env.setdefault("MOLT_SYMPHONY_STREAM_MAX_AGE_SECONDS", "300")
    env.setdefault("MOLT_SYMPHONY_HTTP_RATE_LIMIT_MAX_REQUESTS", "240")
    env.setdefault("MOLT_SYMPHONY_HTTP_RATE_LIMIT_WINDOW_SECONDS", "60")
    env.setdefault("MOLT_SYMPHONY_EVENT_QUEUE_MAX", "8192")
    env.setdefault("MOLT_SYMPHONY_EVENT_QUEUE_DROP_LOG_INTERVAL", "250")
    env.setdefault("MOLT_SYMPHONY_TOOL_STATE_DETAIL", "compact")

    if linear_project_slug is not None:
        env["MOLT_LINEAR_PROJECT_SLUG"] = linear_project_slug
    else:
        env.setdefault("MOLT_LINEAR_PROJECT_SLUG", "")
    if linear_api_key is not None:
        env["LINEAR_API_KEY"] = linear_api_key
    else:
        env.setdefault("LINEAR_API_KEY", "")
    return env


def _run_install_step(
    steps: list[dict[str, Any]],
    *,
    name: str,
    command: list[str],
    cwd: Path | None = None,
    timeout: int = 1800,
) -> None:
    proc = _run(command, cwd=cwd, timeout=timeout)
    steps.append(
        {
            "name": name,
            "command": command,
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout_tail": (proc.stdout or "").strip()[-1200:],
            "stderr_tail": (proc.stderr or "").strip()[-1200:],
        }
    )


def _ensure_mcp_entry(name: str, url: str, steps: list[dict[str, Any]]) -> None:
    listing = _run(["codex", "--yolo", "mcp", "list"], timeout=90)
    if listing.returncode != 0:
        steps.append(
            {
                "name": f"mcp_check_{name}",
                "ok": False,
                "detail": (listing.stderr or listing.stdout).strip()
                or "codex mcp list failed",
            }
        )
        return
    text = (listing.stdout or "").lower()
    if name.lower() in text:
        steps.append(
            {"name": f"mcp_check_{name}", "ok": True, "detail": "already configured"}
        )
        return
    add = _run(["codex", "--yolo", "mcp", "add", name, url], timeout=120)
    steps.append(
        {
            "name": f"mcp_add_{name}",
            "ok": add.returncode == 0,
            "returncode": add.returncode,
            "stdout_tail": (add.stdout or "").strip()[-1200:],
            "stderr_tail": (add.stderr or "").strip()[-1200:],
        }
    )


def _tasklist_running(pid: int) -> bool:
    proc = _run(
        ["tasklist", "/FI", f"PID eq {pid}", "/FO", "CSV", "/NH"],
        timeout=20,
    )
    if proc.returncode != 0:
        return False
    row = (proc.stdout or "").strip().lower()
    if not row:
        return False
    return "no tasks are running" not in row


def _runtime_env(env_file: Path) -> dict[str, str]:
    loaded = _parse_env_file(env_file)
    merged = dict(os.environ)
    merged.update({k: v for k, v in loaded.items() if v is not None})
    return merged


def _path_from_env(runtime_env: dict[str, str], key: str, default: Path) -> Path:
    value = str(runtime_env.get(key) or "").strip()
    return Path(value) if value else default


def _state_root(runtime_env: dict[str, str]) -> Path:
    store = _path_from_env(
        runtime_env,
        "MOLT_SYMPHONY_STORE_ROOT",
        _coerce_symphony_parent(None)
        / str(runtime_env.get("MOLT_SYMPHONY_PROJECT_KEY") or "molt"),
    )
    return _path_from_env(runtime_env, "MOLT_SYMPHONY_STATE_ROOT", store / "state")


def _log_root(runtime_env: dict[str, str]) -> Path:
    store = _path_from_env(
        runtime_env,
        "MOLT_SYMPHONY_STORE_ROOT",
        _coerce_symphony_parent(None)
        / str(runtime_env.get("MOLT_SYMPHONY_PROJECT_KEY") or "molt"),
    )
    return _path_from_env(runtime_env, "MOLT_SYMPHONY_LOG_ROOT", store / "logs")


def _pid_file(runtime_env: dict[str, str]) -> Path:
    return _state_root(runtime_env) / "daemon" / "symphony.pid.json"


def _read_pid_payload(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _read_api_token(runtime_env: dict[str, str]) -> str | None:
    direct = str(runtime_env.get("MOLT_SYMPHONY_API_TOKEN") or "").strip()
    if direct:
        return direct
    token_file = str(runtime_env.get("MOLT_SYMPHONY_API_TOKEN_FILE") or "").strip()
    if not token_file:
        return None
    path = Path(token_file)
    if not path.exists():
        return None
    token = path.read_text(encoding="utf-8").strip()  # secret-guard: allow
    return token or None


def _http_json(
    *,
    method: str,
    url: str,
    payload: dict[str, Any] | None = None,
    token: str | None = None,
    timeout: int = 15,
) -> dict[str, Any]:
    headers = {"Accept": "application/json"}
    body: bytes | None = None
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
        headers["X-Symphony-CSRF"] = "1"
    if token:
        headers["X-Symphony-Token"] = token
    req = request.Request(url, method=method, data=body, headers=headers)
    try:
        with request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
            parsed = json.loads(raw) if raw.strip() else {}
            return {"ok": True, "status": int(resp.status), "payload": parsed}
    except error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        parsed: dict[str, Any]
        try:
            parsed = json.loads(raw) if raw.strip() else {}
        except Exception:
            parsed = {"raw": raw}
        return {
            "ok": False,
            "status": int(exc.code),
            "error": str(exc),
            "payload": parsed,
        }
    except Exception as exc:
        return {"ok": False, "status": 0, "error": str(exc)}


def _summarize_state_payload(payload: dict[str, Any]) -> dict[str, Any]:
    runtime = payload.get("runtime")
    counts = payload.get("counts")
    throughput = payload.get("throughput")
    return {
        "generated_at": payload.get("generated_at"),
        "runtime": runtime if isinstance(runtime, dict) else {},
        "counts": counts if isinstance(counts, dict) else {},
        "throughput": throughput if isinstance(throughput, dict) else {},
        "operator_briefing": payload.get("operator_briefing"),
    }


def _print_json_or_human(payload: dict[str, Any], *, as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(json.dumps(payload, indent=2))


def cmd_doctor(args: argparse.Namespace) -> int:
    env_file = Path(args.env_file).expanduser().resolve()
    report = _collect_doctor_report(env_file)
    _print_report(report, as_json=bool(args.json))
    return 0 if report.get("ok") else 2


def cmd_repair(args: argparse.Namespace) -> int:
    if not sys.platform.startswith("win"):
        payload = {
            "ok": False,
            "error": "windows_only",
            "platform": sys.platform,
            "message": "Run repair on BAT00 (Windows).",
        }
        _print_json_or_human(payload, as_json=bool(args.json))
        return 2

    env_file = Path(args.env_file).expanduser().resolve()
    ext_root = _coerce_ext_root(args.ext_root)
    symphony_parent = _coerce_symphony_parent(args.symphony_parent_root)
    project_key = str(args.project_key or "molt").strip() or "molt"

    existing_env = _parse_env_file(env_file)
    env_values = _build_env_values(
        existing_env,
        ext_root=ext_root,
        symphony_parent=symphony_parent,
        project_key=project_key,
        linear_project_slug=args.project_slug,
        linear_api_key=args.linear_api_key,
    )

    dirs = [
        ext_root,
        Path(env_values["CARGO_TARGET_DIR"]),
        Path(env_values["MOLT_CACHE"]),
        Path(env_values["MOLT_DIFF_ROOT"]),
        Path(env_values["MOLT_DIFF_TMPDIR"]),
        Path(env_values["UV_CACHE_DIR"]),
        Path(env_values["MOLT_APALACHE_WORK_DIR"]),
        Path(env_values["MOLT_SYMPHONY_STORE_ROOT"]),
        Path(env_values["MOLT_SYMPHONY_LOG_ROOT"]),
        Path(env_values["MOLT_SYMPHONY_STATE_ROOT"]),
        Path(env_values["MOLT_SYMPHONY_ARTIFACT_ROOT"]),
        Path(env_values["MOLT_SYMPHONY_WORKSPACE_ROOT"]),
        Path(env_values["MOLT_SYMPHONY_DURABLE_ROOT"]),
        Path(env_values["MOLT_SYMPHONY_SECURITY_EVENTS_FILE"]).parent,
        Path(env_values["MOLT_SYMPHONY_API_TOKEN_FILE"]).parent,
        _state_root(env_values) / "daemon",
        _log_root(env_values) / "daemon",
    ]
    for path in dirs:
        _ensure_dir(path)
    _write_env_file(env_file, env_values)

    steps: list[dict[str, Any]] = []
    steps.append(
        {
            "name": "write_env_file",
            "ok": True,
            "detail": str(env_file),
        }
    )
    steps.append(
        {
            "name": "ensure_directories",
            "ok": True,
            "detail": f"created/verified {len(dirs)} directories",
        }
    )

    if args.install_python:
        for py_ver in ("3.12", "3.13"):
            _run_install_step(
                steps,
                name=f"install_python_{py_ver}",
                command=["uv", "python", "install", py_ver],
                timeout=1800,
            )
    if args.install_llvm:
        _run_install_step(
            steps,
            name="install_llvm",
            command=[
                "winget",
                "install",
                "--id",
                "LLVM.LLVM",
                "--exact",
                "--accept-source-agreements",
                "--accept-package-agreements",
                "--silent",
                "--disable-interactivity",
            ],
            timeout=2400,
        )
    if args.install_wasmtime:
        _run_install_step(
            steps,
            name="install_wasmtime",
            command=[
                "winget",
                "install",
                "--id",
                "BytecodeAlliance.Wasmtime",
                "--exact",
                "--accept-source-agreements",
                "--accept-package-agreements",
                "--silent",
                "--disable-interactivity",
            ],
            timeout=1800,
        )
    if args.install_wasm_tools:
        _run_install_step(
            steps,
            name="install_wasm_tools",
            command=["cargo", "install", "wasm-tools", "--locked"],
            timeout=2400,
        )
    if args.sync_dev_env:
        _run_install_step(
            steps,
            name="uv_sync_dev",
            command=["uv", "sync", "--group", "dev", "--python", "3.12"],
            cwd=REPO_ROOT,
            timeout=1800,
        )
    if args.configure_mcp:
        _ensure_mcp_entry("linear", LINEAR_MCP_URL, steps)
        _ensure_mcp_entry(args.fleet_mcp_name, args.fleet_mcp_url, steps)

    doctor = _collect_doctor_report(env_file)
    payload = {
        "ok": all(step.get("ok", False) for step in steps) and bool(doctor.get("ok")),
        "generated_at": _utc_now(),
        "env_file": str(env_file),
        "ext_root": str(ext_root),
        "symphony_parent_root": str(symphony_parent),
        "steps": steps,
        "doctor": doctor,
    }
    _print_json_or_human(payload, as_json=bool(args.json))
    return 0 if payload["ok"] else 2


def _validate_runtime_env_for_start(runtime_env: dict[str, str]) -> str | None:
    missing = [
        key
        for key in ("LINEAR_API_KEY", "MOLT_LINEAR_PROJECT_SLUG")
        if not str(runtime_env.get(key) or "").strip()
    ]
    if missing:
        return f"missing required values in env file: {', '.join(missing)}"
    py312 = _check_py_version("3.12")
    if not py312.ok:
        return "python 3.12 is required; run repair first"
    return None


def cmd_start(args: argparse.Namespace) -> int:
    env_file = Path(args.env_file).expanduser().resolve()
    runtime_env = _runtime_env(env_file)
    validation_error = _validate_runtime_env_for_start(runtime_env)
    if validation_error:
        payload = {
            "ok": False,
            "error": "invalid_runtime_env",
            "detail": validation_error,
        }
        _print_json_or_human(payload, as_json=bool(args.json))
        return 2

    pid_file = _pid_file(runtime_env)
    pid_file.parent.mkdir(parents=True, exist_ok=True)
    existing = _read_pid_payload(pid_file)
    if existing:
        try:
            pid = int(existing.get("pid"))
        except Exception:
            pid = 0
        if pid > 0 and _tasklist_running(pid):
            payload = {
                "ok": True,
                "status": "already_running",
                "pid": pid,
                "pid_file": str(pid_file),
            }
            _print_json_or_human(payload, as_json=bool(args.json))
            return 0

    log_dir = _log_root(runtime_env) / "daemon"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file = log_dir / "symphony.log"
    command = [
        "uv",
        "run",
        "--python",
        "3.12",
        "python3",
        "tools/symphony_run.py",
        str(Path(args.workflow).as_posix()),
        "--env-file",
        str(env_file),
        "--port",
        str(args.port),
    ]
    if args.exec_mode:
        command.extend(["--exec-mode", str(args.exec_mode)])
    if args.once:
        command.append("--once")

    creationflags = 0
    if hasattr(subprocess, "DETACHED_PROCESS"):
        creationflags |= int(subprocess.DETACHED_PROCESS)
    if hasattr(subprocess, "CREATE_NEW_PROCESS_GROUP"):
        creationflags |= int(subprocess.CREATE_NEW_PROCESS_GROUP)

    with log_file.open("a", encoding="utf-8") as sink:
        sink.write(f"\n[{_utc_now()}] launching: {' '.join(command)}\n")
        sink.flush()
        proc = subprocess.Popen(
            command,
            cwd=str(REPO_ROOT),
            env=runtime_env,
            stdout=sink,
            stderr=sink,
            creationflags=creationflags,
        )

    payload = {
        "pid": int(proc.pid),
        "started_at": _utc_now(),
        "command": command,
        "env_file": str(env_file),
        "port": int(args.port),
        "workflow": str(args.workflow),
        "log_file": str(log_file),
    }
    pid_file.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

    token: str | None = None
    healthy = False
    health_payload: dict[str, Any] = {}
    deadline = time.time() + max(int(args.wait_seconds), 1)
    while time.time() < deadline:
        if not _tasklist_running(proc.pid):
            break
        token = _read_api_token(runtime_env) or token
        health = _http_json(
            method="GET",
            url=f"http://127.0.0.1:{args.port}/api/v1/health",
            token=token,
            timeout=5,
        )
        if health.get("ok"):
            healthy = True
            health_payload = health
            break
        time.sleep(1)

    result = {
        "ok": healthy,
        "status": "running" if healthy else "starting_unhealthy",
        "pid_file": str(pid_file),
        **payload,
    }
    if health_payload:
        result["health"] = health_payload.get("payload")
    _print_json_or_human(result, as_json=bool(args.json))
    return 0 if healthy else 3


def cmd_stop(args: argparse.Namespace) -> int:
    env_file = Path(args.env_file).expanduser().resolve()
    runtime_env = _runtime_env(env_file)
    pid_file = _pid_file(runtime_env)
    payload = _read_pid_payload(pid_file)
    if not payload:
        result = {"ok": True, "status": "already_stopped", "pid_file": str(pid_file)}
        _print_json_or_human(result, as_json=bool(args.json))
        return 0

    pid = int(payload.get("pid") or 0)
    stopped = True
    kill_proc: subprocess.CompletedProcess[str] | None = None
    if pid > 0 and _tasklist_running(pid):
        kill_proc = _run(["taskkill", "/PID", str(pid), "/T", "/F"], timeout=120)
        stopped = kill_proc.returncode == 0
    if stopped and pid_file.exists():
        pid_file.unlink()
    result = {
        "ok": stopped,
        "status": "stopped" if stopped else "failed",
        "pid": pid,
        "pid_file": str(pid_file),
    }
    if kill_proc is not None:
        result["taskkill"] = {
            "returncode": kill_proc.returncode,
            "stdout": (kill_proc.stdout or "").strip()[-500:],
            "stderr": (kill_proc.stderr or "").strip()[-500:],
        }
    _print_json_or_human(result, as_json=bool(args.json))
    return 0 if stopped else 2


def _status_payload(runtime_env: dict[str, str], port: int) -> dict[str, Any]:
    pid_file = _pid_file(runtime_env)
    pid_payload = _read_pid_payload(pid_file)
    pid = int(pid_payload.get("pid") or 0) if pid_payload else 0
    running = pid > 0 and _tasklist_running(pid)
    token = _read_api_token(runtime_env)
    health = _http_json(
        method="GET",
        url=f"http://127.0.0.1:{port}/api/v1/health",
        token=token,
        timeout=8,
    )
    state = _http_json(
        method="GET",
        url=f"http://127.0.0.1:{port}/api/v1/state",
        token=token,
        timeout=12,
    )
    result = {
        "ok": running and bool(health.get("ok")),
        "running": running,
        "pid": pid,
        "pid_file": str(pid_file),
        "health": health,
    }
    if state.get("ok"):
        state_payload = state.get("payload")
        if isinstance(state_payload, dict):
            result["state"] = _summarize_state_payload(state_payload)
        else:
            result["state"] = {}
    else:
        result["state"] = {
            "ok": False,
            "error": state.get("error"),
            "status": state.get("status"),
        }
    return result


def cmd_status(args: argparse.Namespace) -> int:
    env_file = Path(args.env_file).expanduser().resolve()
    runtime_env = _runtime_env(env_file)
    payload = _status_payload(runtime_env, int(args.port))
    _print_json_or_human(payload, as_json=bool(args.json))
    return 0 if payload.get("ok") else 2


def cmd_telemetry(args: argparse.Namespace) -> int:
    env_file = Path(args.env_file).expanduser().resolve()
    runtime_env = _runtime_env(env_file)
    token = _read_api_token(runtime_env)
    state = _http_json(
        method="GET",
        url=f"http://127.0.0.1:{args.port}/api/v1/state",
        token=token,
        timeout=15,
    )
    if not state.get("ok"):
        payload = {
            "ok": False,
            "status": state.get("status"),
            "error": state.get("error"),
            "payload": state.get("payload"),
        }
        _print_json_or_human(payload, as_json=bool(args.json))
        return 2
    raw_payload = state.get("payload")
    parsed = raw_payload if isinstance(raw_payload, dict) else {}
    output = parsed if args.full else _summarize_state_payload(parsed)
    payload = {"ok": True, "telemetry": output}
    _print_json_or_human(payload, as_json=bool(args.json))
    return 0


def cmd_set_concurrency(args: argparse.Namespace) -> int:
    env_file = Path(args.env_file).expanduser().resolve()
    runtime_env = _runtime_env(env_file)
    token = _read_api_token(runtime_env)
    response = _http_json(
        method="POST",
        url=f"http://127.0.0.1:{args.port}/api/v1/tools/run",
        token=token,
        payload={"tool": "set_max_concurrent_agents", "value": int(args.value)},
        timeout=20,
    )
    payload = {
        "ok": response.get("ok", False),
        "status": response.get("status"),
        "response": response.get("payload"),
    }
    _print_json_or_human(payload, as_json=bool(args.json))
    return 0 if response.get("ok") else 2


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Windows admin control-plane for Molt Symphony on BAT00: "
            "doctor/repair toolchain + start/stop/status/telemetry/concurrency."
        )
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    doctor = subparsers.add_parser(
        "doctor", help="Audit BAT00 development + Symphony readiness."
    )
    doctor.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    doctor.add_argument("--json", action="store_true")
    doctor.set_defaults(func=cmd_doctor)

    repair = subparsers.add_parser(
        "repair",
        help="Install/repair Windows toolchain + generate Symphony env file with external-root defaults.",
    )
    repair.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    repair.add_argument("--ext-root", default=str(DEFAULT_EXT_ROOT))
    repair.add_argument("--symphony-parent-root", default=str(DEFAULT_SYMPHONY_PARENT))
    repair.add_argument("--project-key", default="molt")
    repair.add_argument("--project-slug", default=None)
    repair.add_argument("--linear-api-key", default=None)
    repair.add_argument("--fleet-mcp-url", default=DEFAULT_FLEET_MCP_URL)
    repair.add_argument("--fleet-mcp-name", default=DEFAULT_FLEET_MCP_NAME)
    repair.add_argument(
        "--no-install-python", dest="install_python", action="store_false"
    )
    repair.add_argument("--no-install-llvm", dest="install_llvm", action="store_false")
    repair.add_argument(
        "--no-install-wasmtime", dest="install_wasmtime", action="store_false"
    )
    repair.add_argument(
        "--no-install-wasm-tools", dest="install_wasm_tools", action="store_false"
    )
    repair.add_argument("--no-sync-dev-env", dest="sync_dev_env", action="store_false")
    repair.add_argument(
        "--no-configure-mcp", dest="configure_mcp", action="store_false"
    )
    repair.add_argument("--json", action="store_true")
    repair.set_defaults(
        func=cmd_repair,
        install_python=True,
        install_llvm=True,
        install_wasmtime=True,
        install_wasm_tools=True,
        sync_dev_env=True,
        configure_mcp=True,
    )

    start = subparsers.add_parser(
        "start", help="Start Symphony orchestrator as a detached process."
    )
    start.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    start.add_argument("--workflow", default=str(DEFAULT_WORKFLOW))
    start.add_argument("--port", type=int, default=DEFAULT_PORT)
    start.add_argument("--exec-mode", default=None)
    start.add_argument("--once", action="store_true")
    start.add_argument("--wait-seconds", type=int, default=45)
    start.add_argument("--json", action="store_true")
    start.set_defaults(func=cmd_start)

    stop = subparsers.add_parser(
        "stop", help="Stop detached Symphony process on BAT00."
    )
    stop.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    stop.add_argument("--json", action="store_true")
    stop.set_defaults(func=cmd_stop)

    status = subparsers.add_parser("status", help="Get Symphony daemon + API status.")
    status.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    status.add_argument("--port", type=int, default=DEFAULT_PORT)
    status.add_argument("--json", action="store_true")
    status.set_defaults(func=cmd_status)

    telemetry = subparsers.add_parser(
        "telemetry", help="Read live telemetry from /api/v1/state."
    )
    telemetry.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    telemetry.add_argument("--port", type=int, default=DEFAULT_PORT)
    telemetry.add_argument("--full", action="store_true")
    telemetry.add_argument("--json", action="store_true")
    telemetry.set_defaults(func=cmd_telemetry)

    set_concurrency = subparsers.add_parser(
        "set-concurrency",
        help="Set max_concurrent_agents via /api/v1/tools/run.",
    )
    set_concurrency.add_argument("value", type=int)
    set_concurrency.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    set_concurrency.add_argument("--port", type=int, default=DEFAULT_PORT)
    set_concurrency.add_argument("--json", action="store_true")
    set_concurrency.set_defaults(func=cmd_set_concurrency)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
