#!/usr/bin/env python3
"""Materialize tinygrad UPat generated matcher code as static factories.

The generated registry is a compile-time artifact. It records the exact matcher
source strings produced by upstream tinygrad and emits Python factory functions
that bind the runtime globals map into closures. The generated module never
calls exec/eval/compile at runtime; unknown source strings fail closed.
"""

from __future__ import annotations

import argparse
import builtins
import hashlib
import io
import json
import sys
from contextlib import redirect_stdout, suppress
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator


@dataclass(frozen=True)
class MatcherRecord:
    source: str
    globals_keys: tuple[str, ...]

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.source.encode("utf-8")).hexdigest()

    def manifest_payload(self) -> dict[str, Any]:
        first_line = self.source.splitlines()[0] if self.source else ""
        return {
            "sha256": self.sha256,
            "source": self.source,
            "globals": list(self.globals_keys),
            "line_count": self.source.count("\n") + 1,
            "first_line": first_line,
        }


def _is_tinygrad_upat_matcher_source(source: object) -> bool:
    return (
        isinstance(source, str)
        and source.startswith("# match for")
        and "\ndef compiled_match(uop, ctx):" in source
    )


def _iter_body_lines(source: str) -> Iterator[str]:
    lines = source.splitlines()
    try:
        def_index = lines.index("def compiled_match(uop, ctx):")
    except ValueError as exc:
        raise ValueError("matcher source is missing compiled_match signature") from exc
    for raw_line in lines[def_index + 1 :]:
        if not raw_line:
            yield ""
            continue
        if not raw_line.startswith("  "):
            raise ValueError(
                f"compiled_match body line is not two-space indented: {raw_line!r}"
            )
        yield raw_line[2:]


def _validate_global_name(name: str, *, digest: str) -> None:
    if not name.isidentifier():
        raise ValueError(f"matcher {digest} has non-identifier global {name!r}")
    if name in {"compiled_match", "uop", "ctx", "globs"}:
        raise ValueError(f"matcher {digest} has reserved global {name!r}")


def render_registry_module(records: list[MatcherRecord]) -> str:
    unique: dict[str, MatcherRecord] = {}
    for record in records:
        digest = record.sha256
        existing = unique.get(digest)
        if existing is not None:
            if (
                existing.source != record.source
                or existing.globals_keys != record.globals_keys
            ):
                raise ValueError(f"conflicting matcher record for digest {digest}")
            continue
        unique[digest] = record

    lines: list[str] = []
    lines.append(
        "# @generated by tools/tinygrad_upat_static_exec_registry.py. DO NOT EDIT.\n"
    )
    lines.append("def _missing(source):\n")
    lines.append(
        "    first = source.splitlines()[0] if isinstance(source, str) and source else '<non-str>'\n"
    )
    lines.append("    raise RuntimeError(\n")
    lines.append(
        "        'MOLT_COMPAT_ERROR: static exec registry has no admitted tinygrad UPat matcher for '\n"
    )
    lines.append("        + repr(first)\n")
    lines.append("    )\n\n")
    for digest, record in sorted(unique.items()):
        factory_name = f"_factory_{digest[:16]}"
        lines.append(f"def {factory_name}(globs):\n")
        for key in record.globals_keys:
            _validate_global_name(key, digest=digest)
            lines.append(f"    {key} = globs[{key!r}]\n")
        lines.append("    def compiled_match(uop, ctx):\n")
        body = list(_iter_body_lines(record.source))
        if not body:
            lines.append("        return None\n")
        else:
            for body_line in body:
                lines.append(("        " + body_line).rstrip() + "\n")
        lines.append("    return compiled_match\n\n")

    lines.append("_REGISTRY = (\n")
    for digest, record in sorted(unique.items()):
        factory_name = f"_factory_{digest[:16]}"
        lines.append(f"    ({record.source!r}, {factory_name}),\n")
    lines.append(")\n\n")
    lines.append("def exec_static(source, globals=None, locals=None):\n")
    lines.append("    if not isinstance(source, str):\n")
    lines.append("        raise TypeError('static exec registry source must be str')\n")
    lines.append("    if globals is None:\n")
    lines.append("        globals = {}\n")
    lines.append("    if locals is None:\n")
    lines.append("        locals = globals\n")
    lines.append("    for admitted_source, factory in _REGISTRY:\n")
    lines.append("        if source == admitted_source:\n")
    lines.append("            locals['compiled_match'] = factory(globals)\n")
    lines.append("            return None\n")
    lines.append("    return _missing(source)\n")
    return "".join(lines)


def _compile_loaded_tinygrad_pattern_matchers() -> int:
    from tinygrad.uop.ops import PatternMatcher  # noqa: PLC0415
    from tinygrad.uop.upat import upat_compile  # noqa: PLC0415

    compiled = 0
    seen_matchers: set[int] = set()
    for module_name, module in sorted(sys.modules.items()):
        if module is None or not (
            module_name == "tinygrad" or module_name.startswith("tinygrad.")
        ):
            continue
        namespace = getattr(module, "__dict__", None)
        if namespace is None:
            continue
        for attr_name, value in sorted(namespace.items()):
            if not isinstance(value, PatternMatcher):
                continue
            matcher_id = id(value)
            if matcher_id in seen_matchers:
                continue
            seen_matchers.add(matcher_id)
            patterns = getattr(value, "patterns", None)
            if patterns is None:
                raise RuntimeError(
                    "MOLT_COMPAT_ERROR: loaded tinygrad PatternMatcher "
                    f"{module_name}.{attr_name} has no patterns authority"
                )
            for pattern_index, entry in enumerate(tuple(patterns)):
                if not isinstance(entry, tuple) or len(entry) != 2:
                    raise RuntimeError(
                        "MOLT_COMPAT_ERROR: loaded tinygrad PatternMatcher "
                        f"{module_name}.{attr_name} pattern {pattern_index} "
                        "is not a (UPat, function) pair"
                    )
                pattern, fxn = entry
                upat_compile(pattern, fxn)
                compiled += 1
    return compiled


def _capture_tinygrad_upat_matchers(
    *,
    suite_root: Path,
    repo_root: Path,
    workload: str,
    iterations: int,
) -> tuple[int, list[MatcherRecord]]:
    suite_root = suite_root.resolve()
    repo_root = repo_root.resolve()
    sys.path.insert(0, str(suite_root))
    sys.path.insert(0, str(repo_root))
    previous_dont_write_bytecode = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    records: list[MatcherRecord] = []

    def capture_exec(source: object, globals=None, locals=None, *args, **kwargs):
        if _is_tinygrad_upat_matcher_source(source):
            assert isinstance(source, str)
            keys = tuple(
                sorted(key for key in (globals or {}).keys() if key != "__builtins__")
            )
            records.append(MatcherRecord(source=source, globals_keys=keys))
        return original_upat_exec(source, globals, locals, *args, **kwargs)

    from tools import tinygrad_off_shelf_adapter as adapter

    with redirect_stdout(io.StringIO()):
        adapter._import_tinygrad()
    from tinygrad.uop import upat as tinygrad_upat  # noqa: PLC0415

    upat_namespace = vars(tinygrad_upat)
    had_upat_exec = "exec" in upat_namespace
    original_upat_exec = upat_namespace.get("exec", builtins.exec)
    upat_namespace["exec"] = capture_exec
    try:
        with redirect_stdout(io.StringIO()):
            rc = adapter.main(
                [
                    "--suite-root",
                    str(suite_root),
                    "--workload",
                    workload,
                    "--iterations",
                    str(iterations),
                    "--json",
                ]
            )
            _compile_loaded_tinygrad_pattern_matchers()
    finally:
        if had_upat_exec:
            upat_namespace["exec"] = original_upat_exec
        else:
            with suppress(KeyError):
                del upat_namespace["exec"]
        sys.dont_write_bytecode = previous_dont_write_bytecode
        for path_entry in (str(repo_root), str(suite_root)):
            with suppress(ValueError):
                sys.path.remove(path_entry)
    return rc, records


def write_outputs(
    *,
    records: list[MatcherRecord],
    manifest_output: Path,
    module_output: Path,
    suite_root: Path,
    workload: str,
    iterations: int,
) -> dict[str, Any]:
    unique = {record.sha256: record for record in records}
    manifest = {
        "schema": "molt.tinygrad.upat.static_exec_registry.v1",
        "suite_root": str(suite_root.resolve()),
        "workload": workload,
        "iterations": iterations,
        "record_count": len(records),
        "unique_count": len(unique),
        "records": [unique[digest].manifest_payload() for digest in sorted(unique)],
    }
    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    module_output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    module_output.write_text(render_registry_module(list(unique.values())))
    return manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--suite-root", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--workload", default="all")
    parser.add_argument("--iterations", type=int, default=1)
    parser.add_argument("--manifest-output", type=Path, required=True)
    parser.add_argument("--module-output", type=Path, required=True)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    if args.iterations <= 0:
        raise ValueError("--iterations must be positive")

    rc, records = _capture_tinygrad_upat_matchers(
        suite_root=args.suite_root,
        repo_root=args.repo_root,
        workload=args.workload,
        iterations=args.iterations,
    )
    if rc != 0:
        return rc
    if not records:
        raise RuntimeError(
            "MOLT_COMPAT_ERROR: tinygrad UPat static exec capture produced no matcher records"
        )
    manifest = write_outputs(
        records=records,
        manifest_output=args.manifest_output,
        module_output=args.module_output,
        suite_root=args.suite_root,
        workload=args.workload,
        iterations=args.iterations,
    )
    if args.json:
        print(
            json.dumps(
                {k: manifest[k] for k in ("schema", "record_count", "unique_count")},
                sort_keys=True,
            )
        )
    else:
        print(
            "tinygrad UPat static exec registry: "
            f"{manifest['unique_count']} unique / {manifest['record_count']} captured"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
