// Molt Cloudflare Worker Runtime
// Generated by: molt build --profile cloudflare

const CAPABILITIES = [{{CAPABILITIES}}];
const TMP_QUOTA_MB = {{TMP_QUOTA_MB}};

// Error codes matching WASI conventions
const ENOSYS = 38;
const ENOENT = 2;
const EINVAL = 22;

const UTF8_DECODER = new TextDecoder('utf-8');
const UTF8_ENCODER = new TextEncoder();

const stubI32 = () => -ENOSYS;
const stubI64 = () => -BigInt(ENOSYS);
const stubZero = () => 0;

// ---------------------------------------------------------------------------
// In-memory VFS for /tmp
// ---------------------------------------------------------------------------
class TmpFs {
    constructor(quotaBytes) {
        this.files = new Map();
        this.quota = quotaBytes;
        this.used = 0;
    }
    read(path) {
        const data = this.files.get(path);
        if (!data) throw new Error(`ENOENT: ${path}`);
        return data;
    }
    write(path, data) {
        const old = this.files.get(path);
        const delta = data.byteLength - (old ? old.byteLength : 0);
        if (this.used + delta > this.quota) throw new Error('ENOSPC: quota exceeded');
        this.files.set(path, new Uint8Array(data));
        this.used += delta;
    }
    exists(path) { return this.files.has(path); }
    unlink(path) {
        const data = this.files.get(path);
        if (data) { this.used -= data.byteLength; this.files.delete(path); }
    }
    clear() { this.files.clear(); this.used = 0; }
}

// ---------------------------------------------------------------------------
// Stdio capture
// ---------------------------------------------------------------------------
class StdioCapture {
    constructor() {
        this.stdoutBuf = [];
        this.stderrBuf = [];
        this.stdinData = new Uint8Array(0);
        this.stdinOffset = 0;
    }
    writeStdout(text) { this.stdoutBuf.push(text); }
    writeStderr(text) { this.stderrBuf.push(text); }
    readStdin(len) {
        const remaining = this.stdinData.byteLength - this.stdinOffset;
        const n = Math.min(len, remaining);
        if (n <= 0) return new Uint8Array(0);
        const slice = this.stdinData.subarray(this.stdinOffset, this.stdinOffset + n);
        this.stdinOffset += n;
        return slice;
    }
    getStdout() { return this.stdoutBuf.join(''); }
    getStderr() { return this.stderrBuf.join(''); }
}

// ---------------------------------------------------------------------------
// Host imports for the `env` namespace (molt host ABI)
// ---------------------------------------------------------------------------
function createHostImports(state, tmpFs, stdio) {
    const env = {
        // VFS: read file from /tmp into linear memory
        molt_vfs_read: (pathPtr, pathLen, outPtr, outCapacity, outLenPtr) => {
            const memory = state.memory;
            if (!memory) return -ENOSYS;
            const path = UTF8_DECODER.decode(new Uint8Array(memory.buffer, pathPtr >>> 0, pathLen >>> 0));
            if (!tmpFs.exists(path)) return -ENOENT;
            const data = tmpFs.read(path);
            const cap = outCapacity >>> 0;
            if (data.byteLength > cap) return -EINVAL;
            new Uint8Array(memory.buffer, outPtr >>> 0, data.byteLength).set(data);
            new DataView(memory.buffer).setUint32(outLenPtr >>> 0, data.byteLength, true);
            return 0;
        },

        // VFS: write data to /tmp
        molt_vfs_write: (pathPtr, pathLen, dataPtr, dataLen) => {
            const memory = state.memory;
            if (!memory) return -ENOSYS;
            const path = UTF8_DECODER.decode(new Uint8Array(memory.buffer, pathPtr >>> 0, pathLen >>> 0));
            const bytes = new Uint8Array(memory.buffer, dataPtr >>> 0, dataLen >>> 0);
            try {
                tmpFs.write(path, bytes);
            } catch (_err) {
                return -EINVAL;
            }
            return 0;
        },

        // VFS: check if file exists
        molt_vfs_exists: (pathPtr, pathLen) => {
            const memory = state.memory;
            if (!memory) return 0;
            const path = UTF8_DECODER.decode(new Uint8Array(memory.buffer, pathPtr >>> 0, pathLen >>> 0));
            return tmpFs.exists(path) ? 1 : 0;
        },

        // VFS: unlink file
        molt_vfs_unlink: (pathPtr, pathLen) => {
            const memory = state.memory;
            if (!memory) return -ENOSYS;
            const path = UTF8_DECODER.decode(new Uint8Array(memory.buffer, pathPtr >>> 0, pathLen >>> 0));
            tmpFs.unlink(path);
            return 0;
        },

        // Logging host import (matches browser_host.js molt_log_host)
        molt_log_host: (level, ptr, len) => {
            const memory = state.memory;
            if (!memory) return;
            const msg = UTF8_DECODER.decode(new Uint8Array(memory.buffer, ptr >>> 0, len >>> 0));
            if (level === 2) {
                stdio.writeStderr(msg);
            } else {
                stdio.writeStdout(msg);
            }
        },

        // Stubs for unsupported host imports on Workers
        molt_db_query_host: stubI32,
        molt_db_exec_host: stubI32,
        molt_db_host_poll: stubZero,
        molt_getpid_host: () => 0n,
        molt_time_timezone_host: () => 0n,
        molt_time_local_offset_host: () => 0n,
        molt_time_tzname_host: () => -ENOSYS,
        molt_os_close_host: stubI32,
        molt_socket_new_host: stubI64,
        molt_socket_close_host: stubI32,
        molt_socket_clone_host: stubI64,
        molt_socket_bind_host: stubI32,
        molt_socket_listen_host: stubI32,
        molt_socket_accept_host: stubI64,
        molt_socket_connect_host: stubI32,
        molt_socket_connect_ex_host: stubI32,
        molt_socket_recv_host: stubI32,
        molt_socket_send_host: stubI32,
        molt_socket_sendto_host: stubI32,
        molt_socket_sendmsg_host: stubI32,
        molt_socket_recvfrom_host: stubI32,
        molt_socket_recvmsg_host: stubI32,
        molt_socket_shutdown_host: stubI32,
        molt_socket_getsockname_host: stubI32,
        molt_socket_getpeername_host: stubI32,
        molt_socket_setsockopt_host: stubI32,
        molt_socket_getsockopt_host: stubI32,
        molt_socket_detach_host: stubI64,
        molt_socket_socketpair_host: stubI32,
        molt_socket_getaddrinfo_host: stubI32,
        molt_socket_gethostname_host: stubI32,
        molt_socket_getservbyname_host: stubI32,
        molt_socket_getservbyport_host: stubI32,
        molt_socket_poll_host: () => -ENOSYS,
        molt_socket_wait_host: () => -ENOSYS,
        molt_socket_has_ipv6_host: stubZero,
        molt_ws_connect_host: stubI32,
        molt_ws_poll_host: stubI32,
        molt_ws_send_host: stubI32,
        molt_ws_recv_host: stubI32,
        molt_ws_close_host: stubI32,
        molt_process_spawn_host: stubI32,
        molt_process_wait_host: stubI32,
        molt_process_kill_host: stubI32,
        molt_process_terminate_host: stubI32,
        molt_process_write_host: stubI32,
        molt_process_close_stdin_host: stubI32,
        molt_process_stdio_host: stubI32,
        molt_process_host_poll: stubZero,
    };

    if (state.memory) env.memory = state.memory;
    if (state.table) env.__indirect_function_table = state.table;

    return env;
}

// ---------------------------------------------------------------------------
// WASI snapshot preview1 shim (matches browser_host.js buildWasiStub)
// ---------------------------------------------------------------------------
function buildWasiShim(state, stdio) {
    const writeU32 = (ptr, value) => {
        const memory = state.memory;
        if (!memory) return false;
        new DataView(memory.buffer).setUint32(Number(ptr), Number(value) >>> 0, true);
        return true;
    };
    const unsupported = () => ENOSYS;

    return {
        proc_exit: (code) => {
            throw new Error(`WASM proc_exit ${code}`);
        },
        args_sizes_get: (argcPtr, argvBufSizePtr) => {
            if (!writeU32(argcPtr, 0)) return ENOSYS;
            if (!writeU32(argvBufSizePtr, 0)) return ENOSYS;
            return 0;
        },
        args_get: () => 0,
        environ_sizes_get: (countPtr, bufSizePtr) => {
            if (!writeU32(countPtr, 0)) return ENOSYS;
            if (!writeU32(bufSizePtr, 0)) return ENOSYS;
            return 0;
        },
        environ_get: () => 0,
        fd_write: (fd, iovsPtr, iovsLen, outWrittenPtr) => {
            const memory = state.memory;
            if (!memory) return ENOSYS;
            const view = new DataView(memory.buffer);
            const basePtr = typeof iovsPtr === 'bigint' ? Number(iovsPtr) : Number(iovsPtr >>> 0);
            const count = typeof iovsLen === 'bigint' ? Number(iovsLen) : Number(iovsLen >>> 0);
            let text = '';
            let written = 0;
            for (let i = 0; i < count; i++) {
                const ptr = view.getUint32(basePtr + i * 8, true);
                const len = view.getUint32(basePtr + i * 8 + 4, true);
                if (len > 0) {
                    text += UTF8_DECODER.decode(new Uint8Array(memory.buffer, ptr, len));
                    written += len;
                }
            }
            if (outWrittenPtr) {
                view.setUint32(Number(outWrittenPtr), written >>> 0, true);
            }
            const fdNum = typeof fd === 'bigint' ? Number(fd) : Number(fd);
            if (fdNum === 2) {
                stdio.writeStderr(text);
            } else {
                stdio.writeStdout(text);
            }
            return 0;
        },
        fd_read: (fd, iovsPtr, iovsLen, outReadPtr) => {
            const memory = state.memory;
            if (!memory) return ENOSYS;
            const fdNum = typeof fd === 'bigint' ? Number(fd) : Number(fd);
            if (fdNum !== 0) return ENOSYS;
            const view = new DataView(memory.buffer);
            const basePtr = typeof iovsPtr === 'bigint' ? Number(iovsPtr) : Number(iovsPtr >>> 0);
            const count = typeof iovsLen === 'bigint' ? Number(iovsLen) : Number(iovsLen >>> 0);
            let totalRead = 0;
            for (let i = 0; i < count; i++) {
                const ptr = view.getUint32(basePtr + i * 8, true);
                const len = view.getUint32(basePtr + i * 8 + 4, true);
                const chunk = stdio.readStdin(len);
                if (chunk.byteLength > 0) {
                    new Uint8Array(memory.buffer, ptr, chunk.byteLength).set(chunk);
                    totalRead += chunk.byteLength;
                }
                if (chunk.byteLength < len) break;
            }
            if (outReadPtr) {
                view.setUint32(Number(outReadPtr), totalRead >>> 0, true);
            }
            return 0;
        },
        fd_close: () => 0,
        fd_seek: unsupported,
        fd_tell: unsupported,
        fd_fdstat_get: unsupported,
        fd_fdstat_set_flags: unsupported,
        fd_filestat_get: unsupported,
        fd_filestat_set_size: unsupported,
        fd_readdir: unsupported,
        fd_prestat_get: unsupported,
        fd_prestat_dir_name: unsupported,
        path_open: unsupported,
        path_filestat_get: unsupported,
        path_create_directory: unsupported,
        path_remove_directory: unsupported,
        path_unlink_file: unsupported,
        path_rename: unsupported,
        path_readlink: unsupported,
        random_get: (bufPtr, bufLen) => {
            const memory = state.memory;
            if (!memory) return ENOSYS;
            const ptr = typeof bufPtr === 'bigint' ? Number(bufPtr) : Number(bufPtr >>> 0);
            const len = typeof bufLen === 'bigint' ? Number(bufLen) : Number(bufLen >>> 0);
            const bytes = new Uint8Array(memory.buffer, ptr, len);
            crypto.getRandomValues(bytes);
            return 0;
        },
        poll_oneoff: (_inPtr, _outPtr, _nsubscriptions, outEventsPtr) => {
            if (outEventsPtr && !writeU32(outEventsPtr, 0)) return ENOSYS;
            return 0;
        },
        sched_yield: () => 0,
        clock_time_get: (clockIdRaw, _precisionRaw, outPtr) => {
            const memory = state.memory;
            if (!memory) return ENOSYS;
            const clockId = typeof clockIdRaw === 'bigint' ? Number(clockIdRaw) : Number(clockIdRaw >>> 0);
            let nanos;
            if (clockId === 0) {
                nanos = BigInt(Date.now()) * 1000000n;
            } else if (clockId === 1) {
                nanos = BigInt(Math.trunc(performance.now() * 1000000));
            } else {
                return ENOSYS;
            }
            new DataView(memory.buffer).setBigUint64(Number(outPtr), nanos, true);
            return 0;
        },
    };
}

// ---------------------------------------------------------------------------
// Worker entry point
// ---------------------------------------------------------------------------
export default {
    async fetch(request, env, ctx) {
        const tmpFs = new TmpFs(TMP_QUOTA_MB * 1024 * 1024);
        const stdio = new StdioCapture();

        // Populate stdin from request body
        if (request.body) {
            stdio.stdinData = new Uint8Array(await request.arrayBuffer());
        }

        // Shared state object so imports can reference memory after instantiation
        const state = { memory: null, table: null };

        const hostEnv = createHostImports(state, tmpFs, stdio);
        const wasiImports = buildWasiShim(state, stdio);

        try {
            const { instance } = await WebAssembly.instantiate(
                env.__STATIC_CONTENT
                    ? await env.__STATIC_CONTENT.get('{{WASM_FILENAME}}').then(r => WebAssembly.compile(r))
                    : (await import('./{{WASM_FILENAME}}')).default,
                { env: hostEnv, wasi_snapshot_preview1: wasiImports }
            );

            // Bind memory/table from the instance exports so host imports can
            // use them (the WASM module owns memory in Molt builds).
            state.memory = instance.exports.memory || null;
            state.table = instance.exports.__indirect_function_table || null;

            // Initialize function table if the module exports the helper
            if (typeof instance.exports.molt_table_init === 'function') {
                instance.exports.molt_table_init();
            }

            // Run entry point
            if (typeof instance.exports.molt_main === 'function') {
                instance.exports.molt_main();
            } else if (typeof instance.exports._start === 'function') {
                instance.exports._start();
            }

            // Return stdout as response body
            const output = stdio.getStdout();
            const stderr = stdio.getStderr();
            const headers = { 'content-type': 'text/plain; charset=utf-8' };
            if (stderr) headers['x-molt-stderr'] = encodeURIComponent(stderr);
            return new Response(output, { headers });
        } catch (err) {
            // proc_exit(0) is a clean exit
            if (err.message && err.message.includes('proc_exit 0')) {
                const output = stdio.getStdout();
                return new Response(output, {
                    headers: { 'content-type': 'text/plain; charset=utf-8' },
                });
            }
            return new Response(`Error: ${err.message}\n${err.stack}`, {
                status: 500,
                headers: { 'content-type': 'text/plain' },
            });
        } finally {
            tmpFs.clear();
        }
    }
};
