"""Intrinsic-first stdlib package stub for `_pyrepl`.

Generated by tools/gen_stdlib_stubs.py; lowering the package replaces this file.
"""

from _intrinsics import require_intrinsic as _require_intrinsic

_require_intrinsic("molt_capabilities_has")


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `_pyrepl` package stub with full intrinsic-backed lowering.
def __getattr__(attr: str):
    if attr in {
        "__main__",
        "_minimal_curses",
        "_module_completer",
        "_threading_handler",
        "base_eventqueue",
        "commands",
        "completing_reader",
        "console",
        "curses",
        "fancy_termios",
        "historical_reader",
        "input",
        "keymap",
        "main",
        "pager",
        "reader",
        "readline",
        "simple_interact",
        "terminfo",
        "trace",
        "types",
        "unix_console",
        "unix_eventqueue",
        "utils",
        "windows_console",
        "windows_eventqueue",
    }:
        raise AttributeError(f"module {__name__!r} has no attribute {attr!r}", name=attr)
    raise RuntimeError(
        'stdlib package "_pyrepl" is not fully lowered yet; only an intrinsic-first stub is available.'
    )


globals().pop("_require_intrinsic", None)
