"""Intrinsic-first stdlib module stub for `_pyrepl.fancy_termios`.

Generated by tools/gen_stdlib_stubs.py; lowering the module replaces this file.
"""


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `_pyrepl.fancy_termios` module stub with a full lowering.
def __getattr__(attr: str):
    raise RuntimeError(
        'stdlib module "_pyrepl.fancy_termios" is not fully lowered yet; only an intrinsic-first stub is available.'
    )
