from collections.abc import Mapping
from typing import Any

def load_intrinsic(name: str, namespace: Mapping[str, Any] | None = ...) -> Any: ...
def require_intrinsic(name: str, namespace: Mapping[str, Any] | None = ...) -> Any: ...
