# NOTE: Canonical intrinsics manifest (Rust-owned).
# Generated files: src/molt/_intrinsics.pyi and runtime/molt-runtime/src/intrinsics/generated.rs
# Update via: python3 tools/gen_intrinsics.py

from typing import Any

def molt_capabilities_trusted() -> bool: ...
def molt_capabilities_has(name: str) -> bool: ...
def molt_capabilities_require(name: str) -> None: ...
def molt_weakref_register(weakref_obj: Any, obj: Any, callback: Any) -> Any: ...
def molt_weakref_get(weakref_obj: Any) -> Any: ...
def molt_weakref_peek(weakref_obj: Any) -> Any: ...
def molt_weakref_drop(weakref_obj: Any) -> Any: ...
def molt_weakref_collect() -> Any: ...
def molt_weakref_find_nocallback(obj: Any) -> Any: ...
def molt_weakref_refs(obj: Any) -> list[Any]: ...
def molt_weakref_count(obj: Any) -> int: ...
def molt_weakref_finalize_track(finalizer_obj: Any) -> Any: ...
def molt_weakref_finalize_untrack(finalizer_obj: Any) -> Any: ...
def molt_weakkeydict_set(
    weakdict_obj: Any, key_obj: Any, key_ref_obj: Any, key_hash: int, value: Any
) -> Any: ...
def molt_weakkeydict_get(weakdict_obj: Any, key_obj: Any, key_hash: int) -> Any: ...
def molt_weakkeydict_del(weakdict_obj: Any, key_obj: Any, key_hash: int) -> Any: ...
def molt_weakkeydict_contains(
    weakdict_obj: Any, key_obj: Any, key_hash: int
) -> bool: ...
def molt_weakkeydict_len(weakdict_obj: Any) -> int: ...
def molt_weakkeydict_items(weakdict_obj: Any) -> list[tuple[Any, Any]]: ...
def molt_weakkeydict_keyrefs(weakdict_obj: Any) -> list[Any]: ...
def molt_weakkeydict_popitem(weakdict_obj: Any) -> tuple[Any, Any]: ...
def molt_weakkeydict_clear(weakdict_obj: Any) -> Any: ...
def molt_weakvaluedict_set(
    weakdict_obj: Any, key_obj: Any, key_hash: int, value_ref_obj: Any
) -> Any: ...
def molt_weakvaluedict_get(weakdict_obj: Any, key_obj: Any, key_hash: int) -> Any: ...
def molt_weakvaluedict_del(weakdict_obj: Any, key_obj: Any, key_hash: int) -> Any: ...
def molt_weakvaluedict_contains(
    weakdict_obj: Any, key_obj: Any, key_hash: int
) -> bool: ...
def molt_weakvaluedict_len(weakdict_obj: Any) -> int: ...
def molt_weakvaluedict_items(weakdict_obj: Any) -> list[tuple[Any, Any]]: ...
def molt_weakvaluedict_valuerefs(weakdict_obj: Any) -> list[Any]: ...
def molt_weakvaluedict_popitem(weakdict_obj: Any) -> tuple[Any, Any]: ...
def molt_weakvaluedict_clear(weakdict_obj: Any) -> Any: ...
def molt_weakset_add(
    weakset_obj: Any, item: Any, item_ref_obj: Any, item_hash: int
) -> Any: ...
def molt_weakset_discard(weakset_obj: Any, item: Any, item_hash: int) -> Any: ...
def molt_weakset_remove(weakset_obj: Any, item: Any, item_hash: int) -> Any: ...
def molt_weakset_pop(weakset_obj: Any) -> Any: ...
def molt_weakset_contains(weakset_obj: Any, item: Any, item_hash: int) -> bool: ...
def molt_weakset_len(weakset_obj: Any) -> int: ...
def molt_weakset_items(weakset_obj: Any) -> list[Any]: ...
def molt_weakset_clear(weakset_obj: Any) -> Any: ...
def molt_abc_bootstrap() -> dict[str, Any]: ...
def molt_collections_abc_runtime_types() -> dict[str, Any]: ...
def molt_abc_get_cache_token() -> int: ...
def molt_abc_init(cls: Any) -> Any: ...
def molt_abc_register(cls: Any, subclass: Any) -> Any: ...
def molt_abc_instancecheck(cls: Any, instance: Any) -> bool: ...
def molt_abc_subclasscheck(cls: Any, subclass: Any) -> bool: ...
def molt_abc_get_dump(cls: Any) -> tuple[Any, Any, Any, int]: ...
def molt_abc_reset_registry(cls: Any) -> Any: ...
def molt_abc_reset_caches(cls: Any) -> Any: ...
def molt_abc_update_abstractmethods(cls: Any) -> Any: ...
def molt_enum_init_member(member: Any, name: Any, value: Any) -> None: ...
def molt_re_literal_matches(segment: str, literal: str, flags: int) -> bool: ...
def molt_re_literal_advance(
    text: str, pos: int, end: int, literal: str, flags: int
) -> int: ...
def molt_re_any_advance(text: str, pos: int, end: int, flags: int) -> int: ...
def molt_re_char_in_range(ch: str, start: str, end: str, flags: int) -> bool: ...
def molt_re_category_matches(ch: str, category: str, flags: int) -> bool: ...
def molt_re_anchor_matches(
    kind: str, text: str, pos: int, end: int, origin: int, flags: int
) -> bool: ...
def molt_re_group_is_set(groups: Any, index: int) -> bool: ...
def molt_re_backref_advance(
    text: str, pos: int, end: int, start_ref: int, end_ref: int
) -> int: ...
def molt_re_backref_group_advance(
    text: str, pos: int, end: int, groups: Any, index: int
) -> int: ...
def molt_re_apply_scoped_flags(flags: int, add_flags: int, clear_flags: int) -> int: ...
def molt_re_group_capture(groups: Any, index: int, start: int, end: int) -> Any: ...
def molt_re_charclass_matches(
    ch: str,
    negated: bool,
    chars: Any,
    ranges: Any,
    categories: Any,
    flags: int,
) -> bool: ...
def molt_re_charclass_advance(
    text: str,
    pos: int,
    end: int,
    negated: bool,
    chars: Any,
    ranges: Any,
    categories: Any,
    flags: int,
) -> int: ...
def molt_re_group_values(text: str, groups: Any) -> Any: ...
def molt_re_expand_replacement(repl: str, group_values: Any) -> str: ...
def molt_shlex_quote(text: str) -> str: ...
def molt_shlex_split(text: str, whitespace: str) -> list[str]: ...
def molt_shlex_split_ex(
    text: str,
    whitespace: str,
    posix: bool,
    comments: bool,
    whitespace_split: bool,
    commenters: str,
    punctuation_chars: str,
) -> list[str]: ...
def molt_shlex_join(words: Any) -> str: ...
def molt_fnmatch(name: str, pat: str) -> bool: ...
def molt_fnmatchcase(name: str, pat: str) -> bool: ...
def molt_pow(base: Any, exp: Any) -> Any: ...
def molt_pow_mod(base: Any, exp: Any, mod: Any) -> Any: ...
def molt_fnmatch_filter(names: Any, pat: str, invert: bool = ...) -> list[str]: ...
def molt_fnmatch_translate(pat: str) -> str: ...
def molt_pkgutil_iter_modules(
    path: Any, prefix: str
) -> list[tuple[str, str, bool]]: ...
def molt_pkgutil_walk_packages(
    path: Any, prefix: str
) -> list[tuple[str, str, bool]]: ...
def molt_site_help0() -> Any: ...
def molt_site_help1(target: Any) -> Any: ...
def molt_site_credits() -> Any: ...
def molt_site_license() -> Any: ...
def molt_site_copyright() -> Any: ...
def molt_site_quitter_call(code: Any) -> Any: ...
def molt_shutil_copyfile(src: str, dst: str) -> str: ...
def molt_shutil_which(cmd: str, path: str | None = ...) -> str | None: ...
def molt_py_compile_compile(file: str, cfile: str | None = ...) -> str: ...
def molt_compileall_compile_file(fullname: str) -> bool: ...
def molt_compileall_compile_dir(dir: str, maxlevels: int) -> bool: ...
def molt_compileall_compile_path(
    paths: Any, skip_curdir: bool, maxlevels: int
) -> bool: ...
def molt_stat_constants() -> tuple[
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
    int,
]: ...
def molt_stat_ifmt(mode: int) -> int: ...
def molt_stat_imode(mode: int) -> int: ...
def molt_stat_isdir(mode: int) -> bool: ...
def molt_stat_isreg(mode: int) -> bool: ...
def molt_stat_ischr(mode: int) -> bool: ...
def molt_stat_isblk(mode: int) -> bool: ...
def molt_stat_isfifo(mode: int) -> bool: ...
def molt_stat_islnk(mode: int) -> bool: ...
def molt_stat_issock(mode: int) -> bool: ...
def molt_textwrap_wrap(text: str, width: int) -> list[str]: ...
def molt_textwrap_fill(text: str, width: int) -> str: ...
def molt_textwrap_indent(text: str, prefix: str) -> str: ...
def molt_urllib_quote(string: str, safe: str = ...) -> str: ...
def molt_urllib_quote_plus(string: str, safe: str = ...) -> str: ...
def molt_urllib_unquote(string: str) -> str: ...
def molt_urllib_unquote_plus(string: str) -> str: ...
def molt_urllib_parse_qsl(
    qs: str,
    keep_blank_values: bool = ...,
    strict_parsing: bool = ...,
) -> list[tuple[str, str]]: ...
def molt_urllib_parse_qs(
    qs: str,
    keep_blank_values: bool = ...,
    strict_parsing: bool = ...,
) -> dict[str, list[str]]: ...
def molt_urllib_urlencode(query: Any, doseq: bool = ..., safe: str = ...) -> str: ...
def molt_urllib_urlsplit(
    url: str, scheme: str = ..., allow_fragments: bool = ...
) -> tuple[str, str, str, str, str]: ...
def molt_urllib_urlparse(
    url: str, scheme: str = ..., allow_fragments: bool = ...
) -> tuple[str, str, str, str, str, str]: ...
def molt_urllib_urlunsplit(
    scheme: str, netloc: str, path: str, query: str, fragment: str
) -> str: ...
def molt_urllib_urlunparse(
    scheme: str, netloc: str, path: str, params: str, query: str, fragment: str
) -> str: ...
def molt_urllib_urldefrag(url: str) -> tuple[str, str]: ...
def molt_urllib_urljoin(base: str, url: str) -> str: ...
def molt_urllib_error_urlerror_init(
    self_obj: Any, reason: Any, filename: Any = ...
) -> None: ...
def molt_urllib_error_urlerror_str(reason: Any) -> str: ...
def molt_urllib_error_httperror_init(
    self_obj: Any, url: Any, code: Any, msg: Any, hdrs: Any, fp: Any
) -> None: ...
def molt_urllib_error_httperror_str(code: Any, msg: Any) -> str: ...
def molt_urllib_error_content_too_short_init(
    self_obj: Any, msg: Any, content: Any
) -> None: ...
def molt_urllib_request_request_init(
    self_obj: Any,
    url: Any,
    data: Any = ...,
    headers: Any = ...,
    method: Any = ...,
) -> None: ...
def molt_urllib_request_opener_init(self_obj: Any) -> None: ...
def molt_urllib_request_add_handler(opener: Any, handler: Any) -> None: ...
def molt_urllib_request_open(opener: Any, request: Any) -> Any: ...
def molt_urllib_request_process_http_error(request: Any, response: Any) -> Any: ...
def molt_urllib_request_response_read(handle: Any, size: int = ...) -> bytes: ...
def molt_urllib_request_response_close(handle: Any) -> None: ...
def molt_urllib_request_response_drop(handle: Any) -> None: ...
def molt_urllib_request_response_geturl(handle: Any) -> str: ...
def molt_urllib_request_response_getcode(handle: Any) -> Any: ...
def molt_urllib_request_response_getreason(handle: Any) -> Any: ...
def molt_urllib_request_response_getheaders(handle: Any) -> dict[str, str]: ...
def molt_http_cookiejar_new() -> int: ...
def molt_http_cookiejar_len(handle: Any) -> int: ...
def molt_http_cookiejar_clear(handle: Any) -> None: ...
def molt_http_cookiejar_extract(
    handle: Any, request_url: str, headers: Any
) -> None: ...
def molt_http_cookiejar_header_for_url(handle: Any, request_url: str) -> str | None: ...
def molt_ctypes_require_ffi() -> None: ...
def molt_ctypes_coerce_value(ctype: Any, value: Any) -> Any: ...
def molt_ctypes_default_value(ctype: Any) -> Any: ...
def molt_ctypes_sizeof(obj_or_type: Any) -> int: ...
def molt_http_client_execute(
    host: Any,
    port: Any,
    timeout: Any,
    method: Any,
    url: Any,
    headers: Any,
    body: Any = ...,
) -> int: ...
def molt_http_client_response_read(handle: Any, size: int = ...) -> bytes: ...
def molt_http_client_response_close(handle: Any) -> None: ...
def molt_http_client_response_drop(handle: Any) -> None: ...
def molt_http_client_response_getstatus(handle: Any) -> int: ...
def molt_http_client_response_getreason(handle: Any) -> str: ...
def molt_http_client_response_getheader(
    handle: Any, name: Any, default: Any = ...
) -> Any: ...
def molt_http_client_response_getheaders(handle: Any) -> list[tuple[str, str]]: ...
def molt_socketserver_register(server: Any) -> None: ...
def molt_socketserver_unregister(server: Any) -> None: ...
def molt_socketserver_dispatch_begin(server: Any, request_bytes: Any) -> int: ...
def molt_socketserver_dispatch_poll(server: Any, request_id: int) -> bytes | None: ...
def molt_socketserver_dispatch_cancel(server: Any, request_id: int) -> None: ...
def molt_socketserver_get_request_poll(server: Any) -> tuple[int, bytes] | None: ...
def molt_socketserver_set_response(
    server: Any, request_id: int, response_bytes: Any
) -> None: ...
def molt_socketserver_serve_forever(
    server: Any, poll_interval: float = ...
) -> None: ...
def molt_socketserver_handle_request(server: Any) -> None: ...
def molt_socketserver_shutdown(server: Any) -> None: ...
def molt_http_server_read_request(handler: Any) -> int: ...
def molt_http_server_compute_close_connection(handler: Any) -> bool: ...
def molt_http_server_handle_one_request(handler: Any) -> bool: ...
def molt_http_server_send_response(
    handler: Any, code: int, message: Any = ...
) -> None: ...
def molt_http_server_send_response_only(
    handler: Any, code: int, message: Any = ...
) -> None: ...
def molt_http_server_send_header(handler: Any, keyword: Any, value: Any) -> None: ...
def molt_http_server_end_headers(handler: Any) -> None: ...
def molt_http_server_send_error(
    handler: Any, code: int, message: Any = ...
) -> None: ...
def molt_http_server_version_string(server_version: Any, sys_version: Any) -> str: ...
def molt_http_server_date_time_string(timestamp: Any = ...) -> str: ...
def molt_context_null(payload: Any) -> Any: ...
def molt_context_closing(payload: Any) -> Any: ...
def molt_contextlib_closing(payload: Any) -> Any: ...
def molt_contextlib_aclosing_enter(payload: Any) -> Any: ...
def molt_contextlib_aclosing_exit(payload: Any) -> Any: ...
def molt_contextlib_abstract_enter(payload: Any) -> Any: ...
def molt_contextlib_abstract_aenter(payload: Any) -> Any: ...
def molt_contextlib_abstract_subclasshook(candidate: Any) -> Any: ...
def molt_contextlib_abstract_async_subclasshook(candidate: Any) -> Any: ...
def molt_contextlib_contextdecorator_call(
    cm: Any, func: Any, args: Any, kwargs: Any
) -> Any: ...
def molt_contextlib_chdir_enter(path: Any) -> str: ...
def molt_contextlib_chdir_exit(path: Any) -> None: ...
def molt_contextlib_asyncgen_cm_new(func: Any, args: Any, kwargs: Any) -> Any: ...
def molt_contextlib_asyncgen_cm_drop(handle: Any) -> None: ...
def molt_contextlib_asyncgen_cm_aenter(handle: Any) -> Any: ...
def molt_contextlib_asyncgen_cm_aexit(
    handle: Any, exc_type: Any, exc: Any, tb: Any
) -> Any: ...
def molt_contextlib_generator_enter(gen: Any) -> Any: ...
def molt_contextlib_generator_exit(
    gen: Any, exc_type: Any, exc: Any, tb: Any
) -> bool: ...
def molt_contextlib_asyncgen_enter(agen: Any) -> Any: ...
def molt_contextlib_asyncgen_exit(
    agen: Any, exc_type: Any, exc: Any, tb: Any
) -> Any: ...
def molt_contextlib_suppress_match(exc_type: Any, exceptions: Any) -> bool: ...
def molt_contextlib_redirect_enter(
    sys_module: Any, stream_name: Any, new_target: Any
) -> Any: ...
def molt_contextlib_redirect_exit(
    sys_module: Any, stream_name: Any, old_target: Any
) -> bool: ...
def molt_contextlib_exitstack_new() -> Any: ...
def molt_contextlib_exitstack_drop(stack: Any) -> None: ...
def molt_contextlib_exitstack_push(stack: Any, callback: Any) -> None: ...
def molt_contextlib_exitstack_push_callback(
    stack: Any, callback: Any, args: Any, kwargs: Any
) -> None: ...
def molt_contextlib_exitstack_pop(stack: Any) -> Any: ...
def molt_contextlib_exitstack_pop_all(stack: Any) -> Any: ...
def molt_contextlib_exitstack_enter_context(stack: Any, cm: Any) -> Any: ...
def molt_contextlib_exitstack_exit(
    stack: Any, exc_type: Any, exc: Any, tb: Any
) -> bool: ...
def molt_contextlib_async_exitstack_push_callback(
    stack: Any, callback: Any, args: Any, kwargs: Any
) -> None: ...
def molt_contextlib_async_exitstack_push_exit(stack: Any, exit: Any) -> Any: ...
def molt_contextlib_async_exitstack_enter_context(stack: Any, cm: Any) -> Any: ...
def molt_contextlib_async_exitstack_exit(
    stack: Any, exc_type: Any, exc: Any, tb: Any
) -> Any: ...
def molt_email_message_new() -> Any: ...
def molt_email_message_from_bytes(data: Any) -> Any: ...
def molt_email_message_set(message: Any, name: str, value: str) -> None: ...
def molt_email_message_get(message: Any, name: str) -> str | None: ...
def molt_email_message_set_content(message: Any, content: str) -> None: ...
def molt_email_message_add_alternative(
    message: Any, content: str, subtype: str
) -> None: ...
def molt_email_message_add_attachment(
    message: Any,
    data: Any,
    maintype: str,
    subtype: str,
    filename: str | None,
) -> None: ...
def molt_email_message_is_multipart(message: Any) -> bool: ...
def molt_email_message_payload(message: Any) -> Any: ...
def molt_email_message_content(message: Any) -> str: ...
def molt_email_message_content_type(message: Any) -> str: ...
def molt_email_message_filename(message: Any) -> str | None: ...
def molt_email_message_as_string(message: Any) -> str: ...
def molt_email_message_items(message: Any) -> list[tuple[str, str]]: ...
def molt_email_message_drop(message: Any) -> None: ...
def molt_email_utils_make_msgid(domain: str | None) -> str: ...
def molt_email_utils_getaddresses(values: Any) -> list[tuple[str, str]]: ...
def molt_email_utils_parsedate_tz(value: str) -> tuple[int, ...] | None: ...
def molt_email_utils_format_datetime(dt: Any) -> str: ...
def molt_email_utils_parsedate_to_datetime(value: str) -> Any: ...
def molt_email_policy_new(name: str, utf8: bool) -> tuple[str, bool]: ...
def molt_email_header_encode_word(text: str, charset: str | None) -> str: ...
def molt_email_address_addr_spec(username: str, domain: str) -> str: ...
def molt_email_address_format(display_name: str, username: str, domain: str) -> str: ...
def molt_asyncgen_shutdown() -> Any: ...
def molt_block_on(task: Any) -> Any: ...
def molt_chan_new(maxsize: int = ...) -> Any: ...
def molt_chan_send(chan: Any, val: Any) -> int: ...
def molt_chan_recv(chan: Any) -> Any: ...
def molt_chan_try_send(chan: Any, val: Any) -> int: ...
def molt_chan_try_recv(chan: Any) -> Any: ...
def molt_chan_send_blocking(chan: Any, val: Any) -> int: ...
def molt_chan_recv_blocking(chan: Any) -> Any: ...
def molt_chan_drop(chan: Any) -> None: ...
def molt_pending() -> Any: ...
def molt_spawn(task: Any) -> None: ...
def molt_async_sleep(_delay: float = ..., _result: Any | None = ...) -> Any: ...
def molt_asyncio_wait_for_new(future: Any, timeout: Any | None = ...) -> Any: ...
def molt_asyncio_wait_new(
    tasks: Any, timeout: Any | None = ..., return_when: int = ...
) -> Any: ...
def molt_asyncio_gather_new(tasks: Any, return_exceptions: bool = ...) -> Any: ...
def molt_asyncio_cancel_pending(tasks: Any) -> int: ...
def molt_asyncio_ready_batch_run(handles: Any) -> int: ...
def molt_asyncio_ready_queue_drain(ready_lock: Any, ready: Any) -> int: ...
def molt_asyncio_waiters_notify(
    waiters: Any, count: int = ..., result: Any = ...
) -> int: ...
def molt_asyncio_waiters_notify_exception(
    waiters: Any, count: int = ..., exc: Any = ...
) -> int: ...
def molt_asyncio_waiters_remove(waiters: Any, waiter: Any) -> bool: ...
def molt_asyncio_barrier_release(waiters: Any) -> int: ...
def molt_asyncio_condition_wait_for_step(
    condition: Any, predicate: Any
) -> tuple[bool, Any]: ...
def molt_asyncio_future_transfer(source: Any, target: Any) -> bool: ...
def molt_asyncio_event_waiters_cleanup(waiters: Any) -> int: ...
def molt_asyncio_task_registry_set(token_id: int, task: Any | None) -> None: ...
def molt_asyncio_task_registry_get(token_id: int) -> Any | None: ...
def molt_asyncio_task_registry_contains(token_id: int) -> bool: ...
def molt_asyncio_task_registry_current() -> Any | None: ...
def molt_asyncio_task_registry_current_for_loop(
    loop: Any | None = ...,
) -> Any | None: ...
def molt_asyncio_task_registry_pop(token_id: int) -> Any | None: ...
def molt_asyncio_task_registry_move(old_token_id: int, new_token_id: int) -> bool: ...
def molt_asyncio_task_registry_values() -> Any: ...
def molt_asyncio_task_registry_live(loop: Any | None = ...) -> list[Any]: ...
def molt_asyncio_task_registry_live_set(loop: Any | None = ...) -> set[Any]: ...
def molt_asyncio_event_waiters_register(token_id: int, waiter: Any) -> None: ...
def molt_asyncio_event_waiters_unregister(token_id: int, waiter: Any) -> bool: ...
def molt_asyncio_event_waiters_cleanup_token(token_id: int) -> int: ...
def molt_asyncio_child_watcher_add(
    callbacks: Any, pid: int, callback: Any, args: tuple[Any, ...]
) -> None: ...
def molt_asyncio_child_watcher_remove(callbacks: Any, pid: int) -> bool: ...
def molt_asyncio_child_watcher_clear(callbacks: Any) -> None: ...
def molt_asyncio_child_watcher_pop(
    callbacks: Any, pid: int
) -> tuple[Any, tuple[Any, ...]] | None: ...
def molt_asyncio_require_ssl_transport_support() -> None: ...
def molt_asyncio_ssl_transport_orchestrate(
    operation: str,
    ssl: Any,
    server_hostname: str | None = ...,
    server_side: bool = ...,
) -> bool: ...
def molt_asyncio_tls_client_connect_new(
    host: str, port: int, server_hostname: str | None = ...
) -> Any: ...
def molt_asyncio_tls_client_from_fd_new(
    fd: int, server_hostname: str | None = ...
) -> Any: ...
def molt_asyncio_tls_server_payload(ssl: Any) -> tuple[str, str]: ...
def molt_asyncio_tls_server_from_fd_new(
    fd: int, certfile: str, keyfile: str
) -> Any: ...
def molt_asyncio_require_unix_socket_support() -> None: ...
def molt_asyncio_require_child_watcher_support() -> None: ...
def molt_asyncio_running_loop_get() -> Any: ...
def molt_asyncio_running_loop_set(loop: Any) -> None: ...
def molt_asyncio_event_loop_get() -> Any: ...
def molt_asyncio_event_loop_get_current() -> Any: ...
def molt_asyncio_event_loop_set(loop: Any) -> None: ...
def molt_asyncio_event_loop_policy_get() -> Any: ...
def molt_asyncio_event_loop_policy_set(policy: Any) -> None: ...
def molt_asyncio_taskgroup_on_task_done(tasks: Any, errors: Any, task: Any) -> bool: ...
def molt_asyncio_taskgroup_request_cancel(
    loop: Any | None, cancel_callback: Any, cancel_handle: Any | None = ...
) -> Any | None: ...
def molt_asyncio_tasks_add_done_callback(tasks: Any, callback: Any) -> int: ...
def molt_asyncio_task_cancel_apply(future: Any, msg: Any | None = ...) -> bool: ...
def molt_asyncio_task_uncancel_apply(future: Any) -> None: ...
def molt_asyncio_future_invoke_callbacks(future: Any, callbacks: Any) -> int: ...
def molt_asyncio_event_set_waiters(waiters: Any, result: Any = ...) -> int: ...
def molt_asyncio_loop_enqueue_handle(
    loop: Any, ready_lock: Any, ready: Any, handle: Any
) -> int: ...
def molt_asyncio_timer_handle_new(
    handle: Any, delay: Any, loop: Any, scheduled: Any, ready_lock: Any, ready: Any
) -> Any: ...
def molt_asyncio_timer_schedule(
    handle: Any, delay: Any, loop: Any, scheduled: Any, ready_lock: Any, ready: Any
) -> Any: ...
def molt_asyncio_timer_handle_cancel(
    scheduled: Any, handle: Any, timer_task: Any | None
) -> None: ...
def molt_asyncio_fd_watcher_new(
    registry: Any, fileno: Any, callback: Any, args: Any, events: Any
) -> Any: ...
def molt_asyncio_fd_watcher_register(
    loop: Any, registry: Any, fileno: Any, callback: Any, args: Any, events: Any
) -> None: ...
def molt_asyncio_fd_watcher_unregister(registry: Any, fileno: Any) -> bool: ...
def molt_asyncio_subprocess_stdio_normalize(
    value: Any,
    allow_stdout: bool,
    pipe_const: Any,
    devnull_const: Any,
    stdout_const: Any,
    inherit_mode: int,
    pipe_mode: int,
    devnull_mode: int,
    stdout_mode: int,
    fd_base: int,
    fd_max: int,
) -> int: ...
def molt_asyncio_server_accept_loop_new(
    sock: Any,
    callback: Any,
    loop: Any,
    reader_ctor: Any,
    writer_ctor: Any,
    closed_probe: Any,
) -> Any: ...
def molt_asyncio_ready_runner_new(loop: Any, ready_lock: Any, ready: Any) -> Any: ...
def molt_asyncio_stream_reader_read_new(reader: Any, n: int = ...) -> Any: ...
def molt_asyncio_stream_reader_readline_new(reader: Any) -> Any: ...
def molt_asyncio_stream_send_all_new(stream: Any, data: Any) -> Any: ...
def molt_asyncio_stream_buffer_snapshot(buffer: Any) -> Any: ...
def molt_asyncio_stream_buffer_consume(buffer: Any, count: int) -> int: ...
def molt_asyncio_socket_reader_read_new(
    reader: Any, n: int = ..., fd: int = ...
) -> Any: ...
def molt_asyncio_socket_reader_readline_new(reader: Any, fd: int = ...) -> Any: ...
def molt_asyncio_sock_recv_new(sock: Any, size: int, fd: int) -> Any: ...
def molt_asyncio_sock_connect_new(sock: Any, address: Any, fd: int) -> Any: ...
def molt_asyncio_sock_accept_new(sock: Any, fd: int) -> Any: ...
def molt_asyncio_sock_recv_into_new(
    sock: Any, buf: Any, nbytes: int, fd: int
) -> Any: ...
def molt_asyncio_sock_sendall_new(sock: Any, data: Any, fd: int) -> Any: ...
def molt_asyncio_sock_recvfrom_new(sock: Any, size: int, fd: int) -> Any: ...
def molt_asyncio_sock_recvfrom_into_new(
    sock: Any, buf: Any, nbytes: int, fd: int
) -> Any: ...
def molt_asyncio_sock_sendto_new(sock: Any, data: Any, addr: Any, fd: int) -> Any: ...
def molt_time_monotonic() -> float: ...
def molt_time_monotonic_ns() -> int: ...
def molt_time_perf_counter() -> float: ...
def molt_time_perf_counter_ns() -> int: ...
def molt_time_time() -> float: ...
def molt_time_time_ns() -> int: ...
def molt_time_process_time() -> float: ...
def molt_time_process_time_ns() -> int: ...
def molt_time_localtime(secs: Any | None = ...) -> Any: ...
def molt_time_gmtime(secs: Any | None = ...) -> Any: ...
def molt_time_strftime(fmt: Any, time_tuple: Any) -> Any: ...
def molt_time_timezone() -> int: ...
def molt_time_daylight() -> int: ...
def molt_time_altzone() -> int: ...
def molt_time_tzname() -> Any: ...
def molt_time_asctime(time_tuple: Any) -> str: ...
def molt_time_mktime(time_tuple: Any) -> float: ...
def molt_time_timegm(time_tuple: Any) -> float: ...
def molt_time_get_clock_info(name: str) -> tuple[str, str, float, bool, bool]: ...
def molt_heapq_heapify(heap: list[Any]) -> None: ...
def molt_heapq_heappush(heap: list[Any], item: Any) -> None: ...
def molt_heapq_heappop(heap: list[Any]) -> Any: ...
def molt_heapq_heapreplace(heap: list[Any], item: Any) -> Any: ...
def molt_heapq_heappushpop(heap: list[Any], item: Any) -> Any: ...
def molt_math_log(value: float) -> float: ...
def molt_math_log2(value: float) -> float: ...
def molt_math_log10(value: float) -> float: ...
def molt_math_log1p(value: float) -> float: ...
def molt_math_exp(value: float) -> float: ...
def molt_math_expm1(value: float) -> float: ...
def molt_math_fma(x: float, y: float, z: float) -> float: ...
def molt_math_sin(value: float) -> float: ...
def molt_math_cos(value: float) -> float: ...
def molt_math_acos(value: float) -> float: ...
def molt_math_lgamma(value: float) -> float: ...
def molt_math_gamma(value: float) -> float: ...
def molt_math_erf(value: float) -> float: ...
def molt_math_erfc(value: float) -> float: ...
def molt_math_isfinite(value: Any) -> bool: ...
def molt_math_isinf(value: Any) -> bool: ...
def molt_math_isnan(value: Any) -> bool: ...
def molt_math_fabs(value: Any) -> float: ...
def molt_math_copysign(x: Any, y: Any) -> float: ...
def molt_math_sqrt(value: Any) -> float: ...
def molt_math_floor(value: Any) -> int: ...
def molt_math_ceil(value: Any) -> int: ...
def molt_math_trunc(value: Any) -> int: ...
def molt_math_fmod(x: Any, y: Any) -> float: ...
def molt_math_modf(value: Any) -> tuple[float, float]: ...
def molt_math_frexp(value: Any) -> tuple[float, int]: ...
def molt_math_ldexp(value: Any, exp: Any) -> float: ...
def molt_math_isclose(a: Any, b: Any, rel_tol: Any, abs_tol: Any) -> bool: ...
def molt_math_prod(iterable: Any, start: Any) -> Any: ...
def molt_math_fsum(iterable: Any) -> float: ...
def molt_math_gcd(args: tuple[Any, ...]) -> int: ...
def molt_math_lcm(args: tuple[Any, ...]) -> int: ...
def molt_math_factorial(value: Any) -> int: ...
def molt_math_comb(n: Any, k: Any) -> int: ...
def molt_math_perm(n: Any, k: Any) -> int: ...
def molt_math_degrees(value: Any) -> float: ...
def molt_math_radians(value: Any) -> float: ...
def molt_math_hypot(args: tuple[Any, ...]) -> float: ...
def molt_math_dist(p: Any, q: Any) -> float: ...
def molt_math_isqrt(value: Any) -> int: ...
def molt_math_nextafter(x: Any, y: Any) -> float: ...
def molt_math_ulp(value: Any) -> float: ...
def molt_math_remainder(x: Any, y: Any) -> float: ...
def molt_math_tan(value: Any) -> float: ...
def molt_math_asin(value: Any) -> float: ...
def molt_math_atan(value: Any) -> float: ...
def molt_math_atan2(y: Any, x: Any) -> float: ...
def molt_math_sinh(value: Any) -> float: ...
def molt_math_cosh(value: Any) -> float: ...
def molt_math_tanh(value: Any) -> float: ...
def molt_math_asinh(value: Any) -> float: ...
def molt_math_acosh(value: Any) -> float: ...
def molt_math_atanh(value: Any) -> float: ...
def molt_statistics_mean(data: Any) -> float: ...
def molt_statistics_fmean(data: Any) -> float: ...
def molt_statistics_stdev(data: Any, xbar: Any = ...) -> float: ...
def molt_statistics_variance(data: Any, xbar: Any = ...) -> float: ...
def molt_statistics_pvariance(data: Any, mu: Any = ...) -> float: ...
def molt_statistics_pstdev(data: Any, mu: Any = ...) -> float: ...
def molt_statistics_median(data: Any) -> float: ...
def molt_statistics_median_low(data: Any) -> Any: ...
def molt_statistics_median_high(data: Any) -> Any: ...
def molt_statistics_median_grouped(data: Any, interval: Any = ...) -> float: ...
def molt_statistics_mode(data: Any) -> Any: ...
def molt_statistics_multimode(data: Any) -> list[Any]: ...
def molt_statistics_quantiles(
    data: Any, n: Any = ..., inclusive: bool = ...
) -> list[float]: ...
def molt_statistics_harmonic_mean(data: Any) -> float: ...
def molt_statistics_geometric_mean(data: Any) -> float: ...
def molt_statistics_covariance(x: Any, y: Any) -> float: ...
def molt_statistics_correlation(x: Any, y: Any) -> float: ...
def molt_statistics_linear_regression(
    x: Any, y: Any, proportional: bool = ...
) -> tuple[float, float]: ...
def molt_decimal_context_new() -> Any: ...
def molt_decimal_context_get_current() -> Any: ...
def molt_decimal_context_set_current(ctx: Any) -> Any: ...
def molt_decimal_context_copy(ctx: Any) -> Any: ...
def molt_decimal_context_drop(ctx: Any) -> None: ...
def molt_decimal_context_get_prec(ctx: Any) -> int: ...
def molt_decimal_context_set_prec(ctx: Any, prec: int) -> None: ...
def molt_decimal_context_get_rounding(ctx: Any) -> int: ...
def molt_decimal_context_set_rounding(ctx: Any, rounding: int) -> None: ...
def molt_decimal_context_clear_flags(ctx: Any) -> None: ...
def molt_decimal_context_get_flag(ctx: Any, flag: int) -> bool: ...
def molt_decimal_context_set_flag(ctx: Any, flag: int, value: bool) -> None: ...
def molt_decimal_context_get_trap(ctx: Any, flag: int) -> bool: ...
def molt_decimal_context_set_trap(ctx: Any, flag: int, value: bool) -> None: ...
def molt_decimal_from_str(ctx: Any, value: str) -> Any: ...
def molt_decimal_from_int(ctx: Any, value: Any) -> Any: ...
def molt_decimal_clone(value: Any) -> Any: ...
def molt_decimal_drop(value: Any) -> None: ...
def molt_decimal_to_string(value: Any) -> str: ...
def molt_decimal_as_tuple(value: Any) -> Any: ...
def molt_decimal_to_float(value: Any) -> float: ...
def molt_decimal_div(ctx: Any, a: Any, b: Any) -> Any: ...
def molt_decimal_quantize(ctx: Any, a: Any, exp: Any) -> Any: ...
def molt_decimal_compare(ctx: Any, a: Any, b: Any) -> Any: ...
def molt_decimal_compare_total(a: Any, b: Any) -> Any: ...
def molt_decimal_normalize(ctx: Any, a: Any) -> Any: ...
def molt_decimal_exp(ctx: Any, a: Any) -> Any: ...
def molt_hash_new(name: str, data: Any, options: Any) -> Any: ...
def molt_hash_update(handle: Any, data: Any) -> None: ...
def molt_hash_copy(handle: Any) -> Any: ...
def molt_hash_digest(handle: Any, length: Any | None = ...) -> bytes: ...
def molt_hash_drop(handle: Any) -> None: ...
def molt_hmac_new(key: Any, msg: Any, name: str, options: Any) -> Any: ...
def molt_hmac_update(handle: Any, data: Any) -> None: ...
def molt_hmac_copy(handle: Any) -> Any: ...
def molt_hmac_digest(handle: Any) -> bytes: ...
def molt_hmac_drop(handle: Any) -> None: ...
def molt_compare_digest(a: Any, b: Any) -> bool: ...
def molt_pbkdf2_hmac(
    name: str,
    password: Any,
    salt: Any,
    iterations: int,
    dklen: int | None = ...,
) -> bytes: ...
def molt_scrypt(
    password: Any,
    salt: Any,
    n: int,
    r: int,
    p: int,
    maxmem: int,
    dklen: int,
) -> bytes: ...
def molt_os_dup(fd: int) -> int: ...
def molt_os_close(fd: int) -> None: ...
def molt_os_read(fd: int, n: int) -> bytes: ...
def molt_os_write(fd: int, data: Any) -> int: ...
def molt_os_pipe() -> tuple[int, int]: ...
def molt_os_get_inheritable(fd: int) -> bool: ...
def molt_os_set_inheritable(fd: int, inheritable: bool) -> None: ...
def molt_os_urandom(n: int) -> bytes: ...
def molt_os_name() -> str: ...
def molt_os_fsencode(path: Any) -> bytes: ...
def molt_getcwd() -> str: ...
def molt_getpid() -> int: ...
def molt_signal_raise(sig: int) -> None: ...
def molt_env_get(key: str, default: Any = ...) -> Any: ...
def molt_env_snapshot() -> dict[str, str]: ...
def molt_env_set(key: str, value: str) -> None: ...
def molt_env_unset(key: str) -> bool: ...
def molt_env_len() -> int: ...
def molt_env_contains(key: str) -> bool: ...
def molt_env_popitem() -> tuple[str, str]: ...
def molt_env_clear() -> None: ...
def molt_env_putenv(key: str, value: str) -> None: ...
def molt_env_unsetenv(key: str) -> None: ...
def molt_locale_setlocale(category: Any, locale: Any) -> str: ...
def molt_locale_getpreferredencoding(do_setlocale: Any) -> str: ...
def molt_locale_getlocale(category: Any) -> tuple[Any, Any]: ...
def molt_gettext_gettext(message: Any) -> Any: ...
def molt_gettext_ngettext(singular: Any, plural: Any, n: Any) -> Any: ...
def molt_errno_constants() -> tuple[dict[str, int], dict[int, str]]: ...
def molt_path_exists(path: Any) -> bool: ...
def molt_path_isdir(path: Any) -> bool: ...
def molt_path_isfile(path: Any) -> bool: ...
def molt_path_islink(path: Any) -> bool: ...
def molt_path_readlink(path: Any) -> str: ...
def molt_path_symlink(src: Any, dst: Any, target_is_directory: bool = ...) -> None: ...
def molt_path_listdir(path: Any) -> list[str]: ...
def molt_path_mkdir(path: Any) -> None: ...
def molt_path_chmod(path: Any, mode: int) -> None: ...
def molt_path_unlink(path: Any) -> None: ...
def molt_path_rmdir(path: Any) -> None: ...
def molt_path_join(base: Any, part: Any) -> str: ...
def molt_path_join_many(base: Any, parts: tuple[Any, ...] | list[Any]) -> str: ...
def molt_path_isabs(path: Any) -> bool: ...
def molt_path_dirname(path: Any) -> str: ...
def molt_path_basename(path: Any) -> str: ...
def molt_path_name(path: Any) -> str: ...
def molt_path_split(path: Any) -> tuple[str, str]: ...
def molt_path_splitext(path: Any) -> tuple[str, str]: ...
def molt_path_suffix(path: Any) -> str: ...
def molt_path_stem(path: Any) -> str: ...
def molt_path_suffixes(path: Any) -> list[str]: ...
def molt_path_normpath(path: Any) -> str: ...
def molt_path_abspath(path: Any) -> str: ...
def molt_path_resolve(path: Any, strict: bool = ...) -> str: ...
def molt_path_as_uri(path: Any) -> str: ...
def molt_path_relpath(path: Any, start: Any | None = ...) -> str: ...
def molt_path_expandvars(path: Any) -> str: ...
def molt_path_expandvars_env(path: Any, env: dict[str, str]) -> str: ...
def molt_path_makedirs(path: Any, exist_ok: bool = ...) -> None: ...
def molt_path_parts(path: Any) -> list[str]: ...
def molt_path_splitroot(path: Any) -> tuple[str, str, str]: ...
def molt_path_parents(path: Any) -> list[str]: ...
def molt_path_compare(lhs: Any, rhs: Any) -> int: ...
def molt_path_relative_to(path: Any, base: Any) -> str: ...
def molt_path_relative_to_many(
    path: Any, base: Any, parts: tuple[Any, ...] | list[Any]
) -> str: ...
def molt_path_with_name(path: Any, name: str) -> str: ...
def molt_path_with_suffix(path: Any, suffix: str) -> str: ...
def molt_path_with_stem(path: Any, stem: str) -> str: ...
def molt_path_is_relative_to(
    path: Any, base: Any, parts: tuple[Any, ...] | list[Any] | None = ...
) -> bool: ...
def molt_path_expanduser(path: Any) -> str: ...
def molt_path_match(path: Any, pattern: str) -> bool: ...
def molt_path_glob(path: Any, pattern: str) -> list[str]: ...
def molt_glob_has_magic(pathname: Any) -> bool: ...
def molt_glob_escape(pathname: Any) -> str | bytes: ...
def molt_glob_translate(
    pathname: Any,
    recursive: Any = False,
    include_hidden: Any = False,
    seps: Any | None = None,
) -> str: ...
def molt_glob(
    pathname: Any,
    root_dir: Any | None = None,
    dir_fd: Any | None = None,
    recursive: Any = False,
    include_hidden: Any = False,
) -> list[str] | list[bytes]: ...
def molt_io_class(name: str) -> Any: ...
def molt_file_open(path: Any, mode: Any) -> Any: ...
def molt_file_open_ex(
    file: Any,
    mode: Any,
    buffering: int,
    encoding: Any | None,
    errors: Any | None,
    newline: Any | None,
    closefd: bool,
    opener: Any | None,
) -> Any: ...
def molt_file_read(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readline(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readlines(handle: Any, hint: int | None = ...) -> Any: ...
def molt_file_read1(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readall(handle: Any) -> Any: ...
def molt_file_readinto(handle: Any, buffer: Any) -> Any: ...
def molt_file_readinto1(handle: Any, buffer: Any) -> Any: ...
def molt_file_peek(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_getvalue(handle: Any) -> Any: ...
def molt_file_getbuffer(handle: Any) -> Any: ...
def molt_file_detach(handle: Any) -> Any: ...
def molt_file_reconfigure(
    handle: Any,
    encoding: Any | None,
    errors: Any | None,
    newline: Any | None,
    line_buffering: Any | None,
    write_through: Any | None,
) -> Any: ...
def molt_file_seek(handle: Any, offset: int, whence: int) -> Any: ...
def molt_file_tell(handle: Any) -> Any: ...
def molt_file_fileno(handle: Any) -> Any: ...
def molt_file_truncate(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readable(handle: Any) -> Any: ...
def molt_file_writable(handle: Any) -> Any: ...
def molt_file_seekable(handle: Any) -> Any: ...
def molt_file_isatty(handle: Any) -> Any: ...
def molt_file_iter(handle: Any) -> Any: ...
def molt_file_next(handle: Any) -> Any: ...
def molt_file_enter(handle: Any) -> Any: ...
def molt_file_exit(handle: Any, exc: Any) -> Any: ...
def molt_file_exit_method(handle: Any, exc: Any) -> Any: ...
def molt_file_write(handle: Any, data: Any) -> Any: ...
def molt_file_writelines(handle: Any, lines: Any) -> Any: ...
def molt_file_flush(handle: Any) -> Any: ...
def molt_file_close(handle: Any) -> Any: ...
def molt_file_io_new(
    cls: Any,
    name: Any,
    mode: Any = ...,
    closefd: Any = ...,
    opener: Any = ...,
) -> Any: ...
def molt_file_io_init(
    self: Any,
    name: Any,
    mode: Any = ...,
    closefd: Any = ...,
    opener: Any = ...,
) -> None: ...
def molt_buffered_new(cls: Any, raw: Any, buffer_size: int = ...) -> Any: ...
def molt_buffered_init(self: Any, raw: Any, buffer_size: int = ...) -> None: ...
def molt_text_io_wrapper_new(
    cls: Any,
    buffer: Any,
    encoding: str | None = ...,
    errors: str | None = ...,
    newline: str | None = ...,
    line_buffering: bool = ...,
    write_through: bool = ...,
) -> Any: ...
def molt_text_io_wrapper_init(
    self: Any,
    buffer: Any,
    encoding: str | None = ...,
    errors: str | None = ...,
    newline: str | None = ...,
    line_buffering: bool = ...,
    write_through: bool = ...,
) -> None: ...
def molt_bytesio_new(cls: Any, initial: Any = ...) -> Any: ...
def molt_bytesio_init(self: Any, initial: Any = ...) -> None: ...
def molt_stringio_new(
    cls: Any,
    initial: Any = ...,
    newline: str | None = ...,
) -> Any: ...
def molt_stringio_init(
    self: Any,
    initial: Any = ...,
    newline: str | None = ...,
) -> None: ...
def molt_repr_from_obj(value: Any) -> str: ...
def molt_string_capitalize(value: Any) -> str: ...
def molt_codecs_decode(obj: Any, encoding: Any, errors: Any) -> Any: ...
def molt_codecs_encode(obj: Any, encoding: Any, errors: Any) -> Any: ...
def molt_codecs_lookup_name(encoding: Any) -> Any: ...
def molt_encodings_aliases_map() -> dict[str, str]: ...
def molt_struct_pack(fmt: Any, values: Any) -> bytes: ...
def molt_struct_unpack(fmt: Any, buffer: Any) -> Any: ...
def molt_struct_calcsize(fmt: Any) -> int: ...
def molt_struct_pack_into(buffer: Any, offset: Any, data: Any) -> None: ...
def molt_struct_unpack_from(fmt: Any, buffer: Any, offset: Any) -> Any: ...
def molt_struct_iter_unpack(fmt: Any, buffer: Any) -> Any: ...
def molt_deflate_raw(data: Any, level: Any) -> Any: ...
def molt_inflate_raw(data: Any) -> Any: ...
def molt_cancel_token_new(parent: int | None = ...) -> int: ...
def molt_cancel_token_clone(token_id: int) -> None: ...
def molt_cancel_token_drop(token_id: int) -> None: ...
def molt_cancel_token_cancel(token_id: int) -> None: ...
def molt_cancel_token_is_cancelled(token_id: int) -> bool: ...
def molt_cancel_token_set_current(token_id: int | None) -> int: ...
def molt_cancel_token_get_current() -> int: ...
def molt_future_cancel(future: Any) -> None: ...
def molt_future_cancel_msg(future: Any, msg: Any) -> None: ...
def molt_future_cancel_clear(future: Any) -> None: ...
def molt_promise_new() -> Any: ...
def molt_promise_set_result(future: Any, result: Any) -> None: ...
def molt_promise_set_exception(future: Any, exc: Any) -> None: ...
def molt_task_register_token_owned(task: Any, token_id: int) -> None: ...
def molt_io_wait(future: Any) -> int: ...
def molt_io_wait_new(socket: Any, events: int, timeout: float | None) -> Any: ...
def molt_select_select(
    rlist: Any, wlist: Any, xlist: Any, timeout: float | None
) -> tuple[list[Any], list[Any], list[Any]]: ...
def molt_select_selector_new(kind: int) -> Any: ...
def molt_select_selector_fileno(handle: Any) -> int: ...
def molt_select_selector_register(handle: Any, fileobj: Any, events: int) -> int: ...
def molt_select_selector_unregister(handle: Any, fd: int) -> None: ...
def molt_select_selector_modify(handle: Any, fd: int, events: int) -> None: ...
def molt_select_selector_poll(
    handle: Any, timeout: float | None
) -> list[tuple[int, int]]: ...
def molt_select_selector_close(handle: Any) -> None: ...
def molt_select_selector_drop(handle: Any) -> None: ...
def molt_ws_wait_new(ws: Any, events: int, timeout: float | None) -> Any: ...
def molt_ws_pair_obj(capacity: int) -> tuple[Any, Any]: ...
def molt_ws_connect_obj(url: str) -> Any: ...
def molt_ws_send_obj(ws: Any, data: Any) -> int: ...
def molt_ws_recv(ws: Any) -> Any: ...
def molt_ws_close(ws: Any) -> None: ...
def molt_ws_drop(ws: Any) -> None: ...
def molt_thread_submit(fn: Any, args: Any, kwargs: Any) -> Any: ...
def molt_thread_spawn(payload: bytes) -> Any: ...
def molt_thread_spawn_shared(
    token: int, callable: Any, args: Any, kwargs: Any
) -> Any: ...
def molt_thread_join(handle: Any, timeout: float | None) -> Any: ...
def molt_thread_is_alive(handle: Any) -> bool: ...
def molt_thread_ident(handle: Any) -> int | None: ...
def molt_thread_native_id(handle: Any) -> int | None: ...
def molt_thread_current_ident() -> int: ...
def molt_thread_current_native_id() -> int: ...
def molt_thread_drop(handle: Any) -> None: ...
def molt_thread_stack_size_get() -> int: ...
def molt_thread_stack_size_set(size: int) -> int: ...
def molt_thread_registry_set_main(name: str, daemon: bool) -> None: ...
def molt_thread_registry_register(
    handle: Any, token: int, name: str, daemon: bool
) -> None: ...
def molt_thread_registry_forget(token: int) -> None: ...
def molt_thread_registry_snapshot() -> list[
    tuple[str, bool, int | None, int | None, bool, bool]
]: ...
def molt_thread_registry_current() -> (
    tuple[str, bool, int | None, int | None, bool, bool] | None
): ...
def molt_thread_registry_active_count() -> int: ...
def molt_thread_poll(future: Any) -> int: ...
def molt_lock_new() -> Any: ...
def molt_lock_acquire(handle: Any, blocking: bool, timeout: float | None) -> bool: ...
def molt_lock_release(handle: Any) -> None: ...
def molt_lock_locked(handle: Any) -> bool: ...
def molt_lock_drop(handle: Any) -> None: ...
def molt_rlock_new() -> Any: ...
def molt_rlock_acquire(handle: Any, blocking: bool, timeout: float | None) -> bool: ...
def molt_rlock_release(handle: Any) -> None: ...
def molt_rlock_locked(handle: Any) -> bool: ...
def molt_rlock_is_owned(handle: Any) -> bool: ...
def molt_rlock_release_save(handle: Any) -> int: ...
def molt_rlock_acquire_restore(handle: Any, count: int) -> None: ...
def molt_rlock_drop(handle: Any) -> None: ...
def molt_condition_new() -> Any: ...
def molt_condition_wait(handle: Any, timeout: float | None) -> bool: ...
def molt_condition_wait_for(
    condition: Any, predicate: Any, timeout: float | None
) -> bool: ...
def molt_condition_notify(handle: Any, count: int) -> None: ...
def molt_condition_drop(handle: Any) -> None: ...
def molt_event_new() -> Any: ...
def molt_event_set(handle: Any) -> None: ...
def molt_event_clear(handle: Any) -> None: ...
def molt_event_is_set(handle: Any) -> bool: ...
def molt_event_wait(handle: Any, timeout: float | None) -> bool: ...
def molt_event_drop(handle: Any) -> None: ...
def molt_semaphore_new(value: int, bounded: bool) -> Any: ...
def molt_semaphore_acquire(
    handle: Any, blocking: bool, timeout: float | None
) -> bool: ...
def molt_semaphore_release(handle: Any, count: int = ...) -> None: ...
def molt_semaphore_drop(handle: Any) -> None: ...
def molt_barrier_new(parties: int, timeout: float | None = ...) -> Any: ...
def molt_barrier_wait(handle: Any, timeout: float | None = ...) -> int: ...
def molt_barrier_abort(handle: Any) -> None: ...
def molt_barrier_reset(handle: Any) -> None: ...
def molt_barrier_parties(handle: Any) -> int: ...
def molt_barrier_n_waiting(handle: Any) -> int: ...
def molt_barrier_broken(handle: Any) -> bool: ...
def molt_barrier_drop(handle: Any) -> None: ...
def molt_local_new() -> Any: ...
def molt_local_get_dict(handle: Any) -> dict[str, Any]: ...
def molt_local_drop(handle: Any) -> None: ...
def molt_queue_new(maxsize: int) -> Any: ...
def molt_queue_lifo_new(maxsize: int) -> Any: ...
def molt_queue_priority_new(maxsize: int) -> Any: ...
def molt_queue_qsize(handle: Any) -> int: ...
def molt_queue_empty(handle: Any) -> bool: ...
def molt_queue_full(handle: Any) -> bool: ...
def molt_queue_put(
    handle: Any, item: Any, blocking: bool, timeout: float | None
) -> bool: ...
def molt_queue_get(
    handle: Any, blocking: bool, timeout: float | None, sentinel: Any
) -> Any: ...
def molt_queue_task_done(handle: Any) -> bool: ...
def molt_queue_join(handle: Any) -> None: ...
def molt_queue_drop(handle: Any) -> None: ...
def molt_zipfile_crc32(data: Any) -> int: ...
def molt_logging_percent_style_format(fmt: str, mapping: dict[str, Any]) -> str: ...
def molt_logging_runtime_ready() -> bool: ...
def molt_wsgiref_runtime_ready() -> bool: ...
def molt_zoneinfo_runtime_ready() -> bool: ...
def molt_zipapp_runtime_ready() -> bool: ...
def molt_zlib_runtime_ready() -> bool: ...
def molt_xmlrpc_runtime_ready() -> bool: ...
def molt_csv_runtime_ready() -> bool: ...
def molt_datetime_runtime_ready() -> bool: ...
def molt_tokenize_runtime_ready() -> bool: ...
def molt_tomllib_runtime_ready() -> bool: ...
def molt_trace_runtime_ready() -> bool: ...
def molt_unicodedata_runtime_ready() -> bool: ...
def molt_subprocess_runtime_ready() -> bool: ...
def molt_symtable_runtime_ready() -> bool: ...
def molt_import_smoke_runtime_ready() -> bool: ...
def molt_process_spawn(
    args: Any,
    env: Any,
    cwd: Any,
    stdin: Any,
    stdout: Any,
    stderr: Any,
) -> Any: ...
def molt_process_wait_future(proc: Any) -> Any: ...
def molt_process_poll(future: Any) -> int: ...
def molt_process_pid(proc: Any) -> int: ...
def molt_process_returncode(proc: Any) -> int | None: ...
def molt_process_kill(proc: Any) -> None: ...
def molt_process_terminate(proc: Any) -> None: ...
def molt_process_stdin(proc: Any) -> Any: ...
def molt_process_stdout(proc: Any) -> Any: ...
def molt_process_stderr(proc: Any) -> Any: ...
def molt_process_drop(proc: Any) -> None: ...
def molt_stream_new(capacity: int) -> Any: ...
def molt_stream_clone(stream: Any) -> Any: ...
def molt_stream_send_obj(stream: Any, data: Any) -> int: ...
def molt_stream_recv(stream: Any) -> Any: ...
def molt_stream_close(stream: Any) -> None: ...
def molt_stream_drop(stream: Any) -> None: ...
def molt_stream_reader_new(stream: Any) -> Any: ...
def molt_stream_reader_read(reader: Any, n: int) -> Any: ...
def molt_stream_reader_readline(reader: Any) -> Any: ...
def molt_stream_reader_at_eof(reader: Any) -> bool: ...
def molt_stream_reader_drop(reader: Any) -> None: ...
def molt_socket_reader_new(sock: Any) -> Any: ...
def molt_socket_reader_read(reader: Any, n: int) -> Any: ...
def molt_socket_reader_readline(reader: Any) -> Any: ...
def molt_socket_reader_readline_limit(reader: Any, limit: int) -> Any: ...
def molt_socket_reader_at_eof(reader: Any) -> bool: ...
def molt_socket_reader_drop(reader: Any) -> None: ...
def molt_db_query_obj(req: Any, token: Any) -> Any: ...
def molt_db_exec_obj(req: Any, token: Any) -> Any: ...
def molt_msgpack_parse_scalar_obj(data: Any) -> Any: ...
def molt_cbor_parse_scalar_obj(data: Any) -> Any: ...
def molt_json_parse_scalar_obj(data: Any) -> Any: ...
def molt_socket_new(
    family: int,
    type: int,
    proto: int,
    fileno: int | None,
) -> Any: ...
def molt_socket_close(sock: Any) -> None: ...
def molt_socket_drop(sock: Any) -> None: ...
def molt_socket_clone(sock: Any) -> Any: ...
def molt_socket_fileno(sock: Any) -> int: ...
def molt_socket_gettimeout(sock: Any) -> float | None: ...
def molt_socket_settimeout(sock: Any, timeout: float | None) -> None: ...
def molt_socket_setblocking(sock: Any, flag: bool) -> None: ...
def molt_socket_getblocking(sock: Any) -> bool: ...
def molt_socket_bind(sock: Any, addr: Any) -> None: ...
def molt_socket_listen(sock: Any, backlog: int) -> None: ...
def molt_socket_accept(sock: Any) -> tuple[Any, Any]: ...
def molt_socket_connect(sock: Any, addr: Any) -> None: ...
def molt_socket_connect_ex(sock: Any, addr: Any) -> int: ...
def molt_socket_recv(sock: Any, size: int, flags: int) -> bytes: ...
def molt_socket_recv_into(sock: Any, buffer: Any, size: int, flags: int) -> int: ...
def molt_socket_recvfrom_into(
    sock: Any, buffer: Any, size: int, flags: int
) -> tuple[int, Any]: ...
def molt_socket_send(sock: Any, data: Any, flags: int) -> int: ...
def molt_socket_sendall(sock: Any, data: Any, flags: int) -> None: ...
def molt_socket_sendto(sock: Any, data: Any, flags: int, addr: Any) -> int: ...
def molt_socket_recvfrom(sock: Any, size: int, flags: int) -> tuple[bytes, Any]: ...
def molt_socket_sendmsg(
    sock: Any,
    buffers: Any,
    ancdata: Any = ...,
    flags: int = ...,
    address: Any = ...,
) -> int: ...
def molt_socket_recvmsg(
    sock: Any,
    bufsize: int,
    ancbufsize: int = ...,
    flags: int = ...,
) -> tuple[bytes, list[tuple[int, int, bytes]], int, Any]: ...
def molt_socket_recvmsg_into(
    sock: Any,
    buffers: Any,
    ancbufsize: int = ...,
    flags: int = ...,
) -> tuple[int, list[tuple[int, int, bytes]], int, Any]: ...
def molt_socket_shutdown(sock: Any, how: int) -> None: ...
def molt_socket_getsockname(sock: Any) -> Any: ...
def molt_socket_getpeername(sock: Any) -> Any: ...
def molt_socket_setsockopt(sock: Any, level: int, optname: int, value: Any) -> None: ...
def molt_socket_getsockopt(sock: Any, level: int, optname: int, buflen: int) -> Any: ...
def molt_socket_detach(sock: Any) -> int: ...
def molt_socketpair(
    family: int | None, type: int | None, proto: int | None
) -> tuple[Any, Any]: ...
def molt_socket_getaddrinfo(
    host: str | bytes | None,
    port: int | str | bytes | None,
    family: int,
    type: int,
    proto: int,
    flags: int,
) -> list[tuple[int, int, int, str | None, Any]]: ...
def molt_socket_getnameinfo(addr: Any, flags: int) -> tuple[str, str]: ...
def molt_socket_gethostname() -> str: ...
def molt_socket_gethostbyname(hostname: str) -> str: ...
def molt_socket_gethostbyaddr(hostname: str) -> tuple[str, list[str], list[str]]: ...
def molt_socket_getfqdn(name: str | None = ...) -> str: ...
def molt_socket_getservbyname(name: str, proto: str | None) -> int: ...
def molt_socket_getservbyport(port: int, proto: str | None) -> str: ...
def molt_socket_inet_pton(family: int, address: str) -> bytes: ...
def molt_socket_inet_ntop(family: int, packed: bytes) -> str: ...
def molt_socket_htons(value: int) -> int: ...
def molt_socket_ntohs(value: int) -> int: ...
def molt_socket_htonl(value: int) -> int: ...
def molt_socket_ntohl(value: int) -> int: ...
def molt_socket_constants() -> dict[str, int]: ...
def molt_socket_has_ipv6() -> bool: ...
def molt_compile_builtin(
    source: Any,
    filename: Any,
    mode: Any,
    flags: int,
    dont_inherit: bool,
    optimize: int,
) -> Any: ...
def molt_input_builtin(prompt: Any) -> str: ...
def molt_globals_builtin() -> dict[str, Any]: ...
def molt_locals_builtin() -> dict[str, Any]: ...
def molt_code_new(
    filename: str,
    name: str,
    firstlineno: int,
    linetable: Any,
    varnames: Any,
    argcount: int,
    posonlyargcount: int,
    kwonlyargcount: int,
) -> Any: ...
def molt_code_slots_init(count: int) -> None: ...
def molt_code_slot_set(code_id: int, code: Any) -> None: ...
def molt_module_new(name: str) -> Any: ...
def molt_module_import(name: str) -> Any: ...
def molt_runpy_run_module(
    mod_name: str,
    run_name: str | None,
    init_globals: dict[str, Any] | None,
    alter_sys: bool = False,
) -> dict[str, Any]: ...
def molt_runpy_run_path(
    path: str,
    run_name: str | None,
    init_globals: dict[str, Any] | None,
) -> dict[str, Any]: ...
def molt_runpy_resolve_path(
    path: str,
    module_file: str | None,
) -> dict[str, Any]: ...
def molt_uuid_getnode() -> int: ...
def molt_uuid_uuid4_bytes() -> bytes: ...
def molt_uuid_uuid1_bytes(
    node: int | None = ..., clock_seq: int | None = ...
) -> bytes: ...
def molt_uuid_uuid3_bytes(namespace: bytes, name: bytes) -> bytes: ...
def molt_uuid_uuid5_bytes(namespace: bytes, name: bytes) -> bytes: ...
def molt_importlib_source_loader_payload(
    module_name: str,
    path: str,
    spec_is_package: bool,
) -> dict[str, Any]: ...
def molt_importlib_extension_loader_payload(
    module_name: str,
    path: str,
    spec_is_package: bool,
) -> dict[str, Any]: ...
def molt_importlib_sourceless_loader_payload(
    module_name: str,
    path: str,
    spec_is_package: bool,
) -> dict[str, Any]: ...
def molt_importlib_source_exec_payload(
    module_name: str,
    path: str,
    spec_is_package: bool,
) -> dict[str, Any]: ...
def molt_importlib_zip_source_exec_payload(
    module_name: str,
    archive_path: str,
    inner_path: str,
    spec_is_package: bool,
) -> dict[str, Any]: ...
def molt_importlib_read_file(path: str) -> bytes: ...
def molt_importlib_exec_restricted_source(
    namespace: dict[str, Any],
    source: str,
    filename: str,
) -> None: ...
def molt_importlib_exec_extension(
    namespace: dict[str, Any], module_name: str, path: str
) -> None: ...
def molt_importlib_exec_sourceless(
    namespace: dict[str, Any], module_name: str, path: str
) -> None: ...
def molt_importlib_module_spec_is_package(module: Any) -> bool: ...
def molt_importlib_cache_from_source(path: str) -> str: ...
def molt_importlib_find_in_path(
    fullname: str,
    search_paths: list[str] | tuple[str, ...],
) -> dict[str, Any] | None: ...
def molt_importlib_find_in_path_package_context(
    fullname: str,
    search_paths: list[str] | tuple[str, ...],
) -> dict[str, Any] | None: ...
def molt_importlib_find_spec_payload(
    fullname: str,
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
    meta_path: Any,
    path_hooks: Any,
    path_importer_cache: Any,
    package_context: bool,
) -> dict[str, Any] | None: ...
def molt_importlib_bootstrap_payload(
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
) -> dict[str, Any]: ...
def molt_importlib_runtime_state_payload() -> dict[str, Any]: ...
def molt_importlib_search_paths(
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
) -> list[str]: ...
def molt_importlib_namespace_paths(
    package: str,
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
) -> list[str]: ...
def molt_importlib_resources_path_payload(path: str) -> dict[str, Any]: ...
def molt_importlib_resources_package_payload(
    package: str,
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
) -> dict[str, Any]: ...
def molt_importlib_resources_as_file_enter(
    traversable: Any, traversable_type: type[Any]
) -> Any: ...
def molt_importlib_resources_as_file_exit(exc_type: Any, exc: Any, tb: Any) -> bool: ...
def molt_importlib_resources_module_name(
    module: Any, fallback: str | None = ...
) -> str: ...
def molt_importlib_resources_loader_reader(
    module: Any, module_name: str
) -> Any | None: ...
def molt_importlib_resources_reader_files_traversable(reader: Any) -> Any | None: ...
def molt_importlib_resources_reader_roots(reader: Any) -> list[str]: ...
def molt_importlib_resources_reader_contents(reader: Any) -> list[str]: ...
def molt_importlib_resources_reader_resource_path(
    reader: Any, name: str
) -> str | None: ...
def molt_importlib_resources_reader_is_resource(reader: Any, name: str) -> bool: ...
def molt_importlib_resources_reader_open_resource_bytes(
    reader: Any, name: str
) -> bytes: ...
def molt_importlib_resources_reader_child_names(
    reader: Any, parts: list[str] | tuple[str, ...]
) -> list[str]: ...
def molt_importlib_resources_reader_exists(
    reader: Any, parts: list[str] | tuple[str, ...]
) -> bool: ...
def molt_importlib_resources_reader_is_dir(
    reader: Any, parts: list[str] | tuple[str, ...]
) -> bool: ...
def molt_linecache_loader_get_source(loader: Any, module_name: str) -> str | None: ...
def molt_importlib_metadata_dist_paths(
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
) -> list[str]: ...
def molt_importlib_metadata_entry_points_payload(
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
) -> list[tuple[str, str, str]]: ...
def molt_importlib_metadata_entry_points_select_payload(
    search_paths: list[str] | tuple[str, ...],
    module_file: str | None,
    group: str | None = ...,
    name: str | None = ...,
) -> list[tuple[str, str, str]]: ...
def molt_importlib_metadata_normalize_name(name: str) -> str: ...
def molt_importlib_metadata_payload(path: str) -> dict[str, Any]: ...
def molt_importlib_spec_from_file_location_payload(path: str) -> dict[str, Any]: ...
def molt_copyreg_bootstrap() -> tuple[
    dict[Any, Any], dict[Any, Any], dict[Any, Any], dict[Any, Any], set[Any]
]: ...
def molt_copyreg_pickle(cls: Any, reducer: Any, constructor: Any) -> None: ...
def molt_pickle_encode_protocol0(parts: Any) -> bytes: ...
def molt_pickle_dumps_protocol01(obj: Any, protocol: int) -> bytes: ...
def molt_pickle_loads_protocol01(data: str) -> Any: ...
def molt_pickle_dumps_core(
    obj: Any,
    protocol: int,
    fix_imports: bool,
    persistent_id: Any,
    buffer_callback: Any,
    dispatch_table: Any,
) -> bytes: ...
def molt_pickle_loads_core(
    data: Any,
    fix_imports: bool,
    encoding: str,
    errors: str,
    persistent_load: Any,
    find_class: Any,
    buffers: Any,
) -> Any: ...
def molt_copyreg_constructor(func: Any) -> Any: ...
def molt_copyreg_add_extension(module: Any, name: Any, code: Any) -> None: ...
def molt_copyreg_remove_extension(module: Any, name: Any, code: Any) -> None: ...
def molt_copyreg_clear_extension_cache() -> None: ...
def molt_module_cache_set(name: str, module: Any) -> Any: ...
def molt_exception_active() -> Any: ...
def molt_exception_last() -> Any: ...
def molt_exception_pending() -> int: ...
def molt_exception_clear() -> None: ...
def molt_gc_collect(generation: int = ...) -> int: ...
def molt_gc_enable() -> None: ...
def molt_gc_disable() -> None: ...
def molt_gc_isenabled() -> bool: ...
def molt_gc_set_threshold(th0: int, th1: int = ..., th2: int = ...) -> None: ...
def molt_gc_get_threshold() -> tuple[int, int, int]: ...
def molt_gc_set_debug(flags: int) -> None: ...
def molt_gc_get_debug() -> int: ...
def molt_gc_get_count() -> tuple[int, int, int]: ...
def molt_traceback_source_line(filename: str, lineno: int) -> str: ...
def molt_traceback_infer_col_offsets(line: str) -> tuple[int, int]: ...
def molt_traceback_format_caret_line(line: str, colno: int, end_colno: int) -> str: ...
def molt_traceback_format_exception_only(exc_type: Any, value: Any) -> list[str]: ...
def molt_traceback_format_exception(
    exc_type: Any, value: Any, tb: Any, limit: int | None, chain: bool
) -> list[str]: ...
def molt_traceback_format_tb(tb: Any, limit: int | None) -> list[str]: ...
def molt_traceback_format_stack(source: Any, limit: int | None) -> list[str]: ...
def molt_traceback_extract_tb(
    tb: Any, limit: int | None
) -> list[tuple[str, int, int, int, int, str, str]]: ...
def molt_traceback_exception_components(
    value: Any, limit: int | None
) -> tuple[list[tuple[str, int, int, int, int, str, str]], Any, Any, bool]: ...
def molt_traceback_exception_chain_payload(
    value: Any, limit: int | None
) -> list[
    tuple[
        Any,
        list[tuple[str, int, int, int, int, str, str]],
        bool,
        int | None,
        int | None,
    ]
]: ...
def molt_traceback_exception_suppress_context(value: Any) -> bool: ...
def molt_traceback_payload(
    source: Any, limit: int | None
) -> list[tuple[str, int, int, int, int, str, str]]: ...
def molt_getargv() -> list[str]: ...
def molt_getframe(depth: int) -> Any: ...
def molt_getrecursionlimit() -> int: ...
def molt_setrecursionlimit(limit: int) -> None: ...
def molt_sys_executable() -> str: ...
def molt_asyncgen_hooks_get() -> Any: ...
def molt_asyncgen_hooks_set(firstiter: Any, finalizer: Any) -> Any: ...
def molt_asyncgen_locals(asyncgen: Any) -> Any: ...
def molt_gen_locals(gen: Any) -> Any: ...
def molt_ast_parse(
    source: str,
    filename: str,
    mode: str,
    type_comments: bool,
    feature_version: Any | None,
    ctors: list[Any] | tuple[Any, ...],
) -> Any: ...
def molt_ast_walk(node: Any) -> tuple[Any, ...]: ...
def molt_ast_get_docstring(node: Any, clean: bool = ...) -> str | None: ...
def molt_inspect_cleandoc(doc: Any) -> str: ...
def molt_inspect_currentframe() -> Any: ...
def molt_inspect_getdoc(obj: Any) -> Any: ...
def molt_inspect_isfunction(obj: Any) -> bool: ...
def molt_inspect_isclass(obj: Any) -> bool: ...
def molt_inspect_ismodule(obj: Any) -> bool: ...
def molt_inspect_iscoroutine(obj: Any) -> bool: ...
def molt_inspect_iscoroutinefunction(obj: Any) -> bool: ...
def molt_inspect_isasyncgenfunction(obj: Any) -> bool: ...
def molt_inspect_isgeneratorfunction(obj: Any) -> bool: ...
def molt_inspect_isawaitable(obj: Any) -> bool: ...
def molt_inspect_getgeneratorstate(gen: Any) -> str: ...
def molt_inspect_getasyncgenstate(agen: Any) -> str: ...
def molt_inspect_getcoroutinestate(coro: Any) -> str: ...
def molt_inspect_signature_data(obj: Any) -> Any: ...
def molt_function_set_builtin(func: Any) -> None: ...
def molt_builtin_class_lookup(name: str) -> Any: ...
def molt_class_new(name: str) -> Any: ...
def molt_dataclasses_make_dataclass(
    cls_name: Any,
    fields: Any,
    bases: Any,
    namespace: Any,
    module: Any,
    default_field_type: Any,
    field_class: Any,
) -> Any: ...
def molt_dataclasses_is_dataclass(obj: Any) -> bool: ...
def molt_dataclasses_fields(
    class_or_instance: Any, field_tag: Any
) -> tuple[Any, ...]: ...
def molt_dataclasses_asdict(obj: Any, dict_factory: Any, field_tag: Any) -> Any: ...
def molt_dataclasses_astuple(obj: Any, tuple_factory: Any, field_tag: Any) -> Any: ...
def molt_dataclasses_replace(
    obj: Any,
    changes: dict[str, Any],
    field_tag: Any,
    initvar_tag: Any,
) -> Any: ...
def molt_class_set_base(cls: Any, base: Any) -> Any: ...
def molt_class_apply_set_name(cls: Any) -> Any: ...
def molt_classmethod_new(func: Any) -> Any: ...
def molt_staticmethod_new(func: Any) -> Any: ...
def molt_property_new(fget: Any, fset: Any, fdel: Any) -> Any: ...
def molt_generic_alias_new(origin: Any, args: Any) -> Any: ...
def molt_typing_type_param(typevar_ctor: Any, name: str) -> Any: ...
def molt_sys_set_version_info(
    major: int,
    minor: int,
    micro: int,
    releaselevel: str,
    serial: int,
    version: str,
) -> Any: ...
def molt_sys_version_info() -> tuple[int, int, int, str, int]: ...
def molt_sys_version() -> str: ...
def molt_sys_platform() -> str: ...
def molt_sys_bootstrap_path(module_file: str | None) -> list[str]: ...
def molt_sys_bootstrap_pythonpath(module_file: str | None) -> list[str]: ...
def molt_sys_bootstrap_module_roots(module_file: str | None) -> list[str]: ...
def molt_sys_bootstrap_pwd(module_file: str | None) -> str: ...
def molt_sys_bootstrap_include_cwd(module_file: str | None) -> bool: ...
def molt_sys_bootstrap_stdlib_root(module_file: str | None) -> str | None: ...
def molt_sys_bootstrap_payload(module_file: str | None) -> dict[str, Any]: ...
def molt_is_string_obj(val: Any) -> bool: ...
def molt_sys_stdin() -> Any: ...
def molt_sys_stdout() -> Any: ...
def molt_sys_stderr() -> Any: ...
def molt_sys_getfilesystemencodeerrors() -> str: ...
def molt_trace_enter_slot(code_id: int) -> Any: ...
def molt_trace_exit() -> Any: ...
def molt_trace_set_line(line: int) -> None: ...
def molt_operator_add(a: Any, b: Any) -> Any: ...
def molt_operator_mul(a: Any, b: Any) -> Any: ...
def molt_operator_eq(a: Any, b: Any) -> bool: ...
def molt_operator_index(obj: Any) -> int: ...
def molt_operator_itemgetter(items: tuple[Any, ...]) -> Any: ...
def molt_operator_attrgetter(attrs: tuple[Any, ...]) -> Any: ...
def molt_operator_methodcaller(
    name: str, args: tuple[Any, ...], kwargs: dict[str, Any]
) -> Any: ...
def molt_itertools_kwd_mark() -> Any: ...
def molt_itertools_chain(iterables: tuple[Any, ...]) -> Any: ...
def molt_itertools_chain_from_iterable(iterables: Any) -> Any: ...
def molt_itertools_islice(iterable: Any, start: Any, stop: Any, step: Any) -> Any: ...
def molt_itertools_repeat(obj: Any, times: Any | None = ...) -> Any: ...
def molt_itertools_count(start: Any = ..., step: Any = ...) -> Any: ...
def molt_itertools_cycle(iterable: Any) -> Any: ...
def molt_itertools_accumulate(iterable: Any, func: Any, initial: Any) -> Any: ...
def molt_itertools_pairwise(iterable: Any) -> Any: ...
def molt_itertools_product(iterables: tuple[Any, ...], repeat: Any) -> Any: ...
def molt_itertools_permutations(iterable: Any, r: Any | None = ...) -> Any: ...
def molt_itertools_combinations(iterable: Any, r: Any) -> Any: ...
def molt_itertools_groupby(iterable: Any, key: Any | None = ...) -> Any: ...
def molt_itertools_tee(iterable: Any, n: Any = ...) -> Any: ...
def molt_functools_kwd_mark() -> Any: ...
def molt_functools_update_wrapper(
    wrapper: Any, wrapped: Any, assigned: Any, updated: Any
) -> Any: ...
def molt_functools_wraps(wrapped: Any, assigned: Any, updated: Any) -> Any: ...
def molt_functools_cmp_to_key(cmp: Any) -> Any: ...
def molt_functools_total_ordering(cls: Any) -> Any: ...
def molt_functools_partial(
    func: Any, args: tuple[Any, ...], kwargs: dict[str, Any]
) -> Any: ...
def molt_functools_reduce(func: Any, iterable: Any, initializer: Any) -> Any: ...
def molt_functools_lru_cache(maxsize: Any, typed: Any) -> Any: ...
def molt_keyword_lists() -> tuple[list[str], list[str]]: ...
def molt_keyword_iskeyword(value: Any) -> bool: ...
def molt_keyword_issoftkeyword(value: Any) -> bool: ...
def molt_future_features() -> list[
    tuple[str, tuple[Any, ...], tuple[Any, ...] | None, int]
]: ...
def molt_types_bootstrap() -> dict[str, Any]: ...
def molt_stdlib_probe() -> bool: ...
