# NOTE: Canonical intrinsics manifest (Rust-owned).
# Generated files: src/molt/_intrinsics.pyi and runtime/molt-runtime/src/intrinsics/generated.rs
# Update via: python3 tools/gen_intrinsics.py

from typing import Any

def molt_capabilities_trusted() -> bool: ...
def molt_capabilities_has(name: str) -> bool: ...
def molt_capabilities_require(name: str) -> None: ...
def molt_weakref_register(weakref_obj: Any, obj: Any, callback: Any) -> Any: ...
def molt_weakref_get(weakref_obj: Any) -> Any: ...
def molt_weakref_peek(weakref_obj: Any) -> Any: ...
def molt_weakref_drop(weakref_obj: Any) -> Any: ...
def molt_weakref_collect() -> Any: ...
def molt_re_literal_matches(segment: str, literal: str, flags: int) -> bool: ...
def molt_shlex_quote(text: str) -> str: ...
def molt_shlex_split(text: str, whitespace: str) -> list[str]: ...
def molt_email_message_new() -> Any: ...
def molt_email_message_set(message: Any, name: str, value: str) -> None: ...
def molt_email_message_items(message: Any) -> list[tuple[str, str]]: ...
def molt_email_message_drop(message: Any) -> None: ...
def molt_asyncgen_shutdown() -> Any: ...
def molt_block_on(task: Any) -> Any: ...
def molt_chan_new(maxsize: int = ...) -> Any: ...
def molt_chan_send(chan: Any, val: Any) -> int: ...
def molt_chan_recv(chan: Any) -> Any: ...
def molt_chan_try_send(chan: Any, val: Any) -> int: ...
def molt_chan_try_recv(chan: Any) -> Any: ...
def molt_chan_send_blocking(chan: Any, val: Any) -> int: ...
def molt_chan_recv_blocking(chan: Any) -> Any: ...
def molt_chan_drop(chan: Any) -> None: ...
def molt_pending() -> Any: ...
def molt_spawn(task: Any) -> None: ...
def molt_async_sleep(_delay: float = ..., _result: Any | None = ...) -> Any: ...
def molt_time_monotonic() -> float: ...
def molt_time_monotonic_ns() -> int: ...
def molt_time_perf_counter() -> float: ...
def molt_time_perf_counter_ns() -> int: ...
def molt_time_time() -> float: ...
def molt_time_time_ns() -> int: ...
def molt_time_process_time() -> float: ...
def molt_time_process_time_ns() -> int: ...
def molt_time_localtime(secs: Any | None = ...) -> Any: ...
def molt_time_gmtime(secs: Any | None = ...) -> Any: ...
def molt_time_strftime(fmt: Any, time_tuple: Any) -> Any: ...
def molt_time_timezone() -> int: ...
def molt_time_tzname() -> Any: ...
def molt_heapq_heapify(heap: list[Any]) -> None: ...
def molt_heapq_heappush(heap: list[Any], item: Any) -> None: ...
def molt_heapq_heappop(heap: list[Any]) -> Any: ...
def molt_heapq_heapreplace(heap: list[Any], item: Any) -> Any: ...
def molt_heapq_heappushpop(heap: list[Any], item: Any) -> Any: ...
def molt_math_log(value: float) -> float: ...
def molt_math_log2(value: float) -> float: ...
def molt_math_log10(value: float) -> float: ...
def molt_math_log1p(value: float) -> float: ...
def molt_math_exp(value: float) -> float: ...
def molt_math_expm1(value: float) -> float: ...
def molt_math_fma(x: float, y: float, z: float) -> float: ...
def molt_math_sin(value: float) -> float: ...
def molt_math_cos(value: float) -> float: ...
def molt_math_acos(value: float) -> float: ...
def molt_math_lgamma(value: float) -> float: ...
def molt_math_gamma(value: float) -> float: ...
def molt_math_erf(value: float) -> float: ...
def molt_math_erfc(value: float) -> float: ...
def molt_math_isfinite(value: Any) -> bool: ...
def molt_math_isinf(value: Any) -> bool: ...
def molt_math_isnan(value: Any) -> bool: ...
def molt_math_fabs(value: Any) -> float: ...
def molt_math_copysign(x: Any, y: Any) -> float: ...
def molt_math_sqrt(value: Any) -> float: ...
def molt_math_floor(value: Any) -> int: ...
def molt_math_ceil(value: Any) -> int: ...
def molt_math_trunc(value: Any) -> int: ...
def molt_math_fmod(x: Any, y: Any) -> float: ...
def molt_math_modf(value: Any) -> tuple[float, float]: ...
def molt_math_frexp(value: Any) -> tuple[float, int]: ...
def molt_math_ldexp(value: Any, exp: Any) -> float: ...
def molt_math_isclose(a: Any, b: Any, rel_tol: Any, abs_tol: Any) -> bool: ...
def molt_math_prod(iterable: Any, start: Any) -> Any: ...
def molt_math_fsum(iterable: Any) -> float: ...
def molt_math_gcd(args: tuple[Any, ...]) -> int: ...
def molt_math_lcm(args: tuple[Any, ...]) -> int: ...
def molt_math_factorial(value: Any) -> int: ...
def molt_math_comb(n: Any, k: Any) -> int: ...
def molt_math_perm(n: Any, k: Any) -> int: ...
def molt_math_degrees(value: Any) -> float: ...
def molt_math_radians(value: Any) -> float: ...
def molt_math_hypot(args: tuple[Any, ...]) -> float: ...
def molt_math_dist(p: Any, q: Any) -> float: ...
def molt_math_isqrt(value: Any) -> int: ...
def molt_math_nextafter(x: Any, y: Any) -> float: ...
def molt_math_ulp(value: Any) -> float: ...
def molt_math_remainder(x: Any, y: Any) -> float: ...
def molt_math_tan(value: Any) -> float: ...
def molt_math_asin(value: Any) -> float: ...
def molt_math_atan(value: Any) -> float: ...
def molt_math_atan2(y: Any, x: Any) -> float: ...
def molt_math_sinh(value: Any) -> float: ...
def molt_math_cosh(value: Any) -> float: ...
def molt_math_tanh(value: Any) -> float: ...
def molt_math_asinh(value: Any) -> float: ...
def molt_math_acosh(value: Any) -> float: ...
def molt_math_atanh(value: Any) -> float: ...
def molt_decimal_context_new() -> Any: ...
def molt_decimal_context_get_current() -> Any: ...
def molt_decimal_context_set_current(ctx: Any) -> Any: ...
def molt_decimal_context_copy(ctx: Any) -> Any: ...
def molt_decimal_context_drop(ctx: Any) -> None: ...
def molt_decimal_context_get_prec(ctx: Any) -> int: ...
def molt_decimal_context_set_prec(ctx: Any, prec: int) -> None: ...
def molt_decimal_context_get_rounding(ctx: Any) -> int: ...
def molt_decimal_context_set_rounding(ctx: Any, rounding: int) -> None: ...
def molt_decimal_context_clear_flags(ctx: Any) -> None: ...
def molt_decimal_context_get_flag(ctx: Any, flag: int) -> bool: ...
def molt_decimal_context_set_flag(ctx: Any, flag: int, value: bool) -> None: ...
def molt_decimal_context_get_trap(ctx: Any, flag: int) -> bool: ...
def molt_decimal_context_set_trap(ctx: Any, flag: int, value: bool) -> None: ...
def molt_decimal_from_str(ctx: Any, value: str) -> Any: ...
def molt_decimal_from_int(ctx: Any, value: Any) -> Any: ...
def molt_decimal_clone(value: Any) -> Any: ...
def molt_decimal_drop(value: Any) -> None: ...
def molt_decimal_to_string(value: Any) -> str: ...
def molt_decimal_as_tuple(value: Any) -> Any: ...
def molt_decimal_to_float(value: Any) -> float: ...
def molt_decimal_div(ctx: Any, a: Any, b: Any) -> Any: ...
def molt_decimal_quantize(ctx: Any, a: Any, exp: Any) -> Any: ...
def molt_decimal_compare(ctx: Any, a: Any, b: Any) -> Any: ...
def molt_decimal_compare_total(a: Any, b: Any) -> Any: ...
def molt_decimal_normalize(ctx: Any, a: Any) -> Any: ...
def molt_decimal_exp(ctx: Any, a: Any) -> Any: ...
def molt_hash_new(name: str, data: Any, options: Any) -> Any: ...
def molt_hash_update(handle: Any, data: Any) -> None: ...
def molt_hash_copy(handle: Any) -> Any: ...
def molt_hash_digest(handle: Any, length: Any | None = ...) -> bytes: ...
def molt_hash_drop(handle: Any) -> None: ...
def molt_hmac_new(key: Any, msg: Any, name: str, options: Any) -> Any: ...
def molt_hmac_update(handle: Any, data: Any) -> None: ...
def molt_hmac_copy(handle: Any) -> Any: ...
def molt_hmac_digest(handle: Any) -> bytes: ...
def molt_hmac_drop(handle: Any) -> None: ...
def molt_compare_digest(a: Any, b: Any) -> bool: ...
def molt_pbkdf2_hmac(
    name: str,
    password: Any,
    salt: Any,
    iterations: int,
    dklen: int | None = ...,
) -> bytes: ...
def molt_scrypt(
    password: Any,
    salt: Any,
    n: int,
    r: int,
    p: int,
    maxmem: int,
    dklen: int,
) -> bytes: ...
def molt_os_dup(fd: int) -> int: ...
def molt_os_close(fd: int) -> None: ...
def molt_os_get_inheritable(fd: int) -> bool: ...
def molt_os_set_inheritable(fd: int, inheritable: bool) -> None: ...
def molt_os_urandom(n: int) -> bytes: ...
def molt_os_name() -> str: ...
def molt_getcwd() -> str: ...
def molt_getpid() -> int: ...
def molt_env_get(key: str, default: Any = ...) -> Any: ...
def molt_env_snapshot() -> dict[str, str]: ...
def molt_errno_constants() -> tuple[dict[str, int], dict[int, str]]: ...
def molt_path_exists(path: Any) -> bool: ...
def molt_path_listdir(path: Any) -> list[str]: ...
def molt_path_mkdir(path: Any) -> None: ...
def molt_path_chmod(path: Any, mode: int) -> None: ...
def molt_path_unlink(path: Any) -> None: ...
def molt_path_rmdir(path: Any) -> None: ...
def molt_io_class(name: str) -> Any: ...
def molt_file_open(path: Any, mode: Any) -> Any: ...
def molt_file_open_ex(
    file: Any,
    mode: Any,
    buffering: int,
    encoding: Any | None,
    errors: Any | None,
    newline: Any | None,
    closefd: bool,
    opener: Any | None,
) -> Any: ...
def molt_file_read(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readline(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readlines(handle: Any, hint: int | None = ...) -> Any: ...
def molt_file_read1(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readall(handle: Any) -> Any: ...
def molt_file_readinto(handle: Any, buffer: Any) -> Any: ...
def molt_file_readinto1(handle: Any, buffer: Any) -> Any: ...
def molt_file_peek(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_getvalue(handle: Any) -> Any: ...
def molt_file_getbuffer(handle: Any) -> Any: ...
def molt_file_detach(handle: Any) -> Any: ...
def molt_file_reconfigure(
    handle: Any,
    encoding: Any | None,
    errors: Any | None,
    newline: Any | None,
    line_buffering: Any | None,
    write_through: Any | None,
) -> Any: ...
def molt_file_seek(handle: Any, offset: int, whence: int) -> Any: ...
def molt_file_tell(handle: Any) -> Any: ...
def molt_file_fileno(handle: Any) -> Any: ...
def molt_file_truncate(handle: Any, size: int | None = ...) -> Any: ...
def molt_file_readable(handle: Any) -> Any: ...
def molt_file_writable(handle: Any) -> Any: ...
def molt_file_seekable(handle: Any) -> Any: ...
def molt_file_isatty(handle: Any) -> Any: ...
def molt_file_iter(handle: Any) -> Any: ...
def molt_file_next(handle: Any) -> Any: ...
def molt_file_enter(handle: Any) -> Any: ...
def molt_file_exit(handle: Any, exc: Any) -> Any: ...
def molt_file_exit_method(handle: Any, exc: Any) -> Any: ...
def molt_file_write(handle: Any, data: Any) -> Any: ...
def molt_file_writelines(handle: Any, lines: Any) -> Any: ...
def molt_file_flush(handle: Any) -> Any: ...
def molt_file_close(handle: Any) -> Any: ...
def molt_file_io_new(
    cls: Any,
    name: Any,
    mode: Any = ...,
    closefd: Any = ...,
    opener: Any = ...,
) -> Any: ...
def molt_file_io_init(
    self: Any,
    name: Any,
    mode: Any = ...,
    closefd: Any = ...,
    opener: Any = ...,
) -> None: ...
def molt_buffered_new(cls: Any, raw: Any, buffer_size: int = ...) -> Any: ...
def molt_buffered_init(self: Any, raw: Any, buffer_size: int = ...) -> None: ...
def molt_text_io_wrapper_new(
    cls: Any,
    buffer: Any,
    encoding: str | None = ...,
    errors: str | None = ...,
    newline: str | None = ...,
    line_buffering: bool = ...,
    write_through: bool = ...,
) -> Any: ...
def molt_text_io_wrapper_init(
    self: Any,
    buffer: Any,
    encoding: str | None = ...,
    errors: str | None = ...,
    newline: str | None = ...,
    line_buffering: bool = ...,
    write_through: bool = ...,
) -> None: ...
def molt_bytesio_new(cls: Any, initial: Any = ...) -> Any: ...
def molt_bytesio_init(self: Any, initial: Any = ...) -> None: ...
def molt_stringio_new(
    cls: Any,
    initial: Any = ...,
    newline: str | None = ...,
) -> Any: ...
def molt_stringio_init(
    self: Any,
    initial: Any = ...,
    newline: str | None = ...,
) -> None: ...
def molt_codecs_decode(obj: Any, encoding: Any, errors: Any) -> Any: ...
def molt_codecs_encode(obj: Any, encoding: Any, errors: Any) -> Any: ...
def molt_codecs_lookup_name(encoding: Any) -> Any: ...
def molt_struct_pack(fmt: Any, values: Any) -> bytes: ...
def molt_struct_unpack(fmt: Any, buffer: Any) -> Any: ...
def molt_struct_calcsize(fmt: Any) -> int: ...
def molt_deflate_raw(data: Any, level: Any) -> Any: ...
def molt_inflate_raw(data: Any) -> Any: ...
def molt_cancel_token_new(parent: int | None = ...) -> int: ...
def molt_cancel_token_clone(token_id: int) -> None: ...
def molt_cancel_token_drop(token_id: int) -> None: ...
def molt_cancel_token_cancel(token_id: int) -> None: ...
def molt_cancel_token_is_cancelled(token_id: int) -> bool: ...
def molt_cancel_token_set_current(token_id: int | None) -> int: ...
def molt_cancel_token_get_current() -> int: ...
def molt_future_cancel(future: Any) -> None: ...
def molt_future_cancel_msg(future: Any, msg: Any) -> None: ...
def molt_future_cancel_clear(future: Any) -> None: ...
def molt_promise_new() -> Any: ...
def molt_promise_set_result(future: Any, result: Any) -> None: ...
def molt_promise_set_exception(future: Any, exc: Any) -> None: ...
def molt_task_register_token_owned(task: Any, token_id: int) -> None: ...
def molt_io_wait(future: Any) -> int: ...
def molt_io_wait_new(socket: Any, events: int, timeout: float | None) -> Any: ...
def molt_ws_wait_new(ws: Any, events: int, timeout: float | None) -> Any: ...
def molt_ws_pair_obj(capacity: int) -> tuple[Any, Any]: ...
def molt_ws_connect_obj(url: str) -> Any: ...
def molt_ws_send_obj(ws: Any, data: Any) -> int: ...
def molt_ws_recv(ws: Any) -> Any: ...
def molt_ws_close(ws: Any) -> None: ...
def molt_ws_drop(ws: Any) -> None: ...
def molt_thread_submit(fn: Any, args: Any, kwargs: Any) -> Any: ...
def molt_thread_spawn(payload: bytes) -> Any: ...
def molt_thread_join(handle: Any, timeout: float | None) -> Any: ...
def molt_thread_is_alive(handle: Any) -> bool: ...
def molt_thread_ident(handle: Any) -> int | None: ...
def molt_thread_native_id(handle: Any) -> int | None: ...
def molt_thread_current_ident() -> int: ...
def molt_thread_current_native_id() -> int: ...
def molt_thread_drop(handle: Any) -> None: ...
def molt_thread_poll(future: Any) -> int: ...
def molt_lock_new() -> Any: ...
def molt_lock_acquire(handle: Any, blocking: bool, timeout: float | None) -> bool: ...
def molt_lock_release(handle: Any) -> None: ...
def molt_lock_locked(handle: Any) -> bool: ...
def molt_lock_drop(handle: Any) -> None: ...
def molt_rlock_new() -> Any: ...
def molt_rlock_acquire(handle: Any, blocking: bool, timeout: float | None) -> bool: ...
def molt_rlock_release(handle: Any) -> None: ...
def molt_rlock_locked(handle: Any) -> bool: ...
def molt_rlock_drop(handle: Any) -> None: ...
def molt_process_spawn(
    args: Any,
    env: Any,
    cwd: Any,
    stdin: Any,
    stdout: Any,
    stderr: Any,
) -> Any: ...
def molt_process_wait_future(proc: Any) -> Any: ...
def molt_process_poll(future: Any) -> int: ...
def molt_process_pid(proc: Any) -> int: ...
def molt_process_returncode(proc: Any) -> int | None: ...
def molt_process_kill(proc: Any) -> None: ...
def molt_process_terminate(proc: Any) -> None: ...
def molt_process_stdin(proc: Any) -> Any: ...
def molt_process_stdout(proc: Any) -> Any: ...
def molt_process_stderr(proc: Any) -> Any: ...
def molt_process_drop(proc: Any) -> None: ...
def molt_stream_new(capacity: int) -> Any: ...
def molt_stream_clone(stream: Any) -> Any: ...
def molt_stream_send_obj(stream: Any, data: Any) -> int: ...
def molt_stream_recv(stream: Any) -> Any: ...
def molt_stream_close(stream: Any) -> None: ...
def molt_stream_drop(stream: Any) -> None: ...
def molt_stream_reader_new(stream: Any) -> Any: ...
def molt_stream_reader_read(reader: Any, n: int) -> Any: ...
def molt_stream_reader_readline(reader: Any) -> Any: ...
def molt_stream_reader_at_eof(reader: Any) -> bool: ...
def molt_stream_reader_drop(reader: Any) -> None: ...
def molt_socket_reader_new(sock: Any) -> Any: ...
def molt_socket_reader_read(reader: Any, n: int) -> Any: ...
def molt_socket_reader_readline(reader: Any) -> Any: ...
def molt_socket_reader_at_eof(reader: Any) -> bool: ...
def molt_socket_reader_drop(reader: Any) -> None: ...
def molt_db_query_obj(req: Any, token: Any) -> Any: ...
def molt_db_exec_obj(req: Any, token: Any) -> Any: ...
def molt_msgpack_parse_scalar_obj(data: Any) -> Any: ...
def molt_cbor_parse_scalar_obj(data: Any) -> Any: ...
def molt_json_parse_scalar_obj(data: Any) -> Any: ...
def molt_socket_new(
    family: int,
    type: int,
    proto: int,
    fileno: int | None,
) -> Any: ...
def molt_socket_close(sock: Any) -> None: ...
def molt_socket_drop(sock: Any) -> None: ...
def molt_socket_clone(sock: Any) -> Any: ...
def molt_socket_fileno(sock: Any) -> int: ...
def molt_socket_gettimeout(sock: Any) -> float | None: ...
def molt_socket_settimeout(sock: Any, timeout: float | None) -> None: ...
def molt_socket_setblocking(sock: Any, flag: bool) -> None: ...
def molt_socket_getblocking(sock: Any) -> bool: ...
def molt_socket_bind(sock: Any, addr: Any) -> None: ...
def molt_socket_listen(sock: Any, backlog: int) -> None: ...
def molt_socket_accept(sock: Any) -> tuple[Any, Any]: ...
def molt_socket_connect(sock: Any, addr: Any) -> None: ...
def molt_socket_connect_ex(sock: Any, addr: Any) -> int: ...
def molt_socket_recv(sock: Any, size: int, flags: int) -> bytes: ...
def molt_socket_recv_into(sock: Any, buffer: Any, size: int, flags: int) -> int: ...
def molt_socket_send(sock: Any, data: Any, flags: int) -> int: ...
def molt_socket_sendall(sock: Any, data: Any, flags: int) -> None: ...
def molt_socket_sendto(sock: Any, data: Any, flags: int, addr: Any) -> int: ...
def molt_socket_recvfrom(sock: Any, size: int, flags: int) -> tuple[bytes, Any]: ...
def molt_socket_shutdown(sock: Any, how: int) -> None: ...
def molt_socket_getsockname(sock: Any) -> Any: ...
def molt_socket_getpeername(sock: Any) -> Any: ...
def molt_socket_setsockopt(sock: Any, level: int, optname: int, value: Any) -> None: ...
def molt_socket_getsockopt(sock: Any, level: int, optname: int, buflen: int) -> Any: ...
def molt_socket_detach(sock: Any) -> int: ...
def molt_socketpair(
    family: int | None, type: int | None, proto: int | None
) -> tuple[Any, Any]: ...
def molt_socket_getaddrinfo(
    host: str | bytes | None,
    port: int | str | bytes | None,
    family: int,
    type: int,
    proto: int,
    flags: int,
) -> list[tuple[int, int, int, str | None, Any]]: ...
def molt_socket_getnameinfo(addr: Any, flags: int) -> tuple[str, str]: ...
def molt_socket_gethostname() -> str: ...
def molt_socket_getservbyname(name: str, proto: str | None) -> int: ...
def molt_socket_getservbyport(port: int, proto: str | None) -> str: ...
def molt_socket_inet_pton(family: int, address: str) -> bytes: ...
def molt_socket_inet_ntop(family: int, packed: bytes) -> str: ...
def molt_socket_constants() -> dict[str, int]: ...
def molt_socket_has_ipv6() -> bool: ...
def molt_compile_builtin(
    source: Any,
    filename: Any,
    mode: Any,
    flags: int,
    dont_inherit: bool,
    optimize: int,
) -> Any: ...
def molt_code_new(
    filename: str,
    name: str,
    firstlineno: int,
    linetable: Any,
    varnames: Any,
    argcount: int,
    posonlyargcount: int,
    kwonlyargcount: int,
) -> Any: ...
def molt_code_slots_init(count: int) -> None: ...
def molt_code_slot_set(code_id: int, code: Any) -> None: ...
def molt_module_new(name: str) -> Any: ...
def molt_module_import(name: str) -> Any: ...
def molt_runpy_run_module(
    mod_name: str,
    run_name: str | None,
    init_globals: dict[str, Any] | None,
) -> dict[str, Any]: ...
def molt_module_cache_set(name: str, module: Any) -> Any: ...
def molt_exception_active() -> Any: ...
def molt_exception_last() -> Any: ...
def molt_exception_pending() -> int: ...
def molt_getargv() -> list[str]: ...
def molt_getframe(depth: int) -> Any: ...
def molt_getrecursionlimit() -> int: ...
def molt_setrecursionlimit(limit: int) -> None: ...
def molt_sys_executable() -> str: ...
def molt_asyncgen_hooks_get() -> Any: ...
def molt_asyncgen_hooks_set(firstiter: Any, finalizer: Any) -> Any: ...
def molt_asyncgen_locals(asyncgen: Any) -> Any: ...
def molt_gen_locals(gen: Any) -> Any: ...
def molt_function_set_builtin(func: Any) -> None: ...
def molt_class_new(name: str) -> Any: ...
def molt_class_set_base(cls: Any, base: Any) -> Any: ...
def molt_class_apply_set_name(cls: Any) -> Any: ...
def molt_classmethod_new(func: Any) -> Any: ...
def molt_staticmethod_new(func: Any) -> Any: ...
def molt_property_new(fget: Any, fset: Any, fdel: Any) -> Any: ...
def molt_generic_alias_new(origin: Any, args: Any) -> Any: ...
def molt_typing_type_param(typevar_ctor: Any, name: str) -> Any: ...
def molt_sys_set_version_info(
    major: int,
    minor: int,
    micro: int,
    releaselevel: str,
    serial: int,
    version: str,
) -> Any: ...
def molt_sys_version_info() -> tuple[int, int, int, str, int]: ...
def molt_sys_version() -> str: ...
def molt_sys_platform() -> str: ...
def molt_sys_stdin() -> Any: ...
def molt_sys_stdout() -> Any: ...
def molt_sys_stderr() -> Any: ...
def molt_trace_enter_slot(code_id: int) -> Any: ...
def molt_trace_exit() -> Any: ...
def molt_trace_set_line(line: int) -> None: ...
def molt_operator_add(a: Any, b: Any) -> Any: ...
def molt_operator_mul(a: Any, b: Any) -> Any: ...
def molt_operator_eq(a: Any, b: Any) -> bool: ...
def molt_operator_index(obj: Any) -> int: ...
def molt_operator_itemgetter(items: tuple[Any, ...]) -> Any: ...
def molt_operator_attrgetter(attrs: tuple[Any, ...]) -> Any: ...
def molt_operator_methodcaller(
    name: str, args: tuple[Any, ...], kwargs: dict[str, Any]
) -> Any: ...
def molt_itertools_kwd_mark() -> Any: ...
def molt_itertools_chain(iterables: tuple[Any, ...]) -> Any: ...
def molt_itertools_chain_from_iterable(iterables: Any) -> Any: ...
def molt_itertools_islice(iterable: Any, start: Any, stop: Any, step: Any) -> Any: ...
def molt_itertools_repeat(obj: Any, times: Any | None = ...) -> Any: ...
def molt_itertools_count(start: Any = ..., step: Any = ...) -> Any: ...
def molt_itertools_cycle(iterable: Any) -> Any: ...
def molt_itertools_accumulate(iterable: Any, func: Any, initial: Any) -> Any: ...
def molt_itertools_pairwise(iterable: Any) -> Any: ...
def molt_itertools_product(iterables: tuple[Any, ...], repeat: Any) -> Any: ...
def molt_itertools_permutations(iterable: Any, r: Any | None = ...) -> Any: ...
def molt_itertools_combinations(iterable: Any, r: Any) -> Any: ...
def molt_itertools_groupby(iterable: Any, key: Any | None = ...) -> Any: ...
def molt_itertools_tee(iterable: Any, n: Any = ...) -> Any: ...
def molt_functools_kwd_mark() -> Any: ...
def molt_functools_update_wrapper(
    wrapper: Any, wrapped: Any, assigned: Any, updated: Any
) -> Any: ...
def molt_functools_wraps(wrapped: Any, assigned: Any, updated: Any) -> Any: ...
def molt_functools_cmp_to_key(cmp: Any) -> Any: ...
def molt_functools_total_ordering(cls: Any) -> Any: ...
def molt_functools_partial(
    func: Any, args: tuple[Any, ...], kwargs: dict[str, Any]
) -> Any: ...
def molt_functools_reduce(func: Any, iterable: Any, initializer: Any) -> Any: ...
def molt_functools_lru_cache(maxsize: Any, typed: Any) -> Any: ...
def molt_keyword_lists() -> tuple[list[str], list[str]]: ...
def molt_keyword_iskeyword(value: Any) -> bool: ...
def molt_keyword_issoftkeyword(value: Any) -> bool: ...
def molt_future_features() -> (
    list[tuple[str, tuple[Any, ...], tuple[Any, ...] | None, int]]
): ...
def molt_types_bootstrap() -> dict[str, Any]: ...
def molt_stdlib_probe() -> bool: ...
