// @generated by tools/gen_intrinsics.py. DO NOT EDIT.
#[inline(never)]
#[cold]
pub fn resolve_symbol_with(
    symbol: &str,
    runtime_fn_addr: fn(&str, *const ()) -> u64,
) -> Option<u64> {
    match symbol {
        "molt_argparse_add_argument" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_add_argument",
            crate::argparse::molt_argparse_add_argument as *const (),
        )),
        "molt_argparse_add_mutually_exclusive" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_add_mutually_exclusive",
            crate::argparse::molt_argparse_add_mutually_exclusive as *const (),
        )),
        "molt_argparse_add_parser" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_add_parser",
            crate::argparse::molt_argparse_add_parser as *const (),
        )),
        "molt_argparse_add_subparsers" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_add_subparsers",
            crate::argparse::molt_argparse_add_subparsers as *const (),
        )),
        "molt_argparse_error" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_error",
            crate::argparse::molt_argparse_error as *const (),
        )),
        "molt_argparse_format_help" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_format_help",
            crate::argparse::molt_argparse_format_help as *const (),
        )),
        "molt_argparse_format_usage" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_format_usage",
            crate::argparse::molt_argparse_format_usage as *const (),
        )),
        "molt_argparse_group_add_argument" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_group_add_argument",
            crate::argparse::molt_argparse_group_add_argument as *const (),
        )),
        "molt_argparse_parse_args" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_parse_args",
            crate::argparse::molt_argparse_parse_args as *const (),
        )),
        "molt_argparse_parser_drop" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_parser_drop",
            crate::argparse::molt_argparse_parser_drop as *const (),
        )),
        "molt_argparse_parser_new" => Some(runtime_fn_addr(
            "molt_runtime_collections::argparse::molt_argparse_parser_new",
            crate::argparse::molt_argparse_parser_new as *const (),
        )),
        _ => None,
    }
}
