"""Intrinsic-first stdlib package stub for `xml.sax`.

Generated by tools/gen_stdlib_stubs.py; lowering the package replaces this file.
"""


# TODO(stdlib-parity, owner:stdlib, milestone:SL3, priority:P1, status:planned): replace `xml.sax` package stub with a full lowering.
def __getattr__(attr: str):
    if attr in {
        "_exceptions",
        "expatreader",
        "handler",
        "saxutils",
        "xmlreader",
    }:
        raise AttributeError(f"module {__name__!r} has no attribute {attr!r}", name=attr)
    raise RuntimeError(
        'stdlib package "xml.sax" is not fully lowered yet; only an intrinsic-first stub is available.'
    )
